//! Dawnfox. See `REGISTRATION` for pinned upstream sources.
//!
//! Nightfox base shades and declared UI roles. bg0 remains the floating surface, sel0 is hover, and red serves both error levels. Generated bright/dim shades are outside the raw import.

define_palette! {
    Dawnfox, "Dawnfox",
    identity("nightfox/dawnfox", "nightfox", "Nightfox", "dawnfox", "Dawnfox", Light, None);
    support(Light);
    sources: super::SOURCE_DAWNFOX;
    colors {
        BLACK = crate::color::Color::hex(0x575279),
        RED = crate::color::Color::hex(0xb4637a),
        GREEN = crate::color::Color::hex(0x618774),
        YELLOW = crate::color::Color::hex(0xea9d34),
        BLUE = crate::color::Color::hex(0x286983),
        MAGENTA = crate::color::Color::hex(0x907aa9),
        CYAN = crate::color::Color::hex(0x56949f),
        WHITE = crate::color::Color::hex(0xe5e9f0),
        ORANGE = crate::color::Color::hex(0xd7827e),
        PINK = crate::color::Color::hex(0xd685af),
        COMMENT = crate::color::Color::hex(0x9893a5),
        BG_0 = crate::color::Color::hex(0xebe5df),
        BG_1 = crate::color::Color::hex(0xfaf4ed),
        BG_2 = crate::color::Color::hex(0xebe0df),
        BG_3 = crate::color::Color::hex(0xebdfe4),
        BG_4 = crate::color::Color::hex(0xbdbfc9),
        FG_0 = crate::color::Color::hex(0x4c4769),
        FG_1 = crate::color::Color::hex(0x575279),
        FG_2 = crate::color::Color::hex(0x625c87),
        FG_3 = crate::color::Color::hex(0xa8a3b3),
        SEL_0 = crate::color::Color::hex(0xd0d8d8),
        SEL_1 = crate::color::Color::hex(0xb8cece),
    }
    accents {
        Red = RED => ("red", "Red"),
        Green = GREEN => ("green", "Green"),
        Yellow = YELLOW => ("yellow", "Yellow"),
        Blue = BLUE => ("blue", "Blue"),
        Magenta = MAGENTA => ("magenta", "Magenta"),
        Cyan = CYAN => ("cyan", "Cyan"),
        Orange = ORANGE => ("orange", "Orange"),
        Pink = PINK => ("pink", "Pink"),
    }
    default BLUE => "blue";
    roles(primary) {
        surfaces: crate::theme_variant::SurfaceColors {
            background: Self::BG_1,
            base: Self::BG_2,
            raised: Self::BG_3,
            overlay: Self::BG_0,
            hover: Self::SEL_0,
        },
        surfaces_alt: crate::theme_variant::SurfaceColors {
            background: Self::BG_0,
            base: Self::BG_1,
            raised: Self::BG_2,
            overlay: Self::BG_0,
            hover: Self::SEL_0,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FG_1,
            muted: Self::FG_2,
            subtle: Self::COMMENT,
        },
        text_alt: None,
        primary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), primary),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::primary_hover(primary)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::action_pressed(primary)),
            muted: crate::theme_variant::ColorPair::new(Self::FG_1, Self::BG_2),
            disabled: crate::theme_variant::ColorPair::new(Self::COMMENT, Self::BG_2),
        },
        secondary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::MAGENTA), Self::MAGENTA),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::MAGENTA), crate::palette::primary_hover(Self::MAGENTA)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::MAGENTA), crate::palette::action_pressed(Self::MAGENTA)),
            muted: crate::theme_variant::ColorPair::new(Self::FG_1, Self::BG_2),
            disabled: crate::theme_variant::ColorPair::new(Self::COMMENT, Self::BG_2),
        },
        status: crate::theme_variant::StatusColors {
            success: Self::GREEN,
            warning: Self::YELLOW,
            error: Self::RED,
            critical: Self::RED,
            info: Self::BLUE,
            debug: Self::FG_2,
            trace: Self::FG_3,
        },
        border: Self::BG_4,
        border_muted: Self::BG_2,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::RED,
            orange: Self::YELLOW,
            yellow: Self::YELLOW,
            green: Self::GREEN,
            cyan: Self::CYAN,
            blue: Self::BLUE,
            purple: Self::MAGENTA,
            pink: Self::PINK,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::YELLOW,
            boolean: Self::ORANGE,
            builtin: Self::YELLOW,
            builtin_function: Self::BLUE,
            builtin_type: Self::YELLOW,
            comment: Self::COMMENT,
            constant: Self::ORANGE,
            control_keyword: Self::MAGENTA,
            deleted: Self::RED,
            deprecated: Self::RED,
            documentation: Self::COMMENT,
            escape: Self::CYAN,
            foreground: Self::FG_1,
            function: Self::BLUE,
            heading: Self::BLUE,
            inserted: Self::GREEN,
            invalid: Self::RED,
            keyword: Self::MAGENTA,
            link: Self::BLUE,
            macro_name: Self::BLUE,
            markup_bold: Self::FG_1,
            markup_italic: Self::FG_1,
            modifier: Self::MAGENTA,
            namespace: Self::YELLOW,
            number: Self::ORANGE,
            operator: Self::CYAN,
            parameter: Self::FG_1,
            property: Self::FG_1,
            punctuation: Self::FG_1,
            string: Self::GREEN,
            tag: Self::MAGENTA,
            type_keyword: Self::MAGENTA,
            type_name: Self::YELLOW,
            variable: Self::FG_1,
        },
    }
}
