//! Night Owl. See `REGISTRATION` for pinned upstream sources.
//!
//! Editor UI keys supply surfaces and source alpha is retained. Terminal accents supply filled actions. Critical uses bright red; trace uses subdued source text. Roles that share an upstream colour intentionally repeat.

define_palette! {
    Main, "Night Owl",
    identity("night_owl/main", "night_owl", "Night Owl", "main", "Main", Dark, None);
    support(Dark);
    sources: super::SOURCE;
    colors {
        CONTRAST_BORDER = crate::color::Color::hex(0x122d42),
        FOCUS_BORDER = crate::color::Color::hex(0x122d42),
        FOREGROUND = crate::color::Color::hex(0xd6deeb),
        WIDGET_SHADOW = crate::color::Color::hex(0x011627),
        SELECTION_BACKGROUND = crate::color::Color::hex(0x4373c2),
        ERROR_FOREGROUND = crate::color::Color::hex(0xef5350),
        BUTTON_BACKGROUND = crate::color::Color::hex_alpha(0x7e57c2cc),
        BUTTON_FOREGROUND = crate::color::Color::hex_alpha(0xffffffcc),
        BUTTON_HOVER_BACKGROUND = crate::color::Color::hex(0x7e57c2),
        DROPDOWN_BACKGROUND = crate::color::Color::hex(0x011627),
        DROPDOWN_BORDER = crate::color::Color::hex(0x5f7e97),
        DROPDOWN_FOREGROUND = crate::color::Color::hex_alpha(0xffffffcc),
        INPUT_BACKGROUND = crate::color::Color::hex(0x0b253a),
        INPUT_BORDER = crate::color::Color::hex(0x5f7e97),
        INPUT_FOREGROUND = crate::color::Color::hex_alpha(0xffffffcc),
        INPUT_PLACEHOLDER_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        INPUT_OPTION_ACTIVE_BORDER = crate::color::Color::hex_alpha(0xffffffcc),
        PUNCTUATION_DEFINITION_GENERIC_BEGIN_HTML = crate::color::Color::hex_alpha(0xef5350f2),
        INPUT_VALIDATION_ERROR_BACKGROUND = crate::color::Color::hex_alpha(0xab0300f2),
        INPUT_VALIDATION_ERROR_BORDER = crate::color::Color::hex(0xef5350),
        INPUT_VALIDATION_INFO_BACKGROUND = crate::color::Color::hex_alpha(0x00589ef2),
        INPUT_VALIDATION_INFO_BORDER = crate::color::Color::hex(0x64b5f6),
        INPUT_VALIDATION_WARNING_BACKGROUND = crate::color::Color::hex_alpha(0x675700f2),
        INPUT_VALIDATION_WARNING_BORDER = crate::color::Color::hex(0xffca28),
        SCROLLBAR_SHADOW = crate::color::Color::hex(0x010b14),
        SCROLLBAR_SLIDER_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0x084d8180),
        SCROLLBAR_SLIDER_BACKGROUND = crate::color::Color::hex_alpha(0x084d8180),
        SCROLLBAR_SLIDER_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x084d8180),
        BADGE_BACKGROUND = crate::color::Color::hex(0x5f7e97),
        BADGE_FOREGROUND = crate::color::Color::hex(0xffffff),
        PROGRESS_BACKGROUND = crate::color::Color::hex(0x7e57c2),
        BREADCRUMB_FOREGROUND = crate::color::Color::hex(0xa599e9),
        BREADCRUMB_FOCUS_FOREGROUND = crate::color::Color::hex(0xffffff),
        BREADCRUMB_ACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        BREADCRUMB_PICKER_BACKGROUND = crate::color::Color::hex(0x001122),
        LIST_ACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x234d708c),
        LIST_ACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_INVALID_ITEM_FOREGROUND = crate::color::Color::hex(0x975f94),
        LIST_DROP_BACKGROUND = crate::color::Color::hex(0x011627),
        LIST_FOCUS_BACKGROUND = crate::color::Color::hex(0x010d18),
        LIST_FOCUS_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_HOVER_BACKGROUND = crate::color::Color::hex(0x011627),
        LIST_HOVER_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0x0e293f),
        LIST_INACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        ACTIVITY_BAR_BACKGROUND = crate::color::Color::hex(0x011627),
        ACTIVITY_BAR_DROP_BACKGROUND = crate::color::Color::hex(0x5f7e97),
        ACTIVITY_BAR_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        ACTIVITY_BAR_BORDER = crate::color::Color::hex(0x011627),
        ACTIVITY_BAR_BADGE_BACKGROUND = crate::color::Color::hex(0x44596b),
        ACTIVITY_BAR_BADGE_FOREGROUND = crate::color::Color::hex(0xffffff),
        SIDE_BAR_BACKGROUND = crate::color::Color::hex(0x011627),
        SIDE_BAR_FOREGROUND = crate::color::Color::hex(0x89a4bb),
        SIDE_BAR_BORDER = crate::color::Color::hex(0x011627),
        SIDE_BAR_TITLE_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        SIDE_BAR_SECTION_HEADER_BACKGROUND = crate::color::Color::hex(0x011627),
        SIDE_BAR_SECTION_HEADER_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        EDITOR_GROUP_EMPTY_BACKGROUND = crate::color::Color::hex(0x011627),
        EDITOR_GROUP_BORDER = crate::color::Color::hex(0x011627),
        EDITOR_GROUP_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x7e57c273),
        EDITOR_GROUP_HEADER_NO_TABS_BACKGROUND = crate::color::Color::hex(0x011627),
        EDITOR_GROUP_HEADER_TABS_BACKGROUND = crate::color::Color::hex(0x011627),
        EDITOR_GROUP_HEADER_TABS_BORDER = crate::color::Color::hex(0x262a39),
        TAB_ACTIVE_BACKGROUND = crate::color::Color::hex(0x0b2942),
        TAB_ACTIVE_FOREGROUND = crate::color::Color::hex(0xd2dee7),
        TAB_BORDER = crate::color::Color::hex(0x272b3b),
        TAB_ACTIVE_BORDER = crate::color::Color::hex(0x262a39),
        TAB_UNFOCUSED_ACTIVE_BORDER = crate::color::Color::hex(0x262a39),
        TAB_INACTIVE_BACKGROUND = crate::color::Color::hex(0x01111d),
        TAB_INACTIVE_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        TAB_UNFOCUSED_ACTIVE_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        TAB_UNFOCUSED_INACTIVE_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        EDITOR_BACKGROUND = crate::color::Color::hex(0x011627),
        EDITOR_FOREGROUND = crate::color::Color::hex(0xd6deeb),
        EDITOR_LINE_NUMBER_FOREGROUND = crate::color::Color::hex(0x4b6479),
        EDITOR_LINE_NUMBER_ACTIVE_FOREGROUND = crate::color::Color::hex(0xc5e4fd),
        EDITOR_CURSOR_FOREGROUND = crate::color::Color::hex(0x80a4c2),
        EDITOR_SELECTION_BACKGROUND = crate::color::Color::hex(0x1d3b53),
        EDITOR_SELECTION_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x5f7e9779),
        EDITOR_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x7e57c25a),
        EDITOR_WORD_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xf6bbe533),
        EDITOR_WORD_HIGHLIGHT_STRONG_BACKGROUND = crate::color::Color::hex_alpha(0xe2a2f433),
        EDITOR_FIND_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0x5f7e9779),
        EDITOR_FIND_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x1085bb5d),
        EDITOR_HOVER_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x7e57c25a),
        EDITOR_LINE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x28707d29),
        EDITOR_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x7e57c25a),
        EDITOR_INDENT_GUIDE_BACKGROUND = crate::color::Color::hex_alpha(0x5e81ce52),
        EDITOR_INDENT_GUIDE_ACTIVE_BACKGROUND = crate::color::Color::hex(0x7e97ac),
        EDITOR_RULER_FOREGROUND = crate::color::Color::hex_alpha(0x5e81ce52),
        EDITOR_CODE_LENS_FOREGROUND = crate::color::Color::hex_alpha(0x5e82ceb4),
        EDITOR_OVERVIEW_RULER_CURRENT_CONTENT_FOREGROUND = crate::color::Color::hex(0x7e57c2),
        EDITOR_OVERVIEW_RULER_INCOMING_CONTENT_FOREGROUND = crate::color::Color::hex(0x7e57c2),
        EDITOR_OVERVIEW_RULER_COMMON_CONTENT_FOREGROUND = crate::color::Color::hex(0x7e57c2),
        EDITOR_ERROR_FOREGROUND = crate::color::Color::hex(0xef5350),
        EDITOR_WARNING_FOREGROUND = crate::color::Color::hex(0xb39554),
        EDITOR_GUTTER_BACKGROUND = crate::color::Color::hex(0x011627),
        EDITOR_GUTTER_MODIFIED_BACKGROUND = crate::color::Color::hex(0xe2b93d),
        EDITOR_GUTTER_ADDED_BACKGROUND = crate::color::Color::hex(0x9ccc65),
        EDITOR_GUTTER_DELETED_BACKGROUND = crate::color::Color::hex(0xef5350),
        EDITOR_INLAY_HINT_BACKGROUND = crate::color::Color::hex_alpha(0x00000000),
        EDITOR_INLAY_HINT_FOREGROUND = crate::color::Color::hex(0x829d9d),
        DIFF_EDITOR_INSERTED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0x99b76d23),
        DIFF_EDITOR_REMOVED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0xef535033),
        EDITOR_WIDGET_BACKGROUND = crate::color::Color::hex(0x021320),
        EDITOR_WIDGET_BORDER = crate::color::Color::hex(0x5f7e97),
        EDITOR_SUGGEST_WIDGET_BACKGROUND = crate::color::Color::hex(0x2c3043),
        EDITOR_SUGGEST_WIDGET_BORDER = crate::color::Color::hex(0x2b2f40),
        EDITOR_SUGGEST_WIDGET_FOREGROUND = crate::color::Color::hex(0xd6deeb),
        EDITOR_SUGGEST_WIDGET_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_SUGGEST_WIDGET_SELECTED_BACKGROUND = crate::color::Color::hex(0x5f7e97),
        EDITOR_HOVER_WIDGET_BACKGROUND = crate::color::Color::hex(0x011627),
        EDITOR_HOVER_WIDGET_BORDER = crate::color::Color::hex(0x5f7e97),
        DEBUG_EXCEPTION_WIDGET_BACKGROUND = crate::color::Color::hex(0x011627),
        DEBUG_EXCEPTION_WIDGET_BORDER = crate::color::Color::hex(0x5f7e97),
        EDITOR_MARKER_NAVIGATION_BACKGROUND = crate::color::Color::hex(0x0b2942),
        EDITOR_MARKER_NAVIGATION_ERROR_BACKGROUND = crate::color::Color::hex(0xef5350),
        EDITOR_MARKER_NAVIGATION_WARNING_BACKGROUND = crate::color::Color::hex(0xffca28),
        PEEK_VIEW_BORDER = crate::color::Color::hex(0x5f7e97),
        PEEK_VIEW_EDITOR_BACKGROUND = crate::color::Color::hex(0x011627),
        PEEK_VIEW_EDITOR_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x7e57c25a),
        PEEK_VIEW_RESULT_BACKGROUND = crate::color::Color::hex(0x011627),
        PEEK_VIEW_RESULT_FILE_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        PEEK_VIEW_RESULT_LINE_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        PEEK_VIEW_RESULT_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xffffffcc),
        PEEK_VIEW_RESULT_SELECTION_BACKGROUND = crate::color::Color::hex(0x2e3250),
        PEEK_VIEW_RESULT_SELECTION_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        PEEK_VIEW_TITLE_BACKGROUND = crate::color::Color::hex(0x011627),
        PEEK_VIEW_TITLE_DESCRIPTION_FOREGROUND = crate::color::Color::hex(0x697098),
        PEEK_VIEW_TITLE_LABEL_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        MERGE_CURRENT_HEADER_BACKGROUND = crate::color::Color::hex(0x5f7e97),
        MERGE_INCOMING_HEADER_BACKGROUND = crate::color::Color::hex_alpha(0x7e57c25a),
        PANEL_BACKGROUND = crate::color::Color::hex(0x011627),
        PANEL_BORDER = crate::color::Color::hex(0x5f7e97),
        PANEL_TITLE_ACTIVE_BORDER = crate::color::Color::hex(0x5f7e97),
        PANEL_TITLE_ACTIVE_FOREGROUND = crate::color::Color::hex_alpha(0xffffffcc),
        PANEL_TITLE_INACTIVE_FOREGROUND = crate::color::Color::hex_alpha(0xd6deeb80),
        STATUS_BAR_BACKGROUND = crate::color::Color::hex(0x011627),
        STATUS_BAR_FOREGROUND = crate::color::Color::hex(0x5f7e97),
        STATUS_BAR_BORDER = crate::color::Color::hex(0x262a39),
        STATUS_BAR_DEBUGGING_BACKGROUND = crate::color::Color::hex(0x202431),
        STATUS_BAR_DEBUGGING_BORDER = crate::color::Color::hex(0x1f2330),
        STATUS_BAR_NO_FOLDER_BACKGROUND = crate::color::Color::hex(0x011627),
        STATUS_BAR_NO_FOLDER_BORDER = crate::color::Color::hex(0x25293a),
        STATUS_BAR_ITEM_ACTIVE_BACKGROUND = crate::color::Color::hex(0x202431),
        STATUS_BAR_ITEM_HOVER_BACKGROUND = crate::color::Color::hex(0x202431),
        STATUS_BAR_ITEM_PROMINENT_BACKGROUND = crate::color::Color::hex(0x202431),
        STATUS_BAR_ITEM_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0x202431),
        TITLE_BAR_ACTIVE_BACKGROUND = crate::color::Color::hex(0x011627),
        TITLE_BAR_ACTIVE_FOREGROUND = crate::color::Color::hex(0xeeefff),
        TITLE_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x010e1a),
        NOTIFICATIONS_BACKGROUND = crate::color::Color::hex(0x01111d),
        NOTIFICATIONS_BORDER = crate::color::Color::hex(0x262a39),
        NOTIFICATION_CENTER_BORDER = crate::color::Color::hex(0x262a39),
        NOTIFICATION_TOAST_BORDER = crate::color::Color::hex(0x262a39),
        NOTIFICATIONS_FOREGROUND = crate::color::Color::hex_alpha(0xffffffcc),
        NOTIFICATION_LINK_FOREGROUND = crate::color::Color::hex(0x80cbc4),
        EXTENSION_BUTTON_PROMINENT_FOREGROUND = crate::color::Color::hex_alpha(0xffffffcc),
        EXTENSION_BUTTON_PROMINENT_BACKGROUND = crate::color::Color::hex_alpha(0x7e57c2cc),
        EXTENSION_BUTTON_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0x7e57c2),
        PICKER_GROUP_FOREGROUND = crate::color::Color::hex(0xd1aaff),
        PICKER_GROUP_BORDER = crate::color::Color::hex(0x011627),
        TERMINAL_ANSI_WHITE = crate::color::Color::hex(0xffffff),
        TERMINAL_ANSI_BLACK = crate::color::Color::hex(0x011627),
        TERMINAL_ANSI_BLUE = crate::color::Color::hex(0x82aaff),
        TERMINAL_ANSI_CYAN = crate::color::Color::hex(0x21c7a8),
        TERMINAL_ANSI_GREEN = crate::color::Color::hex(0x22da6e),
        TERMINAL_ANSI_MAGENTA = crate::color::Color::hex(0xc792ea),
        TERMINAL_ANSI_RED = crate::color::Color::hex(0xef5350),
        TERMINAL_ANSI_YELLOW = crate::color::Color::hex(0xc5e478),
        TERMINAL_ANSI_BRIGHT_WHITE = crate::color::Color::hex(0xffffff),
        TERMINAL_ANSI_BRIGHT_BLACK = crate::color::Color::hex(0x575656),
        TERMINAL_ANSI_BRIGHT_BLUE = crate::color::Color::hex(0x82aaff),
        TERMINAL_ANSI_BRIGHT_CYAN = crate::color::Color::hex(0x7fdbca),
        TERMINAL_ANSI_BRIGHT_GREEN = crate::color::Color::hex(0x22da6e),
        TERMINAL_ANSI_BRIGHT_MAGENTA = crate::color::Color::hex(0xc792ea),
        TERMINAL_ANSI_BRIGHT_RED = crate::color::Color::hex(0xef5350),
        TERMINAL_ANSI_BRIGHT_YELLOW = crate::color::Color::hex(0xffeb95),
        TERMINAL_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x1b90dd4d),
        TERMINAL_CURSOR_BACKGROUND = crate::color::Color::hex(0x234d70),
        TEXT_CODE_BLOCK_BACKGROUND = crate::color::Color::hex(0x4f4f4f),
        DEBUG_TOOL_BAR_BACKGROUND = crate::color::Color::hex(0x011627),
        WELCOME_PAGE_BUTTON_BACKGROUND = crate::color::Color::hex(0x011627),
        WELCOME_PAGE_BUTTON_HOVER_BACKGROUND = crate::color::Color::hex(0x011627),
        WALK_THROUGH_EMBEDDED_EDITOR_BACKGROUND = crate::color::Color::hex(0x011627),
        GIT_DECORATION_MODIFIED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xa2bffc),
        GIT_DECORATION_DELETED_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0xef535090),
        GIT_DECORATION_UNTRACKED_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0xc5e478ff),
        GIT_DECORATION_IGNORED_RESOURCE_FOREGROUND = crate::color::Color::hex(0x395a75),
        GIT_DECORATION_CONFLICTING_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0xffeb95cc),
        SOURCE_ELM = crate::color::Color::hex(0x5f7e97),
        STRING_QUOTED_SINGLE_JS = crate::color::Color::hex(0xffffff),
        META_OBJECTLITERAL_JS = crate::color::Color::hex(0x82aaff),
        TOKEN_CHANGED = crate::color::Color::hex(0xa2bffc),
        TOKEN_DELETED = crate::color::Color::hex_alpha(0xef535090),
        TOKEN_INSERTED = crate::color::Color::hex_alpha(0xc5e478ff),
        TOKEN_GLOBAL_SETTINGS = crate::color::Color::hex(0xd6deeb),
        TOKEN_COMMENT = crate::color::Color::hex(0x637777),
        TOKEN_STRING = crate::color::Color::hex(0xecc48d),
        TOKEN_STRING_QUOTED = crate::color::Color::hex(0xecc48d),
        TOKEN_SUPPORT_CONSTANT_MATH = crate::color::Color::hex(0xc5e478),
        TOKEN_NUMBER = crate::color::Color::hex(0xf78c6c),
        TOKEN_BUILT_IN_CONSTANT = crate::color::Color::hex(0x82aaff),
        TOKEN_USER_DEFINED_CONSTANT = crate::color::Color::hex(0x82aaff),
        TOKEN_CONSTANT_CHARACTER_ESCAPE = crate::color::Color::hex(0xf78c6c),
        TOKEN_REG_EXP_STRING = crate::color::Color::hex(0x5ca7e4),
        TOKEN_COMMA_IN_FUNCTIONS = crate::color::Color::hex(0x5f7e97),
        TOKEN_VARIABLE = crate::color::Color::hex(0xc5e478),
        TOKEN_KEYWORD = crate::color::Color::hex(0xc792ea),
        TOKEN_STORAGE = crate::color::Color::hex(0xc792ea),
        TOKEN_STORAGE_TYPE = crate::color::Color::hex(0xc792ea),
        TOKEN_CLASS_NAME = crate::color::Color::hex(0xffcb8b),
        TOKEN_INHERITED_CLASS = crate::color::Color::hex(0xc5e478),
        TOKEN_FUNCTION_NAME = crate::color::Color::hex(0xc792ea),
        TOKEN_META_TAG = crate::color::Color::hex(0x7fdbca),
        TOKEN_HTML_TAG_NAMES = crate::color::Color::hex(0xcaece6),
        TOKEN_TAG_ATTRIBUTE = crate::color::Color::hex(0xc5e478),
        TOKEN_ENTITY_NAME_TAG_CUSTOM = crate::color::Color::hex(0xf78c6c),
        TOKEN_LIBRARY_FUNCTION_CONSTANT = crate::color::Color::hex(0x82aaff),
        TOKEN_SUPPORT_CONSTANT_PROPERTY_VALUE_META = crate::color::Color::hex(0x7fdbca),
        TOKEN_LIBRARY_CLASS_TYPE = crate::color::Color::hex(0xc5e478),
        TOKEN_SUPPORT_VARIABLE_DOM = crate::color::Color::hex(0xc5e478),
        TOKEN_INVALID = crate::color::Color::hex(0xffffff),
        TOKEN_INVALID_DEPRECATED = crate::color::Color::hex(0xffffff),
        TOKEN_KEYWORD_OPERATOR = crate::color::Color::hex(0x7fdbca),
        TOKEN_KEYWORD_OPERATOR_RELATIONAL = crate::color::Color::hex(0xc792ea),
        TOKEN_KEYWORD_OPERATOR_ASSIGNMENT = crate::color::Color::hex(0xc792ea),
        TOKEN_KEYWORD_OPERATOR_ARITHMETIC = crate::color::Color::hex(0xc792ea),
        TOKEN_KEYWORD_OPERATOR_BITWISE = crate::color::Color::hex(0xc792ea),
        TOKEN_KEYWORD_OPERATOR_INCREMENT = crate::color::Color::hex(0xc792ea),
        TOKEN_KEYWORD_OPERATOR_TERNARY = crate::color::Color::hex(0xc792ea),
        TOKEN_DOUBLE_SLASHED_COMMENT = crate::color::Color::hex(0x637777),
        TOKEN_OBJECT = crate::color::Color::hex(0xcdebf7),
        TOKEN_NULL = crate::color::Color::hex(0xff5874),
        TOKEN_META_BRACE = crate::color::Color::hex(0xd6deeb),
        TOKEN_META_DELIMITER_PERIOD = crate::color::Color::hex(0xc792ea),
        TOKEN_PUNCTUATION_DEFINITION_STRING = crate::color::Color::hex(0xd9f5dd),
        TOKEN_PUNCTUATION_DEFINITION_STRING_MARKDOWN = crate::color::Color::hex(0xff5874),
        TOKEN_BOOLEAN = crate::color::Color::hex(0xff5874),
        TOKEN_OBJECT_COMMA = crate::color::Color::hex(0xffffff),
        TOKEN_VARIABLE_PARAMETER_FUNCTION = crate::color::Color::hex(0x7fdbca),
        TOKEN_SUPPORT_TYPE_PROPERTY_NAME_ENTITY_NAME_TAGS = crate::color::Color::hex(0x80cbc4),
        TOKEN_ENTITY_NAME_TAG_REFERENCE_IN_STYLESHEETS = crate::color::Color::hex(0x57eaf1),
        TOKEN_CONSTANT_OTHER_COLOR_RGB_VALUE_PUNCTUATION_DEFINITION_CONSTANT = crate::color::Color::hex(0xf78c6c),
        TOKEN_CONSTANT_OTHER_COLOR = crate::color::Color::hex(0xffeb95),
        TOKEN_KEYWORD_OTHER_UNIT = crate::color::Color::hex(0xffeb95),
        TOKEN_META_SELECTOR = crate::color::Color::hex(0xc792ea),
        TOKEN_ENTITY_OTHER_ATTRIBUTE_NAME_ID = crate::color::Color::hex(0xfad430),
        TOKEN_META_PROPERTY_NAME = crate::color::Color::hex(0x80cbc4),
        TOKEN_DOCTYPES = crate::color::Color::hex(0xc792ea),
        TOKEN_PUNCTUATION_DEFINITION_PARAMETERS = crate::color::Color::hex(0xd9f5dd),
        TOKEN_KEYWORD_CONTROL_OPERATOR = crate::color::Color::hex(0x7fdbca),
        TOKEN_KEYWORD_OPERATOR_LOGICAL = crate::color::Color::hex(0xc792ea),
        TOKEN_VARIABLE_INSTANCES = crate::color::Color::hex(0xbaebe2),
        TOKEN_VARIABLE_PROPERTY_OTHER_OBJECT_PROPERTY = crate::color::Color::hex(0xfaf39f),
        TOKEN_ENTITY_NAME_FUNCTION = crate::color::Color::hex(0x82aaff),
        TOKEN_THIS_KEYWORD_JS = crate::color::Color::hex(0x41eec6),
        TOKEN_KEYWORD_OPERATOR_COMPARISON_IMPORTS_RETURNS_AND_KEYWORD_OPERATOR_RUBY = crate::color::Color::hex(0xc792ea),
        TOKEN_KEYWORD_CONTROL_CONDITIONAL = crate::color::Color::hex(0xc792ea),
        TOKEN_SUPPORT_CONSTANT_NEW_KEYWORD_SPECIAL_METHOD_KEYWORD_DEBUGGER_OTHER_KEYWORDS = crate::color::Color::hex(0x7fdbca),
        TOKEN_SUPPORT_FUNCTION = crate::color::Color::hex(0xc5e478),
        TOKEN_INVALID_BROKEN = crate::color::Color::hex(0x020e14),
        TOKEN_INVALID_UNIMPLEMENTED = crate::color::Color::hex(0xffffff),
        TOKEN_INVALID_ILLEGAL = crate::color::Color::hex(0xffffff),
        TOKEN_LANGUAGE_VARIABLE = crate::color::Color::hex(0x7fdbca),
        TOKEN_SUPPORT_VARIABLE_PROPERTY = crate::color::Color::hex(0x7fdbca),
        TOKEN_VARIABLE_FUNCTION = crate::color::Color::hex(0x82aaff),
        TOKEN_VARIABLE_INTERPOLATION = crate::color::Color::hex(0xec5f67),
        TOKEN_META_FUNCTION_CALL = crate::color::Color::hex(0x82aaff),
        TOKEN_PUNCTUATION_SECTION_EMBEDDED = crate::color::Color::hex(0xd3423e),
        TOKEN_PUNCTUATION_TWEAKS = crate::color::Color::hex(0xd6deeb),
        TOKEN_MORE_PUNCTUATION_TWEAKS = crate::color::Color::hex(0xd9f5dd),
        TOKEN_TEMPLATE_STRINGS = crate::color::Color::hex(0xd3423e),
        TOKEN_BACKTICS_IN_TEMPLATE_STRINGS = crate::color::Color::hex(0xd6deeb),
        TOKEN_ITALICS = crate::color::Color::hex(0xc792ea),
        TOKEN_BOLD = crate::color::Color::hex(0xc5e478),
        TOKEN_QUOTE = crate::color::Color::hex(0x697098),
        TOKEN_RAW_CODE = crate::color::Color::hex(0x80cbc4),
        TOKEN_COFFE_SCRIPT_VARIABLE_ASSIGNMENT = crate::color::Color::hex(0x31e1eb),
        TOKEN_COFFE_SCRIPT_PARAMETER_FUNCTION = crate::color::Color::hex(0xd6deeb),
        TOKEN_COFFEE_SCRIPT_ASSIGNMENTS = crate::color::Color::hex(0x7fdbca),
        TOKEN_C_READWRITE_VARIABLES = crate::color::Color::hex(0xd6deeb),
        TOKEN_C_CLASSES_STORAGE_TYPES = crate::color::Color::hex(0xffcb8b),
        TOKEN_C_NAMESPACES = crate::color::Color::hex(0xb2ccd6),
        TOKEN_C_UNQUOTED_STRING_ZONE = crate::color::Color::hex(0xd6deeb),
        TOKEN_C_REGION = crate::color::Color::hex(0xffcb8b),
        TOKEN_C_OTHER_VARIABLES = crate::color::Color::hex(0xb2ccd6),
        TOKEN_C_ENUM = crate::color::Color::hex(0xc5e478),
        TOKEN_DART_STRING = crate::color::Color::hex(0xffcb8b),
        TOKEN_DART_CLASS = crate::color::Color::hex(0xffcb8b),
        TOKEN_TAG_NAMES_IN_STYLESHEETS = crate::color::Color::hex(0xff6363),
        TOKEN_WILDCARD_SELECTOR_IN_STYLESHEETS = crate::color::Color::hex(0x7fdbca),
        TOKEN_CSS_KEYWORD_OTHER_UNIT = crate::color::Color::hex(0xffeb95),
        TOKEN_ATTRIBUTE_NAME_FOR_CSS = crate::color::Color::hex(0xf78c6c),
        TOKEN_ELIXIR_CLASSES = crate::color::Color::hex(0x82aaff),
        TOKEN_ELIXIR_FUNCTIONS = crate::color::Color::hex(0xc5e478),
        TOKEN_ELIXIR_CONSTANTS = crate::color::Color::hex(0x82aaff),
        TOKEN_ELIXIR_STRING_PUNCTUATIONS = crate::color::Color::hex(0xc5e478),
        TOKEN_ELIXIR = crate::color::Color::hex(0xc5e478),
        TOKEN_ELIXIR_BINARY_PUNCTUATIONS = crate::color::Color::hex(0xc792ea),
        TOKEN_CLOSURE_CONSTANT_KEYWORD = crate::color::Color::hex(0x7fdbca),
        TOKEN_GO_FUNCTION_CALLS = crate::color::Color::hex(0xdddddd),
        TOKEN_GO_KEYWORDS = crate::color::Color::hex(0xc792ea),
        TOKEN_GO_CONSTANTS_E_G_NIL_STRING_FORMAT_S_D_ETC = crate::color::Color::hex(0xff5874),
        TOKEN_C_FUNCTIONS = crate::color::Color::hex_alpha(0x7fdbcaff),
        TOKEN_C_META_NAMESPACE = crate::color::Color::hex(0xe0dec6),
        TOKEN_C_LANGUAGE_PRIMITIVE_STORAGE = crate::color::Color::hex(0xff5874),
        TOKEN_C_PREPROCESSOR_MACRO = crate::color::Color::hex(0xd6deeb),
        TOKEN_C_VARIABLE_PARAMETER = crate::color::Color::hex(0xffcb8b),
        TOKEN_POWERSHELL_VARIABLES = crate::color::Color::hex(0x82aaff),
        TOKEN_POWERSHELL_FUNCTION = crate::color::Color::hex_alpha(0x7fdbcaff),
        TOKEN_ID_ATTRIBUTE_NAME_IN_HTML = crate::color::Color::hex(0xc5e478),
        TOKEN_HTML_PUNCTUATION_DEFINITION_TAG = crate::color::Color::hex(0x6ae9f0),
        TOKEN_HTML_DOCTYPE = crate::color::Color::hex(0xc792ea),
        TOKEN_JAVA_SCRIPT_CLASSES = crate::color::Color::hex(0xffcb8b),
        TOKEN_JAVA_SCRIPT_METHOD_DECLARATION_E_G_CONSTRUCTOR = crate::color::Color::hex(0x82aaff),
        TOKEN_JAVA_SCRIPT_TERMINATOR = crate::color::Color::hex(0xd6deeb),
        TOKEN_JAVA_SCRIPT_META_PUNCTUATION_DEFINITION = crate::color::Color::hex(0xd6deeb),
        TOKEN_ENTITY_NAMES_IN_CODE_DOCUMENTATIONS = crate::color::Color::hex(0x5f7e97),
        TOKEN_OTHER_VARIABLES_IN_CODE_DOCUMENTATIONS = crate::color::Color::hex(0x78ccf0),
        TOKEN_JAVA_SCRIPT_MODULE_IMPORTS_AND_EXPORTS = crate::color::Color::hex(0xd6deeb),
        TOKEN_JAVA_SCRIPT_VARIABLE_PARAMETER_FUNCTION = crate::color::Color::hex(0x7986e7),
        TOKEN_JAVA_SCRIPT_REACT_VARIABLE_OTHER_OBJECT = crate::color::Color::hex(0xd6deeb),
        TOKEN_JAVA_SCRIPT_VARIABLES = crate::color::Color::hex(0xd6deeb),
        TOKEN_JAVA_SCRIPT_ENTITY_NAME_TYPE = crate::color::Color::hex(0xffcb8b),
        TOKEN_JAVA_SCRIPT_SUPPORT_CLASSES = crate::color::Color::hex(0xd6deeb),
        TOKEN_JSON_PROPERTY_NAMES = crate::color::Color::hex(0x7fdbca),
        TOKEN_JSON_SUPPORT_CONSTANTS = crate::color::Color::hex(0xc5e478),
        TOKEN_JSON_PROPERTY_VALUES_STRING = crate::color::Color::hex(0xc789d6),
        TOKEN_STRINGS_IN_JSON_VALUES = crate::color::Color::hex(0x80cbc4),
        TOKEN_SPECIFIC_JSON_PROPERTY_VALUES_LIKE_NULL = crate::color::Color::hex(0xff5874),
        TOKEN_JAVA_SCRIPT_OTHER_VARIABLE = crate::color::Color::hex(0x7fdbca),
        TOKEN_RUBY_VARIABLES = crate::color::Color::hex(0xd6deeb),
        TOKEN_RUBY_CLASS = crate::color::Color::hex(0xecc48d),
        TOKEN_RUBY_HASHKEYS = crate::color::Color::hex(0x7fdbca),
        TOKEN_RUBY_SYMBOLS = crate::color::Color::hex(0x7fdbca),
        TOKEN_LESS_TAG_NAMES = crate::color::Color::hex(0x7fdbca),
        TOKEN_LESS_KEYWORD_OTHER_UNIT = crate::color::Color::hex(0xffeb95),
        TOKEN_ATTRIBUTE_NAME_FOR_LESS = crate::color::Color::hex(0xf78c6c),
        TOKEN_MARKDOWN_HEADINGS = crate::color::Color::hex(0x82b1ff),
        TOKEN_MARKDOWN_ITALICS = crate::color::Color::hex(0xc792ea),
        TOKEN_MARKDOWN_BOLD = crate::color::Color::hex(0xc5e478),
        TOKEN_MARKDOWN_QUOTE_OTHERS = crate::color::Color::hex(0x697098),
        TOKEN_MARKDOWN_RAW_CODE_OTHERS = crate::color::Color::hex(0x80cbc4),
        TOKEN_MARKDOWN_LINKS = crate::color::Color::hex(0xff869a),
        TOKEN_MARKDOWN_LINK_TITLE_AND_DESCRIPTION = crate::color::Color::hex(0xd6deeb),
        TOKEN_MARKDOWN_PUNCTUATION = crate::color::Color::hex(0x82b1ff),
        TOKEN_MARKDOWN_META_DATA_PUNCTUATION = crate::color::Color::hex(0x7fdbca),
        TOKEN_MARKDOWN_LIST_PUNCTUATION = crate::color::Color::hex(0x82b1ff),
        TOKEN_MARKDOWN_INLINE_RAW_STRING = crate::color::Color::hex(0xc5e478),
        TOKEN_PHP_VARIABLES = crate::color::Color::hex(0xbec5d4),
        TOKEN_SUPPORT_CLASSES_IN_PHP = crate::color::Color::hex(0xffcb8b),
        TOKEN_PUNCTUATIONS_IN_PHP_FUNCTION_CALLS = crate::color::Color::hex(0xd6deeb),
        TOKEN_PHP_GLOBAL_VARIABLES = crate::color::Color::hex(0xc5e478),
        TOKEN_DECLARATION_PUNCTUATION_IN_PHP_GLOBAL_VARIABLES = crate::color::Color::hex(0xc5e478),
        TOKEN_LANGUAGE_CONSTANTS_IN_PYTHON = crate::color::Color::hex(0xff5874),
        TOKEN_PYTHON_FUNCTION_PARAMETER_AND_ARGUMENTS = crate::color::Color::hex(0x82aaff),
        TOKEN_PYTHON_FUNCTION_CALL = crate::color::Color::hex(0xb2ccd6),
        TOKEN_PUNCTUATIONS_IN_PYTHON = crate::color::Color::hex(0xd6deeb),
        TOKEN_DECORATOR_FUNCTIONS_IN_PYTHON = crate::color::Color::hex(0xc5e478),
        TOKEN_PYTHON_LANGUAGE_VARIABLE = crate::color::Color::hex(0x8eace3),
        TOKEN_PYTHON_IMPORT_CONTROL_KEYWORD = crate::color::Color::hex(0xc792ea),
        TOKEN_SCSS_VARIABLE = crate::color::Color::hex(0xc5e478),
        TOKEN_VARIABLES_IN_SASS_AT_RULES = crate::color::Color::hex(0xbec5d4),
        TOKEN_ATTRIBUTE_NAME_FOR_SASS = crate::color::Color::hex(0xf78c6c),
        TOKEN_TAG_NAMES_IN_SASS = crate::color::Color::hex(0x7fdbca),
        TOKEN_SASS_KEYWORD_OTHER_UNIT = crate::color::Color::hex(0xffeb95),
        TOKEN_TYPE_SCRIPT_REACT_VARIABLES_AND_OBJECT_PROPERTIES = crate::color::Color::hex(0xd6deeb),
        TOKEN_TYPE_SCRIPT_REACT_ENTITY_NAME_TYPES = crate::color::Color::hex(0xffcb8b),
        TOKEN_TYPE_SCRIPT_REACT_NODE_CLASSES = crate::color::Color::hex(0x82aaff),
        TOKEN_TYPE_SCRIPT_REACT_ENTITY_NAME_TYPES_AS_PARAMETERS = crate::color::Color::hex(0x5f7e97),
        TOKEN_TYPE_SCRIPT_REACT_IMPORT_EXPORT_PUNCTUATIONS = crate::color::Color::hex(0xd6deeb),
        TOKEN_TYPE_SCRIPT_REACT_PUNCTUATION_DECORATORS = crate::color::Color::hex(0x82aaff),
        TOKEN_YAML_ENTITY_NAME_TAGS = crate::color::Color::hex(0x7fdbca),
        TOKEN_JAVA_SCRIPT_VARIABLE_OTHER_READ_WRITE = crate::color::Color::hex(0xd7dbe0),
        TOKEN_SUPPORT_CLASS_COMPONENT = crate::color::Color::hex(0xf78c6c),
        TOKEN_TEXT_NESTED_IN_REACT_TAGS = crate::color::Color::hex(0xd6deeb),
        TOKEN_TYPE_SCRIPT_CLASSES = crate::color::Color::hex(0xffcb8b),
        TOKEN_TYPE_SCRIPT_ENTITY_NAME_TYPE = crate::color::Color::hex(0xffcb8b),
        TOKEN_TYPE_SCRIPT_CLASS_VARIABLE_KEYWORD = crate::color::Color::hex(0xc792ea),
        TOKEN_TYPE_SCRIPT_METHOD_DECLARATION_E_G_CONSTRUCTOR = crate::color::Color::hex(0x82aaff),
        TOKEN_TEXTMATE_DELETED = crate::color::Color::hex(0xff0000),
        TOKEN_TEXTMATE_INSERTED = crate::color::Color::hex(0x036a07),
    }
    accents {
        Red = TERMINAL_ANSI_RED => ("red", "Red"),
        Green = TERMINAL_ANSI_GREEN => ("green", "Green"),
        Yellow = TERMINAL_ANSI_YELLOW => ("yellow", "Yellow"),
        Blue = TERMINAL_ANSI_BLUE => ("blue", "Blue"),
        Magenta = TERMINAL_ANSI_MAGENTA => ("magenta", "Magenta"),
        Cyan = TERMINAL_ANSI_CYAN => ("cyan", "Cyan"),
    }
    default TERMINAL_ANSI_BLUE => "blue";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BACKGROUND,
            surface: Self::SIDE_BAR_BACKGROUND,
            raised: Self::DROPDOWN_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::SIDE_BAR_BACKGROUND,
            surface: Self::EDITOR_BACKGROUND,
            raised: Self::SIDE_BAR_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::EDITOR_FOREGROUND,
            muted: Self::FOREGROUND,
            subtle: Self::EDITOR_LINE_NUMBER_FOREGROUND,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::TERMINAL_ANSI_MAGENTA),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::SIDE_BAR_BACKGROUND,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::TERMINAL_ANSI_MAGENTA,
            hover: crate::palette::primary_hover(Self::TERMINAL_ANSI_MAGENTA),
            pressed: crate::palette::action_pressed(Self::TERMINAL_ANSI_MAGENTA),
            muted: Self::SIDE_BAR_BACKGROUND,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::TERMINAL_ANSI_GREEN,
            warning: Self::EDITOR_WARNING_FOREGROUND,
            error: Self::EDITOR_ERROR_FOREGROUND,
            critical: Self::TERMINAL_ANSI_BRIGHT_RED,
            info: Self::TERMINAL_ANSI_BLUE,
            trace: Self::EDITOR_LINE_NUMBER_FOREGROUND,
        },
        border: Self::EDITOR_WIDGET_BORDER,
        border_muted: Self::SIDE_BAR_BACKGROUND,
        focus: primary,
    }
}
