//! Quiet Light. See `REGISTRATION` for pinned upstream sources.
//!
//! Quiet Light is its own family. Source syntax foreground and named token colours supply readable statuses; pale validation borders are not used as status text.

define_palette! {
    Main, "Quiet Light",
    identity("quiet_light/main", "quiet_light", "Quiet Light", "main", "Main", Light, None);
    support(Light);
    sources: super::SOURCE;
    colors {
        FOCUS_BORDER = crate::color::Color::hex(0x9769dc),
        AGENTS_BACKGROUND = crate::color::Color::hex(0xededf5),
        AGENTS_PANEL_BORDER = crate::color::Color::hex_alpha(0xc9d0d966),
        AGENTS_PANEL_BACKGROUND = crate::color::Color::hex(0xf5f5f5),
        AGENTS_CHAT_INPUT_BORDER = crate::color::Color::hex(0xc9d0d9),
        AGENTS_CHAT_INPUT_FOCUS_BORDER = crate::color::Color::hex(0x9769dc),
        AGENTS_NEW_SESSION_BUTTON_BORDER = crate::color::Color::hex(0xc9d0d9),
        PICKER_GROUP_FOREGROUND = crate::color::Color::hex(0xa6b39b),
        PICKER_GROUP_BORDER = crate::color::Color::hex(0x749351),
        LIST_ACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0x6c6c6c),
        QUICK_INPUT_LIST_FOCUS_BACKGROUND = crate::color::Color::hex(0xcadeb9),
        LIST_HOVER_BACKGROUND = crate::color::Color::hex(0xe0e0e0),
        LIST_ACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0xc4d9b1),
        LIST_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0xd3dbcd),
        LIST_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0x9769dc),
        LIST_WARNING_FOREGROUND = crate::color::Color::hex(0x765500),
        SELECTION_BACKGROUND = crate::color::Color::hex(0xc9d0d9),
        EDITOR_BACKGROUND = crate::color::Color::hex(0xf5f5f5),
        EDITOR_WHITESPACE_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        EDITOR_LINE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0xe4f6d4),
        EDITOR_LINE_NUMBER_ACTIVE_FOREGROUND = crate::color::Color::hex(0x9769dc),
        EDITOR_SELECTION_BACKGROUND = crate::color::Color::hex(0xc9d0d9),
        MINIMAP_SELECTION_HIGHLIGHT = crate::color::Color::hex(0xc9d0d9),
        PANEL_BACKGROUND = crate::color::Color::hex(0xf5f5f5),
        PANEL_SECTION_BORDER = crate::color::Color::hex(0xc9d0d9),
        PANEL_SECTION_HEADER_BORDER = crate::color::Color::hex(0xc9d0d9),
        SIDE_BAR_BACKGROUND = crate::color::Color::hex(0xf2f2f2),
        SIDE_BAR_SECTION_HEADER_BACKGROUND = crate::color::Color::hex(0xede8ef),
        SIDE_BAR_SECTION_HEADER_BORDER = crate::color::Color::hex(0xc9d0d9),
        EDITOR_LINE_NUMBER_FOREGROUND = crate::color::Color::hex(0x6d705b),
        EDITOR_CURSOR_FOREGROUND = crate::color::Color::hex(0x54494b),
        INPUT_OPTION_ACTIVE_BORDER = crate::color::Color::hex(0xadafb7),
        DROPDOWN_BACKGROUND = crate::color::Color::hex(0xf5f5f5),
        EDITOR_FIND_MATCH_BACKGROUND = crate::color::Color::hex(0xbf9cac),
        EDITOR_FIND_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xedc9d899),
        PEEK_VIEW_EDITOR_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0xc2dfe3),
        PEEK_VIEW_TITLE_BACKGROUND = crate::color::Color::hex(0xf2f8fc),
        PEEK_VIEW_EDITOR_BACKGROUND = crate::color::Color::hex(0xf2f8fc),
        PEEK_VIEW_RESULT_BACKGROUND = crate::color::Color::hex(0xf2f8fc),
        PEEK_VIEW_BORDER = crate::color::Color::hex(0x705697),
        PEEK_VIEW_RESULT_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x93c6d6),
        EDITOR_GROUP_HEADER_TABS_BACKGROUND = crate::color::Color::hex(0xe4e4e4),
        TAB_INACTIVE_BACKGROUND = crate::color::Color::hex(0xe4e4e4),
        TAB_INACTIVE_FOREGROUND = crate::color::Color::hex(0x54494b),
        TAB_UNFOCUSED_INACTIVE_FOREGROUND = crate::color::Color::hex(0x54494b),
        TAB_HOVER_BACKGROUND = crate::color::Color::hex(0xf2f2f2),
        TAB_LAST_PINNED_BORDER = crate::color::Color::hex(0xc9d0d9),
        STATUS_BAR_BACKGROUND = crate::color::Color::hex(0x705697),
        STATUS_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x715d91),
        WELCOME_PAGE_TILE_BACKGROUND = crate::color::Color::hex(0xf0f0f7),
        STATUS_BAR_NO_FOLDER_BACKGROUND = crate::color::Color::hex(0x705697),
        STATUS_BAR_DEBUGGING_BACKGROUND = crate::color::Color::hex(0x705697),
        STATUS_BAR_ITEM_REMOTE_BACKGROUND = crate::color::Color::hex(0x4e3c69),
        PORTS_ICON_RUNNING_PROCESS_FOREGROUND = crate::color::Color::hex(0x749351),
        ACTIVITY_BAR_BACKGROUND = crate::color::Color::hex(0xededf5),
        ACTIVITY_BAR_FOREGROUND = crate::color::Color::hex(0x705697),
        ACTIVITY_BAR_BADGE_BACKGROUND = crate::color::Color::hex(0x705697),
        TITLE_BAR_ACTIVE_BACKGROUND = crate::color::Color::hex(0xc4b7d7),
        TITLE_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0xd6cfe2),
        BUTTON_BACKGROUND = crate::color::Color::hex(0x705697),
        EDITOR_GROUP_DROP_BACKGROUND = crate::color::Color::hex_alpha(0xc9d0d988),
        INPUT_VALIDATION_INFO_BORDER = crate::color::Color::hex(0x4ec1e5),
        INPUT_VALIDATION_INFO_BACKGROUND = crate::color::Color::hex(0xf2fcff),
        INPUT_VALIDATION_WARNING_BACKGROUND = crate::color::Color::hex(0xfffee2),
        INPUT_VALIDATION_WARNING_BORDER = crate::color::Color::hex(0xffe055),
        INPUT_VALIDATION_ERROR_BACKGROUND = crate::color::Color::hex(0xffeaea),
        INPUT_VALIDATION_ERROR_BORDER = crate::color::Color::hex(0xf1897f),
        ERROR_FOREGROUND = crate::color::Color::hex(0xf1897f),
        BADGE_BACKGROUND = crate::color::Color::hex_alpha(0x705697aa),
        PROGRESS_BAR_BACKGROUND = crate::color::Color::hex(0x705697),
        WALK_THROUGH_EMBEDDED_EDITOR_BACKGROUND = crate::color::Color::hex_alpha(0x00000014),
        EDITOR_INDENT_GUIDE_BACKGROUND = crate::color::Color::hex_alpha(0xaaaaaa60),
        EDITOR_INDENT_GUIDE_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0x777777b0),
        MODERN_EDITOR_TAB_HOVER_FOREGROUND = crate::color::Color::hex(0x54494b),
        SURFACE_BORDER = crate::color::Color::hex_alpha(0x00000000),
        MODERN_SASH_GRIP_FOREGROUND = crate::color::Color::hex(0x705697),
        TOKEN_0 = crate::color::Color::hex(0x333333),
        TOKEN_1 = crate::color::Color::hex(0x333333),
        TOKEN_COMMENTS = crate::color::Color::hex(0xaaaaaa),
        TOKEN_COMMENTS_PREPROCESSOR = crate::color::Color::hex(0xaaaaaa),
        TOKEN_COMMENTS_DOCUMENTATION = crate::color::Color::hex(0x448c27),
        TOKEN_INVALID = crate::color::Color::hex(0xcd3131),
        TOKEN_INVALID_ILLEGAL = crate::color::Color::hex(0x660000),
        TOKEN_OPERATORS = crate::color::Color::hex(0x777777),
        TOKEN_KEYWORDS = crate::color::Color::hex(0x4b69c6),
        TOKEN_TYPES = crate::color::Color::hex(0x7a3e9d),
        TOKEN_LANGUAGE_CONSTANTS = crate::color::Color::hex(0x9c5d27),
        TOKEN_VARIABLES = crate::color::Color::hex(0x7a3e9d),
        TOKEN_FUNCTIONS = crate::color::Color::hex(0xaa3731),
        TOKEN_CLASSES = crate::color::Color::hex(0x7a3e9d),
        TOKEN_EXCEPTIONS = crate::color::Color::hex(0x660000),
        TOKEN_NUMBERS_CHARACTERS = crate::color::Color::hex(0x9c5d27),
        TOKEN_STRINGS = crate::color::Color::hex(0x448c27),
        TOKEN_STRINGS_ESCAPE_SEQUENCES = crate::color::Color::hex(0x777777),
        TOKEN_STRINGS_REGULAR_EXPRESSIONS = crate::color::Color::hex(0x4b69c6),
        TOKEN_STRINGS_SYMBOLS = crate::color::Color::hex(0x9c5d27),
        TOKEN_PUNCTUATION = crate::color::Color::hex(0x777777),
        TOKEN_HTML_DOCTYPE_DECLARATION = crate::color::Color::hex(0xaaaaaa),
        TOKEN_HTML_TAGS = crate::color::Color::hex(0x91b3e0),
        TOKEN_HTML_TAG_NAMES = crate::color::Color::hex(0x4b69c6),
        TOKEN_HTML_ATTRIBUTE_NAMES = crate::color::Color::hex(0x8190a0),
        TOKEN_HTML_ENTITIES = crate::color::Color::hex(0x9c5d27),
        TOKEN_CSS_SELECTORS = crate::color::Color::hex(0x7a3e9d),
        TOKEN_CSS_PROPERTY_NAMES = crate::color::Color::hex(0x9c5d27),
        TOKEN_CSS_PROPERTY_VALUES = crate::color::Color::hex(0x448c27),
        TOKEN_MARKUP_CHANGED = crate::color::Color::hex(0x000000),
        TOKEN_MARKUP_DELETION = crate::color::Color::hex(0x000000),
        TOKEN_MARKUP_ERROR = crate::color::Color::hex(0x660000),
        TOKEN_MARKUP_INSERTION = crate::color::Color::hex(0x000000),
        TOKEN_MARKUP_LINK = crate::color::Color::hex(0x4b69c6),
        TOKEN_MARKUP_OUTPUT = crate::color::Color::hex(0x777777),
        TOKEN_MARKUP_PROMPT = crate::color::Color::hex(0x777777),
        TOKEN_MARKUP_HEADING = crate::color::Color::hex(0xaa3731),
        TOKEN_MARKUP_TRACEBACK = crate::color::Color::hex(0x660000),
        TOKEN_MARKUP_QUOTE = crate::color::Color::hex(0x7a3e9d),
        TOKEN_MARKUP_LISTS = crate::color::Color::hex(0x4b69c6),
        TOKEN_MARKUP_STYLING = crate::color::Color::hex(0x448c27),
        TOKEN_MARKUP_INLINE = crate::color::Color::hex(0x9c5d27),
        TOKEN_EXTRA_DIFF_RANGE = crate::color::Color::hex(0x434343),
        TOKEN_EXTRA_DIFF_FROM = crate::color::Color::hex(0x4b69c6),
        TOKEN_EXTRA_DIFF_TO = crate::color::Color::hex(0x4b69c6),
        TOKEN_DIFF_DELETED = crate::color::Color::hex(0xc73d20),
        TOKEN_DIFF_CHANGED = crate::color::Color::hex(0x9c5d27),
        TOKEN_DIFF_INSERTED = crate::color::Color::hex(0x448c27),
        TOKEN_JSX_TAGS = crate::color::Color::hex(0x91b3e0),
        TOKEN_JSX_INNER_TEXT = crate::color::Color::hex_alpha(0x333333ff),
    }
    accents {
        Blue = TOKEN_KEYWORDS => ("blue", "Blue"),
        Purple = TOKEN_TYPES => ("purple", "Purple"),
        Green = TOKEN_STRINGS => ("green", "Green"),
        Red = TOKEN_FUNCTIONS => ("red", "Red"),
        Orange = TOKEN_NUMBERS_CHARACTERS => ("orange", "Orange"),
    }
    default TOKEN_TYPES => "purple";
    roles(primary) {
        surfaces: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BACKGROUND,
            base: Self::SIDE_BAR_BACKGROUND,
            raised: Self::SIDE_BAR_SECTION_HEADER_BACKGROUND,
            overlay: Self::DROPDOWN_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        surfaces_alt: crate::theme_variant::SurfaceColors {
            background: Self::ACTIVITY_BAR_BACKGROUND,
            base: Self::EDITOR_BACKGROUND,
            raised: Self::SIDE_BAR_BACKGROUND,
            overlay: Self::DROPDOWN_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::TOKEN_0,
            muted: Self::TOKEN_OPERATORS,
            subtle: Self::TOKEN_COMMENTS,
        },
        text_alt: None,
        primary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), primary),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::primary_hover(primary)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::action_pressed(primary)),
            muted: crate::theme_variant::ColorPair::new(Self::TOKEN_0, Self::SIDE_BAR_BACKGROUND),
            disabled: crate::theme_variant::ColorPair::new(Self::TOKEN_COMMENTS, Self::SIDE_BAR_BACKGROUND),
        },
        secondary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::BUTTON_BACKGROUND), Self::BUTTON_BACKGROUND),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::BUTTON_BACKGROUND), crate::palette::primary_hover(Self::BUTTON_BACKGROUND)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::BUTTON_BACKGROUND), crate::palette::action_pressed(Self::BUTTON_BACKGROUND)),
            muted: crate::theme_variant::ColorPair::new(Self::TOKEN_0, Self::SIDE_BAR_BACKGROUND),
            disabled: crate::theme_variant::ColorPair::new(Self::TOKEN_COMMENTS, Self::SIDE_BAR_BACKGROUND),
        },
        status: crate::theme_variant::StatusColors {
            success: Self::TOKEN_STRINGS,
            warning: Self::LIST_WARNING_FOREGROUND,
            error: Self::TOKEN_INVALID,
            critical: Self::TOKEN_INVALID_ILLEGAL,
            info: Self::TOKEN_KEYWORDS,
            debug: Self::TOKEN_OPERATORS,
            trace: Self::TOKEN_OPERATORS,
        },
        border: Self::PANEL_SECTION_BORDER,
        border_muted: Self::SIDE_BAR_BACKGROUND,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::TOKEN_FUNCTIONS,
            orange: Self::TOKEN_NUMBERS_CHARACTERS,
            yellow: Self::LIST_WARNING_FOREGROUND,
            green: Self::TOKEN_STRINGS,
            cyan: Self::TOKEN_HTML_TAGS,
            blue: Self::TOKEN_KEYWORDS,
            purple: Self::TOKEN_TYPES,
            pink: Self::TOKEN_FUNCTIONS,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::LIST_WARNING_FOREGROUND,
            boolean: Self::TOKEN_LANGUAGE_CONSTANTS,
            builtin: Self::LIST_WARNING_FOREGROUND,
            builtin_function: Self::TOKEN_FUNCTIONS,
            builtin_type: Self::TOKEN_TYPES,
            comment: Self::TOKEN_COMMENTS,
            constant: Self::TOKEN_NUMBERS_CHARACTERS,
            control_keyword: Self::TOKEN_KEYWORDS,
            deleted: Self::TOKEN_MARKUP_DELETION,
            deprecated: Self::TOKEN_INVALID,
            documentation: Self::TOKEN_COMMENTS_DOCUMENTATION,
            escape: Self::TOKEN_STRINGS_ESCAPE_SEQUENCES,
            foreground: Self::TOKEN_0,
            function: Self::TOKEN_FUNCTIONS,
            heading: Self::TOKEN_MARKUP_HEADING,
            inserted: Self::TOKEN_MARKUP_INSERTION,
            invalid: Self::TOKEN_INVALID,
            keyword: Self::TOKEN_KEYWORDS,
            link: Self::BUTTON_BACKGROUND,
            macro_name: Self::TOKEN_FUNCTIONS,
            markup_bold: Self::TOKEN_MARKUP_STYLING,
            markup_italic: Self::TOKEN_MARKUP_STYLING,
            modifier: Self::TOKEN_KEYWORDS,
            namespace: Self::TOKEN_CLASSES,
            number: Self::TOKEN_NUMBERS_CHARACTERS,
            operator: Self::TOKEN_OPERATORS,
            parameter: Self::TOKEN_VARIABLES,
            property: Self::TOKEN_VARIABLES,
            punctuation: Self::TOKEN_PUNCTUATION,
            string: Self::TOKEN_STRINGS,
            tag: Self::TOKEN_HTML_TAG_NAMES,
            type_keyword: Self::TOKEN_TYPES,
            type_name: Self::TOKEN_CLASSES,
            variable: Self::TOKEN_VARIABLES,
        },
    }
}
