//! Horizon. See `REGISTRATION` for pinned upstream sources.
//!
//! Editor UI keys supply surfaces and source alpha is retained. Terminal accents supply filled actions. Critical uses bright red. Trace uses normal foreground because the gutter
//! colour has too little contrast on the canvas. Roles that share an upstream colour intentionally repeat.

define_palette! {
    Main, "Horizon",
    identity("horizon/main", "horizon", "Horizon", "main", "Main", Dark, None);
    support(Dark);
    sources: super::SOURCE;
    colors {
        FOCUS_BORDER = crate::color::Color::hex(0x1a1c23),
        FOREGROUND = crate::color::Color::hex(0xd5d8da),
        WIDGET_SHADOW = crate::color::Color::hex(0x16161c),
        SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        ERROR_FOREGROUND = crate::color::Color::hex(0xf43e5c),
        TEXT_LINK_ACTIVE_FOREGROUND = crate::color::Color::hex(0xe9436d),
        TEXT_LINK_FOREGROUND = crate::color::Color::hex(0xe95378),
        BUTTON_BACKGROUND = crate::color::Color::hex(0x2e303e),
        DROPDOWN_BACKGROUND = crate::color::Color::hex(0x232530),
        DROPDOWN_LIST_BACKGROUND = crate::color::Color::hex(0x2e303e),
        INPUT_BACKGROUND = crate::color::Color::hex(0x2e303e),
        INPUT_OPTION_ACTIVE_BORDER = crate::color::Color::hex_alpha(0xe9436d80),
        INPUT_VALIDATION_ERROR_BACKGROUND = crate::color::Color::hex_alpha(0xf43e5c80),
        INPUT_VALIDATION_ERROR_BORDER = crate::color::Color::hex_alpha(0xf43e5c00),
        SCROLLBAR_SHADOW = crate::color::Color::hex(0x16161c),
        SCROLLBAR_SLIDER_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        SCROLLBAR_SLIDER_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f931a),
        SCROLLBAR_SLIDER_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f934d),
        BADGE_FOREGROUND = crate::color::Color::hex(0xd5d8da),
        BADGE_BACKGROUND = crate::color::Color::hex(0x2e303e),
        PROGRESS_BAR_BACKGROUND = crate::color::Color::hex(0xe95378),
        LIST_ACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x2e303e80),
        LIST_ACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xd5d8da),
        LIST_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        LIST_FOCUS_BACKGROUND = crate::color::Color::hex_alpha(0x2e303e80),
        LIST_FOCUS_FOREGROUND = crate::color::Color::hex(0xd5d8da),
        LIST_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xe95378),
        LIST_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x2e303e80),
        LIST_HOVER_FOREGROUND = crate::color::Color::hex(0xd5d8da),
        LIST_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x2e303e4d),
        LIST_INACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xd5d8da),
        LIST_INACTIVE_FOCUS_BACKGROUND = crate::color::Color::hex_alpha(0x2e303e80),
        LIST_ERROR_FOREGROUND = crate::color::Color::hex_alpha(0xf43e5ce6),
        LIST_WARNING_FOREGROUND = crate::color::Color::hex_alpha(0x27d797b3),
        ACTIVITY_BAR_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        ACTIVITY_BAR_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        ACTIVITY_BAR_FOREGROUND = crate::color::Color::hex_alpha(0xd5d8dab3),
        ACTIVITY_BAR_BADGE_BACKGROUND = crate::color::Color::hex(0xe95378),
        ACTIVITY_BAR_BADGE_FOREGROUND = crate::color::Color::hex(0x06060c),
        SIDE_BAR_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        SIDE_BAR_FOREGROUND = crate::color::Color::hex_alpha(0xd5d8da80),
        SIDE_BAR_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f934d),
        SIDE_BAR_SECTION_HEADER_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        SIDE_BAR_SECTION_HEADER_FOREGROUND = crate::color::Color::hex_alpha(0xd5d8dab3),
        EDITOR_GROUP_BORDER = crate::color::Color::hex(0x1a1c23),
        EDITOR_GROUP_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f934d),
        EDITOR_GROUP_HEADER_TABS_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        TAB_BORDER = crate::color::Color::hex_alpha(0x1c1e2600),
        TAB_ACTIVE_BORDER = crate::color::Color::hex(0xe95378),
        TAB_INACTIVE_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        EDITOR_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        EDITOR_LINE_NUMBER_FOREGROUND = crate::color::Color::hex_alpha(0xd5d8da1a),
        EDITOR_LINE_NUMBER_ACTIVE_FOREGROUND = crate::color::Color::hex_alpha(0xd5d8da80),
        EDITOR_CURSOR_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        EDITOR_CURSOR_FOREGROUND = crate::color::Color::hex(0xe95378),
        EDITOR_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x2e303eb3),
        EDITOR_SELECTION_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f934d),
        EDITOR_WORD_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        EDITOR_WORD_HIGHLIGHT_STRONG_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        EDITOR_FIND_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        EDITOR_FIND_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f934d),
        EDITOR_FIND_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f931a),
        EDITOR_HOVER_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f934d),
        EDITOR_LINE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x2e303e4d),
        EDITOR_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x2e303e80),
        EDITOR_INDENT_GUIDE_BACKGROUND = crate::color::Color::hex_alpha(0x2e303e80),
        EDITOR_INDENT_GUIDE_ACTIVE_BACKGROUND = crate::color::Color::hex(0x2e303e),
        EDITOR_RULER_FOREGROUND = crate::color::Color::hex_alpha(0x6c6f934d),
        EDITOR_CODE_LENS_FOREGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        EDITOR_BRACKET_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        EDITOR_BRACKET_MATCH_BORDER = crate::color::Color::hex_alpha(0x6c6f9300),
        EDITOR_OVERVIEW_RULER_BORDER = crate::color::Color::hex_alpha(0x2e303eb3),
        EDITOR_OVERVIEW_RULER_FIND_MATCH_FOREGROUND = crate::color::Color::hex(0x6c6f93),
        EDITOR_OVERVIEW_RULER_MODIFIED_FOREGROUND = crate::color::Color::hex_alpha(0x21bfc280),
        EDITOR_OVERVIEW_RULER_ADDED_FOREGROUND = crate::color::Color::hex_alpha(0x09f7a080),
        EDITOR_OVERVIEW_RULER_DELETED_FOREGROUND = crate::color::Color::hex_alpha(0xf43e5c80),
        EDITOR_OVERVIEW_RULER_ERROR_FOREGROUND = crate::color::Color::hex_alpha(0xf43e5ce6),
        EDITOR_OVERVIEW_RULER_WARNING_FOREGROUND = crate::color::Color::hex_alpha(0x27d79780),
        EDITOR_OVERVIEW_RULER_BRACKET_MATCH_FOREGROUND = crate::color::Color::hex_alpha(0xd5d8da80),
        EDITOR_ERROR_FOREGROUND = crate::color::Color::hex(0xf43e5c),
        EDITOR_WARNING_FOREGROUND = crate::color::Color::hex_alpha(0x27d797b3),
        EDITOR_GUTTER_MODIFIED_BACKGROUND = crate::color::Color::hex_alpha(0x21bfc2b3),
        EDITOR_GUTTER_ADDED_BACKGROUND = crate::color::Color::hex_alpha(0x09f7a0b3),
        EDITOR_GUTTER_DELETED_BACKGROUND = crate::color::Color::hex_alpha(0xf43e5cb3),
        DIFF_EDITOR_INSERTED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0x09f7a01a),
        DIFF_EDITOR_REMOVED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0xf43e5c1a),
        EDITOR_WIDGET_BACKGROUND = crate::color::Color::hex(0x232530),
        EDITOR_WIDGET_BORDER = crate::color::Color::hex(0x232530),
        EDITOR_SUGGEST_WIDGET_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xe95378),
        PEEK_VIEW_BORDER = crate::color::Color::hex(0x1a1c23),
        PEEK_VIEW_EDITOR_BACKGROUND = crate::color::Color::hex(0x232530),
        PEEK_VIEW_EDITOR_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        PEEK_VIEW_RESULT_BACKGROUND = crate::color::Color::hex(0x232530),
        PEEK_VIEW_RESULT_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        PEEK_VIEW_RESULT_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x2e303e80),
        PEEK_VIEW_TITLE_BACKGROUND = crate::color::Color::hex(0x232530),
        PANEL_TITLE_ACTIVE_BORDER = crate::color::Color::hex(0xe95378),
        STATUS_BAR_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        STATUS_BAR_FOREGROUND = crate::color::Color::hex_alpha(0xd5d8da80),
        STATUS_BAR_DEBUGGING_BACKGROUND = crate::color::Color::hex(0xfab38e),
        STATUS_BAR_DEBUGGING_FOREGROUND = crate::color::Color::hex(0x06060c),
        STATUS_BAR_NO_FOLDER_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        STATUS_BAR_ITEM_HOVER_BACKGROUND = crate::color::Color::hex(0x2e303e),
        STATUS_BAR_ITEM_PROMINENT_BACKGROUND = crate::color::Color::hex(0x2e303e),
        STATUS_BAR_ITEM_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0x6c6f93),
        TITLE_BAR_ACTIVE_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        TITLE_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        EXTENSION_BUTTON_PROMINENT_BACKGROUND = crate::color::Color::hex(0xe95378),
        EXTENSION_BUTTON_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0xe9436d),
        PICKER_GROUP_FOREGROUND = crate::color::Color::hex_alpha(0xe95378e6),
        TERMINAL_FOREGROUND = crate::color::Color::hex(0xd5d8da),
        TERMINAL_ANSI_BLUE = crate::color::Color::hex(0x26bbd9),
        TERMINAL_ANSI_BRIGHT_BLUE = crate::color::Color::hex(0x3fc4de),
        TERMINAL_ANSI_BRIGHT_CYAN = crate::color::Color::hex(0x6be4e6),
        TERMINAL_ANSI_BRIGHT_GREEN = crate::color::Color::hex(0x3fdaa4),
        TERMINAL_ANSI_BRIGHT_MAGENTA = crate::color::Color::hex(0xf075b5),
        TERMINAL_ANSI_BRIGHT_RED = crate::color::Color::hex(0xec6a88),
        TERMINAL_ANSI_BRIGHT_YELLOW = crate::color::Color::hex(0xfbc3a7),
        TERMINAL_ANSI_CYAN = crate::color::Color::hex(0x59e1e3),
        TERMINAL_ANSI_GREEN = crate::color::Color::hex(0x29d398),
        TERMINAL_ANSI_MAGENTA = crate::color::Color::hex(0xee64ac),
        TERMINAL_ANSI_RED = crate::color::Color::hex(0xe95678),
        TERMINAL_ANSI_YELLOW = crate::color::Color::hex(0xfab795),
        TERMINAL_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x6c6f934d),
        TERMINAL_CURSOR_BACKGROUND = crate::color::Color::hex(0xd5d8da),
        TERMINAL_CURSOR_FOREGROUND = crate::color::Color::hex_alpha(0x6c6f9380),
        DEBUG_TOOL_BAR_BACKGROUND = crate::color::Color::hex(0x1c1e26),
        WALK_THROUGH_EMBEDDED_EDITOR_BACKGROUND = crate::color::Color::hex(0x232530),
        GIT_DECORATION_ADDED_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0x27d797b3),
        GIT_DECORATION_MODIFIED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xfab38e),
        GIT_DECORATION_DELETED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xf43e5c),
        GIT_DECORATION_UNTRACKED_RESOURCE_FOREGROUND = crate::color::Color::hex(0x27d797),
        GIT_DECORATION_IGNORED_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0xd5d8da4d),
        BREADCRUMB_PICKER_BACKGROUND = crate::color::Color::hex(0x232530),
        TOKEN_COMMENTS = crate::color::Color::hex_alpha(0xbbbbbb4d),
        TOKEN_CONSTANTS = crate::color::Color::hex_alpha(0xf09483e6),
        TOKEN_ESCAPE_CHARACTERS = crate::color::Color::hex_alpha(0x25b0bce6),
        TOKEN_NAMED_ENTITIES = crate::color::Color::hex_alpha(0xfac29ae6),
        TOKEN_FUNCTION_NAMES = crate::color::Color::hex_alpha(0x25b0bce6),
        TOKEN_TAGS = crate::color::Color::hex_alpha(0xe95678e6),
        TOKEN_STATIC_TYPES = crate::color::Color::hex_alpha(0xfac29ae6),
        TOKEN_TAG_ATTRIBUTES = crate::color::Color::hex_alpha(0xf09483e6),
        TOKEN_INHERITED_CLASSES = crate::color::Color::hex_alpha(0xfab795e6),
        TOKEN_CSS_ID_SELECTORS = crate::color::Color::hex_alpha(0x25b0bce6),
        TOKEN_PSEUDO_CSS = crate::color::Color::hex_alpha(0xfab795e6),
        TOKEN_VARIABLE_NAMES = crate::color::Color::hex_alpha(0xe95678e6),
        TOKEN_KEYWORDS = crate::color::Color::hex_alpha(0xb877dbe6),
        TOKEN_OPERATORS = crate::color::Color::hex(0xbbbbbb),
        TOKEN_SPECIAL_OPERATORS = crate::color::Color::hex_alpha(0xb877dbe6),
        TOKEN_UNITS = crate::color::Color::hex_alpha(0xf09483e6),
        TOKEN_MARKUP_QUOTES = crate::color::Color::hex_alpha(0xfab795b3),
        TOKEN_MARKUP_HEADINGS = crate::color::Color::hex_alpha(0xe95678e6),
        TOKEN_MARKUP_BOLD = crate::color::Color::hex_alpha(0xb877dbe6),
        TOKEN_MARKUP_ITALICS = crate::color::Color::hex_alpha(0x25b0bce6),
        TOKEN_MARKUP_CODE = crate::color::Color::hex_alpha(0xf09483e6),
        TOKEN_MARKUP_LINKS = crate::color::Color::hex_alpha(0xfab795e6),
        TOKEN_STORAGE_KEYWORDS = crate::color::Color::hex_alpha(0xb877dbe6),
        TOKEN_STRINGS = crate::color::Color::hex_alpha(0xfab795e6),
        TOKEN_REGEX = crate::color::Color::hex_alpha(0xf09483e6),
        TOKEN_MARKUP_LINK_DESCRIPTIONS = crate::color::Color::hex_alpha(0xf09483e6),
        TOKEN_PROVIDED_SUPPORT_VALUES = crate::color::Color::hex_alpha(0xfac29ae6),
        TOKEN_PROVIDED_FUNCTIONS = crate::color::Color::hex_alpha(0x25b0bce6),
        TOKEN_PROVIEDED_VARIABLES = crate::color::Color::hex_alpha(0xe95678e6),
        TOKEN_OBJECT_JSON_PROPERTY_NAMES = crate::color::Color::hex_alpha(0xe95678e6),
        TOKEN_CSS_PROPERTY_NAMES = crate::color::Color::hex(0xbbbbbb),
        TOKEN_LANGUAGE_VARIABLES = crate::color::Color::hex_alpha(0xfac29ae6),
        TOKEN_EMBEDDED_TEMPLATE_PUNCTUATION = crate::color::Color::hex(0xbbbbbb),
        TOKEN_TAG_BRACKETS = crate::color::Color::hex_alpha(0xe95678b3),
        TOKEN_KEY_VALUE_SEPARATORS = crate::color::Color::hex(0xbbbbbb),
        TOKEN_TEMPLATE_EXPRESSIONS = crate::color::Color::hex_alpha(0xb877dbe6),
        TOKEN_EMBEDDED_SECTION_PUNCTUATION = crate::color::Color::hex_alpha(0xb877dbe6),
        TOKEN_MARKUP_LIST_PUNCTUATION = crate::color::Color::hex_alpha(0xf09483e6),
    }
    accents {
        Red = TERMINAL_ANSI_RED => ("red", "Red"),
        Green = TERMINAL_ANSI_GREEN => ("green", "Green"),
        Yellow = TERMINAL_ANSI_YELLOW => ("yellow", "Yellow"),
        Blue = TERMINAL_ANSI_BLUE => ("blue", "Blue"),
        Magenta = TERMINAL_ANSI_MAGENTA => ("magenta", "Magenta"),
        Cyan = TERMINAL_ANSI_CYAN => ("cyan", "Cyan"),
    }
    default TERMINAL_ANSI_MAGENTA => "magenta";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BACKGROUND,
            surface: Self::SIDE_BAR_BACKGROUND,
            raised: Self::DROPDOWN_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::SIDE_BAR_BACKGROUND,
            surface: Self::EDITOR_BACKGROUND,
            raised: Self::SIDE_BAR_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FOREGROUND,
            muted: Self::FOREGROUND,
            subtle: Self::EDITOR_LINE_NUMBER_FOREGROUND,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::TERMINAL_ANSI_MAGENTA),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::SIDE_BAR_BACKGROUND,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::TERMINAL_ANSI_MAGENTA,
            hover: crate::palette::primary_hover(Self::TERMINAL_ANSI_MAGENTA),
            pressed: crate::palette::action_pressed(Self::TERMINAL_ANSI_MAGENTA),
            muted: Self::SIDE_BAR_BACKGROUND,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::TERMINAL_ANSI_GREEN,
            warning: Self::TERMINAL_ANSI_YELLOW,
            error: Self::EDITOR_ERROR_FOREGROUND,
            critical: Self::TERMINAL_ANSI_BRIGHT_RED,
            info: Self::TERMINAL_ANSI_BLUE,
            trace: Self::FOREGROUND,
        },
        border: Self::EDITOR_WIDGET_BORDER,
        border_muted: Self::SIDE_BAR_BACKGROUND,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::TERMINAL_ANSI_RED,
            orange: Self::TERMINAL_ANSI_YELLOW,
            yellow: Self::TERMINAL_ANSI_YELLOW,
            green: Self::TERMINAL_ANSI_GREEN,
            cyan: Self::TERMINAL_ANSI_CYAN,
            blue: Self::TERMINAL_ANSI_BLUE,
            purple: Self::TERMINAL_ANSI_MAGENTA,
            pink: Self::TERMINAL_ANSI_MAGENTA,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::TOKEN_TAG_ATTRIBUTES,
            boolean: Self::TOKEN_CONSTANTS,
            builtin: Self::TOKEN_PROVIDED_SUPPORT_VALUES,
            builtin_function: Self::TOKEN_PROVIDED_FUNCTIONS,
            builtin_type: Self::TOKEN_PROVIDED_SUPPORT_VALUES,
            comment: Self::TOKEN_COMMENTS,
            constant: Self::TOKEN_CONSTANTS,
            control_keyword: Self::TOKEN_KEYWORDS,
            deleted: Self::EDITOR_ERROR_FOREGROUND,
            deprecated: Self::EDITOR_ERROR_FOREGROUND,
            documentation: Self::TOKEN_COMMENTS,
            escape: Self::TOKEN_ESCAPE_CHARACTERS,
            foreground: Self::FOREGROUND,
            function: Self::TOKEN_FUNCTION_NAMES,
            heading: Self::TOKEN_MARKUP_HEADINGS,
            inserted: Self::TERMINAL_ANSI_GREEN,
            invalid: Self::EDITOR_ERROR_FOREGROUND,
            keyword: Self::TOKEN_KEYWORDS,
            link: Self::TOKEN_MARKUP_LINKS,
            markup_bold: Self::TOKEN_MARKUP_BOLD,
            markup_italic: Self::TOKEN_MARKUP_ITALICS,
            modifier: Self::TOKEN_STORAGE_KEYWORDS,
            namespace: Self::TOKEN_NAMED_ENTITIES,
            number: Self::TOKEN_CONSTANTS,
            operator: Self::TOKEN_OPERATORS,
            parameter: Self::TOKEN_VARIABLE_NAMES,
            property: Self::TOKEN_VARIABLE_NAMES,
            punctuation: Self::FOREGROUND,
            string: Self::TERMINAL_ANSI_GREEN,
            tag: Self::TOKEN_TAGS,
            type_keyword: Self::TOKEN_STORAGE_KEYWORDS,
            type_name: Self::TOKEN_STATIC_TYPES,
            variable: Self::TOKEN_VARIABLE_NAMES,
        },
    }
}
