[package]
name = "ferriswatch-dioxus-example"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
dioxus = { workspace = true, features = ["launch", "web"] }
ferriswatch = { workspace = true, features = ["dioxus-components"] }
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = ["Window", "Navigator", "Clipboard"] }
