//! Darcula. See `REGISTRATION` for pinned upstream sources.
//!
//! Editor scheme inherits Default → Darcula → Dark as applicable. UI surfaces use each theme’s declared palette. Translucent Dark action hover is retained; Darcula has its own editor background and console colours.

define_palette! {
    Darcula, "Darcula",
    identity("jetbrains/darcula", "jetbrains", "JetBrains", "darcula", "Darcula", Dark, None);
    support(Dark);
    sources: super::SOURCE_DARCULA;
    colors {
        EDITOR_SELECTION_BACKGROUND = crate::color::Color::hex(0x214283),
        EDITOR_SELECTION_BACKGROUND_INACTIVE = crate::color::Color::hex(0x4c4f56),
        EDITOR_CARET_ROW_COLOR = crate::color::Color::hex(0x323232),
        EDITOR_GRID_STRIPE_COLOR = crate::color::Color::hex(0xf5f8fe),
        EDITOR_METHOD_SEPARATORS_COLOR = crate::color::Color::hex(0x4d4d4d),
        EDITOR_WHITESPACES = crate::color::Color::hex(0x606060),
        EDITOR_INDENT_GUIDE = crate::color::Color::hex(0x373737),
        EDITOR_GUTTER_BACKGROUND = crate::color::Color::hex(0x313335),
        EDITOR_DOCUMENTATION_COLOR = crate::color::Color::hex(0x46484a),
        EDITOR_LOOKUP_COLOR = crate::color::Color::hex(0x46484a),
        EDITOR_NOTIFICATION_BACKGROUND = crate::color::Color::hex(0x1d3857),
        EDITOR_SELECTED_INDENT_GUIDE = crate::color::Color::hex(0x505050),
        EDITOR_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_LINE_NUMBERS_COLOR = crate::color::Color::hex(0x606366),
        EDITOR_ANNOTATIONS_COLOR = crate::color::Color::hex(0x8b999f),
        EDITOR_RIGHT_MARGIN_COLOR = crate::color::Color::hex(0x4d4d4d),
        EDITOR_SOFT_WRAP_SIGN_COLOR = crate::color::Color::hex(0xc0c0c0),
        EDITOR_TEARLINE_COLOR = crate::color::Color::hex(0x555555),
        EDITOR_SELECTED_TEARLINE_COLOR = crate::color::Color::hex(0x787878),
        EDITOR_READONLY_FRAGMENT_BACKGROUND = crate::color::Color::hex(0xcfe7ff),
        EDITOR_VISUAL_INDENT_GUIDE = crate::color::Color::hex(0x3c3c3c),
        EDITOR_FOLDED_TEXT_BORDER_COLOR = crate::color::Color::hex(0x43474a),
        EDITOR_RECENT_LOCATIONS_SELECTION = crate::color::Color::hex(0x383838),
        EDITOR_DOC_COMMENT_GUIDE = crate::color::Color::hex(0x3b4b38),
        EDITOR_DOC_COMMENT_LINK = crate::color::Color::hex(0x4f86cd),
        EDITOR_INLINE_REFACTORING_SETTINGS_DEFAULT = crate::color::Color::hex_alpha(0x5959598c),
        EDITOR_INLINE_REFACTORING_SETTINGS_FOCUSED = crate::color::Color::hex_alpha(0x7373738c),
        EDITOR_INLINE_REFACTORING_SETTINGS_HOVERED = crate::color::Color::hex_alpha(0x7373738c),
        EDITOR_ADDED_LINES_COLOR = crate::color::Color::hex(0x384c38),
        EDITOR_MODIFIED_LINES_COLOR = crate::color::Color::hex(0x374752),
        EDITOR_DELETED_LINES_COLOR = crate::color::Color::hex(0x656e76),
        EDITOR_WHITESPACES_MODIFIED_LINES_COLOR = crate::color::Color::hex(0x4c4638),
        EDITOR_IGNORED_ADDED_LINES_BORDER_COLOR = crate::color::Color::hex(0x4c674c),
        EDITOR_IGNORED_MODIFIED_LINES_BORDER_COLOR = crate::color::Color::hex(0x455663),
        EDITOR_IGNORED_DELETED_LINES_BORDER_COLOR = crate::color::Color::hex(0x656e76),
        EDITOR_CONSOLE_BACKGROUND_KEY = crate::color::Color::hex(0x2b2b2b),
        EDITOR_DIFF_SEPARATOR_WAVE = crate::color::Color::hex(0x555555),
        EDITOR_STRING_CONTENT_INDENT_GUIDE = crate::color::Color::hex(0x4a5f3e),
        EDITOR_MODIFIED_TAB_ICON = crate::color::Color::hex(0x4083c9),
        EDITOR_FILESTATUS_ADDED = crate::color::Color::hex(0x629755),
        EDITOR_FILESTATUS_COPIED = crate::color::Color::hex(0x629755),
        EDITOR_FILESTATUS_DELETED = crate::color::Color::hex(0x6c6c6c),
        EDITOR_FILESTATUS_IDEA_FILESTATUS_DELETED_FROM_FILE_SYSTEM = crate::color::Color::hex(0x6c6c6c),
        EDITOR_FILESTATUS_IDEA_FILESTATUS_IGNORED = crate::color::Color::hex(0x848504),
        EDITOR_FILESTATUS_IDEA_FILESTATUS_MERGED_WITH_BOTH_CONFLICTS = crate::color::Color::hex(0xd5756c),
        EDITOR_FILESTATUS_IDEA_FILESTATUS_MERGED_WITH_CONFLICTS = crate::color::Color::hex(0xd5756c),
        EDITOR_FILESTATUS_IDEA_FILESTATUS_MERGED_WITH_PROPERTY_CONFLICTS = crate::color::Color::hex(0xd5756c),
        EDITOR_FILESTATUS_MERGED = crate::color::Color::hex(0x9876aa),
        EDITOR_FILESTATUS_MODIFIED = crate::color::Color::hex(0x6897bb),
        EDITOR_FILESTATUS_RENAMED = crate::color::Color::hex(0x3a8484),
        EDITOR_FILESTATUS_NOT_CHANGED_IMMEDIATE = crate::color::Color::hex(0x6897bb),
        EDITOR_FILESTATUS_NOT_CHANGED_RECURSIVE = crate::color::Color::hex(0x6897bb),
        EDITOR_FILESTATUS_UNKNOWN = crate::color::Color::hex(0xd1675a),
        EDITOR_FILESTATUS_ADDED_OUTSIDE = crate::color::Color::hex(0x629755),
        EDITOR_FILESTATUS_CHANGELIST_CONFLICT = crate::color::Color::hex(0xd5756c),
        EDITOR_FILESTATUS_MODIFIED_OUTSIDE = crate::color::Color::hex(0x6897bb),
        EDITOR_FILESTATUS_HIJACKED = crate::color::Color::hex(0xb28c00),
        EDITOR_FILESTATUS_OBSOLETE = crate::color::Color::hex(0x7c7c00),
        EDITOR_FILESTATUS_SWITCHED = crate::color::Color::hex(0x08978f),
        EDITOR_VCS_ANNOTATIONS_COLOR_1 = crate::color::Color::hex(0x464c43),
        EDITOR_VCS_ANNOTATIONS_COLOR_2 = crate::color::Color::hex(0x444342),
        EDITOR_VCS_ANNOTATIONS_COLOR_3 = crate::color::Color::hex(0x41444a),
        EDITOR_VCS_ANNOTATIONS_COLOR_4 = crate::color::Color::hex(0x484248),
        EDITOR_VCS_ANNOTATIONS_COLOR_5 = crate::color::Color::hex(0x4c393a),
        EDITOR_BLOCK_TERMINAL_BLOCK_BACKGROUND_START = crate::color::Color::hex(0x2b2d30),
        EDITOR_BLOCK_TERMINAL_BLOCK_BACKGROUND_END = crate::color::Color::hex(0x212329),
        EDITOR_BLOCK_TERMINAL_SELECTED_BLOCK_BACKGROUND = crate::color::Color::hex(0x25324d),
        EDITOR_BLOCK_TERMINAL_SELECTED_BLOCK_STROKE_COLOR = crate::color::Color::hex(0x3574f0),
        EDITOR_BLOCK_TERMINAL_HOVERED_BLOCK_BACKGROUND_START = crate::color::Color::hex_alpha(0xffffff0a),
        EDITOR_BLOCK_TERMINAL_HOVERED_BLOCK_BACKGROUND_END = crate::color::Color::hex_alpha(0xffffff03),
        EDITOR_BLOCK_TERMINAL_INACTIVE_SELECTED_BLOCK_BACKGROUND = crate::color::Color::hex(0x393b40),
        EDITOR_BLOCK_TERMINAL_INACTIVE_SELECTED_BLOCK_STROKE_COLOR = crate::color::Color::hex(0x5a5d63),
        EDITOR_BLOCK_TERMINAL_ERROR_BLOCK_STROKE_COLOR = crate::color::Color::hex(0xdb5c5c),
        EDITOR_BLOCK_TERMINAL_PROMPT_SEPARATOR_COLOR = crate::color::Color::hex(0x393b40),
        EDITOR_BLOCK_TERMINAL_GENERATE_COMMAND_PLACEHOLDER_FOREGROUND = crate::color::Color::hex(0x6c469c),
        EDITOR_BLOCK_TERMINAL_GENERATE_COMMAND_CARET_COLOR = crate::color::Color::hex(0x955ae0),
        EDITOR_TABLE_HOVER_BACKGROUND = crate::color::Color::hex(0x464a4d),
        EDITOR_BOOKMARK_ICON_BACKGROUND = crate::color::Color::hex(0xd9a343),
        EDITOR_BOOKMARK_MNEMONIC_ICON_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        EDITOR_BOOKMARK_MNEMONIC_ICON_BACKGROUND = crate::color::Color::hex(0x5b5341),
        EDITOR_BOOKMARK_MNEMONIC_ICON_BORDER_COLOR = crate::color::Color::hex(0xd9a343),
        EDITOR_SCROLL_BAR_BACKGROUND = crate::color::Color::hex(0x3f4244),
        EDITOR_SCROLL_BAR_TRACK_COLOR = crate::color::Color::hex_alpha(0x80808000),
        EDITOR_SCROLL_BAR_THUMB_COLOR = crate::color::Color::hex_alpha(0xa6a6a647),
        EDITOR_SCROLL_BAR_THUMB_BORDER_COLOR = crate::color::Color::hex_alpha(0x38383847),
        EDITOR_SCROLL_BAR_HOVER_TRACK_COLOR = crate::color::Color::hex_alpha(0x80808000),
        EDITOR_SCROLL_BAR_HOVER_THUMB_COLOR = crate::color::Color::hex_alpha(0xa6a6a659),
        EDITOR_SCROLL_BAR_HOVER_THUMB_BORDER_COLOR = crate::color::Color::hex_alpha(0x38383859),
        EDITOR_SCROLL_BAR_TRANSPARENT_TRACK_COLOR = crate::color::Color::hex_alpha(0x80808000),
        EDITOR_SCROLL_BAR_TRANSPARENT_THUMB_COLOR = crate::color::Color::hex_alpha(0xa6a6a647),
        EDITOR_SCROLL_BAR_TRANSPARENT_THUMB_BORDER_COLOR = crate::color::Color::hex_alpha(0x38383847),
        EDITOR_SCROLL_BAR_TRANSPARENT_HOVER_TRACK_COLOR = crate::color::Color::hex_alpha(0x8080801a),
        EDITOR_SCROLL_BAR_TRANSPARENT_HOVER_THUMB_COLOR = crate::color::Color::hex_alpha(0xa6a6a659),
        EDITOR_SCROLL_BAR_TRANSPARENT_HOVER_THUMB_BORDER_COLOR = crate::color::Color::hex_alpha(0x38383859),
        EDITOR_SCROLL_BAR_MAC_TRACK_COLOR = crate::color::Color::hex_alpha(0x80808000),
        EDITOR_SCROLL_BAR_MAC_THUMB_COLOR = crate::color::Color::hex_alpha(0x80808059),
        EDITOR_SCROLL_BAR_MAC_THUMB_BORDER_COLOR = crate::color::Color::hex_alpha(0x26262659),
        EDITOR_SCROLL_BAR_MAC_HOVER_TRACK_COLOR = crate::color::Color::hex_alpha(0x80808000),
        EDITOR_SCROLL_BAR_MAC_HOVER_THUMB_COLOR = crate::color::Color::hex_alpha(0x8080808c),
        EDITOR_SCROLL_BAR_MAC_HOVER_THUMB_BORDER_COLOR = crate::color::Color::hex_alpha(0x2626268c),
        EDITOR_SCROLL_BAR_MAC_TRANSPARENT_TRACK_COLOR = crate::color::Color::hex_alpha(0x80808000),
        EDITOR_SCROLL_BAR_MAC_TRANSPARENT_THUMB_COLOR = crate::color::Color::hex_alpha(0x80808000),
        EDITOR_SCROLL_BAR_MAC_TRANSPARENT_THUMB_BORDER_COLOR = crate::color::Color::hex_alpha(0x26262600),
        EDITOR_SCROLL_BAR_MAC_TRANSPARENT_HOVER_TRACK_COLOR = crate::color::Color::hex_alpha(0x8080801a),
        EDITOR_SCROLL_BAR_MAC_TRANSPARENT_HOVER_THUMB_COLOR = crate::color::Color::hex_alpha(0x8080808c),
        EDITOR_SCROLL_BAR_MAC_TRANSPARENT_HOVER_THUMB_BORDER_COLOR = crate::color::Color::hex_alpha(0x2626268c),
        EDITOR_SCROLLBAR_TABS_TRANSPARENT_THUMB_COLOR = crate::color::Color::hex_alpha(0x44434300),
        EDITOR_SCROLLBAR_TABS_THUMB_COLOR = crate::color::Color::hex_alpha(0x444343ff),
        EDITOR_SCROLLBAR_TABS_HOVERED_THUMB_COLOR = crate::color::Color::hex_alpha(0x555453ff),
        EDITOR_ACTION_BUTTON_HOVER_BACKGROUND = crate::color::Color::hex(0x4c5052),
        EDITOR_ACTION_BUTTON_PRESSED_BACKGROUND = crate::color::Color::hex(0x5c6164),
        EDITOR_ACTION_BUTTON_ICON_TEXT_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        EDITOR_DEBUGGER_SMART_STEP_INTO_TARGET_BACKGROUND = crate::color::Color::hex(0x53385e),
        EDITOR_DEBUGGER_SMART_STEP_INTO_TARGET_FOREGROUND = crate::color::Color::hex(0x000000),
        EDITOR_DEBUGGER_SMART_STEP_INTO_SELECTION_BACKGROUND = crate::color::Color::hex(0x824991),
        EDITOR_DEBUGGER_SMART_STEP_INTO_SELECTION_FOREGROUND = crate::color::Color::hex(0x000000),
        EDITOR_DEBUGGER_SMART_STEP_INTO_SELECTION_EFFECT_COLOR = crate::color::Color::hex(0xc76dc7),
        EDITOR_DEBUGGER_INLINED_VALUES_FOREGROUND = crate::color::Color::hex(0x666d75),
        EDITOR_DEBUGGER_INLINED_VALUES_EXECUTION_LINE_FOREGROUND = crate::color::Color::hex(0x7b94b3),
        EDITOR_DEBUGGER_INLINED_VALUES_MODIFIED_FOREGROUND = crate::color::Color::hex(0xca7e03),
        EDITOR_DEFAULT_TEMPLATE_LANGUAGE_COLOR_BACKGROUND = crate::color::Color::hex(0x232525),
        EDITOR_DEFAULT_IDENTIFIER_FOREGROUND = crate::color::Color::hex(0xa9b7c6),
        EDITOR_DEFAULT_INSTANCE_FIELD_FOREGROUND = crate::color::Color::hex(0x9876aa),
        EDITOR_DEFAULT_STATIC_FIELD_FOREGROUND = crate::color::Color::hex(0x9876aa),
        EDITOR_DEFAULT_CONSTANT_FOREGROUND = crate::color::Color::hex(0x9876aa),
        EDITOR_DEFAULT_REASSIGNED_PARAMETER_EFFECT_COLOR = crate::color::Color::hex(0x707d95),
        EDITOR_DEFAULT_REASSIGNED_LOCAL_VARIABLE_EFFECT_COLOR = crate::color::Color::hex(0x707d95),
        EDITOR_DEFAULT_LABEL_EFFECT_COLOR = crate::color::Color::hex(0x808080),
        EDITOR_DEFAULT_METADATA_FOREGROUND = crate::color::Color::hex(0xbbb529),
        EDITOR_DEFAULT_STRING_FOREGROUND = crate::color::Color::hex(0x6a8759),
        EDITOR_DEFAULT_KEYWORD_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_DEFAULT_NUMBER_FOREGROUND = crate::color::Color::hex(0x6897bb),
        EDITOR_DEFAULT_BLOCK_COMMENT_FOREGROUND = crate::color::Color::hex(0x808080),
        EDITOR_DEFAULT_LINE_COMMENT_FOREGROUND = crate::color::Color::hex(0x808080),
        EDITOR_DEFAULT_DOC_COMMENT_FOREGROUND = crate::color::Color::hex(0x629755),
        EDITOR_DEFAULT_DOC_MARKUP_BACKGROUND = crate::color::Color::hex(0xe2ffe2),
        EDITOR_DEFAULT_DOC_COMMENT_TAG_EFFECT_COLOR = crate::color::Color::hex(0x629755),
        EDITOR_DOC_TIPS_SHORTCUT_FOREGROUND = crate::color::Color::hex(0xafb1b3),
        EDITOR_DOC_TIPS_SHORTCUT_EFFECT_COLOR = crate::color::Color::hex(0x6f737a),
        EDITOR_DEFAULT_DOC_COMMENT_TAG_VALUE_FOREGROUND = crate::color::Color::hex(0x8a653b),
        EDITOR_DEFAULT_INVALID_STRING_ESCAPE_FOREGROUND = crate::color::Color::hex(0x6a8759),
        EDITOR_DEFAULT_INVALID_STRING_ESCAPE_BACKGROUND = crate::color::Color::hex(0xffcccc),
        EDITOR_DEFAULT_VALID_STRING_ESCAPE_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_DEFAULT_TAG_BACKGROUND = crate::color::Color::hex(0xefefef),
        EDITOR_DEFAULT_ATTRIBUTE_FOREGROUND = crate::color::Color::hex(0x0000ff),
        EDITOR_DEFAULT_ENTITY_FOREGROUND = crate::color::Color::hex(0x0000ff),
        EDITOR_DEFAULT_HIGHLIGHTED_REFERENCE_EFFECT_COLOR = crate::color::Color::hex(0x707d95),
        EDITOR_LINE_FULL_COVERAGE_FOREGROUND = crate::color::Color::hex(0x485848),
        EDITOR_LINE_PARTIAL_COVERAGE_FOREGROUND = crate::color::Color::hex(0x80805a),
        EDITOR_LINE_NONE_COVERAGE_FOREGROUND = crate::color::Color::hex(0x715353),
        EDITOR_FOLDED_TEXT_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x8c8c8c),
        EDITOR_FOLDED_TEXT_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x3a3a3a),
        EDITOR_DELETED_TEXT_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        EDITOR_DELETED_TEXT_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x450505),
        EDITOR_WRONG_REFERENCES_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xbc3f3c),
        EDITOR_ERRORS_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0xbc3f3c),
        EDITOR_FILESTATUS_ERRORS_EFFECT_COLOR = crate::color::Color::hex(0xbc3f3c),
        EDITOR_RUNTIME_ERROR_EFFECT_COLOR = crate::color::Color::hex(0xf49810),
        EDITOR_BLINKING_HIGHLIGHTS_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0x808080),
        EDITOR_HYPERLINK_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x287bde),
        EDITOR_HYPERLINK_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0x287bde),
        EDITOR_FOLLOWED_HYPERLINK_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x287bde),
        EDITOR_FOLLOWED_HYPERLINK_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0xe9e9e9),
        EDITOR_FOLLOWED_HYPERLINK_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0x287bde),
        EDITOR_INACTIVE_HYPERLINK_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0x707d95),
        EDITOR_WARNING_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x52503a),
        EDITOR_GENERIC_SERVER_ERROR_OR_WARNING_EFFECT_COLOR = crate::color::Color::hex(0xf49810),
        EDITOR_DUPLICATE_FROM_SERVER_BACKGROUND = crate::color::Color::hex(0x5e5339),
        EDITOR_INFO_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0xaeae80),
        EDITOR_DIFF_CONFLICT_BACKGROUND = crate::color::Color::hex(0x45302b),
        EDITOR_DIFF_DELETED_BACKGROUND = crate::color::Color::hex(0x484a4a),
        EDITOR_DIFF_INSERTED_BACKGROUND = crate::color::Color::hex(0x294436),
        EDITOR_DIFF_MODIFIED_BACKGROUND = crate::color::Color::hex(0x385570),
        EDITOR_DIFF_UNKNOWN_BACKGROUND = crate::color::Color::hex(0xdae7c0),
        EDITOR_DIFF_DELETED_FROM_FS_BACKGROUND = crate::color::Color::hex(0x387ee7),
        EDITOR_NOT_USED_ELEMENT_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x72737a),
        EDITOR_INLINE_SUGGESTION_FOREGROUND = crate::color::Color::hex(0x808080),
        EDITOR_INLINE_PARAMETER_HINT_FOREGROUND = crate::color::Color::hex(0x787878),
        EDITOR_INLINE_PARAMETER_HINT_BACKGROUND = crate::color::Color::hex(0x3b3b3b),
        EDITOR_INLINE_PARAMETER_HINT_HIGHLIGHTED_FOREGROUND = crate::color::Color::hex(0xacacac),
        EDITOR_INLINE_PARAMETER_HINT_HIGHLIGHTED_BACKGROUND = crate::color::Color::hex(0x4d4d4d),
        EDITOR_INLINE_PARAMETER_HINT_CURRENT_FOREGROUND = crate::color::Color::hex(0xacacac),
        EDITOR_INLINE_PARAMETER_HINT_CURRENT_BACKGROUND = crate::color::Color::hex(0x305d78),
        EDITOR_INLAY_DEFAULT_FOREGROUND = crate::color::Color::hex(0x787878),
        EDITOR_INLAY_DEFAULT_BACKGROUND = crate::color::Color::hex(0x3b3b3b),
        EDITOR_INLAY_BUTTON_DEFAULT_FOREGROUND = crate::color::Color::hex(0x9da0a8),
        EDITOR_INLAY_BUTTON_DEFAULT_EFFECT_COLOR = crate::color::Color::hex_alpha(0xffffff33),
        EDITOR_INLAY_BUTTON_FOCUSED_FOREGROUND = crate::color::Color::hex(0x9da0a8),
        EDITOR_INLAY_BUTTON_FOCUSED_EFFECT_COLOR = crate::color::Color::hex_alpha(0xffffff52),
        EDITOR_INLAY_BUTTON_HOVERED_FOREGROUND = crate::color::Color::hex(0x9da0a8),
        EDITOR_INLAY_BUTTON_HOVERED_EFFECT_COLOR = crate::color::Color::hex_alpha(0xffffff52),
        EDITOR_AI_INLAY_BUTTON_DEFAULT_FOREGROUND = crate::color::Color::hex(0x9da0a8),
        EDITOR_AI_INLAY_BUTTON_DEFAULT_EFFECT_COLOR = crate::color::Color::hex(0x955ae0),
        EDITOR_AI_INLAY_BUTTON_FOCUSED_FOREGROUND = crate::color::Color::hex(0x9da0a8),
        EDITOR_AI_INLAY_BUTTON_FOCUSED_EFFECT_COLOR = crate::color::Color::hex(0x8150be),
        EDITOR_AI_INLAY_BUTTON_HOVERED_FOREGROUND = crate::color::Color::hex(0x9da0a8),
        EDITOR_AI_INLAY_BUTTON_HOVERED_EFFECT_COLOR = crate::color::Color::hex(0x8150be),
        EDITOR_INLAY_BUTTON_HINT_FOREGROUND = crate::color::Color::hex(0x818594),
        EDITOR_INLAY_TEXT_WITHOUT_BACKGROUND_FOREGROUND = crate::color::Color::hex(0x787878),
        EDITOR_IMPLICIT_ANONYMOUS_CLASS_PARAMETER_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xb389c5),
        EDITOR_TYPE_PARAMETER_NAME_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x507874),
        EDITOR_ANNOTATION_NAME_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xbbb529),
        EDITOR_JOIN_POINT_EFFECT_COLOR = crate::color::Color::hex(0x00ff00),
        EDITOR_INSTANCE_FIELD_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x660e7a),
        EDITOR_DIFF_ABSENT_BACKGROUND = crate::color::Color::hex(0xf0f0f0),
        EDITOR_SEARCH_RESULT_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x155221),
        EDITOR_REGEXP_MATCHED_GROUPS_BACKGROUND = crate::color::Color::hex(0x6b6b6b),
        EDITOR_TERMINAL_CLASS_NAME_LOG_REFERENCE_EFFECT_COLOR = crate::color::Color::hex(0x808080),
        EDITOR_LIVE_TEMPLATE_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0x80bfff),
        EDITOR_LIVE_TEMPLATE_INACTIVE_SEGMENT_EFFECT_COLOR = crate::color::Color::hex(0x737373),
        EDITOR_WRITE_SEARCH_RESULT_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x532b2e),
        EDITOR_IDENTIFIER_UNDER_CARET_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x344134),
        EDITOR_WRITE_IDENTIFIER_UNDER_CARET_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x40332b),
        EDITOR_TEXT_SEARCH_RESULT_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x000000),
        EDITOR_TEXT_SEARCH_RESULT_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x32593d),
        EDITOR_INJECTED_LANGUAGE_FRAGMENT_BACKGROUND = crate::color::Color::hex(0x364135),
        EDITOR_EXECUTIONPOINT_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x2d6099),
        EDITOR_EXECUTIONPOINT_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_NOT_TOP_FRAME_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x2f3f55),
        EDITOR_EVALUATED_EXPRESSION_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x424242),
        EDITOR_EVALUATED_EXPRESSION_EXECUTION_LINE_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x474747),
        EDITOR_UNMATCHED_BRACE_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0xffdcdc),
        EDITOR_BREAKPOINT_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x3a2323),
        EDITOR_INLINE_STACK_FRAMES_BACKGROUND = crate::color::Color::hex(0x534a57),
        EDITOR_MATCHED_BRACE_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0x3b514d),
        EDITOR_STATIC_FIELD_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x660e7a),
        EDITOR_STATIC_FINAL_FIELD_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x660e7a),
        EDITOR_BAD_CHARACTER_BACKGROUND = crate::color::Color::hex(0xffcccc),
        EDITOR_CUSTOM_KEYWORD_1_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_CUSTOM_KEYWORD_2_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xab51ba),
        EDITOR_CUSTOM_KEYWORD_3_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x0f9795),
        EDITOR_CUSTOM_KEYWORD_4_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x93a629),
        EDITOR_CUSTOM_NUMBER_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x0000ff),
        EDITOR_CUSTOM_STRING_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x6a8759),
        EDITOR_CUSTOM_VALID_STRING_ESCAPE_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x4646f1),
        EDITOR_CUSTOM_INVALID_STRING_ESCAPE_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x008000),
        EDITOR_CUSTOM_INVALID_STRING_ESCAPE_ATTRIBUTES_BACKGROUND = crate::color::Color::hex(0xffcccc),
        EDITOR_CUSTOM_LINE_COMMENT_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x808080),
        EDITOR_CUSTOM_MULTI_LINE_COMMENT_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x808080),
        EDITOR_TEMPLATE_VARIABLE_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xae8abe),
        EDITOR_TODO_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0x3a53cf),
        EDITOR_DEPRECATED_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0xc3c3c3),
        EDITOR_MARKED_FOR_REMOVAL_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0xbc3f3c),
        EDITOR_CTRL_CLICKABLE_FOREGROUND = crate::color::Color::hex(0x589df6),
        EDITOR_CTRL_CLICKABLE_EFFECT_COLOR = crate::color::Color::hex(0x589df6),
        EDITOR_CONSOLE_NORMAL_OUTPUT_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        EDITOR_CONSOLE_ERROR_OUTPUT_FOREGROUND = crate::color::Color::hex(0xff6b68),
        EDITOR_LOG_DEBUG_OUTPUT_FOREGROUND = crate::color::Color::hex(0x299999),
        EDITOR_LOG_VERBOSE_OUTPUT_FOREGROUND = crate::color::Color::hex(0x5394ec),
        EDITOR_LOG_INFO_OUTPUT_FOREGROUND = crate::color::Color::hex(0xabc023),
        EDITOR_LOG_WARNING_OUTPUT_FOREGROUND = crate::color::Color::hex(0xa66f00),
        EDITOR_LOG_ERROR_OUTPUT_FOREGROUND = crate::color::Color::hex(0xcc666e),
        EDITOR_LOG_EXPIRED_ENTRY_FOREGROUND = crate::color::Color::hex(0x555555),
        EDITOR_CONSOLE_USER_INPUT_FOREGROUND = crate::color::Color::hex(0x007f00),
        EDITOR_CONSOLE_SYSTEM_OUTPUT_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        EDITOR_TODO_DEFAULT_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xa8c023),
        EDITOR_TYPO_EFFECT_COLOR = crate::color::Color::hex(0x659c6b),
        EDITOR_CONSOLE_BLACK_OUTPUT_FOREGROUND = crate::color::Color::hex(0x000000),
        EDITOR_CONSOLE_BLACK_OUTPUT_BACKGROUND = crate::color::Color::hex(0x000000),
        EDITOR_CONSOLE_BLUE_OUTPUT_FOREGROUND = crate::color::Color::hex(0x3993d4),
        EDITOR_CONSOLE_BLUE_OUTPUT_BACKGROUND = crate::color::Color::hex(0x245980),
        EDITOR_CONSOLE_BLUE_BRIGHT_OUTPUT_FOREGROUND = crate::color::Color::hex(0x1fb0ff),
        EDITOR_CONSOLE_BLUE_BRIGHT_OUTPUT_BACKGROUND = crate::color::Color::hex(0x1778bd),
        EDITOR_CONSOLE_CYAN_OUTPUT_FOREGROUND = crate::color::Color::hex(0x00a3a3),
        EDITOR_CONSOLE_CYAN_OUTPUT_BACKGROUND = crate::color::Color::hex(0x154f4f),
        EDITOR_CONSOLE_CYAN_BRIGHT_OUTPUT_FOREGROUND = crate::color::Color::hex(0x00e5e5),
        EDITOR_CONSOLE_CYAN_BRIGHT_OUTPUT_BACKGROUND = crate::color::Color::hex(0x006e6e),
        EDITOR_CONSOLE_DARKGRAY_OUTPUT_FOREGROUND = crate::color::Color::hex(0x595959),
        EDITOR_CONSOLE_DARKGRAY_OUTPUT_BACKGROUND = crate::color::Color::hex(0x424242),
        EDITOR_CONSOLE_GRAY_OUTPUT_FOREGROUND = crate::color::Color::hex(0x808080),
        EDITOR_CONSOLE_GRAY_OUTPUT_BACKGROUND = crate::color::Color::hex(0x616161),
        EDITOR_CONSOLE_GREEN_OUTPUT_FOREGROUND = crate::color::Color::hex(0x5c962c),
        EDITOR_CONSOLE_GREEN_OUTPUT_BACKGROUND = crate::color::Color::hex(0x39511f),
        EDITOR_CONSOLE_GREEN_BRIGHT_OUTPUT_FOREGROUND = crate::color::Color::hex(0x4fc414),
        EDITOR_CONSOLE_GREEN_BRIGHT_OUTPUT_BACKGROUND = crate::color::Color::hex(0x458500),
        EDITOR_CONSOLE_MAGENTA_OUTPUT_FOREGROUND = crate::color::Color::hex(0xa771bf),
        EDITOR_CONSOLE_MAGENTA_OUTPUT_BACKGROUND = crate::color::Color::hex(0x5c4069),
        EDITOR_CONSOLE_MAGENTA_BRIGHT_OUTPUT_FOREGROUND = crate::color::Color::hex(0xed7eed),
        EDITOR_CONSOLE_MAGENTA_BRIGHT_OUTPUT_BACKGROUND = crate::color::Color::hex(0xb247b2),
        EDITOR_CONSOLE_RED_OUTPUT_FOREGROUND = crate::color::Color::hex(0xf0524f),
        EDITOR_CONSOLE_RED_OUTPUT_BACKGROUND = crate::color::Color::hex(0x772e2c),
        EDITOR_CONSOLE_RED_BRIGHT_OUTPUT_FOREGROUND = crate::color::Color::hex(0xff4050),
        EDITOR_CONSOLE_RED_BRIGHT_OUTPUT_BACKGROUND = crate::color::Color::hex(0xb82421),
        EDITOR_CONSOLE_YELLOW_OUTPUT_FOREGROUND = crate::color::Color::hex(0xa68a0d),
        EDITOR_CONSOLE_YELLOW_OUTPUT_BACKGROUND = crate::color::Color::hex(0x5c4f17),
        EDITOR_CONSOLE_YELLOW_BRIGHT_OUTPUT_FOREGROUND = crate::color::Color::hex(0xe5bf00),
        EDITOR_CONSOLE_YELLOW_BRIGHT_OUTPUT_BACKGROUND = crate::color::Color::hex(0xa87b00),
        EDITOR_CONSOLE_WHITE_OUTPUT_FOREGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_CONSOLE_WHITE_OUTPUT_BACKGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_TERMINAL_COMMAND_TO_RUN_USING_IDE_BACKGROUND = crate::color::Color::hex(0x40503c),
        EDITOR_BLOCK_TERMINAL_COMMAND_FOREGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_BLOCK_TERMINAL_SEARCH_ENTRY_FOREGROUND = crate::color::Color::hex(0x000000),
        EDITOR_BLOCK_TERMINAL_SEARCH_ENTRY_BACKGROUND = crate::color::Color::hex(0xffea00),
        EDITOR_BLOCK_TERMINAL_CURRENT_SEARCH_ENTRY_FOREGROUND = crate::color::Color::hex(0x000000),
        EDITOR_BLOCK_TERMINAL_CURRENT_SEARCH_ENTRY_BACKGROUND = crate::color::Color::hex(0xff941a),
        EDITOR_BLOCK_TERMINAL_GENERATE_COMMAND_PROMPT_TEXT_FOREGROUND = crate::color::Color::hex(0xb589ec),
        EDITOR_BLOCK_TERMINAL_BLACK_FOREGROUND = crate::color::Color::hex(0x000000),
        EDITOR_BLOCK_TERMINAL_BLACK_BACKGROUND = crate::color::Color::hex(0x1e1f22),
        EDITOR_BLOCK_TERMINAL_RED_FOREGROUND = crate::color::Color::hex(0xf27481),
        EDITOR_BLOCK_TERMINAL_RED_BACKGROUND = crate::color::Color::hex(0xba3f4b),
        EDITOR_BLOCK_TERMINAL_GREEN_FOREGROUND = crate::color::Color::hex(0x6bcc62),
        EDITOR_BLOCK_TERMINAL_GREEN_BACKGROUND = crate::color::Color::hex(0x288720),
        EDITOR_BLOCK_TERMINAL_YELLOW_FOREGROUND = crate::color::Color::hex(0xe0ce70),
        EDITOR_BLOCK_TERMINAL_YELLOW_BACKGROUND = crate::color::Color::hex(0xa66900),
        EDITOR_BLOCK_TERMINAL_BLUE_FOREGROUND = crate::color::Color::hex(0x5594fa),
        EDITOR_BLOCK_TERMINAL_BLUE_BACKGROUND = crate::color::Color::hex(0x134ebf),
        EDITOR_BLOCK_TERMINAL_MAGENTA_FOREGROUND = crate::color::Color::hex(0xc092fa),
        EDITOR_BLOCK_TERMINAL_MAGENTA_BACKGROUND = crate::color::Color::hex(0x843ae0),
        EDITOR_BLOCK_TERMINAL_CYAN_FOREGROUND = crate::color::Color::hex(0x47ccbd),
        EDITOR_BLOCK_TERMINAL_CYAN_BACKGROUND = crate::color::Color::hex(0x008576),
        EDITOR_BLOCK_TERMINAL_WHITE_FOREGROUND = crate::color::Color::hex(0xced0d6),
        EDITOR_BLOCK_TERMINAL_WHITE_BACKGROUND = crate::color::Color::hex(0xced0d6),
        EDITOR_BLOCK_TERMINAL_BLACK_BRIGHT_FOREGROUND = crate::color::Color::hex(0x4e5157),
        EDITOR_BLOCK_TERMINAL_BLACK_BRIGHT_BACKGROUND = crate::color::Color::hex(0x4e5157),
        EDITOR_BLOCK_TERMINAL_RED_BRIGHT_FOREGROUND = crate::color::Color::hex(0xff6b7a),
        EDITOR_BLOCK_TERMINAL_RED_BRIGHT_BACKGROUND = crate::color::Color::hex(0xff475a),
        EDITOR_BLOCK_TERMINAL_GREEN_BRIGHT_FOREGROUND = crate::color::Color::hex(0x67ff59),
        EDITOR_BLOCK_TERMINAL_GREEN_BRIGHT_BACKGROUND = crate::color::Color::hex(0x48e539),
        EDITOR_BLOCK_TERMINAL_YELLOW_BRIGHT_FOREGROUND = crate::color::Color::hex(0xffec1a),
        EDITOR_BLOCK_TERMINAL_YELLOW_BRIGHT_BACKGROUND = crate::color::Color::hex(0xffbf00),
        EDITOR_BLOCK_TERMINAL_BLUE_BRIGHT_FOREGROUND = crate::color::Color::hex(0x3399ff),
        EDITOR_BLOCK_TERMINAL_BLUE_BRIGHT_BACKGROUND = crate::color::Color::hex(0x1aafff),
        EDITOR_BLOCK_TERMINAL_MAGENTA_BRIGHT_FOREGROUND = crate::color::Color::hex(0xd970ff),
        EDITOR_BLOCK_TERMINAL_MAGENTA_BRIGHT_BACKGROUND = crate::color::Color::hex(0xb459ff),
        EDITOR_BLOCK_TERMINAL_CYAN_BRIGHT_FOREGROUND = crate::color::Color::hex(0x40ffe9),
        EDITOR_BLOCK_TERMINAL_CYAN_BRIGHT_BACKGROUND = crate::color::Color::hex(0x22e5cf),
        EDITOR_BLOCK_TERMINAL_WHITE_BRIGHT_FOREGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_BLOCK_TERMINAL_WHITE_BRIGHT_BACKGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_SPY_JS_FUNCTION_SCOPE_BACKGROUND = crate::color::Color::hex(0x3a3a3a),
        EDITOR_SPY_JS_PROGRAM_SCOPE_BACKGROUND = crate::color::Color::hex(0x3a3a3a),
        EDITOR_SPY_JS_EXCEPTION_BACKGROUND = crate::color::Color::hex(0x532b2e),
        EDITOR_SPY_JS_PATH_LEVEL_ONE_BACKGROUND = crate::color::Color::hex(0x425f44),
        EDITOR_SPY_JS_PATH_LEVEL_TWO_EFFECT_COLOR = crate::color::Color::hex(0xa9b7c6),
        EDITOR_SPY_JS_VALUE_HINT_EFFECT_COLOR = crate::color::Color::hex(0xa9b7c6),
        EDITOR_RAINBOW_COLOR_0_FOREGROUND = crate::color::Color::hex(0x529d52),
        EDITOR_RAINBOW_COLOR_1_FOREGROUND = crate::color::Color::hex(0xbe7070),
        EDITOR_RAINBOW_COLOR_2_FOREGROUND = crate::color::Color::hex(0x3d7676),
        EDITOR_RAINBOW_COLOR_3_FOREGROUND = crate::color::Color::hex(0xbe9970),
        EDITOR_RAINBOW_COLOR_4_FOREGROUND = crate::color::Color::hex(0x9d527c),
        EDITOR_BREADCRUMBS_DEFAULT_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        EDITOR_BREADCRUMBS_HOVERED_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        EDITOR_BREADCRUMBS_HOVERED_BACKGROUND = crate::color::Color::hex(0x3a3c3e),
        EDITOR_BREADCRUMBS_CURRENT_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        EDITOR_BREADCRUMBS_CURRENT_BACKGROUND = crate::color::Color::hex(0x44474a),
        EDITOR_BREADCRUMBS_INACTIVE_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        EDITOR_CODE_LENS_BORDER_COLOR_EFFECT_COLOR = crate::color::Color::hex(0x999999),
        EDITOR_INLINE_PROMPT_FOREGROUND = crate::color::Color::hex(0xb589ec),
        EDITOR_INLINE_PROMPT_PROGRESS_DARK_FOREGROUND = crate::color::Color::hex(0x955ae0),
        EDITOR_INLINE_PROMPT_PROGRESS_LIGHT_FOREGROUND = crate::color::Color::hex(0xd4b8f9),
        EDITOR_XPATH_KEYWORD_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_XPATH_XPATH_NAME_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_XPATH_FUNCTION_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_BEAN_INACTIVE_EFFECT_COLOR = crate::color::Color::hex(0x6c6c6c),
        EDITOR_CARET_COLOR = crate::color::Color::hex(0xbbbbbb),
        EDITOR_LINE_NUMBER_ON_CARET_ROW_COLOR = crate::color::Color::hex(0xa4a3a3),
        EDITOR_RECURSIVE_CALL_ATTRIBUTES = crate::color::Color::hex(0x574300),
        EDITOR_ANNOTATION_ATTRIBUTE_NAME_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xa9b7c6),
        EDITOR_ATTR_INTERNAL_CALL_ID_FOREGROUND = crate::color::Color::hex(0xa2cff5),
        EDITOR_BAD_CHARACTER_EFFECT_COLOR = crate::color::Color::hex(0xff0000),
        EDITOR_CONSOLE_OUTPUT_BACKGROUND = crate::color::Color::hex(0x454545),
        EDITOR_CSS_COLOR_FOREGROUND = crate::color::Color::hex(0x6897bb),
        EDITOR_CSS_IMPORTANT_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_CSS_URL_FOREGROUND = crate::color::Color::hex(0x287bde),
        EDITOR_DEFAULT_CLASS_REFERENCE_FOREGROUND = crate::color::Color::hex(0x769aa5),
        EDITOR_DEFAULT_COMMA_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_DEFAULT_DOC_COMMENT_TAG_FOREGROUND = crate::color::Color::hex(0x629755),
        EDITOR_DEFAULT_DOC_MARKUP_FOREGROUND = crate::color::Color::hex(0x77b767),
        EDITOR_DEFAULT_FUNCTION_DECLARATION_FOREGROUND = crate::color::Color::hex(0xffc66d),
        EDITOR_DEFAULT_INVALID_STRING_ESCAPE_EFFECT_COLOR = crate::color::Color::hex(0xff0000),
        EDITOR_DEFAULT_SEMICOLON_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_DEFAULT_STATIC_METHOD_FOREGROUND = crate::color::Color::hex(0xffc66d),
        EDITOR_DELETED_TEXT_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0xc3c3c3),
        EDITOR_HAML_CLASS_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_HAML_COMMENT_FOREGROUND = crate::color::Color::hex(0xbc9458),
        EDITOR_HAML_ID_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_HAML_RUBY_CODE_BACKGROUND = crate::color::Color::hex(0x232323),
        EDITOR_HAML_TAG_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_HTML_ATTRIBUTE_NAME_FOREGROUND = crate::color::Color::hex(0xbababa),
        EDITOR_HTML_ATTRIBUTE_VALUE_FOREGROUND = crate::color::Color::hex(0xa5c261),
        EDITOR_HTML_ENTITY_REFERENCE_FOREGROUND = crate::color::Color::hex(0x6d9cbe),
        EDITOR_HTML_TAG_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_HTML_TAG_NAME_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_IMPLICIT_ANONYMOUS_CLASS_PARAMETER_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0xb389c5),
        EDITOR_JSP_DIRECTIVE_NAME_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_LESS_VARIABLE_FOREGROUND = crate::color::Color::hex(0xd0d0ff),
        EDITOR_MATCHED_BRACE_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xffef28),
        EDITOR_PROPERTIES_INVALID_STRING_ESCAPE_FOREGROUND = crate::color::Color::hex(0xffc66d),
        EDITOR_PROPERTIES_INVALID_STRING_ESCAPE_BACKGROUND = crate::color::Color::hex(0x450505),
        EDITOR_PROPERTIES_INVALID_STRING_ESCAPE_EFFECT_COLOR = crate::color::Color::hex(0xff0000),
        EDITOR_PROPERTIES_KEY_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_PROPERTIES_KEY_VALUE_SEPARATOR_FOREGROUND = crate::color::Color::hex(0x808080),
        EDITOR_REGEXP_BRACES_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_REGEXP_BRACKETS_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_REGEXP_CHAR_CLASS_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_REGEXP_ESC_CHARACTER_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_REGEXP_META_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_REGEXP_PARENTHS_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_REGEXP_QUOTE_CHARACTER_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_REGEXP_REDUNDANT_ESCAPE_FOREGROUND = crate::color::Color::hex(0x9396c0),
        EDITOR_SASS_ATTRIBUTE_FOREGROUND = crate::color::Color::hex(0x6d9cbe),
        EDITOR_SASS_COMMENT_FOREGROUND = crate::color::Color::hex(0xbc9455),
        EDITOR_SASS_CONSTANT_FOREGROUND = crate::color::Color::hex(0xd0d0ff),
        EDITOR_SASS_DIRECTIVE_FOREGROUND = crate::color::Color::hex(0xcc7833),
        EDITOR_SASS_MIXIN_FOREGROUND = crate::color::Color::hex(0xd0d0ff),
        EDITOR_SASS_RULE_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_SASS_VARIABLE_FOREGROUND = crate::color::Color::hex(0x6d9cbe),
        EDITOR_SCALA_TYPE_ALIAS_FOREGROUND = crate::color::Color::hex(0x4e807d),
        EDITOR_SCALA_TYPE_PARAMETER_FOREGROUND = crate::color::Color::hex(0x4e807d),
        EDITOR_STATIC_METHOD_ACCESS_FOREGROUND = crate::color::Color::hex(0x9876aa),
        EDITOR_TEXT_FOREGROUND = crate::color::Color::hex(0xa9b7c6),
        EDITOR_TEXT_BACKGROUND = crate::color::Color::hex(0x2b2b2b),
        EDITOR_TEXT_SEARCH_RESULT_ATTRIBUTES_EFFECT_COLOR = crate::color::Color::hex(0x3c704b),
        EDITOR_UNMATCHED_BRACE_ATTRIBUTES_FOREGROUND = crate::color::Color::hex(0xd1243b),
        EDITOR_VELOCITY_DIRECTIVE_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_VELOCITY_KEYWORD_FOREGROUND = crate::color::Color::hex(0xcc7832),
        EDITOR_VELOCITY_REFERENCE_FOREGROUND = crate::color::Color::hex(0xd0d0ff),
        EDITOR_VELOCITY_SCRIPTING_BACKGROUND_BACKGROUND = crate::color::Color::hex(0x303030),
        EDITOR_XML_ATTRIBUTE_NAME_FOREGROUND = crate::color::Color::hex(0xbababa),
        EDITOR_XML_ENTITY_REFERENCE_FOREGROUND = crate::color::Color::hex(0x6d9cbe),
        EDITOR_XML_PROLOGUE_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_XML_TAG_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_XML_TAG_NAME_FOREGROUND = crate::color::Color::hex(0xe8bf6a),
        EDITOR_XPATH_XPATH_VARIABLE_FOREGROUND = crate::color::Color::hex(0xd0d0ff),
        UI_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_TEXT_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_TEXT_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_CARET_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_INACTIVE_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_SELECTION_BACKGROUND_INACTIVE = crate::color::Color::hex(0x0d293e),
        UI_SELECTION_INACTIVE_BACKGROUND = crate::color::Color::hex(0x0d293e),
        UI_SELECTION_FOREGROUND_INACTIVE = crate::color::Color::hex(0xbbbbbb),
        UI_SELECTION_INACTIVE_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_SELECTION_BACKGROUND_OS_DEFAULT = crate::color::Color::hex(0x2f65ca),
        UI_SELECTION_BACKGROUND_OS_WINDOWS = crate::color::Color::hex(0x4b6eaf),
        UI_SELECTION_FOREGROUND = crate::color::Color::hex(0xdedede),
        UI_ACTION_BUTTON_FOCUSED_BORDER_COLOR = crate::color::Color::hex(0x5eacd0),
        UI_ACTION_BUTTON_HOVER_BACKGROUND = crate::color::Color::hex(0x4c5052),
        UI_ACTION_BUTTON_HOVER_BORDER_COLOR = crate::color::Color::hex(0x4c5052),
        UI_ACTION_BUTTON_PRESSED_BACKGROUND = crate::color::Color::hex(0x5c6164),
        UI_ACTION_BUTTON_PRESSED_BORDER_COLOR = crate::color::Color::hex(0x5c6164),
        UI_APP_INSPECTOR_GRAPH_NODE_BACKGROUND = crate::color::Color::hex(0x515658),
        UI_BOOKMARK_MNEMONIC_ASSIGNED_BACKGROUND = crate::color::Color::hex(0x665632),
        UI_BOOKMARK_MNEMONIC_ASSIGNED_BORDER_COLOR = crate::color::Color::hex(0x665632),
        UI_BOOKMARK_MNEMONIC_ASSIGNED_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_BOOKMARK_MNEMONIC_AVAILABLE_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_BOOKMARK_MNEMONIC_AVAILABLE_BORDER_COLOR = crate::color::Color::hex(0x5e6060),
        UI_BOOKMARK_MNEMONIC_AVAILABLE_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_BORDERS_CONTRAST_BORDER_COLOR = crate::color::Color::hex(0x323232),
        UI_BUTTON_DEFAULT_END_BACKGROUND = crate::color::Color::hex(0x365880),
        UI_BUTTON_DEFAULT_END_BORDER_COLOR = crate::color::Color::hex(0x4c708c),
        UI_BUTTON_DEFAULT_FOCUS_COLOR = crate::color::Color::hex(0x43688c),
        UI_BUTTON_DEFAULT_FOCUSED_BORDER_COLOR = crate::color::Color::hex(0x537699),
        UI_BUTTON_DEFAULT_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_BUTTON_DEFAULT_START_BACKGROUND = crate::color::Color::hex(0x365880),
        UI_BUTTON_DEFAULT_START_BORDER_COLOR = crate::color::Color::hex(0x4c708c),
        UI_BUTTON_DISABLED_BORDER_COLOR = crate::color::Color::hex(0x5e6060),
        UI_BUTTON_DISABLED_TEXT = crate::color::Color::hex(0x777777),
        UI_BUTTON_END_BACKGROUND = crate::color::Color::hex(0x4c5052),
        UI_BUTTON_END_BORDER_COLOR = crate::color::Color::hex(0x5e6060),
        UI_BUTTON_FOCUSED_BORDER_COLOR = crate::color::Color::hex(0x466d94),
        UI_BUTTON_SHADOW_COLOR = crate::color::Color::hex_alpha(0x36363680),
        UI_BUTTON_START_BACKGROUND = crate::color::Color::hex(0x4c5052),
        UI_BUTTON_START_BORDER_COLOR = crate::color::Color::hex(0x5e6060),
        UI_CANVAS_TOOLTIP_BACKGROUND = crate::color::Color::hex(0x4a4c4c),
        UI_SEGMENTED_BUTTON_SELECTED_START_BORDER_COLOR = crate::color::Color::hex(0x5e6060),
        UI_SEGMENTED_BUTTON_SELECTED_END_BORDER_COLOR = crate::color::Color::hex(0x5e6060),
        UI_SEGMENTED_BUTTON_SELECTED_BUTTON_COLOR = crate::color::Color::hex(0x4c5052),
        UI_SEGMENTED_BUTTON_FOCUSED_SELECTED_BUTTON_COLOR = crate::color::Color::hex(0x3d4b5c),
        UI_SIDE_PANEL_BACKGROUND = crate::color::Color::hex(0x3e434c),
        UI_CODE_WITH_ME_AVATAR_FOREGROUND = crate::color::Color::hex(0x1d1d1d),
        UI_COMBO_BOX_ARROW_BUTTON_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_COMBO_BOX_ARROW_BUTTON_DISABLED_ICON_COLOR = crate::color::Color::hex(0x585858),
        UI_COMBO_BOX_ARROW_BUTTON_ICON_COLOR = crate::color::Color::hex(0x9a9da1),
        UI_COMBO_BOX_ARROW_BUTTON_NON_EDITABLE_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_COMBO_BOX_DISABLED_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_COMBO_BOX_DISABLED_FOREGROUND = crate::color::Color::hex(0x777777),
        UI_COMBO_BOX_NON_EDITABLE_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_CODE_INLINE_BACKGROUND_COLOR = crate::color::Color::hex(0x1e1f22),
        UI_CODE_BLOCK_BORDER_COLOR = crate::color::Color::hex(0x5a5d63),
        UI_CODE_BLOCK_EDITOR_PANE_BACKGROUND_COLOR = crate::color::Color::hex(0x9da0a8),
        UI_CODE_BLOCK_EDITOR_PANE_BORDER_COLOR = crate::color::Color::hex(0x393b40),
        UI_SHORTCUT_BORDER_COLOR = crate::color::Color::hex(0x6f737a),
        UI_COMBO_BOX_BUTTON_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_COMPLETION_POPUP_ADVERTISER_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_COMPLETION_POPUP_ADVERTISER_FOREGROUND = crate::color::Color::hex(0x808080),
        UI_COMPLETION_POPUP_MATCH_FOREGROUND = crate::color::Color::hex(0x589df6),
        UI_COMPLETION_POPUP_SELECTION_BACKGROUND = crate::color::Color::hex(0x113a5c),
        UI_COMPLETION_POPUP_SELECTION_INACTIVE_BACKGROUND = crate::color::Color::hex(0x515457),
        UI_COMPLETION_POPUP_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_COMPLEX_POPUP_HEADER_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_COMPONENT_BORDER_COLOR = crate::color::Color::hex(0x646464),
        UI_COMPONENT_DISABLED_BORDER_COLOR = crate::color::Color::hex(0x646464),
        UI_COMPONENT_ERROR_FOCUS_COLOR = crate::color::Color::hex(0x8b3c3c),
        UI_COMPONENT_FOCUS_COLOR = crate::color::Color::hex(0x3d6185),
        UI_COMPONENT_FOCUSED_BORDER_COLOR = crate::color::Color::hex(0x466d94),
        UI_COMPONENT_INACTIVE_ERROR_FOCUS_COLOR = crate::color::Color::hex(0x725252),
        UI_COMPONENT_INACTIVE_WARNING_FOCUS_COLOR = crate::color::Color::hex(0x6e5324),
        UI_COMPONENT_INFO_FOREGROUND = crate::color::Color::hex(0x787878),
        UI_COMPONENT_WARNING_FOCUS_COLOR = crate::color::Color::hex(0xac7920),
        UI_CONTENT_BACKGROUND = crate::color::Color::hex(0x2b2b2b),
        UI_COUNTER_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_COUNTER_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_BOOKMARK_MNEMONIC_CURRENT_BACKGROUND = crate::color::Color::hex(0x345f85),
        UI_BOOKMARK_MNEMONIC_CURRENT_BORDER_COLOR = crate::color::Color::hex(0x345f85),
        UI_BOOKMARK_MNEMONIC_CURRENT_FOREGROUND = crate::color::Color::hex(0xfefefe),
        UI_DEFAULT_TABS_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_DRAG_AND_DROP_BORDER_COLOR = crate::color::Color::hex(0x2f65ca),
        UI_DRAG_AND_DROP_ROW_BACKGROUND = crate::color::Color::hex_alpha(0x2f65ca33),
        UI_DRAG_AND_DROP_AREA_BACKGROUND = crate::color::Color::hex_alpha(0xffffff33),
        UI_DRAG_AND_DROP_AREA_BORDER_COLOR = crate::color::Color::hex(0x4f73a8),
        UI_DRAG_AND_DROP_AREA_FOREGROUND = crate::color::Color::hex(0xbababa),
        UI_DEBUGGER_EVALUATE_EXPRESSION_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_DISCLOSURE_BUTTON_DEFAULT_BACKGROUND = crate::color::Color::hex_alpha(0xffffff12),
        UI_DISCLOSURE_BUTTON_HOVER_OVERLAY = crate::color::Color::hex_alpha(0xffffff0d),
        UI_DISCLOSURE_BUTTON_PRESSED_OVERLAY = crate::color::Color::hex_alpha(0xffffff1a),
        UI_EDITOR_BACKGROUND = crate::color::Color::hex(0x282828),
        UI_EDITOR_FOREGROUND = crate::color::Color::hex(0xa0a0a0),
        UI_EDITOR_SEARCH_FIELD_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_EDITOR_PANE_INACTIVE_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_EDITOR_PANE_INACTIVE_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_EDITOR_TABS_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_EDITOR_TABS_UNDERLINED_TAB_BACKGROUND = crate::color::Color::hex(0x4e5254),
        UI_EDITOR_TOOL_TIP_BACKGROUND = crate::color::Color::hex(0x4b4d4d),
        UI_EDITOR_TOOL_TIP_FOREGROUND = crate::color::Color::hex(0xbfbfbf),
        UI_FOCUS_COLOR = crate::color::Color::hex(0xff0000),
        UI_FORMATTED_TEXT_FIELD_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_GROUP_SEPARATOR_COLOR = crate::color::Color::hex(0x515151),
        UI_HELP_BROWSER_AI_EDITOR_BACKGROUND = crate::color::Color::hex(0xfaf5ff),
        UI_HELP_BROWSER_HELP_BROWSER_MESSAGE_SNIPPET_MORE_LINES_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_HELP_BROWSER_HELP_BROWSER_MESSAGE_SNIPPET_MORE_LINES_FOREGROUND = crate::color::Color::hex(0x8c8c8c),
        UI_HELP_BROWSER_USER_MESSAGE_BACKGROUND = crate::color::Color::hex(0x3b4754),
        UI_HELP_BROWSER_USER_MESSAGE_SNIPPET_MORE_LINES_FOREGROUND = crate::color::Color::hex(0x8c8c8c),
        UI_HYPERLINK_LINK_COLOR = crate::color::Color::hex(0x589df6),
        UI_LABEL_DISABLED_FOREGROUND_OS_WINDOWS = crate::color::Color::hex(0x777777),
        UI_LABEL_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_LABEL_SELECTED_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_LINK_TAG_BACKGROUND = crate::color::Color::hex(0x393b40),
        UI_LINK_TAG_FOREGROUND = crate::color::Color::hex(0xa8adbd),
        UI_LINK_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_LINK_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_LINK_ACTIVE_FOREGROUND = crate::color::Color::hex(0x589df6),
        UI_LINK_HOVER_FOREGROUND = crate::color::Color::hex(0x589df6),
        UI_LINK_PRESSED_FOREGROUND = crate::color::Color::hex(0xba6f25),
        UI_LINK_VISITED_FOREGROUND = crate::color::Color::hex(0x589df6),
        UI_MAIN_MENU_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_MAIN_MENU_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_MENU_BORDER_COLOR = crate::color::Color::hex(0x515151),
        UI_MENU_SEPARATOR_COLOR = crate::color::Color::hex(0x515151),
        UI_MENU_BAR_BORDER_COLOR = crate::color::Color::hex(0x515151),
        UI_MENU_BAR_DISABLED_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_MENU_ITEM_ACCELERATOR_FOREGROUND = crate::color::Color::hex(0xbcbcbc),
        UI_MENU_ITEM_ACCELERATOR_SELECTION_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_MENU_ITEM_DISABLED_FOREGROUND = crate::color::Color::hex(0x777777),
        UI_BOOKMARK_ICON_BACKGROUND = crate::color::Color::hex(0xaa8542),
        UI_BOOKMARK_MNEMONIC_ICON_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_BOOKMARK_MNEMONIC_ICON_BACKGROUND = crate::color::Color::hex(0x5b5341),
        UI_BOOKMARK_MNEMONIC_ICON_BORDER_COLOR = crate::color::Color::hex(0xd9a343),
        UI_NAV_BAR_BORDER_COLOR = crate::color::Color::hex(0x515151),
        UI_NEW_CLASS_PANEL_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_NEW_CLASS_SEARCH_FIELD_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_OPTION_PANE_MESSAGE_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_PARAMETER_INFO_BACKGROUND = crate::color::Color::hex(0x4b4d4d),
        UI_PARAMETER_INFO_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_PASSWORD_FIELD_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_POPUP_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_POPUP_HEADER_ACTIVE_BACKGROUND = crate::color::Color::hex(0x4a4e52),
        UI_POPUP_HEADER_INACTIVE_BACKGROUND = crate::color::Color::hex(0x434649),
        UI_POPUP_TOOLBAR_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_POPUP_TOOLBAR_BORDER_COLOR = crate::color::Color::hex(0x4a4e52),
        UI_POPUP_BORDER_COLOR = crate::color::Color::hex(0x616161),
        UI_POPUP_INACTIVE_BORDER_COLOR = crate::color::Color::hex(0x565656),
        UI_POPUP_MENU_TRANSLUCENT_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_PROGRESS_BAR_FAILED_COLOR = crate::color::Color::hex(0xe74848),
        UI_PROGRESS_BAR_FAILED_END_COLOR = crate::color::Color::hex(0xf4a2a0),
        UI_PROGRESS_BAR_FOREGROUND = crate::color::Color::hex(0x808080),
        UI_PROGRESS_BAR_INDETERMINATE_END_COLOR = crate::color::Color::hex(0x838383),
        UI_PROGRESS_BAR_INDETERMINATE_START_COLOR = crate::color::Color::hex(0x696969),
        UI_PROGRESS_BAR_PASSED_COLOR = crate::color::Color::hex(0x008f50),
        UI_PROGRESS_BAR_PASSED_END_COLOR = crate::color::Color::hex(0x5dc48f),
        UI_PROGRESS_BAR_PROGRESS_COLOR = crate::color::Color::hex(0xa0a0a0),
        UI_PROGRESS_BAR_TRACK_COLOR = crate::color::Color::hex(0x555555),
        UI_RADIO_BUTTON_DARCULA_SELECTION_DISABLED_COLOR = crate::color::Color::hex(0x606060),
        UI_RADIO_BUTTON_DARCULA_SELECTION_DISABLED_SHADOW_COLOR = crate::color::Color::hex(0x3c3c3c),
        UI_RADIO_BUTTON_DARCULA_SELECTION_ENABLED_COLOR = crate::color::Color::hex(0xaaaaaa),
        UI_RADIO_BUTTON_DARCULA_SELECTION_ENABLED_SHADOW_COLOR = crate::color::Color::hex(0x1e1e1e),
        UI_REVIEW_BRANCH_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_REVIEW_BRANCH_BACKGROUND_HOVER = crate::color::Color::hex(0x525758),
        UI_REVIEW_STATE_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_REVIEW_STATE_FOREGROUND = crate::color::Color::hex(0x8c8c8c),
        UI_REVIEW_CHAT_ITEM_HOVER = crate::color::Color::hex_alpha(0x4b4b4b33),
        UI_REVIEW_TIMELINE_THREAD_DIFF_ANCHOR_LINE = crate::color::Color::hex(0x544b2d),
        UI_SCREEN_VIEW_DEFAULT_BORDER_COLOR = crate::color::Color::hex(0x000000),
        UI_SCREEN_VIEW_SELECTED_BORDER_COLOR = crate::color::Color::hex(0x548af7),
        UI_SCREEN_VIEW_HOVERED_BORDER_COLOR = crate::color::Color::hex(0x548af7),
        UI_SCROLL_BAR_BACKGROUND = crate::color::Color::hex(0x3f4244),
        UI_SEARCH_EVERYWHERE_ADVERTISER_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_SEARCH_EVERYWHERE_ADVERTISER_FOREGROUND = crate::color::Color::hex(0x808080),
        UI_SEARCH_EVERYWHERE_HEADER_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_SEARCH_EVERYWHERE_LIST_SEPARATOR_COLOR = crate::color::Color::hex(0x505050),
        UI_SEARCH_EVERYWHERE_SEARCH_FIELD_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_SEARCH_EVERYWHERE_SEARCH_FIELD_BORDER_COLOR = crate::color::Color::hex(0x646464),
        UI_SEARCH_EVERYWHERE_SEARCH_FIELD_INFO_FOREGROUND = crate::color::Color::hex(0x808080),
        UI_SEARCH_EVERYWHERE_TAB_SELECTED_BACKGROUND = crate::color::Color::hex(0x555a5e),
        UI_SEARCH_EVERYWHERE_TAB_SELECTED_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_SEPARATOR_SEPARATOR_COLOR = crate::color::Color::hex(0x515151),
        UI_SLIDER_TICK_COLOR = crate::color::Color::hex(0x666666),
        UI_SPACE_REVIEW_ACCEPTED_OUTLINE = crate::color::Color::hex(0x54b576),
        UI_SPACE_REVIEW_WORKING_OUTLINE = crate::color::Color::hex(0xff9466),
        UI_SPACE_REVIEW_WAIT_FOR_RESPONSE_OUTLINE = crate::color::Color::hex(0x8cd3ec),
        UI_SPEED_SEARCH_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_SPEED_SEARCH_BORDER_COLOR = crate::color::Color::hex(0x404040),
        UI_SPEED_SEARCH_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_SPEED_SEARCH_ERROR_FOREGROUND = crate::color::Color::hex(0xff6464),
        UI_SPINNER_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_SPLIT_PANE_HIGHLIGHT = crate::color::Color::hex(0x3c3f41),
        UI_STATUS_BAR_WIDGET_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_STATUS_BAR_BREADCRUMBS_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_STATUS_BAR_LIGHT_EDIT_BACKGROUND = crate::color::Color::hex(0x2f475e),
        UI_STATUS_BAR_BORDER_COLOR = crate::color::Color::hex(0x464646),
        UI_STATUS_BAR_HOVER_BACKGROUND = crate::color::Color::hex(0x4c5052),
        UI_TABBED_PANE_CONTENT_AREA_COLOR = crate::color::Color::hex(0x323232),
        UI_TABBED_PANE_DISABLED_FOREGROUND = crate::color::Color::hex(0x777777),
        UI_TABBED_PANE_DISABLED_UNDERLINE_COLOR = crate::color::Color::hex(0x7a7a7a),
        UI_TABBED_PANE_FOCUS_COLOR = crate::color::Color::hex(0x3d4b5c),
        UI_TABBED_PANE_HOVER_COLOR = crate::color::Color::hex(0x2e3133),
        UI_TABBED_PANE_UNDERLINE_COLOR = crate::color::Color::hex(0x4a88c7),
        UI_TABLE_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_TABLE_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_TABLE_GRID_COLOR = crate::color::Color::hex(0x4f5152),
        UI_TABLE_HEADER_BACKGROUND = crate::color::Color::hex(0x45484a),
        UI_TABLE_HEADER_BOTTOM_SEPARATOR_COLOR = crate::color::Color::hex(0x333638),
        UI_TABLE_HEADER_SEPARATOR_COLOR = crate::color::Color::hex(0x333638),
        UI_TEXT_AREA_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_TEXT_AREA_SELECTION_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_TEXT_FIELD_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_TEXT_FIELD_DISABLED_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_SEARCH_FIELD_WITH_EXTENSION_BACKGROUND = crate::color::Color::hex(0x45494a),
        UI_TITLED_BORDER_TITLE_COLOR = crate::color::Color::hex(0xbbbbbb),
        UI_TOOL_TIP_BACKGROUND = crate::color::Color::hex(0x4b4d4d),
        UI_TOOL_TIP_FOREGROUND = crate::color::Color::hex(0xbfbfbf),
        UI_TOOL_TIP_INFO_FOREGROUND = crate::color::Color::hex(0x919191),
        UI_GOT_IT_TOOLTIP_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_GOT_IT_TOOLTIP_BUTTON_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_GOT_IT_TOOLTIP_HEADER_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_GOT_IT_TOOLTIP_FOREGROUND = crate::color::Color::hex(0xbfbfbf),
        UI_GOT_IT_TOOLTIP_CODE_BACKGROUND = crate::color::Color::hex(0x4c5052),
        UI_GOT_IT_TOOLTIP_CODE_BORDER_COLOR = crate::color::Color::hex(0x6c707e),
        UI_GOT_IT_TOOLTIP_IMAGE_BORDER_COLOR = crate::color::Color::hex_alpha(0xffffff4d),
        UI_TOOL_WINDOW_HEADER_BACKGROUND = crate::color::Color::hex(0x3b4754),
        UI_TOOL_WINDOW_HEADER_INACTIVE_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_TOOL_WINDOW_HEADER_CLOSE_BUTTON_BACKGROUND = crate::color::Color::hex(0x3f4146),
        UI_TOOL_WINDOW_HEADER_TAB_SELECTED_BACKGROUND = crate::color::Color::hex(0x313b45),
        UI_TOOL_WINDOW_HEADER_TAB_SELECTED_INACTIVE_BACKGROUND = crate::color::Color::hex(0x343638),
        UI_TREE_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_TREE_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_TREE_HASH = crate::color::Color::hex(0x505355),
        UI_VALIDATION_TOOLTIP_ERROR_BACKGROUND = crate::color::Color::hex(0x593d41),
        UI_VALIDATION_TOOLTIP_ERROR_BORDER_COLOR = crate::color::Color::hex(0x73454b),
        UI_VALIDATION_TOOLTIP_WARNING_BACKGROUND = crate::color::Color::hex(0x594e32),
        UI_VALIDATION_TOOLTIP_WARNING_BORDER_COLOR = crate::color::Color::hex(0x78550b),
        UI_VERSION_CONTROL_FILE_HISTORY_COMMIT_SELECTED_BRANCH_BACKGROUND = crate::color::Color::hex(0x49493f),
        UI_VERSION_CONTROL_HG_LOG_BOOKMARK_ICON_COLOR = crate::color::Color::hex(0x9f79b5),
        UI_VERSION_CONTROL_HG_LOG_BRANCH_ICON_COLOR = crate::color::Color::hex(0x3cb45c),
        UI_VERSION_CONTROL_HG_LOG_CLOSED_BRANCH_ICON_COLOR = crate::color::Color::hex(0xff5f6f),
        UI_VERSION_CONTROL_HG_LOG_HEAD_ICON_COLOR = crate::color::Color::hex(0xc31e8c),
        UI_VERSION_CONTROL_HG_LOG_LOCAL_TAG_ICON_COLOR = crate::color::Color::hex(0x00f3f3),
        UI_VERSION_CONTROL_HG_LOG_MQ_TAG_ICON_COLOR = crate::color::Color::hex(0x0055ff),
        UI_VERSION_CONTROL_HG_LOG_TAG_ICON_COLOR = crate::color::Color::hex(0x999999),
        UI_VERSION_CONTROL_HG_LOG_TIP_ICON_COLOR = crate::color::Color::hex(0xe1c731),
        UI_VERSION_CONTROL_LOG_COMMIT_CURRENT_BRANCH_BACKGROUND = crate::color::Color::hex(0x3f4749),
        UI_VERSION_CONTROL_LOG_COMMIT_REFERENCE_FOREGROUND = crate::color::Color::hex(0x909090),
        UI_VERSION_CONTROL_LOG_COMMIT_UNMATCHED_FOREGROUND = crate::color::Color::hex(0x606060),
        UI_VERSION_CONTROL_REF_LABEL_FOREGROUND = crate::color::Color::hex(0x909090),
        UI_COMBINED_DIFF_BLOCK_BORDER_SELECTED_ACTIVE_COLOR = crate::color::Color::hex(0x375fad),
        UI_COMBINED_DIFF_BLOCK_BORDER_SELECTED_INACTIVE_COLOR = crate::color::Color::hex(0x5a5d63),
        UI_TAG_BACKGROUND = crate::color::Color::hex(0x4c5052),
        UI_ACTIVE_CAPTION = crate::color::Color::hex(0x434e60),
        UI_CONTROL = crate::color::Color::hex(0x3c3f41),
        UI_CONTROL_TEXT = crate::color::Color::hex(0xbbbbbb),
        UI_INACTIVE_CAPTION = crate::color::Color::hex(0x393c3d),
        UI_INFO_TEXT = crate::color::Color::hex(0xbbbbbb),
        UI_TEXT = crate::color::Color::hex(0xbbbbbb),
        UI_TEXT_INACTIVE_TEXT = crate::color::Color::hex(0x808080),
        UI_TEXT_TEXT = crate::color::Color::hex(0xbbbbbb),
        UI_WINDOW = crate::color::Color::hex(0x3c3f41),
        UI_LESSON_SHORTCUT_BACKGROUND = crate::color::Color::hex(0x333638),
        UI_LESSON_STEP_NUMBER_FOREGROUND = crate::color::Color::hex(0xfefefe),
        UI_LESSON_BADGE_NEW_LESSON_BACKGROUND = crate::color::Color::hex(0x499c54),
        UI_LESSON_BADGE_NEW_LESSON_FOREGROUND = crate::color::Color::hex(0xfefefe),
        UI_TOOLBAR_FLOATING_BACKGROUND = crate::color::Color::hex(0x454a4d),
        UI_TOOLTIP_LEARNING_BACKGROUND = crate::color::Color::hex(0x0e62cf),
        UI_TOOLTIP_LEARNING_BORDER_COLOR = crate::color::Color::hex(0x0e62cf),
        UI_TOOLTIP_LEARNING_SPAN_BACKGROUND = crate::color::Color::hex(0x0250b0),
        UI_TOOLTIP_LEARNING_SPAN_FOREGROUND = crate::color::Color::hex(0xf5f5f5),
        UI_TOOLTIP_LEARNING_FOREGROUND = crate::color::Color::hex(0xf5f5f5),
        UI_TOOLTIP_LEARNING_STEP_NUMBER_FOREGROUND = crate::color::Color::hex(0x6a9dde),
        UI_TOOLTIP_LEARNING_SECONDARY_ACTION_FOREGROUND = crate::color::Color::hex(0x6a9dde),
        UI_TOOLTIP_ACTIONS_BACKGROUND = crate::color::Color::hex(0x43474a),
        UI_TOOLTIP_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_TOOLTIP_FOREGROUND = crate::color::Color::hex(0xbfbfbf),
        UI_MAIN_TOOLBAR_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_MAIN_TOOLBAR_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_MAIN_TOOLBAR_ICON_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_MAIN_TOOLBAR_ICON_HOVER_BACKGROUND = crate::color::Color::hex(0x4c5052),
        UI_MAIN_TOOLBAR_ICON_PRESSED_BACKGROUND = crate::color::Color::hex(0x4c5052),
        UI_MAIN_TOOLBAR_DROPDOWN_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_MAIN_TOOLBAR_DROPDOWN_HOVER_BACKGROUND = crate::color::Color::hex(0x4c5052),
        UI_MAIN_TOOLBAR_DROPDOWN_PRESSED_BACKGROUND = crate::color::Color::hex(0x4c5052),
        UI_PLUGINS_BACKGROUND = crate::color::Color::hex(0x313335),
        UI_PLUGINS_SEARCH_FIELD_BACKGROUND = crate::color::Color::hex(0x313335),
        UI_PLUGINS_SECTION_HEADER_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_PLUGINS_SECTION_HEADER_FOREGROUND = crate::color::Color::hex(0x999999),
        UI_PLUGINS_BORDER_COLOR = crate::color::Color::hex(0x515151),
        UI_TIP_OF_THE_DAY_IMAGE_BORDER_COLOR = crate::color::Color::hex(0x323232),
        UI_PACKAGE_SEARCH_SEARCH_RESULT_BACKGROUND = crate::color::Color::hex(0x3f4749),
        UI_PACKAGE_SEARCH_SEARCH_RESULT_HOVER_BACKGROUND = crate::color::Color::hex(0x464a4d),
        UI_PACKAGE_SEARCH_SEARCH_RESULT_PACKAGE_TAG_BACKGROUND = crate::color::Color::hex(0x4e5658),
        UI_PACKAGE_SEARCH_SEARCH_RESULT_PACKAGE_TAG_FOREGROUND = crate::color::Color::hex(0x8e8f8f),
        UI_PACKAGE_SEARCH_SEARCH_RESULT_PACKAGE_TAG_HOVER_BACKGROUND = crate::color::Color::hex(0x55585b),
        UI_PACKAGE_SEARCH_SEARCH_RESULT_PACKAGE_TAG_SELECTED_BACKGROUND = crate::color::Color::hex(0x2f65ca),
        UI_PACKAGE_SEARCH_SEARCH_RESULT_PACKAGE_TAG_SELECTED_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_PACKAGE_SEARCH_PACKAGE_TAG_BACKGROUND = crate::color::Color::hex(0x4c4e50),
        UI_PACKAGE_SEARCH_PACKAGE_TAG_FOREGROUND = crate::color::Color::hex(0x9c9c9c),
        UI_PACKAGE_SEARCH_PACKAGE_TAG_HOVER_BACKGROUND = crate::color::Color::hex(0x55585b),
        UI_PACKAGE_SEARCH_PACKAGE_TAG_SELECTED_BACKGROUND = crate::color::Color::hex(0x78ade2),
        UI_PACKAGE_SEARCH_PACKAGE_TAG_SELECTED_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_RUN_WIDGET_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_RUN_WIDGET_RUN_ICON_COLOR = crate::color::Color::hex(0x5fad65),
        UI_RUN_WIDGET_RUNNING_BACKGROUND = crate::color::Color::hex(0x599e5e),
        UI_RUN_WIDGET_STOP_BACKGROUND = crate::color::Color::hex(0xc94f4f),
        UI_RUN_WIDGET_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x00000019),
        UI_RUN_WIDGET_PRESSED_BACKGROUND = crate::color::Color::hex_alpha(0x00000028),
        UI_MAIN_WINDOW_FULL_SCREE_CONTROL_BACKGROUND = crate::color::Color::hex(0x575a5c),
        UI_MAIN_WINDOW_TAB_SELECTED_FOREGROUND = crate::color::Color::hex(0xced0d6),
        UI_MAIN_WINDOW_TAB_SELECTED_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_MAIN_WINDOW_TAB_SELECTED_INACTIVE_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_MAIN_WINDOW_TAB_FOREGROUND = crate::color::Color::hex(0xb4b8bf),
        UI_MAIN_WINDOW_TAB_BACKGROUND = crate::color::Color::hex(0x131314),
        UI_MAIN_WINDOW_TAB_HOVER_FOREGROUND = crate::color::Color::hex(0xced0d6),
        UI_MAIN_WINDOW_TAB_HOVER_BACKGROUND = crate::color::Color::hex(0x1a1a1b),
        UI_MAIN_WINDOW_TAB_SEPARATOR_COLOR = crate::color::Color::hex(0x2b2d30),
        UI_MAIN_WINDOW_TAB_BORDER_COLOR = crate::color::Color::hex(0x1e1f22),
        UI_PROFILER_CHART_SLIDER_FOREGROUND = crate::color::Color::hex(0xfefefe),
        UI_PROFILER_CHART_SLIDER_LINE_COLOR = crate::color::Color::hex(0x9aa7b0),
        UI_PROFILER_CPU_CHART_BACKGROUND = crate::color::Color::hex_alpha(0x6296554d),
        UI_PROFILER_CPU_CHART_BORDER_COLOR = crate::color::Color::hex(0x629655),
        UI_PROFILER_CPU_CHART_INACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0x62965533),
        UI_PROFILER_CPU_CHART_INACTIVE_BORDER_COLOR = crate::color::Color::hex(0x4f6a4b),
        UI_PROFILER_CPU_CHART_POINT_BACKGROUND = crate::color::Color::hex(0x629625),
        UI_PROFILER_CPU_CHART_POINT_BORDER_COLOR = crate::color::Color::hex(0x3c3f41),
        UI_PROFILER_MEMORY_CHART_BACKGROUND = crate::color::Color::hex_alpha(0x589df680),
        UI_PROFILER_MEMORY_CHART_BORDER_COLOR = crate::color::Color::hex(0x589df6),
        UI_PROFILER_MEMORY_CHART_INACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0x589df633),
        UI_PROFILER_MEMORY_CHART_INACTIVE_BORDER_COLOR = crate::color::Color::hex(0x476589),
        UI_PROFILER_MEMORY_CHART_POINT_BACKGROUND = crate::color::Color::hex(0x589df6),
        UI_PROFILER_MEMORY_CHART_POINT_BORDER_COLOR = crate::color::Color::hex(0x3c3f41),
        UI_PROFILER_TIMER_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_PROFILER_TIMER_DISABLED_FOREGROUND = crate::color::Color::hex(0x777777),
        UI_PROFILER_TIMER_BACKGROUND = crate::color::Color::hex(0x323232),
        UI_PROFILER_LIVE_CHART_HORIZONTAL_AXIS_COLOR = crate::color::Color::hex(0xd1d1d1),
        UI_COMPILATION_CHARTS_BACKGROUND_ODD = crate::color::Color::hex(0x2b2d30),
        UI_COMPILATION_CHARTS_BACKGROUND_EVEN = crate::color::Color::hex(0x393b40),
        UI_COMPILATION_CHARTS_BACKGROUND_DEFAULT = crate::color::Color::hex(0x2b2d30),
        UI_COMPILATION_CHARTS_TEST_ENABLED = crate::color::Color::hex(0x375239),
        UI_COMPILATION_CHARTS_TEST_DISABLED = crate::color::Color::hex(0x273828),
        UI_COMPILATION_CHARTS_TEST_STROKE = crate::color::Color::hex(0x57965c),
        UI_COMPILATION_CHARTS_TEST_SELECTED = crate::color::Color::hex(0x73bd79),
        UI_COMPILATION_CHARTS_PRODUCTION_ENABLED = crate::color::Color::hex(0x2e436e),
        UI_COMPILATION_CHARTS_PRODUCTION_DISABLED = crate::color::Color::hex(0x25324d),
        UI_COMPILATION_CHARTS_PRODUCTION_STROKE = crate::color::Color::hex(0x3574f0),
        UI_COMPILATION_CHARTS_PRODUCTION_SELECTED = crate::color::Color::hex(0x548af7),
        UI_COMPILATION_CHARTS_MEMORY_BACKGROUND = crate::color::Color::hex(0x2e436e),
        UI_COMPILATION_CHARTS_MEMORY_STROKE = crate::color::Color::hex(0x548af7),
        UI_COMPILATION_CHARTS_CPU_BACKGROUND = crate::color::Color::hex(0x375239),
        UI_COMPILATION_CHARTS_CPU_STROKE = crate::color::Color::hex(0x57965c),
        UI_COMPILATION_CHARTS_LINE_COLOR = crate::color::Color::hex(0x1e1f22),
        UI_COMPILATION_CHARTS_TEXT_COLOR = crate::color::Color::hex(0xb4b8bf),
        UI_FLAME_GRAPH_TOOLTIP_SCALE_BACKGROUND = crate::color::Color::hex(0x363839),
        UI_FLAME_GRAPH_TOOLTIP_SCALE_COLOR = crate::color::Color::hex(0x365880),
        UI_FLAME_GRAPH_TOOLTIP_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_LINE_PROFILER_LINE_LABEL_BACKGROUND = crate::color::Color::hex(0x43474a),
        UI_LINE_PROFILER_LINE_FOREGROUND = crate::color::Color::hex(0x787878),
        UI_LINE_PROFILER_LINE_HOVER_BACKGROUND = crate::color::Color::hex(0x4a4e52),
        UI_LINE_PROFILER_HOT_LINE_LABEL_BACKGROUND = crate::color::Color::hex(0x593d41),
        UI_LINE_PROFILER_HOT_LINE_FOREGROUND = crate::color::Color::hex(0xff5261),
        UI_LINE_PROFILER_HOT_LINE_HOVER_BACKGROUND = crate::color::Color::hex(0x704745),
        UI_LINE_PROFILER_IGNORED_LINE_LABEL_BACKGROUND = crate::color::Color::hex(0x43474a),
        UI_LINE_PROFILER_IGNORED_LINE_FOREGROUND = crate::color::Color::hex(0x5f5f5f),
        UI_IDE_SHADOW_TOP_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_IDE_SHADOW_TOP_1_COLOR = crate::color::Color::hex_alpha(0x00000012),
        UI_IDE_SHADOW_BOTTOM_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_IDE_SHADOW_BOTTOM_1_COLOR = crate::color::Color::hex_alpha(0x00000012),
        UI_IDE_SHADOW_LEFT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_IDE_SHADOW_LEFT_1_COLOR = crate::color::Color::hex_alpha(0x00000012),
        UI_IDE_SHADOW_RIGHT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_IDE_SHADOW_RIGHT_1_COLOR = crate::color::Color::hex_alpha(0x00000012),
        UI_IDE_SHADOW_TOP_LEFT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_IDE_SHADOW_TOP_LEFT_1_COLOR = crate::color::Color::hex_alpha(0x00000012),
        UI_IDE_SHADOW_TOP_RIGHT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_IDE_SHADOW_TOP_RIGHT_1_COLOR = crate::color::Color::hex_alpha(0x00000012),
        UI_IDE_SHADOW_BOTTOM_LEFT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_IDE_SHADOW_BOTTOM_LEFT_1_COLOR = crate::color::Color::hex_alpha(0x00000012),
        UI_IDE_SHADOW_BOTTOM_RIGHT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_IDE_SHADOW_BOTTOM_RIGHT_1_COLOR = crate::color::Color::hex_alpha(0x00000012),
        UI_NOTIFICATION_BACKGROUND = crate::color::Color::hex(0x4e5052),
        UI_NOTIFICATION_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        UI_NOTIFICATION_MORE_BUTTON_BACKGROUND = crate::color::Color::hex(0x3a3c3d),
        UI_NOTIFICATION_MORE_BUTTON_FOREGROUND = crate::color::Color::hex(0x8c8c8c),
        UI_NOTIFICATION_SHADOW_TOP_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_NOTIFICATION_SHADOW_TOP_1_COLOR = crate::color::Color::hex_alpha(0x00000010),
        UI_NOTIFICATION_SHADOW_BOTTOM_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_NOTIFICATION_SHADOW_BOTTOM_1_COLOR = crate::color::Color::hex_alpha(0x00000010),
        UI_NOTIFICATION_SHADOW_LEFT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_NOTIFICATION_SHADOW_LEFT_1_COLOR = crate::color::Color::hex_alpha(0x00000010),
        UI_NOTIFICATION_SHADOW_RIGHT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_NOTIFICATION_SHADOW_RIGHT_1_COLOR = crate::color::Color::hex_alpha(0x00000010),
        UI_NOTIFICATION_SHADOW_TOP_LEFT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_NOTIFICATION_SHADOW_TOP_LEFT_1_COLOR = crate::color::Color::hex_alpha(0x00000009),
        UI_NOTIFICATION_SHADOW_TOP_RIGHT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_NOTIFICATION_SHADOW_TOP_RIGHT_1_COLOR = crate::color::Color::hex_alpha(0x00000009),
        UI_NOTIFICATION_SHADOW_BOTTOM_LEFT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_NOTIFICATION_SHADOW_BOTTOM_LEFT_1_COLOR = crate::color::Color::hex_alpha(0x00000009),
        UI_NOTIFICATION_SHADOW_BOTTOM_RIGHT_0_COLOR = crate::color::Color::hex_alpha(0x00000000),
        UI_NOTIFICATION_SHADOW_BOTTOM_RIGHT_1_COLOR = crate::color::Color::hex_alpha(0x00000009),
        UI_NOTIFICATION_WELCOME_SCREEN_SEPARATOR_COLOR = crate::color::Color::hex(0x717375),
        UI_WELCOME_SCREEN_BACKGROUND = crate::color::Color::hex(0x45474a),
        UI_WELCOME_SCREEN_DETAILS_BACKGROUND = crate::color::Color::hex(0x313335),
        UI_WELCOME_SCREEN_PROJECTS_ACTIONS_SELECTION_BACKGROUND = crate::color::Color::hex(0x326fc1),
        UI_WELCOME_SCREEN_PROJECTS_ACTIONS_SELECTION_BORDER_COLOR = crate::color::Color::hex(0x3574f0),
        UI_WELCOME_SCREEN_PROJECTS_ACTIONS_BACKGROUND = crate::color::Color::hex(0x3c5c86),
        UI_WELCOME_SCREEN_SIDE_PANEL_BACKGROUND = crate::color::Color::hex(0x3c3f41),
        UI_WELCOME_SCREEN_FRAME_DISCLOSURE_BUTTON_HOVER_OVERLAY = crate::color::Color::hex_alpha(0xffffff0d),
        UI_WELCOME_SCREEN_FRAME_DISCLOSURE_BUTTON_PRESSED_OVERLAY = crate::color::Color::hex_alpha(0xffffff1a),
        UI_RECENT_PROJECT_COLOR_1_MAIN_TOOLBAR_GRADIENT_START = crate::color::Color::hex(0x654b40),
        UI_RECENT_PROJECT_COLOR_1_AVATAR_START = crate::color::Color::hex(0xe08855),
        UI_RECENT_PROJECT_COLOR_1_AVATAR_END = crate::color::Color::hex(0xe9806f),
        UI_RECENT_PROJECT_COLOR_2_MAIN_TOOLBAR_GRADIENT_START = crate::color::Color::hex(0x534c33),
        UI_RECENT_PROJECT_COLOR_2_AVATAR_START = crate::color::Color::hex(0xb08b14),
        UI_RECENT_PROJECT_COLOR_2_AVATAR_END = crate::color::Color::hex(0xbb7f19),
        UI_RECENT_PROJECT_COLOR_3_MAIN_TOOLBAR_GRADIENT_START = crate::color::Color::hex(0x455038),
        UI_RECENT_PROJECT_COLOR_3_AVATAR_START = crate::color::Color::hex(0xa1a359),
        UI_RECENT_PROJECT_COLOR_3_AVATAR_END = crate::color::Color::hex(0x87aa59),
        UI_RECENT_PROJECT_COLOR_4_MAIN_TOOLBAR_GRADIENT_START = crate::color::Color::hex(0x31515f),
        UI_RECENT_PROJECT_COLOR_4_AVATAR_START = crate::color::Color::hex(0x3b92b8),
        UI_RECENT_PROJECT_COLOR_4_AVATAR_END = crate::color::Color::hex(0x6183ec),
        UI_RECENT_PROJECT_COLOR_5_MAIN_TOOLBAR_GRADIENT_START = crate::color::Color::hex(0x344c7d),
        UI_RECENT_PROJECT_COLOR_5_AVATAR_START = crate::color::Color::hex(0x3574f0),
        UI_RECENT_PROJECT_COLOR_5_AVATAR_END = crate::color::Color::hex(0x7a64f0),
        UI_RECENT_PROJECT_COLOR_6_MAIN_TOOLBAR_GRADIENT_START = crate::color::Color::hex(0x5d354a),
        UI_RECENT_PROJECT_COLOR_6_AVATAR_START = crate::color::Color::hex(0xc84d8f),
        UI_RECENT_PROJECT_COLOR_6_AVATAR_END = crate::color::Color::hex(0xa956cf),
        UI_RECENT_PROJECT_COLOR_7_MAIN_TOOLBAR_GRADIENT_START = crate::color::Color::hex(0x4f3e65),
        UI_RECENT_PROJECT_COLOR_7_AVATAR_START = crate::color::Color::hex(0x955ae0),
        UI_RECENT_PROJECT_COLOR_7_AVATAR_END = crate::color::Color::hex(0xa84de0),
        UI_RECENT_PROJECT_COLOR_8_MAIN_TOOLBAR_GRADIENT_START = crate::color::Color::hex(0x1d4744),
        UI_RECENT_PROJECT_COLOR_8_AVATAR_START = crate::color::Color::hex(0x24a394),
        UI_RECENT_PROJECT_COLOR_8_AVATAR_END = crate::color::Color::hex(0x279ccd),
        UI_RECENT_PROJECT_COLOR_9_MAIN_TOOLBAR_GRADIENT_START = crate::color::Color::hex(0x3e5540),
        UI_RECENT_PROJECT_COLOR_9_AVATAR_START = crate::color::Color::hex(0x5fad65),
        UI_RECENT_PROJECT_COLOR_9_AVATAR_END = crate::color::Color::hex(0x3d968b),
        UI_MAIN_TOOLBAR_DROPDOWN_TRANSPARENT_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0xffffff1a),
        UI_UIDESIGNER_COLOR_PICKER_BACKGROUND = crate::color::Color::hex(0x404040),
        UI_UIDESIGNER_COLOR_PICKER_FOREGROUND = crate::color::Color::hex(0x404040),
        UI_UIDESIGNER_COMPONENT_BACKGROUND = crate::color::Color::hex(0x515658),
        UI_UIDESIGNER_COMPONENT_BORDER_COLOR = crate::color::Color::hex(0x2d2f31),
        UI_UIDESIGNER_COMPONENT_FOREGROUND = crate::color::Color::hex(0x888888),
        UI_UIDESIGNER_COMPONENT_HOVER_BORDER_COLOR = crate::color::Color::hex(0xa1a1a1),
        UI_UIDESIGNER_CONNECTOR_BORDER_COLOR = crate::color::Color::hex(0x888888),
        UI_UIDESIGNER_CONNECTOR_HOVER_BORDER_COLOR = crate::color::Color::hex(0x888888),
        UI_UIDESIGNER_PLACEHOLDER_BACKGROUND = crate::color::Color::hex(0x515658),
        UI_UIDESIGNER_PLACEHOLDER_BORDER_COLOR = crate::color::Color::hex(0x3f4244),
        UI_UIDESIGNER_PLACEHOLDER_FOREGROUND = crate::color::Color::hex(0x888888),
        UI_UIDESIGNER_PLACEHOLDER_SELECTED_FOREGROUND = crate::color::Color::hex(0x9ccdff),
        UI_UIDESIGNER_ACTIVITY_BORDER_COLOR = crate::color::Color::hex(0x2d2f31),
        UI_UIDESIGNER_CANVAS_BACKGROUND = crate::color::Color::hex(0x2d2f31),
        UI_UIDESIGNER_HIGH_STROKE_FOREGROUND = crate::color::Color::hex(0xb0b0b0),
        UI_UIDESIGNER_LABEL_FOREGROUND = crate::color::Color::hex(0xbababb),
        UI_UIDESIGNER_LIST_SELECTION_BACKGROUND = crate::color::Color::hex(0x36393a),
        UI_UIDESIGNER_PANEL_BACKGROUND = crate::color::Color::hex(0x313435),
        UI_UIDESIGNER_PERCENT_FOREGROUND = crate::color::Color::hex(0x404040),
        UI_RECAP_IJNEXT = crate::color::Color::hex(0x55339c),
        UI_RECAP_CARD_BACKGROUND = crate::color::Color::hex(0x2b2b2b),
        UI_RECAP_CARD_BORDER_COLOR = crate::color::Color::hex(0x2b2b2b),
        UI_RECAP_CARD_HEADER_TITLE = crate::color::Color::hex(0xd3d3d3),
        UI_RECAP_CARD_HEADER_LINK_BACKGROUND = crate::color::Color::hex(0x3d3f41),
        UI_RECAP_CARD_HEADER_SUBTITLE = crate::color::Color::hex(0xb4b8bf),
        UI_RECAP_CARD_FOOTER_FOREGROUND = crate::color::Color::hex(0xced0d6),
        UI_RECAP_CHRONICLES_BACKGROUND = crate::color::Color::hex(0x3d3f41),
        UI_RECAP_CHRONICLES_BORDER_COLOR = crate::color::Color::hex(0x3d3f41),
        UI_RECAP_CHRONICLES_BACKGROUND_HOVERED = crate::color::Color::hex(0x5e6771),
        UI_RECAP_CHRONICLES_FOREGROUND = crate::color::Color::hex(0xdfe1e5),
        UI_RECAP_CHRONICLES_FOREGROUND_GREYED = crate::color::Color::hex(0x868a91),
        UI_RECAP_ERROR_BACKGROUND = crate::color::Color::hex(0x3d3223),
        UI_RECAP_ERROR_BORDER = crate::color::Color::hex(0x5e4d33),
        UI_RECAP_ERROR_FOREGROUND = crate::color::Color::hex(0xdfe1e5),
        UI_OPEN_TELEMETRY_SPAN_REGULAR_BOUNDS = crate::color::Color::hex(0xced0d6),
        UI_OPEN_TELEMETRY_SPAN_REGULAR_FILL_START = crate::color::Color::hex(0x4a83b8),
        UI_OPEN_TELEMETRY_SPAN_REGULAR_FILL_END = crate::color::Color::hex(0x7750ba),
        UI_OPEN_TELEMETRY_SPAN_SELECTED_BOUNDS = crate::color::Color::hex(0xf0f1f2),
        UI_OPEN_TELEMETRY_SPAN_SELECTED_FILL_START = crate::color::Color::hex(0x23a0ff),
        UI_OPEN_TELEMETRY_SPAN_SELECTED_FILL_END = crate::color::Color::hex(0xaf60ff),
    }
    accents {
        Blue = EDITOR_CONSOLE_BLUE_OUTPUT_FOREGROUND => ("blue", "Blue"),
        Green = EDITOR_CONSOLE_GREEN_OUTPUT_FOREGROUND => ("green", "Green"),
        Yellow = EDITOR_CONSOLE_YELLOW_OUTPUT_FOREGROUND => ("yellow", "Yellow"),
        Red = EDITOR_CONSOLE_RED_OUTPUT_FOREGROUND => ("red", "Red"),
        Magenta = EDITOR_CONSOLE_MAGENTA_OUTPUT_FOREGROUND => ("magenta", "Magenta"),
        Cyan = EDITOR_CONSOLE_CYAN_OUTPUT_FOREGROUND => ("cyan", "Cyan"),
    }
    default EDITOR_CONSOLE_BLUE_OUTPUT_FOREGROUND => "blue";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_TEXT_BACKGROUND,
            surface: Self::UI_BACKGROUND,
            raised: Self::UI_TEXT_FIELD_BACKGROUND,
            overlay: Self::UI_POPUP_BACKGROUND,
            hover: Self::UI_ACTION_BUTTON_HOVER_BACKGROUND,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::UI_BACKGROUND,
            surface: Self::EDITOR_TEXT_BACKGROUND,
            raised: Self::UI_BACKGROUND,
            overlay: Self::UI_POPUP_BACKGROUND,
            hover: Self::UI_ACTION_BUTTON_HOVER_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::EDITOR_TEXT_FOREGROUND,
            muted: Self::UI_LABEL_FOREGROUND,
            subtle: Self::UI_COMPONENT_INFO_FOREGROUND,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::UI_BUTTON_START_BACKGROUND),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::UI_BACKGROUND,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::UI_BUTTON_START_BACKGROUND,
            hover: Self::UI_ACTION_BUTTON_HOVER_BACKGROUND,
            pressed: Self::UI_ACTION_BUTTON_PRESSED_BACKGROUND,
            muted: Self::UI_BACKGROUND,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::EDITOR_CONSOLE_GREEN_OUTPUT_FOREGROUND,
            warning: Self::EDITOR_CONSOLE_YELLOW_OUTPUT_FOREGROUND,
            error: Self::EDITOR_CONSOLE_RED_OUTPUT_FOREGROUND,
            critical: Self::EDITOR_ERRORS_ATTRIBUTES_EFFECT_COLOR,
            info: Self::EDITOR_CONSOLE_BLUE_OUTPUT_FOREGROUND,
            trace: Self::UI_COMPONENT_INFO_FOREGROUND,
        },
        border: Self::UI_COMPONENT_BORDER_COLOR,
        border_muted: Self::UI_BACKGROUND,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::EDITOR_CONSOLE_RED_OUTPUT_FOREGROUND,
            orange: Self::EDITOR_DEFAULT_KEYWORD_FOREGROUND,
            yellow: Self::EDITOR_CONSOLE_YELLOW_OUTPUT_FOREGROUND,
            green: Self::EDITOR_CONSOLE_GREEN_OUTPUT_FOREGROUND,
            cyan: Self::EDITOR_CONSOLE_CYAN_OUTPUT_FOREGROUND,
            blue: Self::EDITOR_CONSOLE_BLUE_OUTPUT_FOREGROUND,
            purple: Self::EDITOR_CONSOLE_MAGENTA_OUTPUT_FOREGROUND,
            pink: Self::EDITOR_RAINBOW_COLOR_4_FOREGROUND,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::EDITOR_DEFAULT_METADATA_FOREGROUND,
            boolean: Self::EDITOR_DEFAULT_KEYWORD_FOREGROUND,
            builtin: Self::EDITOR_DEFAULT_CLASS_REFERENCE_FOREGROUND,
            builtin_function: Self::EDITOR_DEFAULT_FUNCTION_DECLARATION_FOREGROUND,
            builtin_type: Self::EDITOR_DEFAULT_CLASS_REFERENCE_FOREGROUND,
            comment: Self::EDITOR_DEFAULT_LINE_COMMENT_FOREGROUND,
            constant: Self::EDITOR_DEFAULT_CONSTANT_FOREGROUND,
            control_keyword: Self::EDITOR_DEFAULT_KEYWORD_FOREGROUND,
            deleted: Self::EDITOR_CONSOLE_RED_OUTPUT_FOREGROUND,
            deprecated: Self::EDITOR_CONSOLE_RED_OUTPUT_FOREGROUND,
            documentation: Self::EDITOR_DEFAULT_DOC_COMMENT_FOREGROUND,
            escape: Self::EDITOR_DEFAULT_VALID_STRING_ESCAPE_FOREGROUND,
            foreground: Self::EDITOR_DEFAULT_IDENTIFIER_FOREGROUND,
            function: Self::EDITOR_DEFAULT_FUNCTION_DECLARATION_FOREGROUND,
            heading: Self::EDITOR_DEFAULT_FUNCTION_DECLARATION_FOREGROUND,
            inserted: Self::EDITOR_CONSOLE_GREEN_OUTPUT_FOREGROUND,
            invalid: Self::EDITOR_CONSOLE_RED_OUTPUT_FOREGROUND,
            keyword: Self::EDITOR_DEFAULT_KEYWORD_FOREGROUND,
            link: Self::UI_BUTTON_START_BACKGROUND,
            markup_bold: Self::EDITOR_TEXT_FOREGROUND,
            markup_italic: Self::EDITOR_TEXT_FOREGROUND,
            modifier: Self::EDITOR_DEFAULT_KEYWORD_FOREGROUND,
            namespace: Self::EDITOR_DEFAULT_CLASS_REFERENCE_FOREGROUND,
            number: Self::EDITOR_DEFAULT_NUMBER_FOREGROUND,
            operator: Self::EDITOR_TEXT_FOREGROUND,
            parameter: Self::EDITOR_DEFAULT_IDENTIFIER_FOREGROUND,
            property: Self::EDITOR_DEFAULT_INSTANCE_FIELD_FOREGROUND,
            punctuation: Self::EDITOR_DEFAULT_COMMA_FOREGROUND,
            string: Self::EDITOR_DEFAULT_STRING_FOREGROUND,
            tag: Self::UI_BUTTON_START_BACKGROUND,
            type_keyword: Self::EDITOR_DEFAULT_KEYWORD_FOREGROUND,
            type_name: Self::EDITOR_DEFAULT_CLASS_REFERENCE_FOREGROUND,
            variable: Self::EDITOR_DEFAULT_IDENTIFIER_FOREGROUND,
        },
    }
}
