//! Kanagawa Dragon. See the family module for its upstream source.

define_palette! {
    Dragon, "Kanagawa Dragon",
    identity("kanagawa/dragon", "kanagawa", "Kanagawa", "dragon", "Dragon", Dark, None);
    support(Dark);
    sources: super::SOURCE;
    colors {
        SUMI_INK_0 = crate::color::Color::hex(0x16161d),
        SUMI_INK_1 = crate::color::Color::hex(0x181820),
        SUMI_INK_2 = crate::color::Color::hex(0x1a1a22),
        SUMI_INK_3 = crate::color::Color::hex(0x1f1f28),
        SUMI_INK_4 = crate::color::Color::hex(0x2a2a37),
        SUMI_INK_5 = crate::color::Color::hex(0x363646),
        SUMI_INK_6 = crate::color::Color::hex(0x54546d),
        WAVE_BLUE_1 = crate::color::Color::hex(0x223249),
        WAVE_BLUE_2 = crate::color::Color::hex(0x2d4f67),
        WINTER_GREEN = crate::color::Color::hex(0x2b3328),
        WINTER_YELLOW = crate::color::Color::hex(0x49443c),
        WINTER_RED = crate::color::Color::hex(0x43242b),
        WINTER_BLUE = crate::color::Color::hex(0x252535),
        AUTUMN_GREEN = crate::color::Color::hex(0x76946a),
        AUTUMN_RED = crate::color::Color::hex(0xc34043),
        AUTUMN_YELLOW = crate::color::Color::hex(0xdca561),
        SAMURAI_RED = crate::color::Color::hex(0xe82424),
        RONIN_YELLOW = crate::color::Color::hex(0xff9e3b),
        WAVE_AQUA_1 = crate::color::Color::hex(0x6a9589),
        DRAGON_BLUE = crate::color::Color::hex(0x658594),
        OLD_WHITE = crate::color::Color::hex(0xc8c093),
        FUJI_WHITE = crate::color::Color::hex(0xdcd7ba),
        FUJI_GRAY = crate::color::Color::hex(0x727169),
        ONI_VIOLET = crate::color::Color::hex(0x957fb8),
        ONI_VIOLET_2 = crate::color::Color::hex(0xb8b4d0),
        CRYSTAL_BLUE = crate::color::Color::hex(0x7e9cd8),
        SPRING_VIOLET_1 = crate::color::Color::hex(0x938aa9),
        SPRING_VIOLET_2 = crate::color::Color::hex(0x9cabca),
        SPRING_BLUE = crate::color::Color::hex(0x7fb4ca),
        LIGHT_BLUE = crate::color::Color::hex(0xa3d4d5),
        WAVE_AQUA_2 = crate::color::Color::hex(0x7aa89f),
        SPRING_GREEN = crate::color::Color::hex(0x98bb6c),
        BOAT_YELLOW_1 = crate::color::Color::hex(0x938056),
        BOAT_YELLOW_2 = crate::color::Color::hex(0xc0a36e),
        CARP_YELLOW = crate::color::Color::hex(0xe6c384),
        SAKURA_PINK = crate::color::Color::hex(0xd27e99),
        WAVE_RED = crate::color::Color::hex(0xe46876),
        PEACH_RED = crate::color::Color::hex(0xff5d62),
        SURIMI_ORANGE = crate::color::Color::hex(0xffa066),
        KATANA_GRAY = crate::color::Color::hex(0x717c7c),
        DRAGON_BLACK_0 = crate::color::Color::hex(0x0d0c0c),
        DRAGON_BLACK_1 = crate::color::Color::hex(0x12120f),
        DRAGON_BLACK_2 = crate::color::Color::hex(0x1d1c19),
        DRAGON_BLACK_3 = crate::color::Color::hex(0x181616),
        DRAGON_BLACK_4 = crate::color::Color::hex(0x282727),
        DRAGON_BLACK_5 = crate::color::Color::hex(0x393836),
        DRAGON_BLACK_6 = crate::color::Color::hex(0x625e5a),
        DRAGON_WHITE = crate::color::Color::hex(0xc5c9c5),
        DRAGON_GREEN = crate::color::Color::hex(0x87a987),
        DRAGON_GREEN_2 = crate::color::Color::hex(0x8a9a7b),
        DRAGON_PINK = crate::color::Color::hex(0xa292a3),
        DRAGON_ORANGE = crate::color::Color::hex(0xb6927b),
        DRAGON_ORANGE_2 = crate::color::Color::hex(0xb98d7b),
        DRAGON_GRAY = crate::color::Color::hex(0xa6a69c),
        DRAGON_GRAY_2 = crate::color::Color::hex(0x9e9b93),
        DRAGON_GRAY_3 = crate::color::Color::hex(0x7a8382),
        DRAGON_BLUE_2 = crate::color::Color::hex(0x8ba4b0),
        DRAGON_VIOLET = crate::color::Color::hex(0x8992a7),
        DRAGON_RED = crate::color::Color::hex(0xc4746e),
        DRAGON_AQUA = crate::color::Color::hex(0x8ea4a2),
        DRAGON_ASH = crate::color::Color::hex(0x737c73),
        DRAGON_TEAL = crate::color::Color::hex(0x949fb5),
        DRAGON_YELLOW = crate::color::Color::hex(0xc4b28a),
        LOTUS_INK_1 = crate::color::Color::hex(0x545464),
        LOTUS_INK_2 = crate::color::Color::hex(0x43436c),
        LOTUS_GRAY = crate::color::Color::hex(0xdcd7ba),
        LOTUS_GRAY_2 = crate::color::Color::hex(0x716e61),
        LOTUS_GRAY_3 = crate::color::Color::hex(0x8a8980),
        LOTUS_WHITE_0 = crate::color::Color::hex(0xd5cea3),
        LOTUS_WHITE_1 = crate::color::Color::hex(0xdcd5ac),
        LOTUS_WHITE_2 = crate::color::Color::hex(0xe5ddb0),
        LOTUS_WHITE_3 = crate::color::Color::hex(0xf2ecbc),
        LOTUS_WHITE_4 = crate::color::Color::hex(0xe7dba0),
        LOTUS_WHITE_5 = crate::color::Color::hex(0xe4d794),
        LOTUS_VIOLET_1 = crate::color::Color::hex(0xa09cac),
        LOTUS_VIOLET_2 = crate::color::Color::hex(0x766b90),
        LOTUS_VIOLET_3 = crate::color::Color::hex(0xc9cbd1),
        LOTUS_VIOLET_4 = crate::color::Color::hex(0x624c83),
        LOTUS_BLUE_1 = crate::color::Color::hex(0xc7d7e0),
        LOTUS_BLUE_2 = crate::color::Color::hex(0xb5cbd2),
        LOTUS_BLUE_3 = crate::color::Color::hex(0x9fb5c9),
        LOTUS_BLUE_4 = crate::color::Color::hex(0x4d699b),
        LOTUS_BLUE_5 = crate::color::Color::hex(0x5d57a3),
        LOTUS_GREEN = crate::color::Color::hex(0x6f894e),
        LOTUS_GREEN_2 = crate::color::Color::hex(0x6e915f),
        LOTUS_GREEN_3 = crate::color::Color::hex(0xb7d0ae),
        LOTUS_PINK = crate::color::Color::hex(0xb35b79),
        LOTUS_ORANGE = crate::color::Color::hex(0xcc6d00),
        LOTUS_ORANGE_2 = crate::color::Color::hex(0xe98a00),
        LOTUS_YELLOW = crate::color::Color::hex(0x77713f),
        LOTUS_YELLOW_2 = crate::color::Color::hex(0x836f4a),
        LOTUS_YELLOW_3 = crate::color::Color::hex(0xde9800),
        LOTUS_YELLOW_4 = crate::color::Color::hex(0xf9d791),
        LOTUS_RED = crate::color::Color::hex(0xc84053),
        LOTUS_RED_2 = crate::color::Color::hex(0xd7474b),
        LOTUS_RED_3 = crate::color::Color::hex(0xe82424),
        LOTUS_RED_4 = crate::color::Color::hex(0xd9a594),
        LOTUS_AQUA = crate::color::Color::hex(0x597b75),
        LOTUS_AQUA_2 = crate::color::Color::hex(0x5e857a),
        LOTUS_TEAL_1 = crate::color::Color::hex(0x4e8ca2),
        LOTUS_TEAL_2 = crate::color::Color::hex(0x6693bf),
        LOTUS_TEAL_3 = crate::color::Color::hex(0x5a7785),
        LOTUS_CYAN = crate::color::Color::hex(0xd7e3d8),
    }
    accents {
        DragonBlue2 = DRAGON_BLUE_2 => ("dragon_blue_2", "Dragon Blue 2"),
        DragonViolet = DRAGON_VIOLET => ("dragon_violet", "Dragon Violet"),
        DragonGreen = DRAGON_GREEN => ("dragon_green", "Dragon Green"),
        DragonYellow = DRAGON_YELLOW => ("dragon_yellow", "Dragon Yellow"),
        DragonPink = DRAGON_PINK => ("dragon_pink", "Dragon Pink"),
        DragonRed = DRAGON_RED => ("dragon_red", "Dragon Red"),
        DragonOrange = DRAGON_ORANGE => ("dragon_orange", "Dragon Orange"),
        DragonAqua = DRAGON_AQUA => ("dragon_aqua", "Dragon Aqua"),
    }
    default DRAGON_BLUE_2 => "dragon_blue_2";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::DRAGON_BLACK_3,
            surface: Self::DRAGON_BLACK_4,
            raised: Self::DRAGON_BLACK_5,
            overlay: Self::DRAGON_BLACK_0,
            hover: Self::DRAGON_BLACK_5,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::DRAGON_BLACK_0,
            surface: Self::DRAGON_BLACK_1,
            raised: Self::DRAGON_BLACK_2,
            overlay: Self::DRAGON_BLACK_0,
            hover: Self::DRAGON_BLACK_4,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::DRAGON_WHITE,
            muted: Self::OLD_WHITE,
            subtle: Self::DRAGON_ASH,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::DRAGON_VIOLET),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::DRAGON_BLACK_5,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::DRAGON_VIOLET,
            hover: crate::palette::primary_hover(Self::DRAGON_VIOLET),
            pressed: crate::palette::action_pressed(Self::DRAGON_VIOLET),
            muted: Self::DRAGON_BLACK_4,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::SPRING_GREEN,
            warning: Self::RONIN_YELLOW,
            error: Self::SAMURAI_RED,
            critical: Self::SAMURAI_RED,
            info: Self::DRAGON_BLUE,
            trace: Self::DRAGON_GRAY_3,
        },
        border: Self::DRAGON_BLACK_6,
        border_muted: Self::DRAGON_BLACK_5,
        focus: primary,
    }
}
