//! Kanagawa Lotus. See the family module for its upstream source.

define_palette! {
    Lotus, "Kanagawa Lotus",
    identity("kanagawa/lotus", "kanagawa", "Kanagawa", "lotus", "Lotus", Light, None);
    sources: super::SOURCE;
    colors {
        SUMI_INK_0 = crate::color::Color::hex(0x16161d),
        SUMI_INK_1 = crate::color::Color::hex(0x181820),
        SUMI_INK_2 = crate::color::Color::hex(0x1a1a22),
        SUMI_INK_3 = crate::color::Color::hex(0x1f1f28),
        SUMI_INK_4 = crate::color::Color::hex(0x2a2a37),
        SUMI_INK_5 = crate::color::Color::hex(0x363646),
        SUMI_INK_6 = crate::color::Color::hex(0x54546d),
        WAVE_BLUE_1 = crate::color::Color::hex(0x223249),
        WAVE_BLUE_2 = crate::color::Color::hex(0x2d4f67),
        WINTER_GREEN = crate::color::Color::hex(0x2b3328),
        WINTER_YELLOW = crate::color::Color::hex(0x49443c),
        WINTER_RED = crate::color::Color::hex(0x43242b),
        WINTER_BLUE = crate::color::Color::hex(0x252535),
        AUTUMN_GREEN = crate::color::Color::hex(0x76946a),
        AUTUMN_RED = crate::color::Color::hex(0xc34043),
        AUTUMN_YELLOW = crate::color::Color::hex(0xdca561),
        SAMURAI_RED = crate::color::Color::hex(0xe82424),
        RONIN_YELLOW = crate::color::Color::hex(0xff9e3b),
        WAVE_AQUA_1 = crate::color::Color::hex(0x6a9589),
        DRAGON_BLUE = crate::color::Color::hex(0x658594),
        OLD_WHITE = crate::color::Color::hex(0xc8c093),
        FUJI_WHITE = crate::color::Color::hex(0xdcd7ba),
        FUJI_GRAY = crate::color::Color::hex(0x727169),
        ONI_VIOLET = crate::color::Color::hex(0x957fb8),
        ONI_VIOLET_2 = crate::color::Color::hex(0xb8b4d0),
        CRYSTAL_BLUE = crate::color::Color::hex(0x7e9cd8),
        SPRING_VIOLET_1 = crate::color::Color::hex(0x938aa9),
        SPRING_VIOLET_2 = crate::color::Color::hex(0x9cabca),
        SPRING_BLUE = crate::color::Color::hex(0x7fb4ca),
        LIGHT_BLUE = crate::color::Color::hex(0xa3d4d5),
        WAVE_AQUA_2 = crate::color::Color::hex(0x7aa89f),
        SPRING_GREEN = crate::color::Color::hex(0x98bb6c),
        BOAT_YELLOW_1 = crate::color::Color::hex(0x938056),
        BOAT_YELLOW_2 = crate::color::Color::hex(0xc0a36e),
        CARP_YELLOW = crate::color::Color::hex(0xe6c384),
        SAKURA_PINK = crate::color::Color::hex(0xd27e99),
        WAVE_RED = crate::color::Color::hex(0xe46876),
        PEACH_RED = crate::color::Color::hex(0xff5d62),
        SURIMI_ORANGE = crate::color::Color::hex(0xffa066),
        KATANA_GRAY = crate::color::Color::hex(0x717c7c),
        DRAGON_BLACK_0 = crate::color::Color::hex(0x0d0c0c),
        DRAGON_BLACK_1 = crate::color::Color::hex(0x12120f),
        DRAGON_BLACK_2 = crate::color::Color::hex(0x1d1c19),
        DRAGON_BLACK_3 = crate::color::Color::hex(0x181616),
        DRAGON_BLACK_4 = crate::color::Color::hex(0x282727),
        DRAGON_BLACK_5 = crate::color::Color::hex(0x393836),
        DRAGON_BLACK_6 = crate::color::Color::hex(0x625e5a),
        DRAGON_WHITE = crate::color::Color::hex(0xc5c9c5),
        DRAGON_GREEN = crate::color::Color::hex(0x87a987),
        DRAGON_GREEN_2 = crate::color::Color::hex(0x8a9a7b),
        DRAGON_PINK = crate::color::Color::hex(0xa292a3),
        DRAGON_ORANGE = crate::color::Color::hex(0xb6927b),
        DRAGON_ORANGE_2 = crate::color::Color::hex(0xb98d7b),
        DRAGON_GRAY = crate::color::Color::hex(0xa6a69c),
        DRAGON_GRAY_2 = crate::color::Color::hex(0x9e9b93),
        DRAGON_GRAY_3 = crate::color::Color::hex(0x7a8382),
        DRAGON_BLUE_2 = crate::color::Color::hex(0x8ba4b0),
        DRAGON_VIOLET = crate::color::Color::hex(0x8992a7),
        DRAGON_RED = crate::color::Color::hex(0xc4746e),
        DRAGON_AQUA = crate::color::Color::hex(0x8ea4a2),
        DRAGON_ASH = crate::color::Color::hex(0x737c73),
        DRAGON_TEAL = crate::color::Color::hex(0x949fb5),
        DRAGON_YELLOW = crate::color::Color::hex(0xc4b28a),
        LOTUS_INK_1 = crate::color::Color::hex(0x545464),
        LOTUS_INK_2 = crate::color::Color::hex(0x43436c),
        LOTUS_GRAY = crate::color::Color::hex(0xdcd7ba),
        LOTUS_GRAY_2 = crate::color::Color::hex(0x716e61),
        LOTUS_GRAY_3 = crate::color::Color::hex(0x8a8980),
        LOTUS_WHITE_0 = crate::color::Color::hex(0xd5cea3),
        LOTUS_WHITE_1 = crate::color::Color::hex(0xdcd5ac),
        LOTUS_WHITE_2 = crate::color::Color::hex(0xe5ddb0),
        LOTUS_WHITE_3 = crate::color::Color::hex(0xf2ecbc),
        LOTUS_WHITE_4 = crate::color::Color::hex(0xe7dba0),
        LOTUS_WHITE_5 = crate::color::Color::hex(0xe4d794),
        LOTUS_VIOLET_1 = crate::color::Color::hex(0xa09cac),
        LOTUS_VIOLET_2 = crate::color::Color::hex(0x766b90),
        LOTUS_VIOLET_3 = crate::color::Color::hex(0xc9cbd1),
        LOTUS_VIOLET_4 = crate::color::Color::hex(0x624c83),
        LOTUS_BLUE_1 = crate::color::Color::hex(0xc7d7e0),
        LOTUS_BLUE_2 = crate::color::Color::hex(0xb5cbd2),
        LOTUS_BLUE_3 = crate::color::Color::hex(0x9fb5c9),
        LOTUS_BLUE_4 = crate::color::Color::hex(0x4d699b),
        LOTUS_BLUE_5 = crate::color::Color::hex(0x5d57a3),
        LOTUS_GREEN = crate::color::Color::hex(0x6f894e),
        LOTUS_GREEN_2 = crate::color::Color::hex(0x6e915f),
        LOTUS_GREEN_3 = crate::color::Color::hex(0xb7d0ae),
        LOTUS_PINK = crate::color::Color::hex(0xb35b79),
        LOTUS_ORANGE = crate::color::Color::hex(0xcc6d00),
        LOTUS_ORANGE_2 = crate::color::Color::hex(0xe98a00),
        LOTUS_YELLOW = crate::color::Color::hex(0x77713f),
        LOTUS_YELLOW_2 = crate::color::Color::hex(0x836f4a),
        LOTUS_YELLOW_3 = crate::color::Color::hex(0xde9800),
        LOTUS_YELLOW_4 = crate::color::Color::hex(0xf9d791),
        LOTUS_RED = crate::color::Color::hex(0xc84053),
        LOTUS_RED_2 = crate::color::Color::hex(0xd7474b),
        LOTUS_RED_3 = crate::color::Color::hex(0xe82424),
        LOTUS_RED_4 = crate::color::Color::hex(0xd9a594),
        LOTUS_AQUA = crate::color::Color::hex(0x597b75),
        LOTUS_AQUA_2 = crate::color::Color::hex(0x5e857a),
        LOTUS_TEAL_1 = crate::color::Color::hex(0x4e8ca2),
        LOTUS_TEAL_2 = crate::color::Color::hex(0x6693bf),
        LOTUS_TEAL_3 = crate::color::Color::hex(0x5a7785),
        LOTUS_CYAN = crate::color::Color::hex(0xd7e3d8),
    }
    accents {
        LotusBlue4 = LOTUS_BLUE_4 => ("lotus_blue_4", "Lotus Blue 4"),
        LotusViolet4 = LOTUS_VIOLET_4 => ("lotus_violet_4", "Lotus Violet 4"),
        LotusGreen = LOTUS_GREEN => ("lotus_green", "Lotus Green"),
        LotusYellow = LOTUS_YELLOW => ("lotus_yellow", "Lotus Yellow"),
        LotusPink = LOTUS_PINK => ("lotus_pink", "Lotus Pink"),
        LotusRed = LOTUS_RED => ("lotus_red", "Lotus Red"),
        LotusOrange = LOTUS_ORANGE => ("lotus_orange", "Lotus Orange"),
        LotusAqua = LOTUS_AQUA => ("lotus_aqua", "Lotus Aqua"),
    }
    default LOTUS_BLUE_4 => "lotus_blue_4";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::LOTUS_WHITE_3,
            surface: Self::LOTUS_WHITE_4,
            raised: Self::LOTUS_WHITE_5,
            overlay: Self::LOTUS_WHITE_0,
            hover: Self::LOTUS_WHITE_5,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::LOTUS_WHITE_0,
            surface: Self::LOTUS_WHITE_1,
            raised: Self::LOTUS_WHITE_2,
            overlay: Self::LOTUS_WHITE_0,
            hover: Self::LOTUS_WHITE_4,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::LOTUS_INK_1,
            muted: Self::LOTUS_INK_2,
            subtle: Self::LOTUS_GRAY_3,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::LOTUS_VIOLET_4),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::LOTUS_WHITE_5,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::LOTUS_VIOLET_4,
            hover: crate::palette::primary_hover(Self::LOTUS_VIOLET_4),
            pressed: crate::palette::action_pressed(Self::LOTUS_VIOLET_4),
            muted: Self::LOTUS_WHITE_4,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::LOTUS_GREEN,
            warning: Self::LOTUS_ORANGE_2,
            error: Self::LOTUS_RED_3,
            critical: Self::LOTUS_RED_3,
            info: Self::LOTUS_TEAL_3,
            trace: Self::LOTUS_GRAY_2,
        },
        border: Self::LOTUS_GRAY_2,
        border_muted: Self::LOTUS_WHITE_5,
        focus: primary,
    }
}
