use ferriswatch::color::Color;
use ferriswatch::css::{DEFAULT_CSS, theme_css};
use ferriswatch::theme::Appearance;
use ferriswatch::theme_variant::{
    ActionColors, StatusColors, SurfaceColors, TextColors, ThemeVariant, ThemeVariantColors,
};
use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn css_lines() -> Vec<&'static str> {
    DEFAULT_CSS
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect()
}

#[test]
fn default_css_has_exact_public_rules_and_declaration_allowlist() {
    let expected = [
        ".fs-bg-background, :where(.fs-page) { background-color: var(--fs-background); }",
        ".fs-bg-surface, :where(.fs-panel, .fs-card) { background-color: var(--fs-surface); }",
        ".fs-bg-raised, :where(.fs-popover) { background-color: var(--fs-raised); }",
        ".fs-bg-overlay { background-color: var(--fs-overlay); }",
        ".fs-bg-hover { background-color: var(--fs-hover); }",
        ".fs-bg-alt-background { background-color: var(--fs-alt-background); }",
        ".fs-bg-alt-surface { background-color: var(--fs-alt-surface); }",
        ".fs-bg-alt-raised { background-color: var(--fs-alt-raised); }",
        ".fs-bg-alt-overlay { background-color: var(--fs-alt-overlay); }",
        ".fs-bg-alt-hover { background-color: var(--fs-alt-hover); }",
        ".fs-text, :where(.fs-page, .fs-panel, .fs-card, .fs-popover) { color: var(--fs-text); }",
        ".fs-text-muted { color: var(--fs-muted); }",
        ".fs-text-subtle { color: var(--fs-subtle); }",
        ".fs-primary { background-color: var(--fs-primary); }",
        ".fs-primary { color: var(--fs-on-primary); }",
        ".fs-primary:hover:not(:disabled, [aria-disabled=\"true\" i]) { background-color: var(--fs-primary-hover); }",
        ".fs-primary:active:not(:disabled, [aria-disabled=\"true\" i]) { background-color: var(--fs-primary-pressed); }",
        ".fs-secondary { background-color: var(--fs-secondary); }",
        ".fs-secondary { color: var(--fs-on-secondary); }",
        ".fs-secondary:hover:not(:disabled, [aria-disabled=\"true\" i]) { background-color: var(--fs-secondary-hover); }",
        ".fs-secondary:active:not(:disabled, [aria-disabled=\"true\" i]) { background-color: var(--fs-secondary-pressed); }",
        ".fs-border, :where(.fs-popover) { border-color: var(--fs-border); }",
        ".fs-border-muted, :where(.fs-card) { border-color: var(--fs-border-muted); }",
        ".fs-success { color: var(--fs-success); }",
        ".fs-warning { color: var(--fs-warning); }",
        ".fs-error { color: var(--fs-error); }",
        ".fs-critical { color: var(--fs-critical); }",
        ".fs-info { color: var(--fs-info); }",
        ".fs-trace { color: var(--fs-trace); }",
        ".fs-focus:focus-visible { outline: 2px solid var(--fs-focus); }",
        ".fs-focus:focus-visible { outline-offset: 2px; }",
    ];
    let mut expected_file = vec![
        "/* Generated by generate-css. Edit src/css/definitions.rs instead. */",
        "@layer ferriswatch {",
    ];
    expected_file.extend(expected);
    expected_file.push("}");
    assert_eq!(css_lines(), expected_file);
    let tracked =
        fs::read(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/css/default.css")).unwrap();
    assert_eq!(tracked, DEFAULT_CSS.as_bytes());
    assert!(DEFAULT_CSS.starts_with("/* Generated by generate-css"));
    assert!(DEFAULT_CSS.contains("@layer ferriswatch {") && DEFAULT_CSS.ends_with("}\n"));
    assert!(!DEFAULT_CSS.contains("!important"));
    for line in &expected {
        let declaration = line.split_once('{').unwrap().1;
        let property = declaration.split(':').next().unwrap().trim();
        assert!(matches!(
            property,
            "background-color" | "color" | "border-color" | "outline" | "outline-offset"
        ));
    }
}

fn rgba(n: u32) -> Color {
    Color::hex_alpha(n)
}

fn custom_theme() -> ThemeVariant {
    let colors = ThemeVariantColors {
        surface: SurfaceColors {
            background: rgba(0x01020304),
            surface: rgba(0x11121314),
            raised: rgba(0x21222324),
            overlay: rgba(0x31323334),
            hover: rgba(0x41424344),
        },
        surface_alt: SurfaceColors {
            background: rgba(0x51525354),
            surface: rgba(0x61626364),
            raised: rgba(0x71727374),
            overlay: rgba(0x81828384),
            hover: rgba(0x91929394),
        },
        text: TextColors {
            normal: rgba(0xa1a2a3a4),
            muted: rgba(0xb1b2b3b4),
            subtle: rgba(0xc1c2c3c4),
            on_primary: rgba(0xd1d2d3d4),
            on_secondary: rgba(0xe1e2e3e4),
        },
        primary: ActionColors {
            normal: rgba(0x02030405),
            hover: rgba(0x12131415),
            pressed: rgba(0x22232425),
            muted: rgba(0x32333435),
        },
        secondary: ActionColors {
            normal: rgba(0x42434445),
            hover: rgba(0x52535455),
            pressed: rgba(0x62636465),
            muted: rgba(0x72737475),
        },
        status: StatusColors {
            success: rgba(0x82838485),
            warning: rgba(0x92939495),
            error: rgba(0xa2a3a4a5),
            critical: rgba(0xb2b3b4b5),
            info: rgba(0xc2c3c4c5),
            trace: rgba(0xd2d3d4d5),
        },
        border: rgba(0xe2e3e4e5),
        border_muted: rgba(0xf2f3f4f5),
        focus: rgba(0x03040506),
    };
    ThemeVariant::new(
        "custom/css_test",
        "CSS test",
        Appearance::Dark,
        colors,
        None,
    )
    .unwrap()
}

#[test]
fn theme_css_exports_all_roles_once_and_preserves_alpha() {
    let theme = custom_theme();
    let exported = theme_css(&theme);
    let declarations: BTreeMap<_, _> = exported
        .split(';')
        .filter_map(|entry| entry.split_once(':'))
        .collect();
    let c = theme.colors();
    let expected = [
        ("background", c.surface.background),
        ("surface", c.surface.surface),
        ("raised", c.surface.raised),
        ("overlay", c.surface.overlay),
        ("hover", c.surface.hover),
        ("alt-background", c.surface_alt.background),
        ("alt-surface", c.surface_alt.surface),
        ("alt-raised", c.surface_alt.raised),
        ("alt-overlay", c.surface_alt.overlay),
        ("alt-hover", c.surface_alt.hover),
        ("text", c.text.normal),
        ("muted", c.text.muted),
        ("subtle", c.text.subtle),
        ("on-primary", c.text.on_primary),
        ("on-secondary", c.text.on_secondary),
        ("primary", c.primary.normal),
        ("primary-hover", c.primary.hover),
        ("primary-pressed", c.primary.pressed),
        ("primary-muted", c.primary.muted),
        ("secondary", c.secondary.normal),
        ("secondary-hover", c.secondary.hover),
        ("secondary-pressed", c.secondary.pressed),
        ("secondary-muted", c.secondary.muted),
        ("border", c.border),
        ("border-muted", c.border_muted),
        ("focus", c.focus),
        ("success", c.status.success),
        ("warning", c.status.warning),
        ("error", c.status.error),
        ("critical", c.status.critical),
        ("info", c.status.info),
        ("trace", c.status.trace),
    ];
    assert_eq!(declarations.len(), 32);
    for (name, color) in expected {
        assert_eq!(
            declarations.get(format!("--fs-{name}").as_str()),
            Some(&color.to_string().as_str())
        );
    }
    assert!(theme_css(&theme).contains(" / 0.016"));
}

fn generator() -> Command {
    Command::new(env!("CARGO_BIN_EXE_generate-css"))
}
fn temp_root() -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "ferriswatch-css-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));
    fs::create_dir_all(root.join("src/css")).unwrap();
    root
}

#[test]
fn generator_check_regeneration_and_determinism() {
    let root = temp_root();
    let path = root.join("src/css/default.css");
    let missing = generator()
        .current_dir(&root)
        .arg("--check")
        .output()
        .unwrap();
    assert!(!missing.status.success());
    assert!(!path.exists());
    assert!(
        generator()
            .current_dir(&root)
            .output()
            .unwrap()
            .status
            .success()
    );
    let first = fs::read(&path).unwrap();
    assert!(
        generator()
            .current_dir(&root)
            .output()
            .unwrap()
            .status
            .success()
    );
    assert_eq!(first, fs::read(&path).unwrap());
    fs::write(&path, b"stale").unwrap();
    let stale = generator()
        .current_dir(&root)
        .arg("--check")
        .output()
        .unwrap();
    assert!(!stale.status.success());
    assert_eq!(fs::read(&path).unwrap(), b"stale");
    assert!(
        generator()
            .current_dir(&root)
            .output()
            .unwrap()
            .status
            .success()
    );
    assert_eq!(first, fs::read(&path).unwrap());
    let _ = fs::remove_dir_all(root);
}

#[test]
fn generator_rejects_invalid_arguments() {
    let root = temp_root();
    let output = generator()
        .current_dir(&root)
        .args(["--check", "extra"])
        .output()
        .unwrap();
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("Usage: generate-css [--check]"));
    let _ = fs::remove_dir_all(root);
}
