//! Catppuccin Macchiato. Pinned palette source is listed in the registration.

define_palette! {
    Macchiato, "Catppuccin Macchiato",
    identity("catppuccin/macchiato", "catppuccin", "Catppuccin", "macchiato", "Macchiato", Dark, None);
    support(Dark);
    sources: super::SOURCE;
    colors {
        ROSEWATER = crate::color::Color::hex(0xf4dbd6),
        FLAMINGO = crate::color::Color::hex(0xf0c6c6),
        PINK = crate::color::Color::hex(0xf5bde6),
        MAUVE = crate::color::Color::hex(0xc6a0f6),
        RED = crate::color::Color::hex(0xed8796),
        MAROON = crate::color::Color::hex(0xee99a0),
        PEACH = crate::color::Color::hex(0xf5a97f),
        YELLOW = crate::color::Color::hex(0xeed49f),
        GREEN = crate::color::Color::hex(0xa6da95),
        TEAL = crate::color::Color::hex(0x8bd5ca),
        SKY = crate::color::Color::hex(0x91d7e3),
        SAPPHIRE = crate::color::Color::hex(0x7dc4e4),
        BLUE = crate::color::Color::hex(0x8aadf4),
        LAVENDER = crate::color::Color::hex(0xb7bdf8),
        TEXT = crate::color::Color::hex(0xcad3f5),
        SUBTEXT_1 = crate::color::Color::hex(0xb8c0e0),
        SUBTEXT_0 = crate::color::Color::hex(0xa5adcb),
        OVERLAY_2 = crate::color::Color::hex(0x939ab7),
        OVERLAY_1 = crate::color::Color::hex(0x8087a2),
        OVERLAY_0 = crate::color::Color::hex(0x6e738d),
        SURFACE_2 = crate::color::Color::hex(0x5b6078),
        SURFACE_1 = crate::color::Color::hex(0x494d64),
        SURFACE_0 = crate::color::Color::hex(0x363a4f),
        BASE = crate::color::Color::hex(0x24273a),
        MANTLE = crate::color::Color::hex(0x1e2030),
        CRUST = crate::color::Color::hex(0x181926),
    }
    accents {
        Rosewater = ROSEWATER => ("rosewater", "Rosewater"),
        Flamingo = FLAMINGO => ("flamingo", "Flamingo"),
        Pink = PINK => ("pink", "Pink"),
        Mauve = MAUVE => ("mauve", "Mauve"),
        Red = RED => ("red", "Red"),
        Maroon = MAROON => ("maroon", "Maroon"),
        Peach = PEACH => ("peach", "Peach"),
        Yellow = YELLOW => ("yellow", "Yellow"),
        Green = GREEN => ("green", "Green"),
        Teal = TEAL => ("teal", "Teal"),
        Sky = SKY => ("sky", "Sky"),
        Sapphire = SAPPHIRE => ("sapphire", "Sapphire"),
        Blue = BLUE => ("blue", "Blue"),
        Lavender = LAVENDER => ("lavender", "Lavender"),
    }
    default MAUVE => "mauve";
    roles(primary) {
        surfaces: crate::theme_variant::SurfaceColors {
            background: Self::BASE,
            base: Self::SURFACE_0,
            raised: Self::SURFACE_2,
            overlay: Self::OVERLAY_0,
            hover: Self::SURFACE_1,
        },
        surfaces_alt: crate::theme_variant::SurfaceColors {
            background: Self::CRUST,
            base: Self::MANTLE,
            raised: Self::SURFACE_0,
            overlay: Self::BASE,
            hover: Self::SURFACE_1,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::TEXT,
            muted: Self::SUBTEXT_1,
            subtle: Self::OVERLAY_1,
        },
        text_alt: None,
        primary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), primary),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::primary_hover(primary)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::action_pressed(primary)),
            muted: crate::theme_variant::ColorPair::new(Self::TEXT, Self::SURFACE_2),
            disabled: crate::theme_variant::ColorPair::new(Self::OVERLAY_1, Self::SURFACE_2),
        },
        secondary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::BLUE), Self::BLUE),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::BLUE), crate::palette::primary_hover(Self::BLUE)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::BLUE), crate::palette::action_pressed(Self::BLUE)),
            muted: crate::theme_variant::ColorPair::new(Self::TEXT, Self::SURFACE_0),
            disabled: crate::theme_variant::ColorPair::new(Self::OVERLAY_1, Self::SURFACE_0),
        },
        status: crate::theme_variant::StatusColors {
            success: Self::GREEN,
            warning: Self::YELLOW,
            error: Self::RED,
            critical: Self::RED,
            info: Self::TEAL,
            debug: Self::SUBTEXT_1,
            trace: Self::SUBTEXT_0,
        },
        border: Self::OVERLAY_0,
        border_muted: Self::SURFACE_1,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::RED,
            orange: Self::PEACH,
            yellow: Self::YELLOW,
            green: Self::GREEN,
            cyan: Self::SKY,
            blue: Self::BLUE,
            purple: Self::MAUVE,
            pink: Self::PINK,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::YELLOW,
            boolean: Self::PEACH,
            builtin: Self::YELLOW,
            builtin_function: Self::BLUE,
            builtin_type: Self::YELLOW,
            comment: Self::OVERLAY_2,
            constant: Self::PEACH,
            control_keyword: Self::MAUVE,
            deleted: Self::RED,
            deprecated: Self::RED,
            documentation: Self::OVERLAY_2,
            escape: Self::PINK,
            foreground: Self::TEXT,
            function: Self::BLUE,
            heading: Self::BLUE,
            inserted: Self::GREEN,
            invalid: Self::RED,
            keyword: Self::MAUVE,
            link: Self::BLUE,
            macro_name: Self::BLUE,
            markup_bold: Self::TEXT,
            markup_italic: Self::TEXT,
            modifier: Self::MAUVE,
            namespace: Self::YELLOW,
            number: Self::PEACH,
            operator: Self::SKY,
            parameter: Self::MAROON,
            property: Self::BLUE,
            punctuation: Self::OVERLAY_2,
            string: Self::GREEN,
            tag: Self::BLUE,
            type_keyword: Self::MAUVE,
            type_name: Self::YELLOW,
            variable: Self::TEXT,
        },
    }
}
