[package]
name = "ferriswatch-componant"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Dioxus widgets for Ferriswatch that wrap dioxus-primitives"
readme = "README.md"
repository = "https://onedev.hankin.io/rust/ferriswatch"
publish = ["onedev"]
keywords = ["theme", "dioxus", "components", "combobox"]
categories = ["gui"]

[dependencies]
dioxus.workspace = true
dioxus-icons.workspace = true
dioxus-primitives.workspace = true
ferriswatch = { path = "..", version = "0.3.0", features = ["dioxus"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys.workspace = true
