[package]
name = "ferriswatch-componant"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
readme = "README.md"
repository.workspace = true
publish = ["onedev"]
keywords.workspace = true
categories.workspace = true

[dependencies]
dioxus.workspace = true
dioxus-icons.workspace = true
dioxus-primitives.workspace = true
ferriswatch = { workspace = true, features = ["dioxus"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys.workspace = true
