//! Material Oceanic. See `REGISTRATION` for pinned upstream sources.
//!
//! Default style branch with high_visibility disabled. Upstream editor active/highlight/selection colours supply placement and hover. Oceanic is the named Material style, independent of Oceanic Next.

define_palette! {
    Oceanic, "Material Oceanic",
    identity("material/oceanic", "material", "Material", "oceanic", "Oceanic", Dark, None);
    support(Dark);
    sources: super::SOURCE_OCEANIC;
    colors {
        MAIN_WHITE = crate::color::Color::hex(0xeeffff),
        MAIN_GRAY = crate::color::Color::hex(0x717cb4),
        MAIN_BLACK = crate::color::Color::hex(0x000000),
        MAIN_RED = crate::color::Color::hex(0xf07178),
        MAIN_GREEN = crate::color::Color::hex(0xc3e88d),
        MAIN_YELLOW = crate::color::Color::hex(0xffcb6b),
        MAIN_BLUE = crate::color::Color::hex(0x82aaff),
        MAIN_PALEBLUE = crate::color::Color::hex(0xb0c9ff),
        MAIN_CYAN = crate::color::Color::hex(0x89ddff),
        MAIN_PURPLE = crate::color::Color::hex(0xc792ea),
        MAIN_ORANGE = crate::color::Color::hex(0xf78c6c),
        MAIN_DARKRED = crate::color::Color::hex(0xdc6068),
        MAIN_DARKGREEN = crate::color::Color::hex(0xabcf76),
        MAIN_DARKYELLOW = crate::color::Color::hex(0xe6b455),
        MAIN_DARKBLUE = crate::color::Color::hex(0x6e98eb),
        MAIN_DARKCYAN = crate::color::Color::hex(0x71c6e7),
        MAIN_DARKPURPLE = crate::color::Color::hex(0xb480d6),
        MAIN_DARKORANGE = crate::color::Color::hex(0xe2795b),
        EDITOR_BG = crate::color::Color::hex(0x25363b),
        EDITOR_BG_ALT = crate::color::Color::hex(0x1c2c30),
        EDITOR_FG = crate::color::Color::hex(0xb0bec5),
        EDITOR_FG_DARK = crate::color::Color::hex(0x7c9ead),
        EDITOR_SELECTION = crate::color::Color::hex(0x395b65),
        EDITOR_BORDER = crate::color::Color::hex(0x355058),
        EDITOR_LINE_NUMBERS = crate::color::Color::hex(0x426367),
        EDITOR_HIGHLIGHT = crate::color::Color::hex(0x354a51),
        EDITOR_DISABLED = crate::color::Color::hex(0x3e5f64),
        EDITOR_ACCENT = crate::color::Color::hex(0x11bba3),
        EDITOR_CONTRAST = crate::color::Color::hex(0x1e272c),
        EDITOR_ACTIVE = crate::color::Color::hex(0x314549),
        SYNTAX_COMMENTS = crate::color::Color::hex(0x546e7a),
        LSP_ERROR = crate::color::Color::hex(0xff5370),
    }
    accents {
        Red = MAIN_RED => ("red", "Red"),
        Green = MAIN_GREEN => ("green", "Green"),
        Yellow = MAIN_YELLOW => ("yellow", "Yellow"),
        Blue = MAIN_BLUE => ("blue", "Blue"),
        Cyan = MAIN_CYAN => ("cyan", "Cyan"),
        Purple = MAIN_PURPLE => ("purple", "Purple"),
        Orange = MAIN_ORANGE => ("orange", "Orange"),
        Accent = EDITOR_ACCENT => ("accent", "Accent"),
    }
    default EDITOR_ACCENT => "accent";
    roles(primary) {
        surfaces: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BG,
            base: Self::EDITOR_ACTIVE,
            raised: Self::EDITOR_HIGHLIGHT,
            overlay: Self::EDITOR_BG,
            hover: Self::EDITOR_SELECTION,
        },
        surfaces_alt: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BG_ALT,
            base: Self::EDITOR_BG,
            raised: Self::EDITOR_ACTIVE,
            overlay: Self::EDITOR_BG,
            hover: Self::EDITOR_SELECTION,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::EDITOR_FG,
            muted: Self::EDITOR_FG_DARK,
            subtle: Self::SYNTAX_COMMENTS,
        },
        text_alt: None,
        primary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), primary),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::primary_hover(primary)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::action_pressed(primary)),
            muted: crate::theme_variant::ColorPair::new(Self::EDITOR_FG, Self::EDITOR_ACTIVE),
            disabled: crate::theme_variant::ColorPair::new(Self::SYNTAX_COMMENTS, Self::EDITOR_ACTIVE),
        },
        secondary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::MAIN_PURPLE), Self::MAIN_PURPLE),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::MAIN_PURPLE), crate::palette::primary_hover(Self::MAIN_PURPLE)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::MAIN_PURPLE), crate::palette::action_pressed(Self::MAIN_PURPLE)),
            muted: crate::theme_variant::ColorPair::new(Self::EDITOR_FG, Self::EDITOR_ACTIVE),
            disabled: crate::theme_variant::ColorPair::new(Self::SYNTAX_COMMENTS, Self::EDITOR_ACTIVE),
        },
        status: crate::theme_variant::StatusColors {
            success: Self::MAIN_GREEN,
            warning: Self::MAIN_YELLOW,
            error: Self::LSP_ERROR,
            critical: Self::MAIN_RED,
            info: Self::MAIN_PALEBLUE,
            debug: Self::EDITOR_FG_DARK,
            trace: Self::SYNTAX_COMMENTS,
        },
        border: Self::EDITOR_BORDER,
        border_muted: Self::EDITOR_ACTIVE,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::MAIN_RED,
            orange: Self::MAIN_ORANGE,
            yellow: Self::MAIN_YELLOW,
            green: Self::MAIN_GREEN,
            cyan: Self::MAIN_CYAN,
            blue: Self::MAIN_BLUE,
            purple: Self::MAIN_PURPLE,
            pink: Self::MAIN_RED,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::MAIN_PURPLE,
            boolean: Self::MAIN_ORANGE,
            builtin: Self::MAIN_PURPLE,
            builtin_function: Self::MAIN_BLUE,
            builtin_type: Self::MAIN_PURPLE,
            comment: Self::SYNTAX_COMMENTS,
            constant: Self::MAIN_ORANGE,
            control_keyword: Self::MAIN_PURPLE,
            deleted: Self::LSP_ERROR,
            deprecated: Self::LSP_ERROR,
            documentation: Self::SYNTAX_COMMENTS,
            escape: Self::MAIN_CYAN,
            foreground: Self::EDITOR_FG,
            function: Self::MAIN_BLUE,
            heading: Self::MAIN_BLUE,
            inserted: Self::MAIN_GREEN,
            invalid: Self::LSP_ERROR,
            keyword: Self::MAIN_PURPLE,
            link: Self::MAIN_BLUE,
            macro_name: Self::MAIN_BLUE,
            markup_bold: Self::EDITOR_FG,
            markup_italic: Self::EDITOR_FG,
            modifier: Self::MAIN_PURPLE,
            namespace: Self::MAIN_PURPLE,
            number: Self::MAIN_ORANGE,
            operator: Self::MAIN_CYAN,
            parameter: Self::MAIN_PALEBLUE,
            property: Self::EDITOR_FG,
            punctuation: Self::EDITOR_FG,
            string: Self::MAIN_GREEN,
            tag: Self::MAIN_PURPLE,
            type_keyword: Self::MAIN_PURPLE,
            type_name: Self::MAIN_PURPLE,
            variable: Self::EDITOR_FG,
        },
    }
}
