//! Synthwave '84. See `REGISTRATION` for pinned upstream sources.
//!
//! Editor UI keys supply surfaces and source alpha is retained. Terminal accents supply filled actions. Critical uses bright red; trace uses subdued source text. Roles that share an upstream colour intentionally repeat.

define_palette! {
    Main, "Synthwave '84",
    identity("synthwave_84/main", "synthwave_84", "Synthwave '84", "main", "Main", Dark, None);
    sources: super::SOURCE;
    colors {
        FOCUS_BORDER = crate::color::Color::hex(0x1f212b),
        FOREGROUND = crate::color::Color::hex(0xffffff),
        WIDGET_SHADOW = crate::color::Color::hex(0x2a2139),
        SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0xffffff20),
        ERROR_FOREGROUND = crate::color::Color::hex(0xfe4450),
        TEXT_LINK_ACTIVE_FOREGROUND = crate::color::Color::hex(0xff7edb),
        TEXT_LINK_FOREGROUND = crate::color::Color::hex(0xf97e72),
        BUTTON_BACKGROUND = crate::color::Color::hex(0x614d85),
        DROPDOWN_BACKGROUND = crate::color::Color::hex(0x232530),
        DROPDOWN_LIST_BACKGROUND = crate::color::Color::hex(0x2a2139),
        INPUT_BACKGROUND = crate::color::Color::hex(0x2a2139),
        INPUT_OPTION_ACTIVE_BORDER = crate::color::Color::hex_alpha(0xff7edb99),
        INPUT_VALIDATION_ERROR_BACKGROUND = crate::color::Color::hex_alpha(0xfe445080),
        INPUT_VALIDATION_ERROR_BORDER = crate::color::Color::hex_alpha(0xfe445000),
        SCROLLBAR_SHADOW = crate::color::Color::hex(0x2a2139),
        SCROLLBAR_SLIDER_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0x9d8bca20),
        SCROLLBAR_SLIDER_BACKGROUND = crate::color::Color::hex_alpha(0x9d8bca30),
        SCROLLBAR_SLIDER_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x9d8bca50),
        BADGE_FOREGROUND = crate::color::Color::hex(0xffffff),
        BADGE_BACKGROUND = crate::color::Color::hex(0x2a2139),
        PROGRESS_BAR_BACKGROUND = crate::color::Color::hex(0xf97e72),
        LIST_ACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0xffffff20),
        LIST_ACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x34294f66),
        LIST_FOCUS_BACKGROUND = crate::color::Color::hex_alpha(0xffffff20),
        LIST_FOCUS_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xf97e72),
        LIST_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x37294d99),
        LIST_HOVER_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0xffffff20),
        LIST_INACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_INACTIVE_FOCUS_BACKGROUND = crate::color::Color::hex_alpha(0x2a213999),
        LIST_ERROR_FOREGROUND = crate::color::Color::hex_alpha(0xfe4450e6),
        LIST_WARNING_FOREGROUND = crate::color::Color::hex_alpha(0x72f1b8bb),
        ACTIVITY_BAR_BACKGROUND = crate::color::Color::hex(0x171520),
        ACTIVITY_BAR_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x34294f66),
        ACTIVITY_BAR_FOREGROUND = crate::color::Color::hex_alpha(0xffffffcc),
        ACTIVITY_BAR_BADGE_BACKGROUND = crate::color::Color::hex(0xf97e72),
        ACTIVITY_BAR_BADGE_FOREGROUND = crate::color::Color::hex(0x2a2139),
        SIDE_BAR_BACKGROUND = crate::color::Color::hex(0x241b2f),
        SIDE_BAR_FOREGROUND = crate::color::Color::hex_alpha(0xffffff99),
        SIDE_BAR_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x34294f4c),
        SIDE_BAR_SECTION_HEADER_BACKGROUND = crate::color::Color::hex(0x241b2f),
        SIDE_BAR_SECTION_HEADER_FOREGROUND = crate::color::Color::hex_alpha(0xffffffca),
        MENU_BACKGROUND = crate::color::Color::hex(0x463465),
        EDITOR_GROUP_BORDER = crate::color::Color::hex(0x495495),
        EDITOR_GROUP_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x4954954a),
        EDITOR_GROUP_HEADER_TABS_BACKGROUND = crate::color::Color::hex(0x241b2f),
        TAB_BORDER = crate::color::Color::hex_alpha(0x241b2f00),
        TAB_ACTIVE_BORDER = crate::color::Color::hex(0x880088),
        TAB_INACTIVE_BACKGROUND = crate::color::Color::hex(0x262335),
        EDITOR_BACKGROUND = crate::color::Color::hex(0x262335),
        EDITOR_LINE_NUMBER_FOREGROUND = crate::color::Color::hex_alpha(0xffffff73),
        EDITOR_LINE_NUMBER_ACTIVE_FOREGROUND = crate::color::Color::hex_alpha(0xffffffcc),
        EDITOR_CURSOR_BACKGROUND = crate::color::Color::hex(0x241b2f),
        EDITOR_CURSOR_FOREGROUND = crate::color::Color::hex(0xf97e72),
        EDITOR_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0xffffff20),
        EDITOR_SELECTION_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xffffff20),
        EDITOR_WORD_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x34294f88),
        EDITOR_WORD_HIGHLIGHT_STRONG_BACKGROUND = crate::color::Color::hex_alpha(0x34294f88),
        EDITOR_FIND_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0xd18616bb),
        EDITOR_FIND_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xd1861655),
        EDITOR_FIND_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x34294f1a),
        EDITOR_HOVER_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x463564),
        EDITOR_LINE_HIGHLIGHT_BORDER = crate::color::Color::hex_alpha(0x7059ab66),
        EDITOR_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x49549539),
        EDITOR_INDENT_GUIDE_BACKGROUND = crate::color::Color::hex(0x444251),
        EDITOR_INDENT_GUIDE_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0xa148ab80),
        EDITOR_RULER_FOREGROUND = crate::color::Color::hex_alpha(0xa148ab80),
        EDITOR_CODE_LENS_FOREGROUND = crate::color::Color::hex_alpha(0xffffff7c),
        EDITOR_BRACKET_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0x34294f66),
        EDITOR_BRACKET_MATCH_BORDER = crate::color::Color::hex(0x495495),
        EDITOR_OVERVIEW_RULER_BORDER = crate::color::Color::hex_alpha(0x34294fb3),
        EDITOR_OVERVIEW_RULER_FIND_MATCH_FOREGROUND = crate::color::Color::hex_alpha(0xd1861699),
        EDITOR_OVERVIEW_RULER_MODIFIED_FOREGROUND = crate::color::Color::hex_alpha(0xb893ce99),
        EDITOR_OVERVIEW_RULER_ADDED_FOREGROUND = crate::color::Color::hex_alpha(0x09f7a099),
        EDITOR_OVERVIEW_RULER_DELETED_FOREGROUND = crate::color::Color::hex_alpha(0xfe445099),
        EDITOR_OVERVIEW_RULER_ERROR_FOREGROUND = crate::color::Color::hex_alpha(0xfe4450dd),
        EDITOR_OVERVIEW_RULER_WARNING_FOREGROUND = crate::color::Color::hex_alpha(0x72f1b8cc),
        EDITOR_ERROR_FOREGROUND = crate::color::Color::hex(0xfe4450),
        EDITOR_WARNING_FOREGROUND = crate::color::Color::hex_alpha(0x72f1b8cc),
        EDITOR_GUTTER_MODIFIED_BACKGROUND = crate::color::Color::hex_alpha(0xb893ce8f),
        EDITOR_GUTTER_ADDED_BACKGROUND = crate::color::Color::hex_alpha(0x206d4bd6),
        EDITOR_GUTTER_DELETED_BACKGROUND = crate::color::Color::hex_alpha(0xfa2e46a4),
        DIFF_EDITOR_INSERTED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0x0beb9935),
        DIFF_EDITOR_REMOVED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0xfe445035),
        EDITOR_WIDGET_BACKGROUND = crate::color::Color::hex_alpha(0x171520dc),
        EDITOR_WIDGET_BORDER = crate::color::Color::hex_alpha(0xffffff22),
        EDITOR_WIDGET_RESIZE_BORDER = crate::color::Color::hex_alpha(0xffffff44),
        EDITOR_SUGGEST_WIDGET_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xf97e72),
        EDITOR_SUGGEST_WIDGET_SELECTED_BACKGROUND = crate::color::Color::hex_alpha(0xffffff36),
        PEEK_VIEW_BORDER = crate::color::Color::hex(0x495495),
        PEEK_VIEW_EDITOR_BACKGROUND = crate::color::Color::hex(0x232530),
        PEEK_VIEW_EDITOR_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xd18616bb),
        PEEK_VIEW_RESULT_BACKGROUND = crate::color::Color::hex(0x232530),
        PEEK_VIEW_RESULT_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xd1861655),
        PEEK_VIEW_RESULT_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x2a213980),
        PEEK_VIEW_TITLE_BACKGROUND = crate::color::Color::hex(0x232530),
        PANEL_TITLE_ACTIVE_BORDER = crate::color::Color::hex(0xf97e72),
        STATUS_BAR_BACKGROUND = crate::color::Color::hex(0x241b2f),
        STATUS_BAR_FOREGROUND = crate::color::Color::hex_alpha(0xffffff80),
        STATUS_BAR_DEBUGGING_BACKGROUND = crate::color::Color::hex(0xf97e72),
        STATUS_BAR_DEBUGGING_FOREGROUND = crate::color::Color::hex(0x08080f),
        STATUS_BAR_NO_FOLDER_BACKGROUND = crate::color::Color::hex(0x241b2f),
        STATUS_BAR_ITEM_PROMINENT_BACKGROUND = crate::color::Color::hex(0x2a2139),
        STATUS_BAR_ITEM_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0x34294f),
        TITLE_BAR_ACTIVE_BACKGROUND = crate::color::Color::hex(0x241b2f),
        TITLE_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x241b2f),
        EXTENSION_BUTTON_PROMINENT_BACKGROUND = crate::color::Color::hex(0xf97e72),
        EXTENSION_BUTTON_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0xff7edb),
        PICKER_GROUP_FOREGROUND = crate::color::Color::hex_alpha(0xf97e72ea),
        TERMINAL_FOREGROUND = crate::color::Color::hex(0xffffff),
        TERMINAL_ANSI_BLUE = crate::color::Color::hex(0x03edf9),
        TERMINAL_ANSI_BRIGHT_BLUE = crate::color::Color::hex(0x03edf9),
        TERMINAL_ANSI_BRIGHT_CYAN = crate::color::Color::hex(0x03edf9),
        TERMINAL_ANSI_BRIGHT_GREEN = crate::color::Color::hex(0x72f1b8),
        TERMINAL_ANSI_BRIGHT_MAGENTA = crate::color::Color::hex(0xff7edb),
        TERMINAL_ANSI_BRIGHT_RED = crate::color::Color::hex(0xfe4450),
        TERMINAL_ANSI_BRIGHT_YELLOW = crate::color::Color::hex(0xfede5d),
        TERMINAL_ANSI_CYAN = crate::color::Color::hex(0x03edf9),
        TERMINAL_ANSI_GREEN = crate::color::Color::hex(0x72f1b8),
        TERMINAL_ANSI_MAGENTA = crate::color::Color::hex(0xff7edb),
        TERMINAL_ANSI_RED = crate::color::Color::hex(0xfe4450),
        TERMINAL_ANSI_YELLOW = crate::color::Color::hex(0xf3e70f),
        TERMINAL_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0xffffff20),
        TERMINAL_CURSOR_BACKGROUND = crate::color::Color::hex(0xffffff),
        TERMINAL_CURSOR_FOREGROUND = crate::color::Color::hex(0x03edf9),
        DEBUG_TOOL_BAR_BACKGROUND = crate::color::Color::hex(0x463465),
        WALK_THROUGH_EMBEDDED_EDITOR_BACKGROUND = crate::color::Color::hex(0x232530),
        GIT_DECORATION_MODIFIED_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0xb893ceee),
        GIT_DECORATION_DELETED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xfe4450),
        GIT_DECORATION_ADDED_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0x72f1b8cc),
        GIT_DECORATION_UNTRACKED_RESOURCE_FOREGROUND = crate::color::Color::hex(0x72f1b8),
        GIT_DECORATION_IGNORED_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0xffffff59),
        MINIMAP_GUTTER_ADDED_BACKGROUND = crate::color::Color::hex_alpha(0x09f7a099),
        MINIMAP_GUTTER_MODIFIED_BACKGROUND = crate::color::Color::hex(0xb893ce),
        MINIMAP_GUTTER_DELETED_BACKGROUND = crate::color::Color::hex(0xfe4450),
        BREADCRUMB_PICKER_BACKGROUND = crate::color::Color::hex(0x232530),
        TOKEN_COMMENT = crate::color::Color::hex(0x848bbd),
        TOKEN_STRING = crate::color::Color::hex(0xff8b39),
        TOKEN_PUNCTUATION_WITHIN_TEMPLATES = crate::color::Color::hex(0xb6b1b1),
        TOKEN_VARIABLE = crate::color::Color::hex(0xff7edb),
        TOKEN_LANGUAGE_VARIABLE = crate::color::Color::hex(0xfe4450),
        TOKEN_STORAGE_DECLARATION_OR_MODIFIER_KEYWORD = crate::color::Color::hex(0xfede5d),
        TOKEN_CONSTANT = crate::color::Color::hex(0xf97e72),
        TOKEN_REGEX = crate::color::Color::hex(0xf97e72),
        TOKEN_NUMBER = crate::color::Color::hex(0xf97e72),
        TOKEN_LANGUAGE_CONSTANT_BOOLEAN_NULL = crate::color::Color::hex(0xf97e72),
        TOKEN_CHARACTER_ESCAPE = crate::color::Color::hex(0x36f9f6),
        TOKEN_ENTITY = crate::color::Color::hex(0xfe4450),
        TOKEN_HTML_OR_XML_TAG = crate::color::Color::hex(0x72f1b8),
        TOKEN_HTML_OR_XML_TAG_BRACKETS = crate::color::Color::hex(0x36f9f6),
        TOKEN_TAG_ATTRIBUTE = crate::color::Color::hex(0xfede5d),
        TOKEN_TAG_ATTRIBUTE_HTML = crate::color::Color::hex(0xfede5d),
        TOKEN_CLASS = crate::color::Color::hex(0xfe4450),
        TOKEN_INHERITED_CLASS = crate::color::Color::hex(0xdd5500),
        TOKEN_FUNCTION = crate::color::Color::hex(0x36f9f6),
        TOKEN_JS_EXPORT = crate::color::Color::hex(0x72f1b8),
        TOKEN_JS_NUMERICS = crate::color::Color::hex(0x2ee2fa),
        TOKEN_KEYWORD = crate::color::Color::hex(0xfede5d),
        TOKEN_CONTROL_KEYWORD = crate::color::Color::hex(0xfede5d),
        TOKEN_OPERATOR = crate::color::Color::hex(0xfede5d),
        TOKEN_SPECIAL_OPERATOR = crate::color::Color::hex(0xfede5d),
        TOKEN_UNIT = crate::color::Color::hex(0xf97e72),
        TOKEN_SUPPORT = crate::color::Color::hex(0xfe4450),
        TOKEN_SUPPORT_FUNCTION = crate::color::Color::hex(0x36f9f6),
        TOKEN_SUPPORT_VARIABLE = crate::color::Color::hex(0xff7edb),
        TOKEN_OBJECT_LITERAL_KEY_PROPERTY = crate::color::Color::hex(0xff7edb),
        TOKEN_KEY_VALUE_SEPARATOR = crate::color::Color::hex(0xb6b1b1),
        TOKEN_EMBEDDED_PUNCTUATION = crate::color::Color::hex(0xfede5d),
        TOKEN_TEMPLATE_EXPRESSION = crate::color::Color::hex(0x72f1b8),
        TOKEN_CSS_PROPERTY = crate::color::Color::hex(0x72f1b8),
        TOKEN_JS_SWITCH_CONTROL = crate::color::Color::hex(0x72f1b8),
        TOKEN_JS_OBJECT_PATH = crate::color::Color::hex(0x2ee2fa),
        TOKEN_COLOR = crate::color::Color::hex(0xf97e72),
        TOKEN_FONT_NAMES = crate::color::Color::hex(0xf97e72),
        TOKEN_CSS_ID = crate::color::Color::hex(0x36f9f6),
        TOKEN_PSEUDO_CSS = crate::color::Color::hex(0xdd5500),
        TOKEN_CSS_SUPPORT_FUNCTIONS_RGB = crate::color::Color::hex(0xfe4450),
        TOKEN_MARKUP_HEADING = crate::color::Color::hex(0xff7edb),
        TOKEN_MARKUP_TEXT = crate::color::Color::hex_alpha(0xffffffee),
        TOKEN_MARKUP_QUOTE = crate::color::Color::hex_alpha(0xb6b1b1cc),
        TOKEN_MARKUP_LIST = crate::color::Color::hex(0xff7edb),
        TOKEN_MARKUP_LINK = crate::color::Color::hex(0xdd5500),
        TOKEN_MARKUP_LINK_DESCRIPTION = crate::color::Color::hex(0xf97e72),
        TOKEN_PYTHON_FUNCTION_CALL = crate::color::Color::hex(0x36f9f6),
        TOKEN_PYTHON_VARIABLE_PARAMS = crate::color::Color::hex(0x72f1b8),
        TOKEN_C_STORAGE_TYPE = crate::color::Color::hex(0xfe4450),
        TOKEN_C_LOCAL_VARIABLE = crate::color::Color::hex(0xff7edb),
        TOKEN_C_PROPERTIES_AND_FIELDS = crate::color::Color::hex(0xff7edb),
        TOKEN_C_PLACEHOLDER = crate::color::Color::hex(0x72f1b8),
        TOKEN_C_PREPROCESSORS = crate::color::Color::hex(0x72f1b8),
        TOKEN_C_STORAGE_MODIFIER = crate::color::Color::hex(0xfe4450),
        TOKEN_C_OPERATORS = crate::color::Color::hex(0xfede5d),
        TOKEN_C_INCLUDE = crate::color::Color::hex(0x72f1b8),
        TOKEN_C_CONSTANT_MODIFIER = crate::color::Color::hex(0xfe4450),
        TOKEN_ELIXIR_CLASSES = crate::color::Color::hex(0x36f9f6),
        TOKEN_ELIXIR_FUNCTIONS = crate::color::Color::hex(0x72f1b8),
        TOKEN_ELIXIR_CONSTANTS = crate::color::Color::hex(0x36f9f6),
        TOKEN_ELIXIR_STRING_PUNCTUATION = crate::color::Color::hex(0x72f1b8),
        TOKEN_ELIXIR = crate::color::Color::hex(0x72f1b8),
        TOKEN_ELIXIR_BINARY_PUNCTUATION = crate::color::Color::hex(0xff7edb),
        TOKEN_CLOJURE_GLOBALS = crate::color::Color::hex(0x36f9f6),
        TOKEN_CLOJURE_STORAGE = crate::color::Color::hex(0x36f9f6),
        TOKEN_CLOJURE_METADATA = crate::color::Color::hex(0xfe4450),
        TOKEN_CLOJURE_SYMBOLS = crate::color::Color::hex_alpha(0xff7edbff),
        TOKEN_GO_BASIC = crate::color::Color::hex_alpha(0xff7edbff),
        TOKEN_GO_FUNCTION_CALLS = crate::color::Color::hex(0x36f9f6),
        TOKEN_GO_KEYWORDS = crate::color::Color::hex(0xfede5d),
        TOKEN_GO_INTERFACES = crate::color::Color::hex(0x72f1b8),
        TOKEN_GO_CONSTANTS_E_G_NIL_STRING_FORMAT_S_D_ETC = crate::color::Color::hex(0x2ee2fa),
        TOKEN_MARKDOWN_LINKS_AND_IMAGE_PATHS = crate::color::Color::hex(0xfede5d),
        TOKEN_MARKDOWN_HEADINGS = crate::color::Color::hex(0xff7edb),
        TOKEN_MARKDOWN_ITALIC = crate::color::Color::hex(0x2ee2fa),
        TOKEN_MARKDOWN_BOLD = crate::color::Color::hex(0x2ee2fa),
        TOKEN_MARKDOWN_QUOTES = crate::color::Color::hex(0x72f1b8),
        TOKEN_BASIC_SOURCE_COLOURS = crate::color::Color::hex_alpha(0xff7edbff),
        TOKEN_DART_STRINGS = crate::color::Color::hex(0xf97e72),
        TOKEN_DART_VARIABLE_PARAMS = crate::color::Color::hex(0x72f1b8),
        TOKEN_DART_NUMERICS = crate::color::Color::hex(0x2ee2fa),
        TOKEN_SCALA_VARIABLE_PARAMS = crate::color::Color::hex(0x2ee2fa),
        TOKEN_SCALA = crate::color::Color::hex(0x72f1b8),
    }
    accents {
        Red = TERMINAL_ANSI_RED => ("red", "Red"),
        Green = TERMINAL_ANSI_GREEN => ("green", "Green"),
        Yellow = TERMINAL_ANSI_YELLOW => ("yellow", "Yellow"),
        Blue = TERMINAL_ANSI_BLUE => ("blue", "Blue"),
        Magenta = TERMINAL_ANSI_MAGENTA => ("magenta", "Magenta"),
        Cyan = TERMINAL_ANSI_CYAN => ("cyan", "Cyan"),
    }
    default TERMINAL_ANSI_MAGENTA => "magenta";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BACKGROUND,
            surface: Self::SIDE_BAR_BACKGROUND,
            raised: Self::DROPDOWN_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::SIDE_BAR_BACKGROUND,
            surface: Self::EDITOR_BACKGROUND,
            raised: Self::SIDE_BAR_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FOREGROUND,
            muted: Self::FOREGROUND,
            subtle: Self::EDITOR_LINE_NUMBER_FOREGROUND,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::TERMINAL_ANSI_MAGENTA),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::SIDE_BAR_BACKGROUND,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::TERMINAL_ANSI_MAGENTA,
            hover: crate::palette::primary_hover(Self::TERMINAL_ANSI_MAGENTA),
            pressed: crate::palette::action_pressed(Self::TERMINAL_ANSI_MAGENTA),
            muted: Self::SIDE_BAR_BACKGROUND,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::TERMINAL_ANSI_GREEN,
            warning: Self::TERMINAL_ANSI_YELLOW,
            error: Self::EDITOR_ERROR_FOREGROUND,
            critical: Self::TERMINAL_ANSI_BRIGHT_RED,
            info: Self::TERMINAL_ANSI_BLUE,
            trace: Self::EDITOR_LINE_NUMBER_FOREGROUND,
        },
        border: Self::EDITOR_WIDGET_BORDER,
        border_muted: Self::SIDE_BAR_BACKGROUND,
        focus: primary,
    }
}
