//! Everforest Light Hard. See the family module for its upstream source.

define_palette! {
    LightHard, "Everforest Light Hard",
    identity("everforest/light/hard", "everforest", "Everforest", "light", "Light", Light, Some(crate::theme_variant::Contrast::Hard));
    support(Light);
    sources: super::SOURCE;
    colors {
        BG_DIM = crate::color::Color::hex(0xf2efdf),
        BG_0 = crate::color::Color::hex(0xfffbef),
        BG_1 = crate::color::Color::hex(0xf8f5e4),
        BG_2 = crate::color::Color::hex(0xf2efdf),
        BG_3 = crate::color::Color::hex(0xedeada),
        BG_4 = crate::color::Color::hex(0xe8e5d5),
        BG_5 = crate::color::Color::hex(0xbec5b2),
        BG_VISUAL = crate::color::Color::hex(0xf0f2d4),
        BG_RED = crate::color::Color::hex(0xffe7de),
        BG_YELLOW = crate::color::Color::hex(0xfef2d5),
        BG_GREEN = crate::color::Color::hex(0xf3f5d9),
        BG_BLUE = crate::color::Color::hex(0xecf5ed),
        BG_PURPLE = crate::color::Color::hex(0xfceced),
        FG = crate::color::Color::hex(0x5c6a72),
        RED = crate::color::Color::hex(0xf85552),
        ORANGE = crate::color::Color::hex(0xf57d26),
        YELLOW = crate::color::Color::hex(0xdfa000),
        GREEN = crate::color::Color::hex(0x8da101),
        AQUA = crate::color::Color::hex(0x35a77c),
        BLUE = crate::color::Color::hex(0x3a94c5),
        PURPLE = crate::color::Color::hex(0xdf69ba),
        GREY_0 = crate::color::Color::hex(0xa6b0a0),
        GREY_1 = crate::color::Color::hex(0x939f91),
        GREY_2 = crate::color::Color::hex(0x829181),
        STATUSLINE_1 = crate::color::Color::hex(0x93b259),
        STATUSLINE_2 = crate::color::Color::hex(0x708089),
        STATUSLINE_3 = crate::color::Color::hex(0xe66868),
    }
    accents {
        Red = RED => ("red", "Red"),
        Orange = ORANGE => ("orange", "Orange"),
        Yellow = YELLOW => ("yellow", "Yellow"),
        Green = GREEN => ("green", "Green"),
        Aqua = AQUA => ("aqua", "Aqua"),
        Blue = BLUE => ("blue", "Blue"),
        Purple = PURPLE => ("purple", "Purple"),
    }
    default GREEN => "green";
    roles(primary) {
        surfaces: crate::theme_variant::SurfaceColors {
            background: Self::BG_0,
            base: Self::BG_1,
            raised: Self::BG_2,
            overlay: Self::BG_DIM,
            hover: Self::BG_2,
        },
        surfaces_alt: crate::theme_variant::SurfaceColors {
            background: Self::BG_DIM,
            base: Self::BG_0,
            raised: Self::BG_1,
            overlay: Self::BG_DIM,
            hover: Self::BG_2,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FG,
            muted: Self::GREY_2,
            subtle: Self::GREY_0,
        },
        text_alt: None,
        primary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(
                crate::palette::action_text(primary, Self::BG_0, Self::FG),
                primary,
                ),
            hover: crate::theme_variant::ColorPair::new(
                crate::palette::action_text(primary, Self::BG_0, Self::FG),
                crate::palette::primary_hover(primary),
            ),
            pressed: crate::theme_variant::ColorPair::new(
                crate::palette::action_text(primary, Self::BG_0, Self::FG),
                crate::palette::action_pressed(primary),
            ),
            muted: crate::theme_variant::ColorPair::new(Self::FG, Self::BG_2),
            disabled: crate::theme_variant::ColorPair::new(Self::GREY_0, Self::BG_2),
        },
        secondary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(
                crate::palette::action_text(Self::BLUE, Self::BG_0, Self::FG),
                Self::BLUE,
            ),
            hover: crate::theme_variant::ColorPair::new(
                crate::palette::action_text(Self::BLUE, Self::BG_0, Self::FG),
                crate::palette::primary_hover(Self::BLUE),
            ),
            pressed: crate::theme_variant::ColorPair::new(
                crate::palette::action_text(Self::BLUE, Self::BG_0, Self::FG),
                crate::palette::action_pressed(Self::BLUE),
            ),
            muted: crate::theme_variant::ColorPair::new(Self::FG, Self::BG_1),
            disabled: crate::theme_variant::ColorPair::new(Self::GREY_0, Self::BG_1),
        },
        status: crate::theme_variant::StatusColors {
            success: Self::GREEN,
            warning: Self::YELLOW,
            error: Self::RED,
            critical: Self::RED,
            info: Self::BLUE,
            debug: Self::GREY_2,
            trace: Self::FG,
        },
        border: Self::BG_4,
        border_muted: Self::BG_3,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::RED,
            orange: Self::ORANGE,
            yellow: Self::YELLOW,
            green: Self::GREEN,
            cyan: Self::BLUE,
            blue: Self::BLUE,
            purple: Self::PURPLE,
            pink: Self::PURPLE,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::YELLOW,
            boolean: Self::PURPLE,
            builtin: Self::YELLOW,
            builtin_function: Self::BLUE,
            builtin_type: Self::YELLOW,
            comment: Self::GREY_1,
            constant: Self::PURPLE,
            control_keyword: Self::RED,
            deleted: Self::RED,
            deprecated: Self::RED,
            documentation: Self::GREY_1,
            escape: Self::ORANGE,
            foreground: Self::FG,
            function: Self::BLUE,
            heading: Self::BLUE,
            inserted: Self::GREEN,
            invalid: Self::RED,
            keyword: Self::RED,
            link: Self::BLUE,
            macro_name: Self::BLUE,
            markup_bold: Self::FG,
            markup_italic: Self::FG,
            modifier: Self::RED,
            namespace: Self::YELLOW,
            number: Self::PURPLE,
            operator: Self::ORANGE,
            parameter: Self::FG,
            property: Self::FG,
            punctuation: Self::FG,
            string: Self::GREEN,
            tag: Self::RED,
            type_keyword: Self::RED,
            type_name: Self::YELLOW,
            variable: Self::FG,
        },
    }
}
