//! Poimandres. See `REGISTRATION` for pinned upstream sources.
//!
//! Editor UI keys supply surfaces and source alpha is retained. Terminal accents supply filled actions. Critical uses bright red. Trace uses normal foreground because the gutter
//! colour has too little contrast on the canvas. Roles that share an upstream colour intentionally repeat.

define_palette! {
    Main, "Poimandres",
    identity("poimandres/main", "poimandres", "Poimandres", "main", "Main", Dark, None);
    support(Dark);
    sources: super::SOURCE;
    colors {
        ACTIVITY_BAR_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        ACTIVITY_BAR_FOREGROUND = crate::color::Color::hex(0xa6accd),
        ACTIVITY_BAR_BADGE_BACKGROUND = crate::color::Color::hex(0x303340),
        ACTIVITY_BAR_BADGE_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        BADGE_BACKGROUND = crate::color::Color::hex(0x303340),
        BADGE_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        BUTTON_BACKGROUND = crate::color::Color::hex(0x303340),
        DIFF_EDITOR_INSERTED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0x50647715),
        DIFF_EDITOR_REMOVED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0xd0679d20),
        DROPDOWN_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        DROPDOWN_BORDER = crate::color::Color::hex_alpha(0xffffff10),
        EDITOR_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        EDITOR_FIND_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0xadd7ff40),
        EDITOR_FIND_MATCH_BORDER = crate::color::Color::hex(0xadd7ff),
        EDITOR_FIND_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xadd7ff40),
        EDITOR_FOREGROUND = crate::color::Color::hex(0xa6accd),
        EDITOR_LINE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x717cb425),
        EDITOR_LINE_HIGHLIGHT_BORDER = crate::color::Color::hex_alpha(0x00000000),
        EDITOR_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x717cb425),
        EDITOR_SELECTION_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x00000000),
        EDITOR_SELECTION_HIGHLIGHT_BORDER = crate::color::Color::hex_alpha(0xadd7ff80),
        EDITOR_WORD_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xadd7ff20),
        EDITOR_WORD_HIGHLIGHT_STRONG_BACKGROUND = crate::color::Color::hex_alpha(0xadd7ff40),
        EDITOR_BRACKET_MATCH_BORDER = crate::color::Color::hex_alpha(0xe4f0fb40),
        EDITOR_CURSOR_FOREGROUND = crate::color::Color::hex(0xa6accd),
        EDITOR_GROUP_BORDER = crate::color::Color::hex_alpha(0x00000030),
        EDITOR_GROUP_HEADER_TABS_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        EDITOR_HOVER_WIDGET_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        EDITOR_HOVER_WIDGET_BORDER = crate::color::Color::hex_alpha(0xffffff10),
        EDITOR_INDENT_GUIDE_BACKGROUND = crate::color::Color::hex(0x303340),
        EDITOR_LINE_NUMBER_FOREGROUND = crate::color::Color::hex_alpha(0x767c9d50),
        EDITOR_LINK_ACTIVE_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        EDITOR_SUGGEST_WIDGET_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        EDITOR_SUGGEST_WIDGET_BORDER = crate::color::Color::hex_alpha(0xffffff10),
        EDITOR_SUGGEST_WIDGET_FOREGROUND = crate::color::Color::hex(0xa6accd),
        EDITOR_SUGGEST_WIDGET_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0x5de4c7),
        EDITOR_SUGGEST_WIDGET_SELECTED_BACKGROUND = crate::color::Color::hex_alpha(0x00000050),
        EDITOR_WIDGET_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        EDITOR_FIND_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xadd7ff40),
        EDITOR_FOCUSED_STACK_FRAME_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x7abd7a4d),
        EDITOR_FOLD_BACKGROUND = crate::color::Color::hex_alpha(0x717cb40b),
        EDITOR_HOVER_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x264f7840),
        EDITOR_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x717cb425),
        EDITOR_LINKED_EDITING_BACKGROUND = crate::color::Color::hex_alpha(0xd0679d4d),
        EDITOR_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xffffff0b),
        EDITOR_SNIPPET_FINAL_TABSTOP_HIGHLIGHT_BORDER = crate::color::Color::hex(0x525252),
        EDITOR_SNIPPET_TABSTOP_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x7c7c7c4d),
        EDITOR_STACK_FRAME_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xffff0033),
        EDITOR_SYMBOL_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x89ddff60),
        EDITOR_BRACKET_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0x00000000),
        EDITOR_CODE_LENS_FOREGROUND = crate::color::Color::hex(0xa6accd),
        EDITOR_ERROR_FOREGROUND = crate::color::Color::hex(0xd0679d),
        EDITOR_GROUP_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x7390aa80),
        EDITOR_GROUP_HEADER_NO_TABS_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        EDITOR_GUTTER_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        EDITOR_GUTTER_COMMENT_RANGE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        EDITOR_GUTTER_FOLDING_CONTROL_FOREGROUND = crate::color::Color::hex(0xa6accd),
        EDITOR_GUTTER_ADDED_BACKGROUND = crate::color::Color::hex_alpha(0x5fb3a140),
        EDITOR_GUTTER_DELETED_BACKGROUND = crate::color::Color::hex_alpha(0xd0679d40),
        EDITOR_GUTTER_MODIFIED_BACKGROUND = crate::color::Color::hex_alpha(0xadd7ff20),
        EDITOR_HINT_FOREGROUND = crate::color::Color::hex_alpha(0x7390aab3),
        EDITOR_HOVER_WIDGET_FOREGROUND = crate::color::Color::hex(0xa6accd),
        EDITOR_HOVER_WIDGET_STATUS_BAR_BACKGROUND = crate::color::Color::hex(0x202430),
        EDITOR_INDENT_GUIDE_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0xe3e4e229),
        EDITOR_INFO_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        EDITOR_INLINE_HINT_BACKGROUND = crate::color::Color::hex(0xa6accd),
        EDITOR_INLINE_HINT_FOREGROUND = crate::color::Color::hex(0x1b1e28),
        EDITOR_LIGHT_BULB_FOREGROUND = crate::color::Color::hex(0xfffac2),
        EDITOR_LIGHT_BULB_AUTO_FIX_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        EDITOR_LINE_NUMBER_ACTIVE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        EDITOR_MARKER_NAVIGATION_BACKGROUND = crate::color::Color::hex(0x2d2d30),
        EDITOR_MARKER_NAVIGATION_ERROR_BACKGROUND = crate::color::Color::hex(0xd0679d),
        EDITOR_MARKER_NAVIGATION_INFO_BACKGROUND = crate::color::Color::hex(0xadd7ff),
        EDITOR_MARKER_NAVIGATION_WARNING_BACKGROUND = crate::color::Color::hex(0xfffac2),
        EDITOR_OVERVIEW_RULER_ADDED_FOREGROUND = crate::color::Color::hex_alpha(0x5fb3a199),
        EDITOR_OVERVIEW_RULER_BORDER = crate::color::Color::hex_alpha(0x00000000),
        EDITOR_OVERVIEW_RULER_BRACKET_MATCH_FOREGROUND = crate::color::Color::hex(0xa0a0a0),
        EDITOR_OVERVIEW_RULER_COMMON_CONTENT_FOREGROUND = crate::color::Color::hex_alpha(0xa6accd66),
        EDITOR_OVERVIEW_RULER_CURRENT_CONTENT_FOREGROUND = crate::color::Color::hex_alpha(0x5fb3a180),
        EDITOR_OVERVIEW_RULER_DELETED_FOREGROUND = crate::color::Color::hex_alpha(0xd0679d99),
        EDITOR_OVERVIEW_RULER_ERROR_FOREGROUND = crate::color::Color::hex_alpha(0xd0679db3),
        EDITOR_OVERVIEW_RULER_FIND_MATCH_FOREGROUND = crate::color::Color::hex_alpha(0xe4f0fb20),
        EDITOR_OVERVIEW_RULER_INCOMING_CONTENT_FOREGROUND = crate::color::Color::hex_alpha(0x89ddff80),
        EDITOR_OVERVIEW_RULER_INFO_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        EDITOR_OVERVIEW_RULER_MODIFIED_FOREGROUND = crate::color::Color::hex_alpha(0x89ddff99),
        EDITOR_OVERVIEW_RULER_RANGE_HIGHLIGHT_FOREGROUND = crate::color::Color::hex_alpha(0x89ddff99),
        EDITOR_OVERVIEW_RULER_SELECTION_HIGHLIGHT_FOREGROUND = crate::color::Color::hex_alpha(0xa0a0a0cc),
        EDITOR_OVERVIEW_RULER_WARNING_FOREGROUND = crate::color::Color::hex(0xfffac2),
        EDITOR_OVERVIEW_RULER_WORD_HIGHLIGHT_FOREGROUND = crate::color::Color::hex_alpha(0xa0a0a0cc),
        EDITOR_OVERVIEW_RULER_WORD_HIGHLIGHT_STRONG_FOREGROUND = crate::color::Color::hex_alpha(0x89ddffcc),
        EDITOR_PANE_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        EDITOR_RULER_FOREGROUND = crate::color::Color::hex_alpha(0xe4f0fb10),
        EDITOR_UNNECESSARY_CODE_OPACITY = crate::color::Color::hex_alpha(0x000000aa),
        EDITOR_WARNING_FOREGROUND = crate::color::Color::hex(0xfffac2),
        EDITOR_WHITESPACE_FOREGROUND = crate::color::Color::hex(0x303340),
        EDITOR_WIDGET_BORDER = crate::color::Color::hex(0xa6accd),
        EDITOR_WIDGET_FOREGROUND = crate::color::Color::hex(0xa6accd),
        EXTENSION_BUTTON_PROMINENT_BACKGROUND = crate::color::Color::hex_alpha(0x30334090),
        EXTENSION_BUTTON_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0x303340),
        FOCUS_BORDER = crate::color::Color::hex_alpha(0x00000000),
        INPUT_BACKGROUND = crate::color::Color::hex_alpha(0xffffff05),
        INPUT_BORDER = crate::color::Color::hex_alpha(0xffffff10),
        INPUT_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        INPUT_PLACEHOLDER_FOREGROUND = crate::color::Color::hex_alpha(0xa6accd60),
        INPUT_VALIDATION_ERROR_BORDER = crate::color::Color::hex(0xd0679d),
        INPUT_VALIDATION_ERROR_FOREGROUND = crate::color::Color::hex(0xd0679d),
        INPUT_VALIDATION_INFO_BORDER = crate::color::Color::hex(0x89ddff),
        INPUT_VALIDATION_WARNING_BORDER = crate::color::Color::hex(0xfffac2),
        NOTIFICATIONS_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        NOTIFICATIONS_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        PANEL_BORDER = crate::color::Color::hex_alpha(0x00000030),
        PANEL_TITLE_ACTIVE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        PEEK_VIEW_BORDER = crate::color::Color::hex_alpha(0x00000030),
        PEEK_VIEW_EDITOR_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd05),
        PEEK_VIEW_EDITOR_GUTTER_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd05),
        PEEK_VIEW_RESULT_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd05),
        PEEK_VIEW_TITLE_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd05),
        PEEK_VIEW_TITLE_DESCRIPTION_FOREGROUND = crate::color::Color::hex_alpha(0xa6accd60),
        SCROLLBAR_SHADOW = crate::color::Color::hex_alpha(0x00000000),
        SCROLLBAR_SLIDER_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd25),
        SCROLLBAR_SLIDER_BACKGROUND = crate::color::Color::hex_alpha(0x00000080),
        SCROLLBAR_SLIDER_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd25),
        SELECTION_BACKGROUND = crate::color::Color::hex(0xa6accd),
        SIDE_BAR_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        SIDE_BAR_FOREGROUND = crate::color::Color::hex(0x767c9d),
        SIDE_BAR_SECTION_HEADER_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        SIDE_BAR_TITLE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        STATUS_BAR_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        STATUS_BAR_FOREGROUND = crate::color::Color::hex(0xa6accd),
        STATUS_BAR_NO_FOLDER_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        TAB_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0x30334080),
        TAB_ACTIVE_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        TAB_BORDER = crate::color::Color::hex_alpha(0x00000000),
        TAB_INACTIVE_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        TAB_INACTIVE_FOREGROUND = crate::color::Color::hex(0x767c9d),
        TAB_UNFOCUSED_ACTIVE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        TAB_ACTIVE_MODIFIED_BORDER = crate::color::Color::hex(0xadd7ff),
        TAB_INACTIVE_MODIFIED_BORDER = crate::color::Color::hex_alpha(0xadd7ff80),
        TAB_LAST_PINNED_BORDER = crate::color::Color::hex_alpha(0x00000000),
        TAB_UNFOCUSED_ACTIVE_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        TAB_UNFOCUSED_ACTIVE_MODIFIED_BORDER = crate::color::Color::hex_alpha(0xadd7ff40),
        TAB_UNFOCUSED_INACTIVE_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        TAB_UNFOCUSED_INACTIVE_FOREGROUND = crate::color::Color::hex_alpha(0xa6accd80),
        TAB_UNFOCUSED_INACTIVE_MODIFIED_BORDER = crate::color::Color::hex_alpha(0xadd7ff40),
        TERMINAL_ANSI_BLACK = crate::color::Color::hex(0x1b1e28),
        TERMINAL_ANSI_BLUE = crate::color::Color::hex(0x89ddff),
        TERMINAL_ANSI_BRIGHT_BLACK = crate::color::Color::hex(0xa6accd),
        TERMINAL_ANSI_BRIGHT_BLUE = crate::color::Color::hex(0xadd7ff),
        TERMINAL_ANSI_BRIGHT_CYAN = crate::color::Color::hex(0xadd7ff),
        TERMINAL_ANSI_BRIGHT_GREEN = crate::color::Color::hex(0x5de4c7),
        TERMINAL_ANSI_BRIGHT_MAGENTA = crate::color::Color::hex(0xf087bd),
        TERMINAL_ANSI_BRIGHT_RED = crate::color::Color::hex(0xd0679d),
        TERMINAL_ANSI_BRIGHT_WHITE = crate::color::Color::hex(0xffffff),
        TERMINAL_ANSI_BRIGHT_YELLOW = crate::color::Color::hex(0xfffac2),
        TERMINAL_ANSI_CYAN = crate::color::Color::hex(0x89ddff),
        TERMINAL_ANSI_GREEN = crate::color::Color::hex(0x5de4c7),
        TERMINAL_ANSI_MAGENTA = crate::color::Color::hex(0xf087bd),
        TERMINAL_ANSI_RED = crate::color::Color::hex(0xd0679d),
        TERMINAL_ANSI_WHITE = crate::color::Color::hex(0xffffff),
        TERMINAL_ANSI_YELLOW = crate::color::Color::hex(0xfffac2),
        TEXT_LINK_ACTIVE_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        TEXT_LINK_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        TITLE_BAR_ACTIVE_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        TITLE_BAR_ACTIVE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        TITLE_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        TITLE_BAR_INACTIVE_FOREGROUND = crate::color::Color::hex(0x767c9d),
        TREE_INDENT_GUIDES_STROKE = crate::color::Color::hex(0x303340),
        WIDGET_SHADOW = crate::color::Color::hex_alpha(0x00000030),
        ACTIVITY_BAR_ACTIVE_BORDER = crate::color::Color::hex(0xa6accd),
        ACTIVITY_BAR_DROP_BORDER = crate::color::Color::hex(0xa6accd),
        ACTIVITY_BAR_INACTIVE_FOREGROUND = crate::color::Color::hex_alpha(0xa6accd66),
        BREADCRUMB_ACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        BREADCRUMB_BACKGROUND = crate::color::Color::hex_alpha(0x00000000),
        BREADCRUMB_FOCUS_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        BREADCRUMB_FOREGROUND = crate::color::Color::hex_alpha(0x767c9dcc),
        BREADCRUMB_PICKER_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        BUTTON_FOREGROUND = crate::color::Color::hex(0xffffff),
        BUTTON_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x50647750),
        BUTTON_SECONDARY_BACKGROUND = crate::color::Color::hex(0xa6accd),
        BUTTON_SECONDARY_FOREGROUND = crate::color::Color::hex(0xffffff),
        BUTTON_SECONDARY_HOVER_BACKGROUND = crate::color::Color::hex(0xa6accd),
        CHARTS_BLUE = crate::color::Color::hex(0xadd7ff),
        CHARTS_FOREGROUND = crate::color::Color::hex(0xa6accd),
        CHARTS_GREEN = crate::color::Color::hex(0x5de4c7),
        CHARTS_LINES = crate::color::Color::hex_alpha(0xa6accd80),
        CHARTS_ORANGE = crate::color::Color::hex(0x89ddff),
        CHARTS_PURPLE = crate::color::Color::hex(0xf087bd),
        CHARTS_RED = crate::color::Color::hex(0xd0679d),
        CHARTS_YELLOW = crate::color::Color::hex(0xfffac2),
        CHECKBOX_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        CHECKBOX_BORDER = crate::color::Color::hex_alpha(0xffffff10),
        CHECKBOX_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        DEBUG_CONSOLE_ERROR_FOREGROUND = crate::color::Color::hex(0xd0679d),
        DEBUG_CONSOLE_INFO_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        DEBUG_CONSOLE_SOURCE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        DEBUG_CONSOLE_WARNING_FOREGROUND = crate::color::Color::hex(0xfffac2),
        DEBUG_CONSOLE_INPUT_ICON_FOREGROUND = crate::color::Color::hex(0xa6accd),
        DEBUG_EXCEPTION_WIDGET_BACKGROUND = crate::color::Color::hex(0xd0679d),
        DEBUG_EXCEPTION_WIDGET_BORDER = crate::color::Color::hex(0xd0679d),
        DEBUG_ICON_BREAKPOINT_CURRENT_STACKFRAME_FOREGROUND = crate::color::Color::hex(0xfffac2),
        DEBUG_ICON_BREAKPOINT_DISABLED_FOREGROUND = crate::color::Color::hex(0x7390aa),
        DEBUG_ICON_BREAKPOINT_FOREGROUND = crate::color::Color::hex(0xd0679d),
        DEBUG_ICON_BREAKPOINT_STACKFRAME_FOREGROUND = crate::color::Color::hex(0x5fb3a1),
        DEBUG_ICON_BREAKPOINT_UNVERIFIED_FOREGROUND = crate::color::Color::hex(0x7390aa),
        DEBUG_ICON_CONTINUE_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        DEBUG_ICON_DISCONNECT_FOREGROUND = crate::color::Color::hex(0xd0679d),
        DEBUG_ICON_PAUSE_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        DEBUG_ICON_RESTART_FOREGROUND = crate::color::Color::hex(0x5fb3a1),
        DEBUG_ICON_START_FOREGROUND = crate::color::Color::hex(0x5fb3a1),
        DEBUG_ICON_STEP_BACK_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        DEBUG_ICON_STEP_INTO_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        DEBUG_ICON_STEP_OUT_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        DEBUG_ICON_STEP_OVER_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        DEBUG_ICON_STOP_FOREGROUND = crate::color::Color::hex(0xd0679d),
        DEBUG_TOKEN_EXPRESSION_BOOLEAN = crate::color::Color::hex(0x89ddff),
        DEBUG_TOKEN_EXPRESSION_ERROR = crate::color::Color::hex(0xd0679d),
        DEBUG_TOKEN_EXPRESSION_NAME = crate::color::Color::hex(0xe4f0fb),
        DEBUG_TOKEN_EXPRESSION_NUMBER = crate::color::Color::hex(0x5fb3a1),
        DEBUG_TOKEN_EXPRESSION_STRING = crate::color::Color::hex(0x89ddff),
        DEBUG_TOKEN_EXPRESSION_VALUE = crate::color::Color::hex_alpha(0xa6accd99),
        DEBUG_TOOL_BAR_BACKGROUND = crate::color::Color::hex(0x303340),
        DEBUG_VIEW_EXCEPTION_LABEL_BACKGROUND = crate::color::Color::hex(0xd0679d),
        DEBUG_VIEW_EXCEPTION_LABEL_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        DEBUG_VIEW_STATE_LABEL_BACKGROUND = crate::color::Color::hex(0x303340),
        DEBUG_VIEW_STATE_LABEL_FOREGROUND = crate::color::Color::hex(0xa6accd),
        DEBUG_VIEW_VALUE_CHANGED_HIGHLIGHT = crate::color::Color::hex(0x89ddff),
        DESCRIPTION_FOREGROUND = crate::color::Color::hex_alpha(0xa6accdb3),
        DIFF_EDITOR_DIAGONAL_FILL = crate::color::Color::hex_alpha(0xa6accd33),
        DROPDOWN_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        ERROR_FOREGROUND = crate::color::Color::hex(0xd0679d),
        EXTENSION_BADGE_REMOTE_BACKGROUND = crate::color::Color::hex(0x303340),
        EXTENSION_BADGE_REMOTE_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        EXTENSION_BUTTON_PROMINENT_FOREGROUND = crate::color::Color::hex(0xffffff),
        EXTENSION_ICON_STAR_FOREGROUND = crate::color::Color::hex(0xfffac2),
        FOREGROUND = crate::color::Color::hex(0xa6accd),
        GIT_DECORATION_ADDED_RESOURCE_FOREGROUND = crate::color::Color::hex(0x5fb3a1),
        GIT_DECORATION_CONFLICTING_RESOURCE_FOREGROUND = crate::color::Color::hex(0xd0679d),
        GIT_DECORATION_DELETED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xd0679d),
        GIT_DECORATION_IGNORED_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0x767c9d70),
        GIT_DECORATION_MODIFIED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        GIT_DECORATION_RENAMED_RESOURCE_FOREGROUND = crate::color::Color::hex(0x5de4c7),
        GIT_DECORATION_STAGE_DELETED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xd0679d),
        GIT_DECORATION_STAGE_MODIFIED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        GIT_DECORATION_SUBMODULE_RESOURCE_FOREGROUND = crate::color::Color::hex(0x89ddff),
        GIT_DECORATION_UNTRACKED_RESOURCE_FOREGROUND = crate::color::Color::hex(0x5de4c7),
        ICON_FOREGROUND = crate::color::Color::hex(0xa6accd),
        IMAGE_PREVIEW_BORDER = crate::color::Color::hex(0x303340),
        INPUT_OPTION_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0x00000000),
        INPUT_OPTION_ACTIVE_BORDER = crate::color::Color::hex_alpha(0x00000000),
        INPUT_OPTION_ACTIVE_FOREGROUND = crate::color::Color::hex(0xffffff),
        INPUT_VALIDATION_ERROR_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        INPUT_VALIDATION_INFO_BACKGROUND = crate::color::Color::hex(0x506477),
        INPUT_VALIDATION_WARNING_BACKGROUND = crate::color::Color::hex(0x506477),
        LIST_DEEMPHASIZED_FOREGROUND = crate::color::Color::hex(0x767c9d),
        LIST_DROP_BACKGROUND = crate::color::Color::hex(0x506477),
        LIST_FILTER_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0x89ddff60),
        LIST_FOCUS_OUTLINE = crate::color::Color::hex_alpha(0x00000000),
        LIST_INVALID_ITEM_FOREGROUND = crate::color::Color::hex(0xfffac2),
        LIST_WARNING_FOREGROUND = crate::color::Color::hex(0xfffac2),
        LIST_FILTER_WIDGET_BACKGROUND = crate::color::Color::hex(0x303340),
        LIST_FILTER_WIDGET_NO_MATCHES_OUTLINE = crate::color::Color::hex(0xd0679d),
        LIST_FILTER_WIDGET_OUTLINE = crate::color::Color::hex_alpha(0x00000000),
        LIST_ACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x30334080),
        LIST_ACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        LIST_ERROR_FOREGROUND = crate::color::Color::hex(0xd0679d),
        LIST_FOCUS_BACKGROUND = crate::color::Color::hex_alpha(0x30334080),
        LIST_FOCUS_FOREGROUND = crate::color::Color::hex(0xa6accd),
        LIST_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0x5fb3a1),
        LIST_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x30334080),
        LIST_HOVER_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        LIST_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x30334080),
        LIST_INACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        MENU_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        MENU_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        MENU_SELECTION_BACKGROUND = crate::color::Color::hex(0x303340),
        MENU_SELECTION_FOREGROUND = crate::color::Color::hex(0x7390aa),
        MENU_SEPARATOR_BACKGROUND = crate::color::Color::hex(0x767c9d),
        MENUBAR_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x717cb425),
        MENUBAR_SELECTION_FOREGROUND = crate::color::Color::hex(0xa6accd),
        MERGE_COMMON_CONTENT_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd29),
        MERGE_COMMON_HEADER_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd66),
        MERGE_CURRENT_CONTENT_BACKGROUND = crate::color::Color::hex_alpha(0x5fb3a133),
        MERGE_CURRENT_HEADER_BACKGROUND = crate::color::Color::hex_alpha(0x5fb3a180),
        MERGE_INCOMING_CONTENT_BACKGROUND = crate::color::Color::hex_alpha(0x89ddff33),
        MERGE_INCOMING_HEADER_BACKGROUND = crate::color::Color::hex_alpha(0x89ddff80),
        MINIMAP_ERROR_HIGHLIGHT = crate::color::Color::hex(0xd0679d),
        MINIMAP_FIND_MATCH_HIGHLIGHT = crate::color::Color::hex(0xadd7ff),
        MINIMAP_SELECTION_HIGHLIGHT = crate::color::Color::hex_alpha(0xe4f0fb40),
        MINIMAP_WARNING_HIGHLIGHT = crate::color::Color::hex(0xfffac2),
        MINIMAP_GUTTER_ADDED_BACKGROUND = crate::color::Color::hex_alpha(0x5fb3a180),
        MINIMAP_GUTTER_DELETED_BACKGROUND = crate::color::Color::hex_alpha(0xd0679d80),
        MINIMAP_GUTTER_MODIFIED_BACKGROUND = crate::color::Color::hex_alpha(0xadd7ff80),
        MINIMAP_SLIDER_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd30),
        MINIMAP_SLIDER_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd20),
        MINIMAP_SLIDER_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd30),
        NOTEBOOK_CELL_BORDER_COLOR = crate::color::Color::hex(0x1b1e28),
        NOTEBOOK_CELL_INSERTION_INDICATOR = crate::color::Color::hex_alpha(0x00000000),
        NOTEBOOK_CELL_STATUS_BAR_ITEM_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0xffffff26),
        NOTEBOOK_CELL_TOOLBAR_SEPARATOR = crate::color::Color::hex(0x303340),
        NOTEBOOK_FOCUSED_CELL_BORDER = crate::color::Color::hex_alpha(0x00000000),
        NOTEBOOK_FOCUSED_EDITOR_BORDER = crate::color::Color::hex_alpha(0x00000000),
        NOTEBOOK_FOCUSED_ROW_BORDER = crate::color::Color::hex_alpha(0x00000000),
        NOTEBOOK_INACTIVE_FOCUSED_CELL_BORDER = crate::color::Color::hex_alpha(0x00000000),
        NOTEBOOK_OUTPUT_CONTAINER_BACKGROUND_COLOR = crate::color::Color::hex(0x1b1e28),
        NOTEBOOK_ROW_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x30334000),
        NOTEBOOK_SELECTED_CELL_BACKGROUND = crate::color::Color::hex(0x303340),
        NOTEBOOK_SELECTED_CELL_BORDER = crate::color::Color::hex(0x1b1e28),
        NOTEBOOK_SYMBOL_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xffffff0b),
        NOTEBOOK_SCROLLBAR_SLIDER_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd25),
        NOTEBOOK_SCROLLBAR_SLIDER_BACKGROUND = crate::color::Color::hex_alpha(0x00000050),
        NOTEBOOK_SCROLLBAR_SLIDER_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd25),
        NOTEBOOK_STATUS_ERROR_ICON_FOREGROUND = crate::color::Color::hex(0xd0679d),
        NOTEBOOK_STATUS_RUNNING_ICON_FOREGROUND = crate::color::Color::hex(0xa6accd),
        NOTEBOOK_STATUS_SUCCESS_ICON_FOREGROUND = crate::color::Color::hex(0x5fb3a1),
        NOTIFICATION_CENTER_HEADER_BACKGROUND = crate::color::Color::hex(0x303340),
        NOTIFICATION_LINK_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        NOTIFICATIONS_BORDER = crate::color::Color::hex(0x303340),
        NOTIFICATIONS_ERROR_ICON_FOREGROUND = crate::color::Color::hex(0xd0679d),
        NOTIFICATIONS_INFO_ICON_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        NOTIFICATIONS_WARNING_ICON_FOREGROUND = crate::color::Color::hex(0xfffac2),
        PANEL_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        PANEL_DROP_BORDER = crate::color::Color::hex(0xa6accd),
        PANEL_SECTION_BORDER = crate::color::Color::hex(0x1b1e28),
        PANEL_SECTION_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x7390aa80),
        PANEL_SECTION_HEADER_BACKGROUND = crate::color::Color::hex(0x303340),
        PANEL_TITLE_ACTIVE_BORDER = crate::color::Color::hex(0xa6accd),
        PANEL_TITLE_INACTIVE_FOREGROUND = crate::color::Color::hex_alpha(0xa6accd99),
        PEEK_VIEW_EDITOR_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x303340),
        PEEK_VIEW_RESULT_FILE_FOREGROUND = crate::color::Color::hex(0xffffff),
        PEEK_VIEW_RESULT_LINE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        PEEK_VIEW_RESULT_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x303340),
        PEEK_VIEW_RESULT_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x717cb425),
        PEEK_VIEW_RESULT_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        PEEK_VIEW_TITLE_LABEL_FOREGROUND = crate::color::Color::hex(0xffffff),
        PICKER_GROUP_BORDER = crate::color::Color::hex(0xa6accd),
        PICKER_GROUP_FOREGROUND = crate::color::Color::hex(0x89ddff),
        PROBLEMS_ERROR_ICON_FOREGROUND = crate::color::Color::hex(0xd0679d),
        PROBLEMS_INFO_ICON_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        PROBLEMS_WARNING_ICON_FOREGROUND = crate::color::Color::hex(0xfffac2),
        PROGRESS_BAR_BACKGROUND = crate::color::Color::hex(0x89ddff),
        QUICK_INPUT_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        QUICK_INPUT_FOREGROUND = crate::color::Color::hex(0xa6accd),
        QUICK_INPUT_LIST_FOCUS_BACKGROUND = crate::color::Color::hex_alpha(0xa6accd10),
        QUICK_INPUT_TITLE_BACKGROUND = crate::color::Color::hex_alpha(0xffffff1b),
        SASH_HOVER_BORDER = crate::color::Color::hex_alpha(0x00000000),
        SCM_PROVIDER_BORDER = crate::color::Color::hex_alpha(0xe4f0fb10),
        SEARCH_EDITOR_FIND_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0xadd7ff50),
        SEARCH_EDITOR_TEXT_INPUT_BORDER = crate::color::Color::hex_alpha(0xffffff10),
        SETTINGS_CHECKBOX_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        SETTINGS_CHECKBOX_BORDER = crate::color::Color::hex_alpha(0xffffff10),
        SETTINGS_CHECKBOX_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        SETTINGS_DROPDOWN_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        SETTINGS_DROPDOWN_BORDER = crate::color::Color::hex_alpha(0xffffff10),
        SETTINGS_DROPDOWN_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        SETTINGS_DROPDOWN_LIST_BORDER = crate::color::Color::hex_alpha(0xe4f0fb10),
        SETTINGS_FOCUSED_ROW_BACKGROUND = crate::color::Color::hex_alpha(0x00000000),
        SETTINGS_HEADER_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        SETTINGS_MODIFIED_ITEM_INDICATOR = crate::color::Color::hex(0xadd7ff),
        SETTINGS_NUMBER_INPUT_BACKGROUND = crate::color::Color::hex_alpha(0xffffff05),
        SETTINGS_NUMBER_INPUT_BORDER = crate::color::Color::hex_alpha(0xffffff10),
        SETTINGS_NUMBER_INPUT_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        SETTINGS_TEXT_INPUT_BACKGROUND = crate::color::Color::hex_alpha(0xffffff05),
        SETTINGS_TEXT_INPUT_BORDER = crate::color::Color::hex_alpha(0xffffff10),
        SETTINGS_TEXT_INPUT_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        SIDE_BAR_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x7390aa80),
        SIDE_BAR_SECTION_HEADER_FOREGROUND = crate::color::Color::hex(0xa6accd),
        STATUS_BAR_DEBUGGING_BACKGROUND = crate::color::Color::hex(0x303340),
        STATUS_BAR_DEBUGGING_FOREGROUND = crate::color::Color::hex(0xffffff),
        STATUS_BAR_NO_FOLDER_FOREGROUND = crate::color::Color::hex(0xa6accd),
        STATUS_BAR_ITEM_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0xffffff2e),
        STATUS_BAR_ITEM_ERROR_BACKGROUND = crate::color::Color::hex(0xd0679d),
        STATUS_BAR_ITEM_ERROR_FOREGROUND = crate::color::Color::hex(0xffffff),
        STATUS_BAR_ITEM_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0xffffff1f),
        STATUS_BAR_ITEM_PROMINENT_BACKGROUND = crate::color::Color::hex_alpha(0x00000080),
        STATUS_BAR_ITEM_PROMINENT_FOREGROUND = crate::color::Color::hex(0xa6accd),
        STATUS_BAR_ITEM_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x0000004d),
        STATUS_BAR_ITEM_REMOTE_BACKGROUND = crate::color::Color::hex(0x303340),
        STATUS_BAR_ITEM_REMOTE_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        SYMBOL_ICON_ARRAY_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_BOOLEAN_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_CLASS_FOREGROUND = crate::color::Color::hex(0xfffac2),
        SYMBOL_ICON_COLOR_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_CONSTANT_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_CONSTRUCTOR_FOREGROUND = crate::color::Color::hex(0xf087bd),
        SYMBOL_ICON_ENUMERATOR_FOREGROUND = crate::color::Color::hex(0xfffac2),
        SYMBOL_ICON_ENUMERATOR_MEMBER_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        SYMBOL_ICON_EVENT_FOREGROUND = crate::color::Color::hex(0xfffac2),
        SYMBOL_ICON_FIELD_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        SYMBOL_ICON_FILE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_FOLDER_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_FUNCTION_FOREGROUND = crate::color::Color::hex(0xf087bd),
        SYMBOL_ICON_INTERFACE_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        SYMBOL_ICON_KEY_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_KEYWORD_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_METHOD_FOREGROUND = crate::color::Color::hex(0xf087bd),
        SYMBOL_ICON_MODULE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_NAMESPACE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_NULL_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_NUMBER_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_OBJECT_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_OPERATOR_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_PACKAGE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_PROPERTY_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_REFERENCE_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_SNIPPET_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_STRING_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_STRUCT_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_TEXT_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_TYPE_PARAMETER_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_UNIT_FOREGROUND = crate::color::Color::hex(0xa6accd),
        SYMBOL_ICON_VARIABLE_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        TERMINAL_BORDER = crate::color::Color::hex_alpha(0x00000000),
        TERMINAL_FOREGROUND = crate::color::Color::hex(0xa6accd),
        TERMINAL_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x717cb425),
        TERMINAL_COMMAND_DECORATION_ERROR_BACKGROUND = crate::color::Color::hex(0xd0679d),
        TERMINAL_COMMAND_DECORATION_SUCCESS_BACKGROUND = crate::color::Color::hex(0x5de4c7),
        TERMINAL_COMMAND_DECORATION_DEFAULT_BACKGROUND = crate::color::Color::hex(0x767c9d),
        TESTING_ICON_ERRORED = crate::color::Color::hex(0xd0679d),
        TESTING_ICON_FAILED = crate::color::Color::hex(0xd0679d),
        TESTING_ICON_PASSED = crate::color::Color::hex(0x5de4c7),
        TESTING_ICON_QUEUED = crate::color::Color::hex(0xfffac2),
        TESTING_ICON_SKIPPED = crate::color::Color::hex(0x7390aa),
        TESTING_ICON_UNSET = crate::color::Color::hex(0x7390aa),
        TESTING_MESSAGE_ERROR_DECORATION_FOREGROUND = crate::color::Color::hex(0xd0679d),
        TESTING_MESSAGE_ERROR_LINE_BACKGROUND = crate::color::Color::hex_alpha(0xd0679d33),
        TESTING_MESSAGE_HINT_DECORATION_FOREGROUND = crate::color::Color::hex_alpha(0x7390aab3),
        TESTING_MESSAGE_INFO_DECORATION_FOREGROUND = crate::color::Color::hex(0xadd7ff),
        TESTING_MESSAGE_INFO_LINE_BACKGROUND = crate::color::Color::hex_alpha(0x89ddff33),
        TESTING_MESSAGE_WARNING_DECORATION_FOREGROUND = crate::color::Color::hex(0xfffac2),
        TESTING_MESSAGE_WARNING_LINE_BACKGROUND = crate::color::Color::hex_alpha(0xfffac233),
        TESTING_PEEK_BORDER = crate::color::Color::hex(0xd0679d),
        TESTING_RUN_ACTION = crate::color::Color::hex(0x5de4c7),
        TEXT_BLOCK_QUOTE_BACKGROUND = crate::color::Color::hex_alpha(0x7390aa1a),
        TEXT_BLOCK_QUOTE_BORDER = crate::color::Color::hex_alpha(0x89ddff80),
        TEXT_CODE_BLOCK_BACKGROUND = crate::color::Color::hex_alpha(0x00000050),
        TEXT_PREFORMAT_FOREGROUND = crate::color::Color::hex(0xe4f0fb),
        TEXT_SEPARATOR_FOREGROUND = crate::color::Color::hex_alpha(0xffffff2e),
        TREE_TABLE_COLUMNS_BORDER = crate::color::Color::hex_alpha(0xa6accd20),
        WELCOME_PAGE_PROGRESS_BACKGROUND = crate::color::Color::hex_alpha(0xffffff05),
        WELCOME_PAGE_PROGRESS_FOREGROUND = crate::color::Color::hex(0x5fb3a1),
        WELCOME_PAGE_TILE_BACKGROUND = crate::color::Color::hex(0x1b1e28),
        WELCOME_PAGE_TILE_HOVER_BACKGROUND = crate::color::Color::hex(0x303340),
        TOKEN_0 = crate::color::Color::hex_alpha(0x767c9db0),
        TOKEN_1 = crate::color::Color::hex(0xa6accd),
        TOKEN_2 = crate::color::Color::hex(0xadd7ff),
        TOKEN_3 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_4 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_5 = crate::color::Color::hex(0xadd7ff),
        TOKEN_6 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_7 = crate::color::Color::hex_alpha(0x5de4c7c0),
        TOKEN_8 = crate::color::Color::hex(0x5de4c7),
        TOKEN_9 = crate::color::Color::hex(0x5de4c7),
        TOKEN_10 = crate::color::Color::hex(0xd0679d),
        TOKEN_11 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_12 = crate::color::Color::hex(0xffffff),
        TOKEN_13 = crate::color::Color::hex(0xd0679d),
        TOKEN_14 = crate::color::Color::hex(0xd0679d),
        TOKEN_15 = crate::color::Color::hex(0xa6accd),
        TOKEN_16 = crate::color::Color::hex(0x91b4d5),
        TOKEN_17 = crate::color::Color::hex(0x5de4c7),
        TOKEN_19 = crate::color::Color::hex(0xadd7ff),
        TOKEN_20 = crate::color::Color::hex(0xa6accd),
        TOKEN_21 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_22 = crate::color::Color::hex(0x5de4c7),
        TOKEN_23 = crate::color::Color::hex(0x5de4c7),
        TOKEN_FUNCTION_CALL = crate::color::Color::hex_alpha(0xe4f0fbd0),
        TOKEN_FUNCTION_CLASS_NAME = crate::color::Color::hex(0xadd7ff),
        TOKEN_26 = crate::color::Color::hex(0xadd7ff),
        TOKEN_27 = crate::color::Color::hex(0x5de4c7),
        TOKEN_28 = crate::color::Color::hex(0x5de4c7),
        TOKEN_29 = crate::color::Color::hex(0xadd7ff),
        TOKEN_30 = crate::color::Color::hex(0xadd7ff),
        TOKEN_31 = crate::color::Color::hex(0xa6accd),
        TOKEN_32 = crate::color::Color::hex_alpha(0xa6accdc0),
        TOKEN_33 = crate::color::Color::hex(0x91b4d5),
        TOKEN_34 = crate::color::Color::hex(0xadd7ff),
        TOKEN_35 = crate::color::Color::hex(0xadd7ff),
        TOKEN_36 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_37 = crate::color::Color::hex(0xadd7ff),
        TOKEN_38 = crate::color::Color::hex(0x91b4d5),
        TOKEN_39 = crate::color::Color::hex(0x91b4d5),
        TOKEN_40 = crate::color::Color::hex(0x91b4d5),
        TOKEN_41 = crate::color::Color::hex(0x5fb3a1),
        TOKEN_42 = crate::color::Color::hex(0x5fb3a1),
        TOKEN_43 = crate::color::Color::hex(0x42675a),
        TOKEN_44 = crate::color::Color::hex(0xadd7ff),
        TOKEN_45 = crate::color::Color::hex(0x506477),
        TOKEN_46 = crate::color::Color::hex(0x91b4d5),
        TOKEN_47 = crate::color::Color::hex(0x5fb3a1),
        TOKEN_48 = crate::color::Color::hex(0x5fb3a1),
        TOKEN_49 = crate::color::Color::hex(0xadd7ff),
        TOKEN_50 = crate::color::Color::hex(0x42675a),
        TOKEN_51 = crate::color::Color::hex(0x5fb3a1),
        TOKEN_52 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_53 = crate::color::Color::hex(0xadd7ff),
        TOKEN_54 = crate::color::Color::hex(0x91b4d5),
        TOKEN_55 = crate::color::Color::hex(0x7390aa),
        TOKEN_56 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_57 = crate::color::Color::hex(0xadd7ff),
        TOKEN_58 = crate::color::Color::hex(0x91b4d5),
        TOKEN_59 = crate::color::Color::hex(0x7390aa),
        TOKEN_60 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_61 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_62 = crate::color::Color::hex(0xadd7ff),
        TOKEN_63 = crate::color::Color::hex(0x91b4d5),
        TOKEN_64 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_65 = crate::color::Color::hex(0x7390aa),
        TOKEN_66 = crate::color::Color::hex(0x7390aa),
        TOKEN_67 = crate::color::Color::hex(0x7390aa),
        TOKEN_68 = crate::color::Color::hex(0x7390aa),
        TOKEN_70 = crate::color::Color::hex(0x5de4c7),
        TOKEN_72 = crate::color::Color::hex(0xadd7ff),
        TOKEN_73 = crate::color::Color::hex(0xadd7ff),
        TOKEN_74 = crate::color::Color::hex(0xadd7ff),
        TOKEN_75 = crate::color::Color::hex(0xadd7ff),
        TOKEN_76 = crate::color::Color::hex_alpha(0x50647750),
        TOKEN_77 = crate::color::Color::hex_alpha(0x50647750),
        TOKEN_78 = crate::color::Color::hex(0x91b4d5),
        TOKEN_79 = crate::color::Color::hex(0x91b4d5),
        TOKEN_80 = crate::color::Color::hex(0x7390aa),
        TOKEN_81 = crate::color::Color::hex(0xadd7ff),
        TOKEN_82 = crate::color::Color::hex(0x89ddff),
        TOKEN_83 = crate::color::Color::hex(0xfffac2),
        TOKEN_84 = crate::color::Color::hex(0xd0679d),
        TOKEN_85 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_86 = crate::color::Color::hex(0xe4f0fb),
        TOKEN_87 = crate::color::Color::hex_alpha(0xe4f0fbd0),
        TOKEN_88 = crate::color::Color::hex(0x506477),
        TOKEN_89 = crate::color::Color::hex(0x7390aa),
        TOKEN_90 = crate::color::Color::hex(0x767c9d),
        TOKEN_93 = crate::color::Color::hex(0xadd7ff),
        TOKEN_94 = crate::color::Color::hex(0xadd7ff),
        TOKEN_95 = crate::color::Color::hex(0xadd7ff),
        TOKEN_96 = crate::color::Color::hex(0x5de4c7),
        TOKEN_97 = crate::color::Color::hex(0xadd7ff),
        TOKEN_98 = crate::color::Color::hex(0xadd7ff),
        TOKEN_99 = crate::color::Color::hex(0xd0679d),
        TOKEN_100 = crate::color::Color::hex(0xa6accd),
    }
    accents {
        Red = TERMINAL_ANSI_RED => ("red", "Red"),
        Green = TERMINAL_ANSI_GREEN => ("green", "Green"),
        Yellow = TERMINAL_ANSI_YELLOW => ("yellow", "Yellow"),
        Blue = TERMINAL_ANSI_BLUE => ("blue", "Blue"),
        Magenta = TERMINAL_ANSI_MAGENTA => ("magenta", "Magenta"),
        Cyan = TERMINAL_ANSI_CYAN => ("cyan", "Cyan"),
    }
    default TERMINAL_ANSI_GREEN => "green";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BACKGROUND,
            surface: Self::SIDE_BAR_BACKGROUND,
            raised: Self::DROPDOWN_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::SIDE_BAR_BACKGROUND,
            surface: Self::EDITOR_BACKGROUND,
            raised: Self::SIDE_BAR_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::EDITOR_FOREGROUND,
            muted: Self::DESCRIPTION_FOREGROUND,
            subtle: Self::EDITOR_LINE_NUMBER_FOREGROUND,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::TERMINAL_ANSI_MAGENTA),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::SIDE_BAR_BACKGROUND,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::TERMINAL_ANSI_MAGENTA,
            hover: crate::palette::primary_hover(Self::TERMINAL_ANSI_MAGENTA),
            pressed: crate::palette::action_pressed(Self::TERMINAL_ANSI_MAGENTA),
            muted: Self::SIDE_BAR_BACKGROUND,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::TERMINAL_ANSI_GREEN,
            warning: Self::EDITOR_WARNING_FOREGROUND,
            error: Self::EDITOR_ERROR_FOREGROUND,
            critical: Self::TERMINAL_ANSI_BRIGHT_RED,
            info: Self::EDITOR_INFO_FOREGROUND,
            trace: Self::FOREGROUND,
        },
        border: Self::EDITOR_WIDGET_BORDER,
        border_muted: Self::SIDE_BAR_BACKGROUND,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::TERMINAL_ANSI_RED,
            orange: Self::TERMINAL_ANSI_YELLOW,
            yellow: Self::TERMINAL_ANSI_YELLOW,
            green: Self::TERMINAL_ANSI_GREEN,
            cyan: Self::TERMINAL_ANSI_CYAN,
            blue: Self::EDITOR_LINK_ACTIVE_FOREGROUND,
            purple: Self::TERMINAL_ANSI_MAGENTA,
            pink: Self::TERMINAL_ANSI_MAGENTA,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::TOKEN_40,
            boolean: Self::TOKEN_28,
            builtin: Self::EDITOR_WARNING_FOREGROUND,
            builtin_function: Self::TERMINAL_ANSI_MAGENTA,
            builtin_type: Self::TOKEN_32,
            comment: Self::TOKEN_0,
            constant: Self::EDITOR_WARNING_FOREGROUND,
            control_keyword: Self::TOKEN_15,
            deleted: Self::TOKEN_45,
            deprecated: Self::TOKEN_14,
            documentation: Self::TOKEN_0,
            escape: Self::TOKEN_48,
            foreground: Self::EDITOR_FOREGROUND,
            function: Self::TOKEN_FUNCTION_CLASS_NAME,
            heading: Self::TOKEN_28,
            inserted: Self::TOKEN_44,
            invalid: Self::TOKEN_13,
            keyword: Self::TOKEN_15,
            link: Self::TOKEN_68,
            markup_bold: Self::TOKEN_66,
            markup_italic: Self::TOKEN_65,
            modifier: Self::TOKEN_9,
            namespace: Self::TOKEN_33,
            number: Self::TOKEN_28,
            operator: Self::TOKEN_16,
            parameter: Self::TOKEN_11,
            property: Self::TOKEN_3,
            punctuation: Self::TOKEN_20,
            string: Self::TOKEN_28,
            tag: Self::TOKEN_23,
            type_keyword: Self::TOKEN_16,
            type_name: Self::TOKEN_32,
            variable: Self::EDITOR_FOREGROUND,
        },
    }
}
