//! VS Code Dark+. See `REGISTRATION` for pinned upstream sources.
//!
//! The Plus theme is merged over its included VS theme. Source menu and tabs supply surfaces, token colours supply named accents, and no Modern theme is substituted.

define_palette! {
    DarkPlus, "VS Code Dark+",
    identity("vscode/dark_plus", "vscode", "VS Code", "dark_plus", "Dark+", Dark, None);
    sources: super::SOURCE_DARK_PLUS;
    colors {
        CHECKBOX_BORDER = crate::color::Color::hex(0x6b6b6b),
        EDITOR_BACKGROUND = crate::color::Color::hex(0x1e1e1e),
        EDITOR_FOREGROUND = crate::color::Color::hex(0xd4d4d4),
        EDITOR_GROUP_HEADER_TABS_BACKGROUND = crate::color::Color::hex(0x303031),
        EDITOR_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0x3a3d41),
        EDITOR_INDENT_GUIDE_BACKGROUND_1 = crate::color::Color::hex(0x404040),
        EDITOR_INDENT_GUIDE_ACTIVE_BACKGROUND_1 = crate::color::Color::hex(0x707070),
        EDITOR_SELECTION_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xadd6ff26),
        LIST_DROP_BACKGROUND = crate::color::Color::hex(0x383b3d),
        ACTIVITY_BAR_BADGE_BACKGROUND = crate::color::Color::hex(0x007acc),
        BROWSER_BORDER = crate::color::Color::hex_alpha(0x00000000),
        SIDE_BAR_TITLE_FOREGROUND = crate::color::Color::hex(0xbbbbbb),
        INPUT_PLACEHOLDER_FOREGROUND = crate::color::Color::hex(0xa6a6a6),
        MENU_BACKGROUND = crate::color::Color::hex(0x252526),
        MENU_FOREGROUND = crate::color::Color::hex(0xcccccc),
        MENU_SEPARATOR_BACKGROUND = crate::color::Color::hex(0x454545),
        MENU_BORDER = crate::color::Color::hex(0x454545),
        MENU_SELECTION_BACKGROUND = crate::color::Color::hex(0x0078d4),
        STATUS_BAR_ITEM_REMOTE_FOREGROUND = crate::color::Color::hex(0xffffff),
        STATUS_BAR_ITEM_REMOTE_BACKGROUND = crate::color::Color::hex(0x16825d),
        STATUS_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x1476b8),
        TITLE_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x323233),
        PORTS_ICON_RUNNING_PROCESS_FOREGROUND = crate::color::Color::hex(0x369432),
        SIDE_BAR_SECTION_HEADER_BACKGROUND = crate::color::Color::hex_alpha(0x00000000),
        SIDE_BAR_SECTION_HEADER_BORDER = crate::color::Color::hex_alpha(0xcccccc33),
        TAB_SELECTED_BACKGROUND = crate::color::Color::hex(0x37373d),
        TAB_INACTIVE_BACKGROUND = crate::color::Color::hex(0x303031),
        TAB_INACTIVE_FOREGROUND = crate::color::Color::hex(0xa6a6a6),
        TAB_SELECTED_FOREGROUND = crate::color::Color::hex(0xffffff),
        TAB_LAST_PINNED_BORDER = crate::color::Color::hex_alpha(0xcccccc33),
        LIST_ACTIVE_SELECTION_ICON_FOREGROUND = crate::color::Color::hex(0xffffff),
        TERMINAL_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0x3a3d41),
        WIDGET_BORDER = crate::color::Color::hex(0x303031),
        ACTION_BAR_TOGGLED_BACKGROUND = crate::color::Color::hex(0x383a49),
        AGENTS_PANEL_BORDER = crate::color::Color::hex(0x303031),
        AGENTS_CARD_BORDER = crate::color::Color::hex_alpha(0x00000000),
        AGENTS_CHAT_INPUT_BORDER = crate::color::Color::hex(0x303031),
        AGENTS_CHAT_INPUT_FOCUS_BORDER = crate::color::Color::hex(0x007acc),
        AGENTS_NEW_SESSION_BUTTON_BORDER = crate::color::Color::hex(0x303031),
        SURFACE_BORDER = crate::color::Color::hex(0x252526),
        MODERN_ACTIVITY_BAR_ITEM_ACTIVE_BACKGROUND = crate::color::Color::hex(0x1e1e1e),
        MODERN_ACTIVITY_BAR_ITEM_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x1e1e1e66),
        MODERN_ACTIVITY_BAR_BORDER = crate::color::Color::hex(0x252526),
        TOKEN_0 = crate::color::Color::hex(0xd4d4d4),
        TOKEN_3 = crate::color::Color::hex(0x000080),
        TOKEN_4 = crate::color::Color::hex(0x6a9955),
        TOKEN_5 = crate::color::Color::hex(0x569cd6),
        TOKEN_6 = crate::color::Color::hex(0xb5cea8),
        TOKEN_7 = crate::color::Color::hex(0x646695),
        TOKEN_8 = crate::color::Color::hex(0x569cd6),
        TOKEN_9 = crate::color::Color::hex(0xd16969),
        TOKEN_10 = crate::color::Color::hex(0xdcdcaa),
        TOKEN_11 = crate::color::Color::hex(0xd7ba7d),
        TOKEN_12 = crate::color::Color::hex(0x569cd6),
        TOKEN_14 = crate::color::Color::hex(0xc8c8c8),
        TOKEN_15 = crate::color::Color::hex(0x569cd6),
        TOKEN_16 = crate::color::Color::hex(0xc586c0),
        TOKEN_18 = crate::color::Color::hex(0xb5cea8),
        TOKEN_19 = crate::color::Color::hex(0xce9178),
        TOKEN_20 = crate::color::Color::hex(0x569cd6),
        TOKEN_21 = crate::color::Color::hex(0x6a9955),
        TOKEN_22 = crate::color::Color::hex(0x6796e6),
        TOKEN_23 = crate::color::Color::hex(0xce9178),
        TOKEN_BRACKETS_OF_XML_HTML_TAGS = crate::color::Color::hex(0x808080),
        TOKEN_25 = crate::color::Color::hex(0x569cd6),
        TOKEN_26 = crate::color::Color::hex(0xce9178),
        TOKEN_27 = crate::color::Color::hex(0xb5cea8),
        TOKEN_28 = crate::color::Color::hex(0x9cdcfe),
        TOKEN_29 = crate::color::Color::hex(0x569cd6),
        TOKEN_30 = crate::color::Color::hex(0x569cd6),
        TOKEN_31 = crate::color::Color::hex(0x569cd6),
        TOKEN_32 = crate::color::Color::hex(0x569cd6),
        TOKEN_33 = crate::color::Color::hex(0xce9178),
        TOKEN_34 = crate::color::Color::hex(0xce9178),
        TOKEN_35 = crate::color::Color::hex(0xce9178),
        TOKEN_36 = crate::color::Color::hex(0xd16969),
        TOKEN_STRING_INTERPOLATION = crate::color::Color::hex(0x569cd6),
        TOKEN_RESET_JAVA_SCRIPT_STRING_INTERPOLATION_EXPRESSION = crate::color::Color::hex(0xd4d4d4),
        TOKEN_39 = crate::color::Color::hex(0x9cdcfe),
        TOKEN_40 = crate::color::Color::hex(0x569cd6),
        TOKEN_41 = crate::color::Color::hex(0x569cd6),
        TOKEN_42 = crate::color::Color::hex(0xd4d4d4),
        TOKEN_43 = crate::color::Color::hex(0x569cd6),
        TOKEN_44 = crate::color::Color::hex(0xb5cea8),
        TOKEN_45 = crate::color::Color::hex(0x569cd6),
        TOKEN_46 = crate::color::Color::hex(0x9cdcfe),
        TOKEN_47 = crate::color::Color::hex(0xb5cea8),
        TOKEN_COLORING_OF_THE_JAVA_IMPORT_AND_PACKAGE_IDENTIFIERS = crate::color::Color::hex(0xd4d4d4),
        TOKEN_THIS_SELF = crate::color::Color::hex(0x569cd6),
        TOKEN_FUNCTION_DECLARATIONS = crate::color::Color::hex(0xdcdcaa),
        TOKEN_TYPES_DECLARATION_AND_REFERENCES = crate::color::Color::hex(0x4ec9b0),
        TOKEN_TYPES_DECLARATION_AND_REFERENCES_TS_GRAMMAR_SPECIFIC = crate::color::Color::hex(0x4ec9b0),
        TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS = crate::color::Color::hex(0xc586c0),
        TOKEN_VARIABLE_AND_PARAMETER_NAME = crate::color::Color::hex(0x9cdcfe),
        TOKEN_CONSTANTS_AND_ENUMS = crate::color::Color::hex(0x4fc1ff),
        TOKEN_OBJECT_KEYS_TS_GRAMMAR_SPECIFIC = crate::color::Color::hex(0x9cdcfe),
        TOKEN_CSS_PROPERTY_VALUE = crate::color::Color::hex(0xce9178),
        TOKEN_REGULAR_EXPRESSION_GROUPS = crate::color::Color::hex(0xce9178),
        TOKEN_13 = crate::color::Color::hex(0xd7ba7d),
    }
    accents {
        Blue = ACTIVITY_BAR_BADGE_BACKGROUND => ("blue", "Blue"),
        Purple = TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS => ("purple", "Purple"),
        Cyan = TOKEN_TYPES_DECLARATION_AND_REFERENCES => ("cyan", "Cyan"),
        Function = TOKEN_FUNCTION_DECLARATIONS => ("function", "Function"),
        Variable = TOKEN_VARIABLE_AND_PARAMETER_NAME => ("variable", "Variable"),
    }
    default ACTIVITY_BAR_BADGE_BACKGROUND => "blue";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BACKGROUND,
            surface: Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND,
            raised: Self::MENU_BACKGROUND,
            overlay: Self::MENU_BACKGROUND,
            hover: Self::LIST_DROP_BACKGROUND,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::MENU_BACKGROUND,
            surface: Self::EDITOR_BACKGROUND,
            raised: Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND,
            overlay: Self::MENU_BACKGROUND,
            hover: Self::LIST_DROP_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::EDITOR_FOREGROUND,
            muted: Self::SIDE_BAR_TITLE_FOREGROUND,
            subtle: Self::INPUT_PLACEHOLDER_FOREGROUND,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS,
            hover: crate::palette::primary_hover(Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS),
            pressed: crate::palette::action_pressed(Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS),
            muted: Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::PORTS_ICON_RUNNING_PROCESS_FOREGROUND,
            warning: Self::TOKEN_FUNCTION_DECLARATIONS,
            error: Self::TOKEN_9,
            critical: Self::TOKEN_9,
            info: Self::ACTIVITY_BAR_BADGE_BACKGROUND,
            trace: Self::INPUT_PLACEHOLDER_FOREGROUND,
        },
        border: Self::MENU_BORDER,
        border_muted: Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND,
        focus: primary,
    }
}
