//! VS Code Light+. See `REGISTRATION` for pinned upstream sources.
//!
//! The Plus theme is merged over its included VS theme. Source menu and tabs supply surfaces, token colours supply named accents, and no Modern theme is substituted.

define_palette! {
    LightPlus, "VS Code Light+",
    identity("vscode/light_plus", "vscode", "VS Code", "light_plus", "Light+", Light, None);
    support(Light);
    sources: super::SOURCE_LIGHT_PLUS;
    colors {
        CHECKBOX_BORDER = crate::color::Color::hex(0x919191),
        EDITOR_BACKGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_FOREGROUND = crate::color::Color::hex(0x000000),
        EDITOR_GROUP_HEADER_TABS_BACKGROUND = crate::color::Color::hex(0xe8e8e8),
        EDITOR_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0xe5ebf1),
        EDITOR_INDENT_GUIDE_BACKGROUND_1 = crate::color::Color::hex(0xd3d3d3),
        EDITOR_INDENT_GUIDE_ACTIVE_BACKGROUND_1 = crate::color::Color::hex(0x939393),
        EDITOR_SELECTION_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xadd6ff80),
        EDITOR_SUGGEST_WIDGET_BACKGROUND = crate::color::Color::hex(0xf3f3f3),
        ACTIVITY_BAR_BADGE_BACKGROUND = crate::color::Color::hex(0x007acc),
        BROWSER_BORDER = crate::color::Color::hex_alpha(0x00000000),
        SIDE_BAR_TITLE_FOREGROUND = crate::color::Color::hex(0x6f6f6f),
        LIST_HOVER_BACKGROUND = crate::color::Color::hex(0xe8e8e8),
        MENU_BORDER = crate::color::Color::hex(0xd4d4d4),
        INPUT_PLACEHOLDER_FOREGROUND = crate::color::Color::hex(0x767676),
        SEARCH_EDITOR_TEXT_INPUT_BORDER = crate::color::Color::hex(0xcecece),
        SETTINGS_TEXT_INPUT_BORDER = crate::color::Color::hex(0xcecece),
        SETTINGS_NUMBER_INPUT_BORDER = crate::color::Color::hex(0xcecece),
        STATUS_BAR_ITEM_REMOTE_FOREGROUND = crate::color::Color::hex(0xffffff),
        STATUS_BAR_ITEM_REMOTE_BACKGROUND = crate::color::Color::hex(0x16825d),
        STATUS_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x1476b8),
        PORTS_ICON_RUNNING_PROCESS_FOREGROUND = crate::color::Color::hex(0x369432),
        SIDE_BAR_SECTION_HEADER_BACKGROUND = crate::color::Color::hex_alpha(0x00000000),
        SIDE_BAR_SECTION_HEADER_BORDER = crate::color::Color::hex_alpha(0x61616130),
        TAB_SELECTED_FOREGROUND = crate::color::Color::hex(0x333333),
        TAB_INACTIVE_BACKGROUND = crate::color::Color::hex(0xe8e8e8),
        TAB_INACTIVE_FOREGROUND = crate::color::Color::hex(0x616161),
        TAB_SELECTED_BACKGROUND = crate::color::Color::hex(0xe4e6f1),
        TAB_LAST_PINNED_BORDER = crate::color::Color::hex_alpha(0x61616130),
        NOTEBOOK_CELL_BORDER_COLOR = crate::color::Color::hex(0xe8e8e8),
        NOTEBOOK_SELECTED_CELL_BACKGROUND = crate::color::Color::hex_alpha(0xc8ddf150),
        STATUS_BAR_ITEM_ERROR_BACKGROUND = crate::color::Color::hex(0xc72e0f),
        LIST_ACTIVE_SELECTION_ICON_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_FOCUS_AND_SELECTION_OUTLINE = crate::color::Color::hex(0x90c2f9),
        TERMINAL_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0xe5ebf1),
        WIDGET_BORDER = crate::color::Color::hex(0xd4d4d4),
        ACTION_BAR_TOGGLED_BACKGROUND = crate::color::Color::hex(0xdddddd),
        DIFF_EDITOR_UNCHANGED_REGION_BACKGROUND = crate::color::Color::hex(0xf8f8f8),
        AGENTS_NEW_SESSION_BUTTON_BORDER = crate::color::Color::hex(0xd8d8d8),
        AGENTS_CHAT_INPUT_BORDER = crate::color::Color::hex(0xd8d8d8),
        AGENTS_PANEL_BORDER = crate::color::Color::hex_alpha(0x00000000),
        SURFACE_BORDER = crate::color::Color::hex(0xf3f3f3),
        MODERN_ACTIVITY_BAR_ITEM_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0xe4e6f122),
        MODERN_ACTIVITY_BAR_ITEM_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0xe8e8e822),
        MODERN_ACTIVITY_BAR_ITEM_ACTIVE_FOREGROUND = crate::color::Color::hex(0xffffff),
        MODERN_ACTIVITY_BAR_ITEM_HOVER_FOREGROUND = crate::color::Color::hex(0xffffff),
        MODERN_ACTIVITY_BAR_BORDER = crate::color::Color::hex(0x2c2c2c),
        TITLE_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0xe5e5e5),
        TOKEN_0 = crate::color::Color::hex_alpha(0x000000ff),
        TOKEN_3 = crate::color::Color::hex(0x000080),
        TOKEN_4 = crate::color::Color::hex(0x008000),
        TOKEN_5 = crate::color::Color::hex(0x0000ff),
        TOKEN_6 = crate::color::Color::hex(0x098658),
        TOKEN_7 = crate::color::Color::hex(0x811f3f),
        TOKEN_CSS_TAGS_IN_SELECTORS_XML_TAGS = crate::color::Color::hex(0x800000),
        TOKEN_9 = crate::color::Color::hex(0x811f3f),
        TOKEN_10 = crate::color::Color::hex(0x000000),
        TOKEN_11 = crate::color::Color::hex(0xee0000),
        TOKEN_12 = crate::color::Color::hex(0x0000ff),
        TOKEN_14 = crate::color::Color::hex(0x000000),
        TOKEN_15 = crate::color::Color::hex(0x800000),
        TOKEN_16 = crate::color::Color::hex(0x800080),
        TOKEN_18 = crate::color::Color::hex(0x098658),
        TOKEN_19 = crate::color::Color::hex(0xa31515),
        TOKEN_20 = crate::color::Color::hex(0x0451a5),
        TOKEN_21 = crate::color::Color::hex(0x0451a5),
        TOKEN_22 = crate::color::Color::hex(0x800000),
        TOKEN_BRACKETS_OF_XML_HTML_TAGS = crate::color::Color::hex(0x800000),
        TOKEN_24 = crate::color::Color::hex(0x0000ff),
        TOKEN_25 = crate::color::Color::hex(0xa31515),
        TOKEN_26 = crate::color::Color::hex(0x098658),
        TOKEN_27 = crate::color::Color::hex(0x0451a5),
        TOKEN_28 = crate::color::Color::hex(0x0000ff),
        TOKEN_29 = crate::color::Color::hex(0x0000ff),
        TOKEN_30 = crate::color::Color::hex(0x0000ff),
        TOKEN_31 = crate::color::Color::hex(0xa31515),
        TOKEN_32 = crate::color::Color::hex(0x0000ff),
        TOKEN_33 = crate::color::Color::hex(0x811f3f),
        TOKEN_STRING_INTERPOLATION = crate::color::Color::hex(0x0000ff),
        TOKEN_RESET_JAVA_SCRIPT_STRING_INTERPOLATION_EXPRESSION = crate::color::Color::hex(0x000000),
        TOKEN_36 = crate::color::Color::hex(0x0451a5),
        TOKEN_37 = crate::color::Color::hex(0xe50000),
        TOKEN_38 = crate::color::Color::hex(0x0451a5),
        TOKEN_39 = crate::color::Color::hex(0x0000ff),
        TOKEN_40 = crate::color::Color::hex(0x0000ff),
        TOKEN_41 = crate::color::Color::hex(0x000000),
        TOKEN_42 = crate::color::Color::hex(0x0000ff),
        TOKEN_43 = crate::color::Color::hex(0x098658),
        TOKEN_44 = crate::color::Color::hex(0x800000),
        TOKEN_45 = crate::color::Color::hex(0x0451a5),
        TOKEN_46 = crate::color::Color::hex(0x098658),
        TOKEN_COLORING_OF_THE_JAVA_IMPORT_AND_PACKAGE_IDENTIFIERS = crate::color::Color::hex(0x000000),
        TOKEN_THIS_SELF = crate::color::Color::hex(0x0000ff),
        TOKEN_FUNCTION_DECLARATIONS = crate::color::Color::hex(0x795e26),
        TOKEN_TYPES_DECLARATION_AND_REFERENCES = crate::color::Color::hex(0x267f99),
        TOKEN_TYPES_DECLARATION_AND_REFERENCES_TS_GRAMMAR_SPECIFIC = crate::color::Color::hex(0x267f99),
        TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS = crate::color::Color::hex(0xaf00db),
        TOKEN_VARIABLE_AND_PARAMETER_NAME = crate::color::Color::hex(0x001080),
        TOKEN_CONSTANTS_AND_ENUMS = crate::color::Color::hex(0x0070c1),
        TOKEN_OBJECT_KEYS_TS_GRAMMAR_SPECIFIC = crate::color::Color::hex(0x001080),
        TOKEN_CSS_PROPERTY_VALUE = crate::color::Color::hex(0x0451a5),
        TOKEN_REGULAR_EXPRESSION_GROUPS = crate::color::Color::hex(0xd16969),
        TOKEN_13 = crate::color::Color::hex(0xee0000),
    }
    accents {
        Blue = ACTIVITY_BAR_BADGE_BACKGROUND => ("blue", "Blue"),
        Purple = TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS => ("purple", "Purple"),
        Cyan = TOKEN_TYPES_DECLARATION_AND_REFERENCES => ("cyan", "Cyan"),
        Function = TOKEN_FUNCTION_DECLARATIONS => ("function", "Function"),
        Variable = TOKEN_VARIABLE_AND_PARAMETER_NAME => ("variable", "Variable"),
    }
    default ACTIVITY_BAR_BADGE_BACKGROUND => "blue";
    roles(primary) {
        surfaces: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BACKGROUND,
            base: Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND,
            raised: Self::EDITOR_SUGGEST_WIDGET_BACKGROUND,
            overlay: Self::EDITOR_SUGGEST_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        surfaces_alt: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_SUGGEST_WIDGET_BACKGROUND,
            base: Self::EDITOR_BACKGROUND,
            raised: Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND,
            overlay: Self::EDITOR_SUGGEST_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::EDITOR_FOREGROUND,
            muted: Self::SIDE_BAR_TITLE_FOREGROUND,
            subtle: Self::INPUT_PLACEHOLDER_FOREGROUND,
        },
        text_alt: None,
        primary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), primary),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::primary_hover(primary)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::action_pressed(primary)),
            muted: crate::theme_variant::ColorPair::new(Self::EDITOR_FOREGROUND, Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND),
            disabled: crate::theme_variant::ColorPair::new(Self::INPUT_PLACEHOLDER_FOREGROUND, Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND),
        },
        secondary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS), Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS), crate::palette::primary_hover(Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS), crate::palette::action_pressed(Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS)),
            muted: crate::theme_variant::ColorPair::new(Self::EDITOR_FOREGROUND, Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND),
            disabled: crate::theme_variant::ColorPair::new(Self::INPUT_PLACEHOLDER_FOREGROUND, Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND),
        },
        status: crate::theme_variant::StatusColors {
            success: Self::PORTS_ICON_RUNNING_PROCESS_FOREGROUND,
            warning: Self::TOKEN_FUNCTION_DECLARATIONS,
            error: Self::TOKEN_11,
            critical: Self::TOKEN_11,
            info: Self::ACTIVITY_BAR_BADGE_BACKGROUND,
            debug: Self::SIDE_BAR_TITLE_FOREGROUND,
            trace: Self::INPUT_PLACEHOLDER_FOREGROUND,
        },
        border: Self::MENU_BORDER,
        border_muted: Self::EDITOR_GROUP_HEADER_TABS_BACKGROUND,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::TOKEN_11,
            orange: Self::TOKEN_FUNCTION_DECLARATIONS,
            yellow: Self::TOKEN_FUNCTION_DECLARATIONS,
            green: Self::TOKEN_4,
            cyan: Self::TOKEN_TYPES_DECLARATION_AND_REFERENCES,
            blue: Self::ACTIVITY_BAR_BADGE_BACKGROUND,
            purple: Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS,
            pink: Self::TOKEN_7,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::TOKEN_10,
            boolean: Self::TOKEN_5,
            builtin: Self::TOKEN_FUNCTION_DECLARATIONS,
            builtin_function: Self::TOKEN_FUNCTION_DECLARATIONS,
            builtin_type: Self::TOKEN_TYPES_DECLARATION_AND_REFERENCES,
            comment: Self::TOKEN_4,
            constant: Self::TOKEN_FUNCTION_DECLARATIONS,
            control_keyword: Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS,
            deleted: Self::TOKEN_19,
            deprecated: Self::TOKEN_12,
            documentation: Self::TOKEN_4,
            escape: Self::TOKEN_13,
            foreground: Self::EDITOR_FOREGROUND,
            function: Self::TOKEN_FUNCTION_DECLARATIONS,
            heading: Self::TOKEN_15,
            inserted: Self::TOKEN_18,
            invalid: Self::TOKEN_12,
            keyword: Self::TOKEN_39,
            link: Self::TOKEN_CONTROL_FLOW_SPECIAL_KEYWORDS,
            macro_name: Self::TOKEN_FUNCTION_DECLARATIONS,
            markup_bold: Self::TOKEN_14,
            markup_italic: Self::TOKEN_16,
            modifier: Self::TOKEN_30,
            namespace: Self::TOKEN_TYPES_DECLARATION_AND_REFERENCES,
            number: Self::TOKEN_6,
            operator: Self::TOKEN_41,
            parameter: Self::TOKEN_VARIABLE_AND_PARAMETER_NAME,
            property: Self::TOKEN_VARIABLE_AND_PARAMETER_NAME,
            punctuation: Self::EDITOR_FOREGROUND,
            string: Self::TOKEN_31,
            tag: Self::TOKEN_CSS_TAGS_IN_SELECTORS_XML_TAGS,
            type_keyword: Self::TOKEN_29,
            type_name: Self::TOKEN_TYPES_DECLARATION_AND_REFERENCES,
            variable: Self::TOKEN_VARIABLE_AND_PARAMETER_NAME,
        },
    }
}
