//! Shared by the build script and generator; no renderer or palette dependency.

use std::fmt::Write;

/// Render the complete, palette-independent default stylesheet.

pub fn render() -> String {

    let mut out = String::from(
        "/* Generated by ferriswatch-generate-css. Edit src/css/definitions.rs instead. */\n@layer ferriswatch {\n",
    );

    let mut rule = |selectors: &str, property: &str, value: &str| {

        writeln!(out, "  {selectors} {{ {property}: {value}; }}").unwrap();
    };

    for (role, convenience) in [
        ("background", ", :where(.fs-page)"),
        ("surface", ", :where(.fs-panel, .fs-card)"),
        ("raised", ", :where(.fs-popover)"),
        ("overlay", ""),
        ("hover", ""),
        ("alt-background", ""),
        ("alt-surface", ""),
        ("alt-raised", ""),
        ("alt-overlay", ""),
        ("alt-hover", ""),
    ] {

        rule(
            &format!(".fs-bg-{role}{convenience}"),
            "background-color",
            &format!("var(--fs-{role})"),
        );
    }

    for (selectors, role) in [
        (
            ".fs-text, :where(.fs-page, .fs-panel, .fs-card, .fs-popover)",
            "text",
        ),
        (".fs-text-muted", "muted"),
        (".fs-text-subtle", "subtle"),
    ] {

        rule(selectors, "color", &format!("var(--fs-{role})"));
    }

    for role in ["primary", "secondary"] {

        rule(
            &format!(".fs-{role}"),
            "background-color",
            &format!("var(--fs-{role})"),
        );

        rule(
            &format!(".fs-{role}"),
            "color",
            &format!("var(--fs-on-{role})"),
        );

        for (state, value) in [("hover", "hover"), ("active", "pressed")] {

            rule(
                &format!(".fs-{role}:{state}:not(:disabled, [aria-disabled=\"true\" i])"),
                "background-color",
                &format!("var(--fs-{role}-{value})"),
            );
        }
    }

    rule(
        ".fs-border, :where(.fs-popover)",
        "border-color",
        "var(--fs-border)",
    );

    rule(
        ".fs-border-muted, :where(.fs-card)",
        "border-color",
        "var(--fs-border-muted)",
    );

    for role in [
        "success", "warning", "error", "critical", "info", "debug", "trace",
    ] {

        rule(
            &format!(".fs-{role}"),
            "color",
            &format!("var(--fs-{role})"),
        );
    }

    rule(
        ".fs-focus:focus-visible",
        "outline",
        "2px solid var(--fs-focus)",
    );

    rule(".fs-focus:focus-visible", "outline-offset", "2px");

    out.push_str("}\n");

    out
}
