//! Monokai. See `REGISTRATION` for pinned upstream sources.
//!
//! VS Code’s bundled original-Monokai-based theme, not Monokai Pro. Bright terminal colours preserve the familiar accent palette. Editor and sidebar keys supply surfaces.

define_palette! {
    Main, "Monokai",
    identity("monokai/main", "monokai", "Monokai", "main", "Main", Dark, None);
    support(Dark);
    sources: super::SOURCE;
    colors {
        DROPDOWN_BACKGROUND = crate::color::Color::hex(0x414339),
        LIST_ACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0x75715e),
        QUICK_INPUT_LIST_FOCUS_BACKGROUND = crate::color::Color::hex(0x414339),
        DROPDOWN_LIST_BACKGROUND = crate::color::Color::hex(0x1e1f1c),
        LIST_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0x414339),
        LIST_HOVER_BACKGROUND = crate::color::Color::hex(0x3e3d32),
        LIST_DROP_BACKGROUND = crate::color::Color::hex(0x414339),
        LIST_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xf8f8f2),
        BUTTON_BACKGROUND = crate::color::Color::hex(0x75715e),
        EDITOR_BACKGROUND = crate::color::Color::hex(0x272822),
        EDITOR_FOREGROUND = crate::color::Color::hex(0xf8f8f2),
        SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x878b9180),
        EDITOR_SELECTION_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x575b6180),
        EDITOR_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x878b9180),
        MINIMAP_SELECTION_HIGHLIGHT = crate::color::Color::hex_alpha(0x878b9180),
        EDITOR_WORD_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x4a4a7680),
        EDITOR_WORD_HIGHLIGHT_STRONG_BACKGROUND = crate::color::Color::hex_alpha(0x6a6a9680),
        EDITOR_LINE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x3e3d32),
        EDITOR_LINE_NUMBER_ACTIVE_FOREGROUND = crate::color::Color::hex(0xc2c2bf),
        EDITOR_CURSOR_FOREGROUND = crate::color::Color::hex(0xf8f8f0),
        EDITOR_WHITESPACE_FOREGROUND = crate::color::Color::hex(0x464741),
        EDITOR_INDENT_GUIDE_BACKGROUND = crate::color::Color::hex(0x464741),
        EDITOR_INDENT_GUIDE_ACTIVE_BACKGROUND = crate::color::Color::hex(0x767771),
        EDITOR_GROUP_HEADER_TABS_BACKGROUND = crate::color::Color::hex(0x1e1f1c),
        EDITOR_GROUP_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x41433980),
        TAB_INACTIVE_BACKGROUND = crate::color::Color::hex(0x34352f),
        TAB_BORDER = crate::color::Color::hex(0x1e1f1c),
        TAB_INACTIVE_FOREGROUND = crate::color::Color::hex(0xccccc7),
        TAB_LAST_PINNED_BORDER = crate::color::Color::hex(0x414339),
        WIDGET_SHADOW = crate::color::Color::hex_alpha(0x00000098),
        PROGRESS_BAR_BACKGROUND = crate::color::Color::hex(0x75715e),
        BADGE_BACKGROUND = crate::color::Color::hex(0x75715e),
        BADGE_FOREGROUND = crate::color::Color::hex(0xf8f8f2),
        EDITOR_LINE_NUMBER_FOREGROUND = crate::color::Color::hex(0x90908a),
        PANEL_TITLE_ACTIVE_FOREGROUND = crate::color::Color::hex(0xf8f8f2),
        PANEL_TITLE_ACTIVE_BORDER = crate::color::Color::hex(0x75715e),
        PANEL_TITLE_INACTIVE_FOREGROUND = crate::color::Color::hex(0x75715e),
        PANEL_BORDER = crate::color::Color::hex(0x414339),
        PANEL_SECTION_BORDER = crate::color::Color::hex(0x414339),
        PANEL_SECTION_HEADER_BORDER = crate::color::Color::hex(0x414339),
        SETTINGS_FOCUSED_ROW_BACKGROUND = crate::color::Color::hex_alpha(0x4143395a),
        TITLE_BAR_ACTIVE_BACKGROUND = crate::color::Color::hex(0x1e1f1c),
        TITLE_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x202120),
        STATUS_BAR_BACKGROUND = crate::color::Color::hex(0x414339),
        STATUS_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x202120),
        STATUS_BAR_NO_FOLDER_BACKGROUND = crate::color::Color::hex(0x414339),
        STATUS_BAR_DEBUGGING_BACKGROUND = crate::color::Color::hex(0x75715e),
        STATUS_BAR_ITEM_REMOTE_BACKGROUND = crate::color::Color::hex(0xac6218),
        PORTS_ICON_RUNNING_PROCESS_FOREGROUND = crate::color::Color::hex(0xccccc7),
        ACTIVITY_BAR_BACKGROUND = crate::color::Color::hex(0x272822),
        ACTIVITY_BAR_FOREGROUND = crate::color::Color::hex(0xf8f8f2),
        SIDE_BAR_BACKGROUND = crate::color::Color::hex(0x1e1f1c),
        SIDE_BAR_SECTION_HEADER_BACKGROUND = crate::color::Color::hex(0x272822),
        SIDE_BAR_SECTION_HEADER_BORDER = crate::color::Color::hex(0x414339),
        MENU_BACKGROUND = crate::color::Color::hex(0x1e1f1c),
        MENU_FOREGROUND = crate::color::Color::hex(0xcccccc),
        PICKER_GROUP_FOREGROUND = crate::color::Color::hex(0x75715e),
        INPUT_BACKGROUND = crate::color::Color::hex(0x414339),
        INPUT_OPTION_ACTIVE_BORDER = crate::color::Color::hex(0x75715e),
        FOCUS_BORDER = crate::color::Color::hex(0x99947c),
        AGENTS_PANEL_BORDER = crate::color::Color::hex_alpha(0x00000000),
        AGENTS_CHAT_INPUT_BORDER = crate::color::Color::hex(0x414339),
        AGENTS_CHAT_INPUT_FOCUS_BORDER = crate::color::Color::hex(0x99947c),
        AGENTS_NEW_SESSION_BUTTON_BORDER = crate::color::Color::hex(0x414339),
        EDITOR_WIDGET_BACKGROUND = crate::color::Color::hex(0x1e1f1c),
        DEBUG_TOOL_BAR_BACKGROUND = crate::color::Color::hex(0x1e1f1c),
        DIFF_EDITOR_INSERTED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0x4b661680),
        DIFF_EDITOR_REMOVED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0x90274a70),
        INPUT_VALIDATION_ERROR_BACKGROUND = crate::color::Color::hex(0x90274a),
        INPUT_VALIDATION_ERROR_BORDER = crate::color::Color::hex(0xf92672),
        INPUT_VALIDATION_WARNING_BACKGROUND = crate::color::Color::hex(0x848528),
        INPUT_VALIDATION_WARNING_BORDER = crate::color::Color::hex(0xe2e22e),
        INPUT_VALIDATION_INFO_BACKGROUND = crate::color::Color::hex(0x546190),
        INPUT_VALIDATION_INFO_BORDER = crate::color::Color::hex(0x819aff),
        EDITOR_HOVER_WIDGET_BACKGROUND = crate::color::Color::hex(0x414339),
        EDITOR_HOVER_WIDGET_BORDER = crate::color::Color::hex(0x75715e),
        EDITOR_SUGGEST_WIDGET_BACKGROUND = crate::color::Color::hex(0x272822),
        EDITOR_SUGGEST_WIDGET_BORDER = crate::color::Color::hex(0x75715e),
        EDITOR_GROUP_BORDER = crate::color::Color::hex(0x34352f),
        PEEK_VIEW_BORDER = crate::color::Color::hex(0x75715e),
        PEEK_VIEW_EDITOR_BACKGROUND = crate::color::Color::hex(0x272822),
        PEEK_VIEW_RESULT_BACKGROUND = crate::color::Color::hex(0x1e1f1c),
        PEEK_VIEW_TITLE_BACKGROUND = crate::color::Color::hex(0x1e1f1c),
        PEEK_VIEW_RESULT_SELECTION_BACKGROUND = crate::color::Color::hex(0x414339),
        PEEK_VIEW_RESULT_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x75715e),
        PEEK_VIEW_EDITOR_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x75715e),
        TERMINAL_ANSI_BLACK = crate::color::Color::hex(0x333333),
        TERMINAL_ANSI_RED = crate::color::Color::hex(0xc4265e),
        TERMINAL_ANSI_GREEN = crate::color::Color::hex(0x86b42b),
        TERMINAL_ANSI_YELLOW = crate::color::Color::hex(0xb3b42b),
        TERMINAL_ANSI_BLUE = crate::color::Color::hex(0x6a7ec8),
        TERMINAL_ANSI_MAGENTA = crate::color::Color::hex(0x8c6bc8),
        TERMINAL_ANSI_CYAN = crate::color::Color::hex(0x56adbc),
        TERMINAL_ANSI_WHITE = crate::color::Color::hex(0xe3e3dd),
        TERMINAL_ANSI_BRIGHT_BLACK = crate::color::Color::hex(0x666666),
        TERMINAL_ANSI_BRIGHT_RED = crate::color::Color::hex(0xf92672),
        TERMINAL_ANSI_BRIGHT_GREEN = crate::color::Color::hex(0xa6e22e),
        TERMINAL_ANSI_BRIGHT_YELLOW = crate::color::Color::hex(0xe2e22e),
        TERMINAL_ANSI_BRIGHT_BLUE = crate::color::Color::hex(0x819aff),
        TERMINAL_ANSI_BRIGHT_MAGENTA = crate::color::Color::hex(0xae81ff),
        TERMINAL_ANSI_BRIGHT_CYAN = crate::color::Color::hex(0x66d9ef),
        TERMINAL_ANSI_BRIGHT_WHITE = crate::color::Color::hex(0xf8f8f2),
        SURFACE_BORDER = crate::color::Color::hex(0x272822),
        TOKEN_0 = crate::color::Color::hex(0xf8f8f2),
        TOKEN_1 = crate::color::Color::hex(0xf8f8f2),
        TOKEN_COMMENT = crate::color::Color::hex(0x88846f),
        TOKEN_STRING = crate::color::Color::hex(0xe6db74),
        TOKEN_TEMPLATE_DEFINITION = crate::color::Color::hex(0xf92672),
        TOKEN_RESET_JAVA_SCRIPT_STRING_INTERPOLATION_EXPRESSION = crate::color::Color::hex(0xf8f8f2),
        TOKEN_NUMBER = crate::color::Color::hex(0xae81ff),
        TOKEN_BUILT_IN_CONSTANT = crate::color::Color::hex(0xae81ff),
        TOKEN_USER_DEFINED_CONSTANT = crate::color::Color::hex(0xae81ff),
        TOKEN_VARIABLE = crate::color::Color::hex(0xf8f8f2),
        TOKEN_KEYWORD = crate::color::Color::hex(0xf92672),
        TOKEN_STORAGE = crate::color::Color::hex(0xf92672),
        TOKEN_STORAGE_TYPE = crate::color::Color::hex(0x66d9ef),
        TOKEN_CLASS_NAME = crate::color::Color::hex(0xa6e22e),
        TOKEN_INHERITED_CLASS = crate::color::Color::hex(0xa6e22e),
        TOKEN_FUNCTION_NAME = crate::color::Color::hex(0xa6e22e),
        TOKEN_FUNCTION_ARGUMENT = crate::color::Color::hex(0xfd971f),
        TOKEN_TAG_NAME = crate::color::Color::hex(0xf92672),
        TOKEN_TAG_ATTRIBUTE = crate::color::Color::hex(0xa6e22e),
        TOKEN_LIBRARY_FUNCTION = crate::color::Color::hex(0x66d9ef),
        TOKEN_LIBRARY_CONSTANT = crate::color::Color::hex(0x66d9ef),
        TOKEN_LIBRARY_CLASS_TYPE = crate::color::Color::hex(0x66d9ef),
        TOKEN_INVALID = crate::color::Color::hex(0xf44747),
        TOKEN_INVALID_DEPRECATED = crate::color::Color::hex(0xf44747),
        TOKEN_JSON_STRING = crate::color::Color::hex(0xcfcfc2),
        TOKEN_DIFF_HEADER = crate::color::Color::hex(0x75715e),
        TOKEN_DIFF_DELETED = crate::color::Color::hex(0xf92672),
        TOKEN_DIFF_INSERTED = crate::color::Color::hex(0xa6e22e),
        TOKEN_DIFF_CHANGED = crate::color::Color::hex(0xe6db74),
        TOKEN_30 = crate::color::Color::hex_alpha(0xae81ffa0),
        TOKEN_31 = crate::color::Color::hex(0xe6db74),
        TOKEN_MARKUP_QUOTE = crate::color::Color::hex(0xf92672),
        TOKEN_MARKUP_LISTS = crate::color::Color::hex(0xe6db74),
        TOKEN_MARKUP_STYLING = crate::color::Color::hex(0x66d9ef),
        TOKEN_MARKUP_INLINE = crate::color::Color::hex(0xfd971f),
        TOKEN_MARKUP_HEADINGS = crate::color::Color::hex(0xa6e22e),
        TOKEN_MARKUP_SETEXT_HEADER = crate::color::Color::hex(0xa6e22e),
        TOKEN_MARKDOWN_QUOTE = crate::color::Color::hex(0x75715e),
        TOKEN_MARKDOWN_LINK_TITLE_DESCRIPTION = crate::color::Color::hex(0xae81ff),
        TOKEN_MARKDOWN_UNDERLINE_LINK_IMAGE = crate::color::Color::hex(0xe6db74),
        TOKEN_MARKDOWN_PUNCTUATION_DEFINITION_LINK = crate::color::Color::hex(0xf8f8f2),
        TOKEN_MARKDOWN_LIST_PUNCTUATION = crate::color::Color::hex(0xa6e22e),
        TOKEN_47 = crate::color::Color::hex(0x6796e6),
        TOKEN_48 = crate::color::Color::hex(0xcd9731),
        TOKEN_49 = crate::color::Color::hex(0xf44747),
        TOKEN_50 = crate::color::Color::hex(0xb267e6),
        TOKEN_THIS_SELF = crate::color::Color::hex(0xfd971f),
    }
    accents {
        Red = TERMINAL_ANSI_BRIGHT_RED => ("red", "Red"),
        Green = TERMINAL_ANSI_BRIGHT_GREEN => ("green", "Green"),
        Yellow = TERMINAL_ANSI_BRIGHT_YELLOW => ("yellow", "Yellow"),
        Blue = TERMINAL_ANSI_BRIGHT_BLUE => ("blue", "Blue"),
        Magenta = TERMINAL_ANSI_BRIGHT_MAGENTA => ("magenta", "Magenta"),
        Cyan = TERMINAL_ANSI_BRIGHT_CYAN => ("cyan", "Cyan"),
    }
    default TERMINAL_ANSI_BRIGHT_GREEN => "green";
    roles(primary) {
        surfaces: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BACKGROUND,
            base: Self::SIDE_BAR_BACKGROUND,
            raised: Self::DROPDOWN_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        surfaces_alt: crate::theme_variant::SurfaceColors {
            background: Self::SIDE_BAR_BACKGROUND,
            base: Self::EDITOR_BACKGROUND,
            raised: Self::SIDE_BAR_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::EDITOR_FOREGROUND,
            muted: Self::EDITOR_FOREGROUND,
            subtle: Self::EDITOR_LINE_NUMBER_FOREGROUND,
        },
        text_alt: None,
primary: crate::theme_variant::ActionColors {
    normal: crate::theme_variant::ColorPair::new(
        Self::BADGE_FOREGROUND,
        Self::BUTTON_BACKGROUND,
    ),
    // Monokai doesn't author separate button hover/pressed colours.
    hover: crate::theme_variant::ColorPair::new(
        Self::BADGE_FOREGROUND,
        Self::BUTTON_BACKGROUND,
    ),
    pressed: crate::theme_variant::ColorPair::new(
        Self::BADGE_FOREGROUND,
        Self::BUTTON_BACKGROUND,
    ),
    muted: crate::theme_variant::ColorPair::new(
        Self::EDITOR_FOREGROUND,
        Self::SIDE_BAR_BACKGROUND,
    ),
    disabled: crate::theme_variant::ColorPair::new(
        Self::EDITOR_LINE_NUMBER_FOREGROUND,
        Self::SIDE_BAR_BACKGROUND,
    ),
},
secondary: crate::theme_variant::ActionColors {
    normal: crate::theme_variant::ColorPair::new(
        crate::palette::action_text(
            Self::TERMINAL_ANSI_BRIGHT_MAGENTA,
            Self::EDITOR_BACKGROUND,
            Self::EDITOR_FOREGROUND,
        ),
        Self::TERMINAL_ANSI_BRIGHT_MAGENTA,
    ),
    hover: crate::theme_variant::ColorPair::new(
        crate::palette::action_text(
            Self::TERMINAL_ANSI_BRIGHT_MAGENTA,
            Self::EDITOR_BACKGROUND,
            Self::EDITOR_FOREGROUND,
        ),
        crate::palette::primary_hover(Self::TERMINAL_ANSI_BRIGHT_MAGENTA),
    ),
    pressed: crate::theme_variant::ColorPair::new(
        crate::palette::action_text(
            Self::TERMINAL_ANSI_BRIGHT_MAGENTA,
            Self::EDITOR_BACKGROUND,
            Self::EDITOR_FOREGROUND,
        ),
        crate::palette::action_pressed(Self::TERMINAL_ANSI_BRIGHT_MAGENTA),
    ),
    muted: crate::theme_variant::ColorPair::new(
        Self::EDITOR_FOREGROUND,
        Self::SIDE_BAR_BACKGROUND,
    ),
    disabled: crate::theme_variant::ColorPair::new(
        Self::EDITOR_LINE_NUMBER_FOREGROUND,
        Self::SIDE_BAR_BACKGROUND,
    ),
},
        status: crate::theme_variant::StatusColors {
    success: Self::TERMINAL_ANSI_BRIGHT_GREEN,
    warning: Self::TOKEN_48,
    error: Self::TOKEN_49,
    critical: Self::TERMINAL_ANSI_BRIGHT_RED,
    info: Self::TOKEN_47,
    debug: Self::TOKEN_50,
    trace: Self::EDITOR_LINE_NUMBER_FOREGROUND,
},
        border: Self::PANEL_BORDER,
        border_muted: Self::SIDE_BAR_BACKGROUND,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::TOKEN_INVALID,
            orange: Self::TOKEN_FUNCTION_ARGUMENT,
            yellow: Self::TOKEN_STRING,
            green: Self::TERMINAL_ANSI_BRIGHT_GREEN,
            cyan: Self::TERMINAL_ANSI_BRIGHT_CYAN,
            blue: Self::TERMINAL_ANSI_BRIGHT_BLUE,
            purple: Self::TERMINAL_ANSI_BRIGHT_MAGENTA,
            pink: Self::TERMINAL_ANSI_BRIGHT_RED,
        },
        syntax: crate::theme_variant::SyntaxColors {
    attribute: Self::TOKEN_TAG_ATTRIBUTE,
    boolean: Self::TOKEN_BUILT_IN_CONSTANT,
    builtin: Self::TOKEN_LIBRARY_CONSTANT,
    builtin_function: Self::TOKEN_LIBRARY_FUNCTION,
    builtin_type: Self::TOKEN_LIBRARY_CLASS_TYPE,
    comment: Self::TOKEN_COMMENT,
    constant: Self::TOKEN_USER_DEFINED_CONSTANT,
    control_keyword: Self::TOKEN_KEYWORD,
    deleted: Self::TOKEN_DIFF_DELETED,
    deprecated: Self::TOKEN_INVALID_DEPRECATED,
    documentation: Self::TOKEN_COMMENT,
    escape: Self::TOKEN_USER_DEFINED_CONSTANT,
    foreground: Self::EDITOR_FOREGROUND,
    function: Self::TOKEN_FUNCTION_NAME,
    heading: Self::TOKEN_MARKUP_HEADINGS,
    inserted: Self::TOKEN_DIFF_INSERTED,
    invalid: Self::TOKEN_INVALID,
    keyword: Self::TOKEN_KEYWORD,
    link: Self::TOKEN_MARKDOWN_UNDERLINE_LINK_IMAGE,
    macro_name: Self::TOKEN_FUNCTION_NAME,
    markup_bold: Self::TOKEN_MARKUP_STYLING,
    markup_italic: Self::TOKEN_MARKUP_STYLING,
    modifier: Self::TOKEN_STORAGE,
    namespace: Self::TOKEN_CLASS_NAME,
    number: Self::TOKEN_NUMBER,
    operator: Self::TOKEN_KEYWORD,
    parameter: Self::TOKEN_FUNCTION_ARGUMENT,
    property: Self::TOKEN_VARIABLE,
    punctuation: Self::EDITOR_FOREGROUND,
    string: Self::TOKEN_STRING,
    tag: Self::TOKEN_TAG_NAME,
    type_keyword: Self::TOKEN_STORAGE_TYPE,
    type_name: Self::TOKEN_CLASS_NAME,
    variable: Self::TOKEN_VARIABLE,
},
    }
}
