//! Everforest Dark Hard. See the family module for its upstream source.

define_palette! {
    DarkHard, "Everforest Dark Hard",
    identity("everforest/dark/hard", "everforest", "Everforest", "dark", "Dark", Dark, Some(crate::theme_variant::Contrast::Hard));
    support(Dark);
    sources: super::SOURCE;
    colors {
        BG_DIM = crate::color::Color::hex(0x1e2326),
        BG_0 = crate::color::Color::hex(0x272e33),
        BG_1 = crate::color::Color::hex(0x2e383c),
        BG_2 = crate::color::Color::hex(0x374145),
        BG_3 = crate::color::Color::hex(0x414b50),
        BG_4 = crate::color::Color::hex(0x495156),
        BG_5 = crate::color::Color::hex(0x4f5b58),
        BG_VISUAL = crate::color::Color::hex(0x4c3743),
        BG_RED = crate::color::Color::hex(0x493b40),
        BG_YELLOW = crate::color::Color::hex(0x45443c),
        BG_GREEN = crate::color::Color::hex(0x3c4841),
        BG_BLUE = crate::color::Color::hex(0x384b55),
        BG_PURPLE = crate::color::Color::hex(0x463f48),
        FG = crate::color::Color::hex(0xd3c6aa),
        RED = crate::color::Color::hex(0xe67e80),
        ORANGE = crate::color::Color::hex(0xe69875),
        YELLOW = crate::color::Color::hex(0xdbbc7f),
        GREEN = crate::color::Color::hex(0xa7c080),
        AQUA = crate::color::Color::hex(0x83c092),
        BLUE = crate::color::Color::hex(0x7fbbb3),
        PURPLE = crate::color::Color::hex(0xd699b6),
        GREY_0 = crate::color::Color::hex(0x7a8478),
        GREY_1 = crate::color::Color::hex(0x859289),
        GREY_2 = crate::color::Color::hex(0x9da9a0),
        STATUSLINE_1 = crate::color::Color::hex(0xa7c080),
        STATUSLINE_2 = crate::color::Color::hex(0xd3c6aa),
        STATUSLINE_3 = crate::color::Color::hex(0xe67e80),
    }
    accents {
        Red = RED => ("red", "Red"),
        Orange = ORANGE => ("orange", "Orange"),
        Yellow = YELLOW => ("yellow", "Yellow"),
        Green = GREEN => ("green", "Green"),
        Aqua = AQUA => ("aqua", "Aqua"),
        Blue = BLUE => ("blue", "Blue"),
        Purple = PURPLE => ("purple", "Purple"),
    }
    default GREEN => "green";
    roles(primary) {
        surfaces: crate::theme_variant::SurfaceColors {
            background: Self::BG_0,
            base: Self::BG_1,
            raised: Self::BG_2,
            overlay: Self::BG_DIM,
            hover: Self::BG_2,
        },
        surfaces_alt: crate::theme_variant::SurfaceColors {
            background: Self::BG_DIM,
            base: Self::BG_0,
            raised: Self::BG_1,
            overlay: Self::BG_DIM,
            hover: Self::BG_2,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FG,
            muted: Self::GREY_2,
            subtle: Self::GREY_0,
        },
        text_alt: None,
        primary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), primary),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::primary_hover(primary)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(primary), crate::palette::action_pressed(primary)),
            muted: crate::theme_variant::ColorPair::new(Self::FG, Self::BG_2),
            disabled: crate::theme_variant::ColorPair::new(Self::GREY_0, Self::BG_2),
        },
        secondary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::BLUE), Self::BLUE),
            hover: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::BLUE), crate::palette::primary_hover(Self::BLUE)),
            pressed: crate::theme_variant::ColorPair::new(crate::palette::action_text(Self::BLUE), crate::palette::action_pressed(Self::BLUE)),
            muted: crate::theme_variant::ColorPair::new(Self::FG, Self::BG_1),
            disabled: crate::theme_variant::ColorPair::new(Self::GREY_0, Self::BG_1),
        },
        status: crate::theme_variant::StatusColors {
            success: Self::GREEN,
            warning: Self::YELLOW,
            error: Self::RED,
            critical: Self::RED,
            info: Self::BLUE,
            debug: Self::GREY_2,
            trace: Self::GREY_2,
        },
        border: Self::BG_4,
        border_muted: Self::BG_3,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::RED,
            orange: Self::ORANGE,
            yellow: Self::YELLOW,
            green: Self::GREEN,
            cyan: Self::BLUE,
            blue: Self::BLUE,
            purple: Self::PURPLE,
            pink: Self::PURPLE,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::YELLOW,
            boolean: Self::PURPLE,
            builtin: Self::YELLOW,
            builtin_function: Self::BLUE,
            builtin_type: Self::YELLOW,
            comment: Self::GREY_1,
            constant: Self::PURPLE,
            control_keyword: Self::RED,
            deleted: Self::RED,
            deprecated: Self::RED,
            documentation: Self::GREY_1,
            escape: Self::ORANGE,
            foreground: Self::FG,
            function: Self::BLUE,
            heading: Self::BLUE,
            inserted: Self::GREEN,
            invalid: Self::RED,
            keyword: Self::RED,
            link: Self::BLUE,
            macro_name: Self::BLUE,
            markup_bold: Self::FG,
            markup_italic: Self::FG,
            modifier: Self::RED,
            namespace: Self::YELLOW,
            number: Self::PURPLE,
            operator: Self::ORANGE,
            parameter: Self::FG,
            property: Self::FG,
            punctuation: Self::FG,
            string: Self::GREEN,
            tag: Self::RED,
            type_keyword: Self::RED,
            type_name: Self::YELLOW,
            variable: Self::FG,
        },
    }
}
