//! Cobalt2. See `REGISTRATION` for pinned upstream sources.
//!
//! Editor UI keys supply surfaces and source alpha is retained. Terminal accents supply filled actions. Critical uses bright red; trace uses subdued source text. Roles that share an upstream colour intentionally repeat.

define_palette! {
    Main, "Cobalt2",
    identity("cobalt2/main", "cobalt2", "Cobalt2", "main", "Main", Dark, None);
    support(Dark);
    sources: super::SOURCE;
    colors {
        ACTIVITY_BAR_BACKGROUND = crate::color::Color::hex(0x122738),
        ACTIVITY_BAR_BADGE_BACKGROUND = crate::color::Color::hex(0xffc600),
        ACTIVITY_BAR_BADGE_FOREGROUND = crate::color::Color::hex(0x000000),
        ACTIVITY_BAR_BORDER = crate::color::Color::hex(0x0d3a58),
        ACTIVITY_BAR_DROP_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        ACTIVITY_BAR_FOREGROUND = crate::color::Color::hex(0xffffff),
        BADGE_BACKGROUND = crate::color::Color::hex(0xffc600),
        BADGE_FOREGROUND = crate::color::Color::hex(0x000000),
        BUTTON_BACKGROUND = crate::color::Color::hex(0x0088ff),
        BUTTON_FOREGROUND = crate::color::Color::hex(0xffffff),
        BUTTON_HOVER_BACKGROUND = crate::color::Color::hex(0xff9d00),
        CONTRAST_BORDER = crate::color::Color::hex_alpha(0xffffff00),
        DEBUG_CONSOLE_ERROR_FOREGROUND = crate::color::Color::hex(0xff5630),
        DEBUG_EXCEPTION_WIDGET_BACKGROUND = crate::color::Color::hex(0x193549),
        DEBUG_EXCEPTION_WIDGET_BORDER = crate::color::Color::hex(0xaaaaaa),
        DEBUG_TOOL_BAR_BACKGROUND = crate::color::Color::hex(0x193549),
        DESCRIPTION_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        DIFF_EDITOR_INSERTED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0x3ad90033),
        DIFF_EDITOR_INSERTED_TEXT_BORDER = crate::color::Color::hex_alpha(0x00000000),
        DIFF_EDITOR_REMOVED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0xee3a4333),
        DIFF_EDITOR_REMOVED_TEXT_BORDER = crate::color::Color::hex_alpha(0x00000000),
        DROPDOWN_BACKGROUND = crate::color::Color::hex(0x193549),
        DROPDOWN_BORDER = crate::color::Color::hex(0x15232d),
        DROPDOWN_FOREGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_BACKGROUND = crate::color::Color::hex(0x193549),
        EDITOR_BRACKET_HIGHLIGHT_FOREGROUND_1 = crate::color::Color::hex(0xffa500),
        EDITOR_BRACKET_HIGHLIGHT_FOREGROUND_2 = crate::color::Color::hex(0xff69b4),
        EDITOR_BRACKET_HIGHLIGHT_FOREGROUND_3 = crate::color::Color::hex(0x00ff7f),
        EDITOR_BRACKET_HIGHLIGHT_FOREGROUND_4 = crate::color::Color::hex(0x00ffff),
        EDITOR_BRACKET_HIGHLIGHT_FOREGROUND_5 = crate::color::Color::hex(0xffd700),
        EDITOR_BRACKET_HIGHLIGHT_FOREGROUND_6 = crate::color::Color::hex(0xff00ff),
        EDITOR_BRACKET_MATCH_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        EDITOR_BRACKET_MATCH_BORDER = crate::color::Color::hex_alpha(0xffc60080),
        EDITOR_CODE_LENS_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        EDITOR_CURSOR_FOREGROUND = crate::color::Color::hex(0xffc600),
        EDITOR_ERROR_BORDER = crate::color::Color::hex(0x0d3a58),
        EDITOR_ERROR_FOREGROUND = crate::color::Color::hex(0xa22929),
        EDITOR_FIND_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0xff720066),
        EDITOR_FIND_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xcad40f66),
        EDITOR_FIND_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x243e51),
        EDITOR_FOREGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_GROUP_BACKGROUND = crate::color::Color::hex(0xa22929),
        EDITOR_GROUP_BORDER = crate::color::Color::hex(0x122738),
        EDITOR_GROUP_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x12273899),
        EDITOR_GROUP_HEADER_NO_TABS_BACKGROUND = crate::color::Color::hex(0x193549),
        EDITOR_GROUP_HEADER_TABS_BACKGROUND = crate::color::Color::hex(0x122738),
        EDITOR_GROUP_HEADER_TABS_BORDER = crate::color::Color::hex(0x15232d),
        EDITOR_GUTTER_ADDED_BACKGROUND = crate::color::Color::hex(0x3c9f4a),
        EDITOR_GUTTER_BACKGROUND = crate::color::Color::hex_alpha(0x12273866),
        EDITOR_GUTTER_DELETED_BACKGROUND = crate::color::Color::hex(0xa22929),
        EDITOR_GUTTER_MODIFIED_BACKGROUND = crate::color::Color::hex(0xffc600),
        EDITOR_HINT_FOREGROUND = crate::color::Color::hex(0xffc600),
        EDITOR_HOVER_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xffc60033),
        EDITOR_HOVER_WIDGET_BACKGROUND = crate::color::Color::hex(0x15232d),
        EDITOR_HOVER_WIDGET_BORDER = crate::color::Color::hex(0x0d3a58),
        EDITOR_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0x003b8b),
        EDITOR_INDENT_GUIDE_BACKGROUND = crate::color::Color::hex(0x3b5364),
        EDITOR_INLAY_HINT_BACKGROUND = crate::color::Color::hex_alpha(0x0000001a),
        EDITOR_INLAY_HINT_FOREGROUND = crate::color::Color::hex(0xff68b8),
        EDITOR_LINE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x1f4662),
        EDITOR_LINE_HIGHLIGHT_BORDER = crate::color::Color::hex(0x234e6d),
        EDITOR_LINE_NUMBER_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        EDITOR_LINK_ACTIVE_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        EDITOR_MARKER_NAVIGATION_BACKGROUND = crate::color::Color::hex_alpha(0x3b536433),
        EDITOR_MARKER_NAVIGATION_ERROR_BACKGROUND = crate::color::Color::hex(0xa22929),
        EDITOR_MARKER_NAVIGATION_WARNING_BACKGROUND = crate::color::Color::hex(0xffc600),
        EDITOR_OVERVIEW_RULER_BORDER = crate::color::Color::hex(0x0d3a58),
        EDITOR_OVERVIEW_RULER_COMMON_CONTENT_FOREGROUND = crate::color::Color::hex_alpha(0xffc60055),
        EDITOR_OVERVIEW_RULER_CURRENT_CONTENT_FOREGROUND = crate::color::Color::hex_alpha(0xee3a4355),
        EDITOR_OVERVIEW_RULER_INCOMING_CONTENT_FOREGROUND = crate::color::Color::hex_alpha(0x3ad90055),
        EDITOR_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x1f4662),
        EDITOR_RULER_FOREGROUND = crate::color::Color::hex(0x1f4662),
        EDITOR_SELECTION_BACKGROUND = crate::color::Color::hex(0x0050a4),
        EDITOR_SELECTION_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x0050a480),
        EDITOR_SUGGEST_WIDGET_BACKGROUND = crate::color::Color::hex(0x15232d),
        EDITOR_SUGGEST_WIDGET_BORDER = crate::color::Color::hex(0x15232d),
        EDITOR_SUGGEST_WIDGET_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        EDITOR_SUGGEST_WIDGET_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xffc600),
        EDITOR_SUGGEST_WIDGET_SELECTED_BACKGROUND = crate::color::Color::hex(0x193549),
        EDITOR_WARNING_BORDER = crate::color::Color::hex_alpha(0xffffff00),
        EDITOR_WARNING_FOREGROUND = crate::color::Color::hex(0xffc600),
        EDITOR_WHITESPACE_FOREGROUND = crate::color::Color::hex_alpha(0xffffff52),
        EDITOR_WIDGET_BACKGROUND = crate::color::Color::hex(0x15232d),
        EDITOR_WIDGET_BORDER = crate::color::Color::hex(0x0d3a58),
        EDITOR_WORD_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xffffff21),
        EDITOR_WORD_HIGHLIGHT_STRONG_BACKGROUND = crate::color::Color::hex_alpha(0xffffff21),
        ERROR_FOREGROUND = crate::color::Color::hex(0xa22929),
        EXTENSION_BUTTON_PROMINENT_BACKGROUND = crate::color::Color::hex(0x0088ff),
        EXTENSION_BUTTON_PROMINENT_FOREGROUND = crate::color::Color::hex(0xffffff),
        EXTENSION_BUTTON_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0xff9d00),
        FOCUS_BORDER = crate::color::Color::hex(0x0d3a58),
        FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        GIT_DECORATION_CONFLICTING_RESOURCE_FOREGROUND = crate::color::Color::hex(0xff7200),
        GIT_DECORATION_DELETED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xff628c),
        GIT_DECORATION_IGNORED_RESOURCE_FOREGROUND = crate::color::Color::hex(0x808080),
        GIT_DECORATION_MODIFIED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xffc600),
        GIT_DECORATION_UNTRACKED_RESOURCE_FOREGROUND = crate::color::Color::hex(0x3ad900),
        INPUT_BACKGROUND = crate::color::Color::hex(0x193549),
        INPUT_BORDER = crate::color::Color::hex(0x0d3a58),
        INPUT_FOREGROUND = crate::color::Color::hex(0xffc600),
        INPUT_OPTION_ACTIVE_BORDER = crate::color::Color::hex(0x8dffff),
        INPUT_PLACEHOLDER_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        INPUT_VALIDATION_ERROR_BACKGROUND = crate::color::Color::hex(0x193549),
        INPUT_VALIDATION_ERROR_BORDER = crate::color::Color::hex(0xffc600),
        INPUT_VALIDATION_INFO_BACKGROUND = crate::color::Color::hex(0x193549),
        INPUT_VALIDATION_INFO_BORDER = crate::color::Color::hex(0x0d3a58),
        INPUT_VALIDATION_WARNING_BACKGROUND = crate::color::Color::hex(0x193549),
        INPUT_VALIDATION_WARNING_BORDER = crate::color::Color::hex(0xffc600),
        LIST_ACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0x193549),
        LIST_ACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        LIST_DROP_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        LIST_FOCUS_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        LIST_FOCUS_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        LIST_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xffc600),
        LIST_HOVER_BACKGROUND = crate::color::Color::hex(0x193549),
        LIST_HOVER_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        LIST_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        LIST_INACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        MENUBAR_SELECTION_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        MENU_BACKGROUND = crate::color::Color::hex(0x122738),
        MENU_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        MERGE_BORDER = crate::color::Color::hex_alpha(0xffffff00),
        MERGE_COMMON_CONTENT_BACKGROUND = crate::color::Color::hex(0xc97d0c),
        MERGE_COMMON_HEADER_BACKGROUND = crate::color::Color::hex(0xc97d0c),
        MERGE_CURRENT_CONTENT_BACKGROUND = crate::color::Color::hex(0x2f7366),
        MERGE_CURRENT_HEADER_BACKGROUND = crate::color::Color::hex(0x2f7366),
        MERGE_INCOMING_CONTENT_BACKGROUND = crate::color::Color::hex(0x185294),
        MERGE_INCOMING_HEADER_BACKGROUND = crate::color::Color::hex(0x185294),
        NOTIFICATIONS_BACKGROUND = crate::color::Color::hex(0x122738),
        NOTIFICATIONS_BORDER = crate::color::Color::hex(0xffc600),
        NOTIFICATIONS_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        NOTIFICATION_CENTER_BORDER = crate::color::Color::hex(0xffc600),
        NOTIFICATION_CENTER_HEADER_BACKGROUND = crate::color::Color::hex(0x122738),
        NOTIFICATION_CENTER_HEADER_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        NOTIFICATION_LINK_FOREGROUND = crate::color::Color::hex(0xffc600),
        NOTIFICATION_TOAST_BORDER = crate::color::Color::hex(0xffc600),
        PANEL_BACKGROUND = crate::color::Color::hex(0x122738),
        PANEL_BORDER = crate::color::Color::hex(0xffc600),
        PANEL_TITLE_ACTIVE_BORDER = crate::color::Color::hex(0xffc600),
        PANEL_TITLE_ACTIVE_FOREGROUND = crate::color::Color::hex(0xffc600),
        PANEL_TITLE_INACTIVE_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        PEEK_VIEW_BORDER = crate::color::Color::hex(0xffc600),
        PEEK_VIEW_EDITOR_BACKGROUND = crate::color::Color::hex(0x193549),
        PEEK_VIEW_EDITOR_GUTTER_BACKGROUND = crate::color::Color::hex(0x122738),
        PEEK_VIEW_EDITOR_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x19354900),
        PEEK_VIEW_RESULT_BACKGROUND = crate::color::Color::hex(0x15232d),
        PEEK_VIEW_RESULT_FILE_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        PEEK_VIEW_RESULT_LINE_FOREGROUND = crate::color::Color::hex(0xffffff),
        PEEK_VIEW_RESULT_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        PEEK_VIEW_RESULT_SELECTION_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        PEEK_VIEW_RESULT_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        PEEK_VIEW_TITLE_BACKGROUND = crate::color::Color::hex(0x15232d),
        PEEK_VIEW_TITLE_DESCRIPTION_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        PEEK_VIEW_TITLE_LABEL_FOREGROUND = crate::color::Color::hex(0xffc600),
        PICKER_GROUP_BORDER = crate::color::Color::hex(0x0d3a58),
        PICKER_GROUP_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        PROGRESS_BAR_BACKGROUND = crate::color::Color::hex(0xffc600),
        SCROLLBAR_SHADOW = crate::color::Color::hex_alpha(0x00000000),
        SCROLLBAR_SLIDER_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0x355166cc),
        SCROLLBAR_SLIDER_BACKGROUND = crate::color::Color::hex_alpha(0x406179cc),
        SCROLLBAR_SLIDER_HOVER_BACKGROUND = crate::color::Color::hex_alpha(0x437da3cc),
        SELECTION_BACKGROUND = crate::color::Color::hex(0x027dff),
        SEMANTIC_FUNCTION = crate::color::Color::hex(0xffc600),
        SEMANTIC_INTERFACE = crate::color::Color::hex(0xff68b8),
        SEMANTIC_PROPERTY = crate::color::Color::hex(0x9effff),
        SEMANTIC_TYPE = crate::color::Color::hex(0xff68b8),
        SEMANTIC_VARIABLE = crate::color::Color::hex(0xffffff),
        SETTINGS_CHECKBOX_BORDER = crate::color::Color::hex(0xaaaaaa),
        SIDE_BAR_BACKGROUND = crate::color::Color::hex(0x15232d),
        SIDE_BAR_BORDER = crate::color::Color::hex(0x0d3a58),
        SIDE_BAR_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        SIDE_BAR_SECTION_HEADER_BACKGROUND = crate::color::Color::hex(0x193549),
        SIDE_BAR_SECTION_HEADER_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        SIDE_BAR_TITLE_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        STATUS_BAR_BACKGROUND = crate::color::Color::hex(0x15232d),
        STATUS_BAR_BORDER = crate::color::Color::hex(0x0d3a58),
        STATUS_BAR_DEBUGGING_BACKGROUND = crate::color::Color::hex(0x15232d),
        STATUS_BAR_DEBUGGING_BORDER = crate::color::Color::hex(0xffc600),
        STATUS_BAR_DEBUGGING_FOREGROUND = crate::color::Color::hex(0xffc600),
        STATUS_BAR_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        STATUS_BAR_ITEM_ACTIVE_BACKGROUND = crate::color::Color::hex(0x0088ff),
        STATUS_BAR_ITEM_HOVER_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        STATUS_BAR_ITEM_PROMINENT_BACKGROUND = crate::color::Color::hex(0x15232d),
        STATUS_BAR_ITEM_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        STATUS_BAR_ITEM_REMOTE_BACKGROUND = crate::color::Color::hex(0x15232d),
        STATUS_BAR_ITEM_REMOTE_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        STATUS_BAR_NO_FOLDER_BACKGROUND = crate::color::Color::hex(0x15232d),
        STATUS_BAR_NO_FOLDER_BORDER = crate::color::Color::hex(0x0d3a58),
        STATUS_BAR_NO_FOLDER_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        TAB_ACTIVE_BACKGROUND = crate::color::Color::hex(0x193549),
        TAB_ACTIVE_BORDER = crate::color::Color::hex(0xffc600),
        TAB_ACTIVE_FOREGROUND = crate::color::Color::hex(0xffffff),
        TAB_BORDER = crate::color::Color::hex(0x15232d),
        TAB_INACTIVE_BACKGROUND = crate::color::Color::hex(0x122738),
        TAB_INACTIVE_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        TAB_UNFOCUSED_ACTIVE_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        TAB_UNFOCUSED_INACTIVE_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        TERMINAL_ANSI_BLACK = crate::color::Color::hex(0x000000),
        TERMINAL_ANSI_BLUE = crate::color::Color::hex(0x0088ff),
        TERMINAL_ANSI_BRIGHT_BLACK = crate::color::Color::hex(0x0050a4),
        TERMINAL_ANSI_BRIGHT_BLUE = crate::color::Color::hex(0x0088ff),
        TERMINAL_ANSI_BRIGHT_CYAN = crate::color::Color::hex(0x80fcff),
        TERMINAL_ANSI_BRIGHT_GREEN = crate::color::Color::hex(0x3ad900),
        TERMINAL_ANSI_BRIGHT_MAGENTA = crate::color::Color::hex(0xfb94ff),
        TERMINAL_ANSI_BRIGHT_RED = crate::color::Color::hex(0xff628c),
        TERMINAL_ANSI_BRIGHT_WHITE = crate::color::Color::hex(0xffffff),
        TERMINAL_ANSI_BRIGHT_YELLOW = crate::color::Color::hex(0xffc600),
        TERMINAL_ANSI_CYAN = crate::color::Color::hex(0x80fcff),
        TERMINAL_ANSI_GREEN = crate::color::Color::hex(0x3ad900),
        TERMINAL_ANSI_MAGENTA = crate::color::Color::hex(0xfb94ff),
        TERMINAL_ANSI_RED = crate::color::Color::hex(0xff628c),
        TERMINAL_ANSI_WHITE = crate::color::Color::hex(0xffffff),
        TERMINAL_ANSI_YELLOW = crate::color::Color::hex(0xffc600),
        TERMINAL_BACKGROUND = crate::color::Color::hex(0x122738),
        TERMINAL_CURSOR_BACKGROUND = crate::color::Color::hex(0x122738),
        TERMINAL_CURSOR_FOREGROUND = crate::color::Color::hex(0xffc600),
        TERMINAL_FOREGROUND = crate::color::Color::hex(0xffffff),
        TEXT_BLOCK_QUOTE_BACKGROUND = crate::color::Color::hex(0x193549),
        TEXT_BLOCK_QUOTE_BORDER = crate::color::Color::hex(0x0088ff),
        TEXT_CODE_BLOCK_BACKGROUND = crate::color::Color::hex(0x193549),
        TEXT_LINK_ACTIVE_FOREGROUND = crate::color::Color::hex(0x0088ff),
        TEXT_LINK_FOREGROUND = crate::color::Color::hex(0x0088ff),
        TEXT_PREFORMAT_FOREGROUND = crate::color::Color::hex(0xffc600),
        TEXT_SEPARATOR_FOREGROUND = crate::color::Color::hex(0x0d3a58),
        TITLE_BAR_ACTIVE_BACKGROUND = crate::color::Color::hex(0x15232d),
        TITLE_BAR_ACTIVE_FOREGROUND = crate::color::Color::hex(0xffffff),
        TITLE_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x193549),
        TITLE_BAR_INACTIVE_FOREGROUND = crate::color::Color::hex_alpha(0xffffff33),
        TOKEN_COMMENT = crate::color::Color::hex(0x0088ff),
        TOKEN_CONSTANT = crate::color::Color::hex(0xff628c),
        TOKEN_CSS_CONSTANT = crate::color::Color::hex(0xffee80),
        TOKEN_CSS_ELEMENT_SELECTOR = crate::color::Color::hex(0x9effff),
        TOKEN_CSS_ENTITY = crate::color::Color::hex(0x3ad900),
        TOKEN_CSS_ID_SELECTOR = crate::color::Color::hex(0xffb454),
        TOKEN_CSS_STRING = crate::color::Color::hex(0xffee80),
        TOKEN_CSS_SUPPORT = crate::color::Color::hex(0xa5ff90),
        TOKEN_CSS_VARIABLE = crate::color::Color::hex(0x9effff),
        TOKEN_C_ANNOTATIONS = crate::color::Color::hex(0x9effff),
        TOKEN_C_PROPERTIES = crate::color::Color::hex(0x9effff),
        TOKEN_C_STORAGE_MODIFIERS = crate::color::Color::hex(0x80ffbb),
        TOKEN_ENTITY = crate::color::Color::hex(0xffc600),
        TOKEN_EXPORT_DEFAULT = crate::color::Color::hex(0xff9d00),
        TOKEN_HTML_ENTITY_NAME = crate::color::Color::hex(0x9effff),
        TOKEN_HTML_ENTITY_OTHER = crate::color::Color::hex(0xffc600),
        TOKEN_HTML_ID_VALUE = crate::color::Color::hex(0xa5ff90),
        TOKEN_HTML_QUOTES_THESE_ARE_A_SLIGHTLY_DIFFERENT_COLOUR_BECAUSE_EXPAND_SELECTION_WILL_THEN_NOT_INCLUDE_QUOTES = crate::color::Color::hex(0x92fc79),
        TOKEN_HTML_SCRIPT_TAG = crate::color::Color::hex(0xffc600),
        TOKEN_INI_ENTITY = crate::color::Color::hex(0xe1efff),
        TOKEN_INI_KEYWORD = crate::color::Color::hex(0xffc600),
        TOKEN_INI_PUNCTUATION_DEFINITION = crate::color::Color::hex(0xffee80),
        TOKEN_INI_PUNCTUATION_SEPARATOR = crate::color::Color::hex(0xff9d00),
        TOKEN_INVALID = crate::color::Color::hex(0xf44542),
        TOKEN_JAVASCRIPT_INHERITED_COMPONENT = crate::color::Color::hex(0xcccccc),
        TOKEN_JAVASCRIPT_STORAGE_TYPE_FUNCTION = crate::color::Color::hex(0xfb94ff),
        TOKEN_JAVASCRIPT_VARIABLE_LANGUAGE = crate::color::Color::hex(0xfb94ff),
        TOKEN_JSON_STRING = crate::color::Color::hex(0xe1efff),
        TOKEN_JSON_SUPPORT = crate::color::Color::hex(0xffc600),
        TOKEN_KEYWORD = crate::color::Color::hex(0xff9d00),
        TOKEN_MARKDOWN_CODE_BLOCK = crate::color::Color::hex(0x9effff),
        TOKEN_MARKDOWN_EMPHASIS_BOLD = crate::color::Color::hex(0x9effff),
        TOKEN_MARKDOWN_EMPHASIS_ITALIC = crate::color::Color::hex(0x9effff),
        TOKEN_MARKDOWN_HEADING_NAME_SECTION = crate::color::Color::hex(0xffc600),
        TOKEN_MARKDOWN_HEADING_PUNCTUATION = crate::color::Color::hex(0xe1efff),
        TOKEN_MARKDOWN_INLINE_CODE = crate::color::Color::hex(0x9effff),
        TOKEN_MARKDOWN_LINK_ADDRESS = crate::color::Color::hex(0x9effff),
        TOKEN_MARKDOWN_LINK_IMAGE_TITLE = crate::color::Color::hex(0xa5ff90),
        TOKEN_MARKDOWN_LINK_TITLE = crate::color::Color::hex(0xa5ff90),
        TOKEN_MARKDOWN_LISTS = crate::color::Color::hex(0xffc600),
        TOKEN_MARKDOWN_PARAGRAPH = crate::color::Color::hex(0xe1efff),
        TOKEN_MARKDOWN_QUOTE_PARAGRAPH = crate::color::Color::hex(0x9effff),
        TOKEN_MARKDOWN_QUOTE_PUNCTUATION = crate::color::Color::hex(0xffc600),
        TOKEN_MARKDOWN_SEPARATOR = crate::color::Color::hex(0xffc600),
        TOKEN_MARKUP_DELETED = crate::color::Color::hex(0xff628c),
        TOKEN_MARKUP_DELETED_PUNCTUATION = crate::color::Color::hex_alpha(0xff628ccc),
        TOKEN_MARKUP_INSERTED = crate::color::Color::hex(0xa5ff90),
        TOKEN_MARKUP_INSERTED_PUNCTUATION = crate::color::Color::hex_alpha(0xa5ff90cc),
        TOKEN_META = crate::color::Color::hex(0x9effff),
        TOKEN_META_BRACE = crate::color::Color::hex(0xe1efff),
        TOKEN_META_JSX = crate::color::Color::hex(0xffffff),
        TOKEN_PHP_ENTITY = crate::color::Color::hex(0x9effff),
        TOKEN_PHP_VARIABLES = crate::color::Color::hex(0xffc600),
        TOKEN_PUG_ENTITY_NAME = crate::color::Color::hex(0x9effff),
        TOKEN_PUG_STRING_INTERPOLATED = crate::color::Color::hex(0xffee80),
        TOKEN_PUNCTUATION = crate::color::Color::hex(0xe1efff),
        TOKEN_PUNCTUATION_PARAMETERS = crate::color::Color::hex(0xffee80),
        TOKEN_PUNCTUATION_TEMPLATE_EXPRESSION = crate::color::Color::hex(0xffee80),
        TOKEN_PYTHON_FUNCTION_CALL_ARGUMENT = crate::color::Color::hex(0xfb94ff),
        TOKEN_PYTHON_SELF_ARGUMENT = crate::color::Color::hex(0x9effff),
        TOKEN_STORAGE = crate::color::Color::hex(0xffc600),
        TOKEN_STORAGE_TYPE_ARROW_FUNCTION = crate::color::Color::hex(0xffc600),
        TOKEN_STORAGE_TYPE_FUNCTION = crate::color::Color::hex(0xff9d00),
        TOKEN_STRING = crate::color::Color::hex(0xa5ff90),
        TOKEN_STRING_TEMPLATE = crate::color::Color::hex(0x3ad900),
        TOKEN_SUPPORT = crate::color::Color::hex(0x80ffbb),
        TOKEN_SUPPORT_FUNCTION = crate::color::Color::hex(0xff9d00),
        TOKEN_SUPPORT_VARIABLE_PROPERTY_DOM = crate::color::Color::hex(0xe1efff),
        TOKEN_TYPESCRIPT_ENTITY_NAME_TYPE = crate::color::Color::hex(0x80ffbb),
        TOKEN_TYPESCRIPT_KEYWORD = crate::color::Color::hex(0xffc600),
        TOKEN_TYPESCRIPT_PUNCTUATION_ARROW_PARAMETERS = crate::color::Color::hex(0xffee80),
        TOKEN_TYPESCRIPT_PUNCTUATION_PARAMETERS = crate::color::Color::hex(0xe1efff),
        TOKEN_TYPESCRIPT_RETURNED_TYPE = crate::color::Color::hex(0xff0088),
        TOKEN_VARIABLE = crate::color::Color::hex(0xe1efff),
        WALK_THROUGH_EMBEDDED_EDITOR_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        WELCOME_PAGE_BUTTON_BACKGROUND = crate::color::Color::hex(0x193549),
        WELCOME_PAGE_BUTTON_HOVER_BACKGROUND = crate::color::Color::hex(0x0d3a58),
        WIDGET_SHADOW = crate::color::Color::hex_alpha(0x00000026),
    }
    accents {
        Red = TERMINAL_ANSI_RED => ("red", "Red"),
        Green = TERMINAL_ANSI_GREEN => ("green", "Green"),
        Yellow = TERMINAL_ANSI_YELLOW => ("yellow", "Yellow"),
        Blue = TERMINAL_ANSI_BLUE => ("blue", "Blue"),
        Magenta = TERMINAL_ANSI_MAGENTA => ("magenta", "Magenta"),
        Cyan = TERMINAL_ANSI_CYAN => ("cyan", "Cyan"),
    }
    default TERMINAL_ANSI_BLUE => "blue";
    roles(primary) {
        surfaces: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BACKGROUND,
            base: Self::SIDE_BAR_BACKGROUND,
            raised: Self::DROPDOWN_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        surfaces_alt: crate::theme_variant::SurfaceColors {
            background: Self::SIDE_BAR_BACKGROUND,
            base: Self::EDITOR_BACKGROUND,
            raised: Self::SIDE_BAR_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::EDITOR_FOREGROUND,
            muted: Self::DESCRIPTION_FOREGROUND,
            subtle: Self::EDITOR_LINE_NUMBER_FOREGROUND,
        },
        text_alt: None,
primary: crate::theme_variant::ActionColors {
    normal: crate::theme_variant::ColorPair::new(
        Self::BUTTON_FOREGROUND,
        Self::BUTTON_BACKGROUND,
    ),
    hover: crate::theme_variant::ColorPair::new(
        Self::BUTTON_FOREGROUND,
        Self::BUTTON_HOVER_BACKGROUND,
    ),
    // Upstream has no distinct pressed token. Reuse its authored hover state
    // rather than inventing another Cobalt2 colour.
    pressed: crate::theme_variant::ColorPair::new(
        Self::BUTTON_FOREGROUND,
        Self::BUTTON_HOVER_BACKGROUND,
    ),
    muted: crate::theme_variant::ColorPair::new(
        Self::EDITOR_FOREGROUND,
        Self::SIDE_BAR_BACKGROUND,
    ),
    disabled: crate::theme_variant::ColorPair::new(
        Self::EDITOR_LINE_NUMBER_FOREGROUND,
        Self::SIDE_BAR_BACKGROUND,
    ),
},
secondary: crate::theme_variant::ActionColors {
    normal: crate::theme_variant::ColorPair::new(
        crate::palette::action_text(
            Self::TERMINAL_ANSI_MAGENTA,
            Self::EDITOR_BACKGROUND,
            Self::EDITOR_FOREGROUND,
        ),
        Self::TERMINAL_ANSI_MAGENTA,
    ),
    hover: crate::theme_variant::ColorPair::new(
        crate::palette::action_text(
            Self::TERMINAL_ANSI_MAGENTA,
            Self::EDITOR_BACKGROUND,
            Self::EDITOR_FOREGROUND,
        ),
        crate::palette::primary_hover(Self::TERMINAL_ANSI_MAGENTA),
    ),
    pressed: crate::theme_variant::ColorPair::new(
        crate::palette::action_text(
            Self::TERMINAL_ANSI_MAGENTA,
            Self::EDITOR_BACKGROUND,
            Self::EDITOR_FOREGROUND,
        ),
        crate::palette::action_pressed(Self::TERMINAL_ANSI_MAGENTA),
    ),
    muted: crate::theme_variant::ColorPair::new(
        Self::EDITOR_FOREGROUND,
        Self::SIDE_BAR_BACKGROUND,
    ),
    disabled: crate::theme_variant::ColorPair::new(
        Self::EDITOR_LINE_NUMBER_FOREGROUND,
        Self::SIDE_BAR_BACKGROUND,
    ),
},
        status: crate::theme_variant::StatusColors {
            success: Self::TERMINAL_ANSI_GREEN,
            warning: Self::EDITOR_WARNING_FOREGROUND,
            error: Self::TERMINAL_ANSI_RED,
            critical: Self::TERMINAL_ANSI_BRIGHT_RED,
            info: Self::TERMINAL_ANSI_BLUE,
            debug: Self::DESCRIPTION_FOREGROUND,
            trace: Self::EDITOR_LINE_NUMBER_FOREGROUND,
        },
        border: Self::EDITOR_WIDGET_BORDER,
        border_muted: Self::SIDE_BAR_BACKGROUND,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::TOKEN_INVALID,
            orange: Self::TOKEN_CSS_ID_SELECTOR,
            yellow: Self::TERMINAL_ANSI_YELLOW,
            green: Self::TERMINAL_ANSI_GREEN,
            cyan: Self::TERMINAL_ANSI_CYAN,
            blue: Self::TERMINAL_ANSI_BLUE,
            purple: Self::TERMINAL_ANSI_MAGENTA,
            pink: Self::EDITOR_BRACKET_HIGHLIGHT_FOREGROUND_2,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::TOKEN_ENTITY,
            boolean: Self::TOKEN_CONSTANT,
            builtin: Self::TOKEN_SUPPORT,
            builtin_function: Self::TOKEN_SUPPORT_FUNCTION,
            builtin_type: Self::TOKEN_SUPPORT,
            comment: Self::TOKEN_COMMENT,
            constant: Self::TOKEN_CONSTANT,
            control_keyword: Self::TOKEN_KEYWORD,
            deleted: Self::TOKEN_MARKUP_DELETED,
            deprecated: Self::TOKEN_INVALID,
            documentation: Self::TOKEN_COMMENT,
            escape: Self::TOKEN_CONSTANT,
            foreground: Self::EDITOR_FOREGROUND,
            function: Self::SEMANTIC_FUNCTION,
            heading: Self::TOKEN_MARKDOWN_HEADING_NAME_SECTION,
            inserted: Self::TOKEN_MARKUP_INSERTED,
            invalid: Self::TOKEN_INVALID,
            keyword: Self::TOKEN_KEYWORD,
            link: Self::TOKEN_MARKDOWN_LINK_ADDRESS,
            macro_name: Self::TOKEN_ENTITY,
            markup_bold: Self::TOKEN_MARKDOWN_EMPHASIS_BOLD,
            markup_italic: Self::TOKEN_MARKDOWN_EMPHASIS_ITALIC,
            modifier: Self::TOKEN_STORAGE,
            namespace: Self::TOKEN_ENTITY,
            number: Self::TOKEN_CONSTANT,
            operator: Self::TOKEN_KEYWORD,
            parameter: Self::TOKEN_VARIABLE,
            property: Self::SEMANTIC_PROPERTY,
            punctuation: Self::TOKEN_PUNCTUATION,
            string: Self::TOKEN_STRING,
            tag: Self::TOKEN_CSS_ELEMENT_SELECTOR,
            type_keyword: Self::TOKEN_STORAGE,
            type_name: Self::SEMANTIC_TYPE,
            variable: Self::SEMANTIC_VARIABLE,
        },
    }
}
