//! Tokyo Night Day. See the family module for its upstream source.

define_palette! {
    Day, "Tokyo Night Day",
    identity("tokyo_night/day", "tokyo_night", "Tokyo Night", "day", "Day", Light, None);
    support(Light);
    sources: super::SOURCE;
    colors {
        BG = crate::color::Color::hex(0xe1e2e7),
        BG_DARK = crate::color::Color::hex(0xd0d5e3),
        BG_DARK_1 = crate::color::Color::hex(0xc1c9df),
        BG_HIGHLIGHT = crate::color::Color::hex(0xc4c8da),
        BLUE = crate::color::Color::hex(0x2e7de9),
        BLUE_0 = crate::color::Color::hex(0x7890dd),
        BLUE_1 = crate::color::Color::hex(0x188092),
        BLUE_2 = crate::color::Color::hex(0x07879d),
        BLUE_5 = crate::color::Color::hex(0x006a83),
        BLUE_6 = crate::color::Color::hex(0x2e5857),
        BLUE_7 = crate::color::Color::hex(0x92a6d5),
        COMMENT = crate::color::Color::hex(0x848cb5),
        CYAN = crate::color::Color::hex(0x007197),
        DARK_3 = crate::color::Color::hex(0x8990b3),
        DARK_5 = crate::color::Color::hex(0x68709a),
        FG = crate::color::Color::hex(0x3760bf),
        FG_DARK = crate::color::Color::hex(0x6172b0),
        FG_GUTTER = crate::color::Color::hex(0xa8aecb),
        GREEN = crate::color::Color::hex(0x587539),
        GREEN_1 = crate::color::Color::hex(0x387068),
        GREEN_2 = crate::color::Color::hex(0x38919f),
        MAGENTA = crate::color::Color::hex(0x9854f1),
        MAGENTA_2 = crate::color::Color::hex(0xd20065),
        ORANGE = crate::color::Color::hex(0xb15c00),
        PURPLE = crate::color::Color::hex(0x7847bd),
        RED = crate::color::Color::hex(0xf52a65),
        RED_1 = crate::color::Color::hex(0xc64343),
        TEAL = crate::color::Color::hex(0x118c74),
        TERMINAL_BLACK = crate::color::Color::hex(0xa1a6c5),
        YELLOW = crate::color::Color::hex(0x8c6c3e),
    }
    accents {
        Blue = BLUE => ("blue", "Blue"),
        Cyan = CYAN => ("cyan", "Cyan"),
        Green = GREEN => ("green", "Green"),
        Magenta = MAGENTA => ("magenta", "Magenta"),
        Orange = ORANGE => ("orange", "Orange"),
        Purple = PURPLE => ("purple", "Purple"),
        Red = RED => ("red", "Red"),
        Teal = TEAL => ("teal", "Teal"),
        Yellow = YELLOW => ("yellow", "Yellow"),
    }
    default BLUE => "blue";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::BG,
            surface: Self::BG_DARK,
            raised: Self::BG_HIGHLIGHT,
            overlay: Self::BG_DARK_1,
            hover: Self::BG_HIGHLIGHT,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::BG_DARK_1,
            surface: Self::BG_DARK,
            raised: Self::BG,
            overlay: Self::BG_DARK_1,
            hover: Self::BG_HIGHLIGHT,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FG,
            muted: Self::FG_DARK,
            subtle: Self::COMMENT,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::MAGENTA),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::BG_HIGHLIGHT,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::MAGENTA,
            hover: crate::palette::primary_hover(Self::MAGENTA),
            pressed: crate::palette::action_pressed(Self::MAGENTA),
            muted: Self::BG_DARK,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::GREEN,
            warning: Self::YELLOW,
            error: Self::RED_1,
            critical: Self::RED,
            info: Self::BLUE_2,
            trace: Self::FG_DARK,
        },
        border: Self::FG_GUTTER,
        border_muted: Self::BG_HIGHLIGHT,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::RED,
            orange: Self::ORANGE,
            yellow: Self::YELLOW,
            green: Self::GREEN,
            cyan: Self::CYAN,
            blue: Self::BLUE,
            purple: Self::PURPLE,
            pink: Self::MAGENTA_2,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::BLUE_1,
            boolean: Self::ORANGE,
            builtin: Self::BLUE_1,
            builtin_function: Self::BLUE,
            builtin_type: Self::BLUE_1,
            comment: Self::COMMENT,
            constant: Self::ORANGE,
            control_keyword: Self::MAGENTA,
            deleted: Self::RED_1,
            deprecated: Self::RED_1,
            documentation: Self::COMMENT,
            escape: Self::BLUE_5,
            foreground: Self::FG,
            function: Self::BLUE,
            heading: Self::BLUE,
            inserted: Self::GREEN,
            invalid: Self::RED_1,
            keyword: Self::MAGENTA,
            link: Self::BLUE,
            markup_bold: Self::FG,
            markup_italic: Self::FG,
            modifier: Self::MAGENTA,
            namespace: Self::BLUE_1,
            number: Self::ORANGE,
            operator: Self::BLUE_5,
            parameter: Self::FG,
            property: Self::FG,
            punctuation: Self::FG,
            string: Self::GREEN,
            tag: Self::MAGENTA,
            type_keyword: Self::MAGENTA,
            type_name: Self::BLUE_1,
            variable: Self::FG,
        },
    }
}
