//! Tokyo Night Day. See the family module for its upstream source.

define_palette! {
    Day, "Tokyo Night Day",
    colors {
        BG = 0xe1e2e7,
        BG_DARK = 0xd0d5e3,
        BG_DARK_1 = 0xc1c9df,
        BG_HIGHLIGHT = 0xc4c8da,
        BLUE = 0x2e7de9,
        BLUE_0 = 0x7890dd,
        BLUE_1 = 0x188092,
        BLUE_2 = 0x07879d,
        BLUE_5 = 0x006a83,
        BLUE_6 = 0x2e5857,
        BLUE_7 = 0x92a6d5,
        COMMENT = 0x848cb5,
        CYAN = 0x007197,
        DARK_3 = 0x8990b3,
        DARK_5 = 0x68709a,
        FG = 0x3760bf,
        FG_DARK = 0x6172b0,
        FG_GUTTER = 0xa8aecb,
        GREEN = 0x587539,
        GREEN_1 = 0x387068,
        GREEN_2 = 0x38919f,
        MAGENTA = 0x9854f1,
        MAGENTA_2 = 0xd20065,
        ORANGE = 0xb15c00,
        PURPLE = 0x7847bd,
        RED = 0xf52a65,
        RED_1 = 0xc64343,
        TEAL = 0x118c74,
        TERMINAL_BLACK = 0xa1a6c5,
        YELLOW = 0x8c6c3e,
    }
    accents {
        Blue = BLUE,
        Cyan = CYAN,
        Green = GREEN,
        Magenta = MAGENTA,
        Orange = ORANGE,
        Purple = PURPLE,
        Red = RED,
        Teal = TEAL,
        Yellow = YELLOW,
    }
    default BLUE;
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::BG,
            surface: Self::BG_DARK,
            raised: Self::BG_HIGHLIGHT,
            overlay: Self::BG_DARK_1,
            hover: Self::BG_HIGHLIGHT,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::BG,
            surface: Self::BG_DARK,
            raised: Self::BG_HIGHLIGHT,
            overlay: Self::BG_DARK_1,
            hover: Self::BG_HIGHLIGHT,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FG,
            muted: Self::FG_DARK,
            subtle: Self::COMMENT,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::MAGENTA),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: primary,
            muted: Self::BG_HIGHLIGHT,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::MAGENTA,
            hover: crate::palette::primary_hover(Self::MAGENTA),
            pressed: Self::MAGENTA,
            muted: Self::MAGENTA,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::GREEN,
            warning: Self::YELLOW,
            error: Self::RED_1,
            critical: Self::RED_1,
            info: Self::BLUE_2,
            trace: Self::COMMENT,
        },
        border: Self::FG_GUTTER,
        border_muted: Self::BG_HIGHLIGHT,
        focus: primary,
    }
}
