//! Tokyo Night Moon. See the family module for its upstream source.

define_palette! {
    Moon, "Tokyo Night Moon",
    colors {
        BG = 0x222436,
        BG_DARK = 0x1e2030,
        BG_DARK_1 = 0x191b29,
        BG_HIGHLIGHT = 0x2f334d,
        BLUE = 0x82aaff,
        BLUE_0 = 0x3e68d7,
        BLUE_1 = 0x65bcff,
        BLUE_2 = 0x0db9d7,
        BLUE_5 = 0x89ddff,
        BLUE_6 = 0xb4f9f8,
        BLUE_7 = 0x394b70,
        COMMENT = 0x636da6,
        CYAN = 0x86e1fc,
        DARK_3 = 0x545c7e,
        DARK_5 = 0x737aa2,
        FG = 0xc8d3f5,
        FG_DARK = 0x828bb8,
        FG_GUTTER = 0x3b4261,
        GREEN = 0xc3e88d,
        GREEN_1 = 0x4fd6be,
        GREEN_2 = 0x41a6b5,
        MAGENTA = 0xc099ff,
        MAGENTA_2 = 0xff007c,
        ORANGE = 0xff966c,
        PURPLE = 0xfca7ea,
        RED = 0xff757f,
        RED_1 = 0xc53b53,
        TEAL = 0x4fd6be,
        TERMINAL_BLACK = 0x444a73,
        YELLOW = 0xffc777,
    }
    accents {
        Blue = BLUE,
        Cyan = CYAN,
        Green = GREEN,
        Magenta = MAGENTA,
        Orange = ORANGE,
        Purple = PURPLE,
        Red = RED,
        Teal = TEAL,
        Yellow = YELLOW,
    }
    default BLUE;
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::BG,
            surface: Self::BG_DARK,
            raised: Self::BG_HIGHLIGHT,
            overlay: Self::BG_DARK_1,
            hover: Self::BG_HIGHLIGHT,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::BG,
            surface: Self::BG_DARK,
            raised: Self::BG_HIGHLIGHT,
            overlay: Self::BG_DARK_1,
            hover: Self::BG_HIGHLIGHT,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FG,
            muted: Self::FG_DARK,
            subtle: Self::COMMENT,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::MAGENTA),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: primary,
            muted: Self::BG_HIGHLIGHT,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::MAGENTA,
            hover: crate::palette::primary_hover(Self::MAGENTA),
            pressed: Self::MAGENTA,
            muted: Self::MAGENTA,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::GREEN,
            warning: Self::YELLOW,
            error: Self::RED_1,
            critical: Self::RED_1,
            info: Self::BLUE_2,
            trace: Self::COMMENT,
        },
        border: Self::FG_GUTTER,
        border_muted: Self::BG_HIGHLIGHT,
        focus: primary,
    }
}
