//! Tokyo Night Night. See the family module for its upstream source.

define_palette! {
    Night, "Tokyo Night Night",
    colors {
        BG = 0x1a1b26,
        BG_DARK = 0x16161e,
        BG_DARK_1 = 0x0c0e14,
        BG_HIGHLIGHT = 0x292e42,
        BLUE = 0x7aa2f7,
        BLUE_0 = 0x3d59a1,
        BLUE_1 = 0x2ac3de,
        BLUE_2 = 0x0db9d7,
        BLUE_5 = 0x89ddff,
        BLUE_6 = 0xb4f9f8,
        BLUE_7 = 0x394b70,
        COMMENT = 0x565f89,
        CYAN = 0x7dcfff,
        DARK_3 = 0x545c7e,
        DARK_5 = 0x737aa2,
        FG = 0xc0caf5,
        FG_DARK = 0xa9b1d6,
        FG_GUTTER = 0x3b4261,
        GREEN = 0x9ece6a,
        GREEN_1 = 0x73daca,
        GREEN_2 = 0x41a6b5,
        MAGENTA = 0xbb9af7,
        MAGENTA_2 = 0xff007c,
        ORANGE = 0xff9e64,
        PURPLE = 0x9d7cd8,
        RED = 0xf7768e,
        RED_1 = 0xdb4b4b,
        TEAL = 0x1abc9c,
        TERMINAL_BLACK = 0x414868,
        YELLOW = 0xe0af68,
    }
    accents {
        Blue = BLUE,
        Cyan = CYAN,
        Green = GREEN,
        Magenta = MAGENTA,
        Orange = ORANGE,
        Purple = PURPLE,
        Red = RED,
        Teal = TEAL,
        Yellow = YELLOW,
    }
    default BLUE;
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::BG,
            surface: Self::BG_DARK,
            raised: Self::BG_HIGHLIGHT,
            overlay: Self::BG_DARK_1,
            hover: Self::BG_HIGHLIGHT,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::BG,
            surface: Self::BG_DARK,
            raised: Self::BG_HIGHLIGHT,
            overlay: Self::BG_DARK_1,
            hover: Self::BG_HIGHLIGHT,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FG,
            muted: Self::FG_DARK,
            subtle: Self::COMMENT,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::MAGENTA),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: primary,
            muted: Self::BG_HIGHLIGHT,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::MAGENTA,
            hover: crate::palette::primary_hover(Self::MAGENTA),
            pressed: Self::MAGENTA,
            muted: Self::MAGENTA,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::GREEN,
            warning: Self::YELLOW,
            error: Self::RED_1,
            critical: Self::RED_1,
            info: Self::BLUE_2,
            trace: Self::COMMENT,
        },
        border: Self::FG_GUTTER,
        border_muted: Self::BG_HIGHLIGHT,
        focus: primary,
    }
}
