//! Tokyo Night Storm. See the family module for its upstream source.

define_palette! {
    Storm, "Tokyo Night Storm",
    identity("tokyo_night/storm", "tokyo_night", "Tokyo Night", "storm", "Storm", Dark, None);
    support(Dark);
    sources: super::SOURCE;
    colors {
        BG = crate::color::Color::hex(0x24283b),
        BG_DARK = crate::color::Color::hex(0x1f2335),
        BG_DARK_1 = crate::color::Color::hex(0x1b1e2d),
        BLACK = crate::color::Color::hex(0x1d202f),
        BG_HIGHLIGHT = crate::color::Color::hex(0x292e42),
        BLUE = crate::color::Color::hex(0x7aa2f7),
        BLUE_0 = crate::color::Color::hex(0x3d59a1),
        BLUE_1 = crate::color::Color::hex(0x2ac3de),
        BLUE_2 = crate::color::Color::hex(0x0db9d7),
        BLUE_5 = crate::color::Color::hex(0x89ddff),
        BLUE_6 = crate::color::Color::hex(0xb4f9f8),
        BLUE_7 = crate::color::Color::hex(0x394b70),
        COMMENT = crate::color::Color::hex(0x565f89),
        CYAN = crate::color::Color::hex(0x7dcfff),
        DARK_3 = crate::color::Color::hex(0x545c7e),
        DARK_5 = crate::color::Color::hex(0x737aa2),
        FG = crate::color::Color::hex(0xc0caf5),
        FG_DARK = crate::color::Color::hex(0xa9b1d6),
        FG_GUTTER = crate::color::Color::hex(0x3b4261),
        GIT_ADD = crate::color::Color::hex(0x449dab),
        GIT_CHANGE = crate::color::Color::hex(0x6183bb),
        GIT_DELETE = crate::color::Color::hex(0x914c54),
        GREEN = crate::color::Color::hex(0x9ece6a),
        GREEN_1 = crate::color::Color::hex(0x73daca),
        GREEN_2 = crate::color::Color::hex(0x41a6b5),
        MAGENTA = crate::color::Color::hex(0xbb9af7),
        MAGENTA_2 = crate::color::Color::hex(0xff007c),
        ORANGE = crate::color::Color::hex(0xff9e64),
        PURPLE = crate::color::Color::hex(0x9d7cd8),
        RED = crate::color::Color::hex(0xf7768e),
        RED_1 = crate::color::Color::hex(0xdb4b4b),
        TEAL = crate::color::Color::hex(0x1abc9c),
        TERMINAL_BLACK = crate::color::Color::hex(0x414868),
        YELLOW = crate::color::Color::hex(0xe0af68),
    }
    accents {
        Blue = BLUE => ("blue", "Blue"),
        Cyan = CYAN => ("cyan", "Cyan"),
        Green = GREEN => ("green", "Green"),
        Magenta = MAGENTA => ("magenta", "Magenta"),
        Orange = ORANGE => ("orange", "Orange"),
        Purple = PURPLE => ("purple", "Purple"),
        Red = RED => ("red", "Red"),
        Teal = TEAL => ("teal", "Teal"),
        Yellow = YELLOW => ("yellow", "Yellow"),
    }
    default BLUE => "blue";
    roles(primary) {
        surfaces: crate::theme_variant::SurfaceColors {
            background: Self::BG,
            base: Self::BG_DARK,
            raised: Self::BG_HIGHLIGHT,
            overlay: Self::BG_DARK_1,
            hover: Self::BG_HIGHLIGHT,
        },
        surfaces_alt: crate::theme_variant::SurfaceColors {
            background: Self::BG_DARK_1,
            base: Self::BG_DARK,
            raised: Self::BG,
            overlay: Self::BG_DARK_1,
            hover: Self::BG_HIGHLIGHT,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FG,
            muted: Self::FG_DARK,
            subtle: Self::COMMENT,
        },
        text_alt: None,
        primary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(
                Self::BLACK,
                primary,
            ),
            hover: crate::theme_variant::ColorPair::new(
                Self::BLACK,
                crate::palette::primary_hover(primary),
            ),
            pressed: crate::theme_variant::ColorPair::new(
                Self::BLACK,
                crate::palette::action_pressed(primary),
            ),
            muted: crate::theme_variant::ColorPair::new(
                Self::BLUE,
                Self::BG_DARK,
            ),
            disabled: crate::theme_variant::ColorPair::new(
                Self::FG_GUTTER,
                Self::BG_DARK,
            ),
        },
        secondary: crate::theme_variant::ActionColors {
            normal: crate::theme_variant::ColorPair::new(
                Self::BLACK,
                Self::MAGENTA,
            ),
            hover: crate::theme_variant::ColorPair::new(
                Self::BLACK,
                crate::palette::primary_hover(Self::MAGENTA),
            ),
            pressed: crate::theme_variant::ColorPair::new(
                Self::BLACK,
                crate::palette::action_pressed(Self::MAGENTA),
            ),
            muted: crate::theme_variant::ColorPair::new(
                Self::BLUE,
                Self::BG_DARK,
            ),
            disabled: crate::theme_variant::ColorPair::new(
                Self::FG_GUTTER,
                Self::BG_DARK,
            ),
        },
        status: crate::theme_variant::StatusColors {
            success: Self::GREEN_1,
            warning: Self::YELLOW,
            error: Self::RED_1,
            critical: Self::RED,
            info: Self::BLUE_2,
            debug: Self::COMMENT,
            trace: Self::PURPLE,
        },
        border: Self::BLACK,
        border_muted: Self::BG_HIGHLIGHT,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::RED,
            orange: Self::ORANGE,
            yellow: Self::YELLOW,
            green: Self::GREEN,
            cyan: Self::CYAN,
            blue: Self::BLUE,
            purple: Self::PURPLE,
            pink: Self::MAGENTA_2,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::MAGENTA,
            boolean: Self::ORANGE,
            builtin: Self::BLUE_1,
            builtin_function: Self::BLUE_1,
            builtin_type: Self::BLUE_2,
            comment: Self::COMMENT,
            constant: Self::ORANGE,
            control_keyword: Self::MAGENTA,
            deleted: Self::GIT_DELETE,
            deprecated: Self::MAGENTA,
            documentation: Self::COMMENT,
            escape: Self::BLUE_5,
            foreground: Self::FG,
            function: Self::BLUE,
            heading: Self::GREEN_1,
            inserted: Self::GIT_ADD,
            invalid: Self::RED,
            keyword: Self::MAGENTA,
            link: Self::GREEN_1,
            macro_name: Self::CYAN,
            markup_bold: Self::FG,
            markup_italic: Self::FG,
            modifier: Self::PURPLE,
            namespace: Self::BLUE_2,
            number: Self::ORANGE,
            operator: Self::BLUE_5,
            parameter: Self::YELLOW,
            property: Self::CYAN,
            punctuation: Self::BLUE_5,
            string: Self::GREEN,
            tag: Self::RED,
            type_keyword: Self::MAGENTA,
            type_name: Self::BLUE_2,
            variable: Self::FG,
        },
    }
}
