[package]
name = "ferriswatch-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Macro support for Ferriswatch"
repository.workspace = true
publish.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(docsrs)"] }
