//! Shades of Purple. See `REGISTRATION` for pinned upstream sources.
//!
//! Editor UI keys supply surfaces and source alpha is retained. Terminal accents supply filled actions. Critical uses bright red; trace uses subdued source text. Roles that share an upstream colour intentionally repeat.

define_palette! {
    Main, "Shades of Purple",
    identity("shades_of_purple/main", "shades_of_purple", "Shades of Purple", "main", "Main", Dark, None);
    sources: crate::palette::sources::SHADES_OF_PURPLE_MAIN;
    colors {
        ACTIVITY_BAR_BACKGROUND = crate::color::Color::hex(0x28284e),
        ACTIVITY_BAR_BORDER = crate::color::Color::hex(0x222244),
        ACTIVITY_BAR_DROP_BACKGROUND = crate::color::Color::hex(0x222145),
        ACTIVITY_BAR_FOREGROUND = crate::color::Color::hex(0xffffff),
        ACTIVITY_BAR_INACTIVE_FOREGROUND = crate::color::Color::hex(0xa599e9),
        ACTIVITY_BAR_BADGE_BACKGROUND = crate::color::Color::hex(0xfad000),
        ACTIVITY_BAR_BADGE_FOREGROUND = crate::color::Color::hex(0x1e1e3f),
        ACTIVITY_BAR_ACTIVE_BORDER = crate::color::Color::hex_alpha(0x6943ff62),
        ACTIVITY_BAR_ACTIVE_BACKGROUND = crate::color::Color::hex(0x222244),
        DEBUG_ICON_START_FOREGROUND = crate::color::Color::hex(0xfad000),
        DEBUG_ICON_CONTINUE_FOREGROUND = crate::color::Color::hex(0xfad000),
        DEBUG_ICON_DISCONNECT_FOREGROUND = crate::color::Color::hex(0xfad000),
        DEBUG_ICON_PAUSE_FOREGROUND = crate::color::Color::hex(0xfad000),
        DEBUG_ICON_RESTART_FOREGROUND = crate::color::Color::hex(0x3ad900),
        DEBUG_ICON_STEP_BACK_FOREGROUND = crate::color::Color::hex(0xfad000),
        DEBUG_ICON_STEP_INTO_FOREGROUND = crate::color::Color::hex(0xfad000),
        DEBUG_ICON_STEP_OUT_FOREGROUND = crate::color::Color::hex(0xfad000),
        DEBUG_ICON_STEP_OVER_FOREGROUND = crate::color::Color::hex(0xfad000),
        DEBUG_ICON_STOP_FOREGROUND = crate::color::Color::hex_alpha(0xec3a37f5),
        SIDE_BAR_BACKGROUND = crate::color::Color::hex(0x222244),
        SIDE_BAR_BORDER = crate::color::Color::hex(0x25254b),
        SIDE_BAR_FOREGROUND = crate::color::Color::hex(0xa599e9),
        SIDE_BAR_SECTION_HEADER_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        SIDE_BAR_SECTION_HEADER_FOREGROUND = crate::color::Color::hex(0xa599e9),
        SIDE_BAR_TITLE_FOREGROUND = crate::color::Color::hex(0xa599e9),
        SIDE_BAR_SECTION_HEADER_BORDER = crate::color::Color::hex(0x1e1e3f),
        BADGE_BACKGROUND = crate::color::Color::hex(0xfad000),
        BADGE_FOREGROUND = crate::color::Color::hex(0x1e1e3f),
        BUTTON_BACKGROUND = crate::color::Color::hex_alpha(0xfad000dd),
        BUTTON_FOREGROUND = crate::color::Color::hex(0x222244),
        BUTTON_HOVER_BACKGROUND = crate::color::Color::hex(0xfad000),
        BUTTON_SECONDARY_BACKGROUND = crate::color::Color::hex_alpha(0xa599e9cc),
        BUTTON_SECONDARY_FOREGROUND = crate::color::Color::hex(0x222244),
        BUTTON_SECONDARY_HOVER_BACKGROUND = crate::color::Color::hex(0xa599e9),
        CHECKBOX_BACKGROUND = crate::color::Color::hex(0x222244),
        CHECKBOX_FOREGROUND = crate::color::Color::hex(0xfad000),
        CONTRAST_ACTIVE_BORDER = crate::color::Color::hex_alpha(0xffffff00),
        CONTRAST_BORDER = crate::color::Color::hex_alpha(0xffffff00),
        DESCRIPTION_FOREGROUND = crate::color::Color::hex(0xa599e9),
        SELECTION_BACKGROUND = crate::color::Color::hex(0xb362ff),
        DROPDOWN_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        DROPDOWN_BORDER = crate::color::Color::hex(0x1e1e3f),
        DROPDOWN_FOREGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        EDITOR_FOREGROUND = crate::color::Color::hex(0xffffff),
        EDITOR_LINE_NUMBER_FOREGROUND = crate::color::Color::hex(0xa599e9),
        EDITOR_CURSOR_FOREGROUND = crate::color::Color::hex(0xfad000),
        EDITOR_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0xb362ff88),
        EDITOR_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex_alpha(0x7580b8c0),
        EDITOR_SELECTION_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x7e46df46),
        EDITOR_LINKED_EDITING_BACKGROUND = crate::color::Color::hex_alpha(0x7e46dfaa),
        EDITOR_WORD_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xffffff0d),
        EDITOR_WORD_HIGHLIGHT_STRONG_BACKGROUND = crate::color::Color::hex_alpha(0xffffff0d),
        EDITOR_FIND_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0xff7300ab),
        EDITOR_FIND_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xffff0336),
        EDITOR_FIND_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0xffff0336),
        EDITOR_HOVER_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x1e1e3f80),
        EDITOR_LINE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x1f1f41),
        EDITOR_LINE_HIGHLIGHT_BORDER = crate::color::Color::hex(0x1f1f41),
        EDITOR_RANGE_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x1f1f41),
        EDITOR_LINK_ACTIVE_FOREGROUND = crate::color::Color::hex(0xa599e9),
        EDITOR_INDENT_GUIDE_BACKGROUND = crate::color::Color::hex_alpha(0xa599e90f),
        EDITOR_INDENT_GUIDE_ACTIVE_BACKGROUND = crate::color::Color::hex_alpha(0xa599e942),
        EDITOR_RULER_FOREGROUND = crate::color::Color::hex_alpha(0xa599e91c),
        EDITOR_OVERVIEW_RULER_BORDER = crate::color::Color::hex_alpha(0xa599e91c),
        EDITOR_CODE_LENS_FOREGROUND = crate::color::Color::hex(0xa599e9),
        EDITOR_BRACKET_MATCH_BACKGROUND = crate::color::Color::hex_alpha(0xad70fc46),
        EDITOR_BRACKET_MATCH_BORDER = crate::color::Color::hex_alpha(0xad70fc46),
        EDITOR_OVERVIEW_RULER_COMMON_CONTENT_FOREGROUND = crate::color::Color::hex_alpha(0xffc60055),
        EDITOR_OVERVIEW_RULER_CURRENT_CONTENT_FOREGROUND = crate::color::Color::hex_alpha(0xee3a4355),
        EDITOR_OVERVIEW_RULER_INCOMING_CONTENT_FOREGROUND = crate::color::Color::hex_alpha(0x3ad90055),
        EDITOR_ERROR_FOREGROUND = crate::color::Color::hex_alpha(0xec3a37f5),
        EDITOR_WARNING_BORDER = crate::color::Color::hex_alpha(0xffffff00),
        EDITOR_WARNING_FOREGROUND = crate::color::Color::hex(0xfad000),
        EDITOR_GUTTER_BACKGROUND = crate::color::Color::hex(0x28284e),
        EDITOR_GUTTER_ADDED_BACKGROUND = crate::color::Color::hex(0x35ad68),
        EDITOR_GUTTER_DELETED_BACKGROUND = crate::color::Color::hex_alpha(0xec3a37f5),
        EDITOR_GUTTER_MODIFIED_BACKGROUND = crate::color::Color::hex_alpha(0xad70fc46),
        DIFF_EDITOR_INSERTED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0x3ad90020),
        DIFF_EDITOR_REMOVED_TEXT_BACKGROUND = crate::color::Color::hex_alpha(0xee3a4320),
        EDITOR_GROUP_BORDER = crate::color::Color::hex(0x222244),
        EDITOR_GROUP_DROP_BACKGROUND = crate::color::Color::hex_alpha(0x222244d0),
        EDITOR_GROUP_HEADER_NO_TABS_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        EDITOR_GROUP_HEADER_TABS_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        EDITOR_GROUP_HEADER_TABS_BORDER = crate::color::Color::hex(0x1f1f41),
        TAB_ACTIVE_BACKGROUND = crate::color::Color::hex(0x222244),
        TAB_ACTIVE_FOREGROUND = crate::color::Color::hex(0xffffff),
        TAB_BORDER = crate::color::Color::hex(0x1e1e3f),
        TAB_ACTIVE_BORDER = crate::color::Color::hex(0xfad000),
        TAB_INACTIVE_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        TAB_INACTIVE_FOREGROUND = crate::color::Color::hex(0xa599e9),
        TAB_UNFOCUSED_ACTIVE_FOREGROUND = crate::color::Color::hex(0xa599e9),
        TAB_UNFOCUSED_INACTIVE_FOREGROUND = crate::color::Color::hex(0xa599e9),
        TAB_ACTIVE_MODIFIED_BORDER = crate::color::Color::hex(0xa599e9),
        TAB_INACTIVE_MODIFIED_BORDER = crate::color::Color::hex_alpha(0xa599e966),
        TAB_UNFOCUSED_ACTIVE_MODIFIED_BORDER = crate::color::Color::hex_alpha(0xa599e966),
        TAB_UNFOCUSED_INACTIVE_MODIFIED_BORDER = crate::color::Color::hex_alpha(0xa599e966),
        EDITOR_WIDGET_BACKGROUND = crate::color::Color::hex(0x222244),
        EDITOR_WIDGET_BORDER = crate::color::Color::hex(0x1f1f41),
        EDITOR_HOVER_WIDGET_BACKGROUND = crate::color::Color::hex(0x161633),
        EDITOR_HOVER_WIDGET_BORDER = crate::color::Color::hex(0x161633),
        EDITOR_SUGGEST_WIDGET_BACKGROUND = crate::color::Color::hex(0x1f1f41),
        EDITOR_SUGGEST_WIDGET_BORDER = crate::color::Color::hex(0x1f1f41),
        EDITOR_SUGGEST_WIDGET_FOREGROUND = crate::color::Color::hex(0xa599e9),
        EDITOR_SUGGEST_WIDGET_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xfad000),
        EDITOR_SUGGEST_WIDGET_SELECTED_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        DEBUG_TOOL_BAR_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        DEBUG_EXCEPTION_WIDGET_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        DEBUG_EXCEPTION_WIDGET_BORDER = crate::color::Color::hex(0xa599e9),
        EDITOR_MARKER_NAVIGATION_BACKGROUND = crate::color::Color::hex_alpha(0x3b536433),
        EDITOR_MARKER_NAVIGATION_ERROR_BACKGROUND = crate::color::Color::hex_alpha(0xec3a37f5),
        EDITOR_MARKER_NAVIGATION_WARNING_BACKGROUND = crate::color::Color::hex(0xfad000),
        EDITOR_WHITESPACE_FOREGROUND = crate::color::Color::hex_alpha(0xffffff1a),
        ERROR_FOREGROUND = crate::color::Color::hex_alpha(0xec3a37f5),
        EXTENSION_BUTTON_PROMINENT_BACKGROUND = crate::color::Color::hex(0x5d37f0),
        EXTENSION_BUTTON_PROMINENT_FOREGROUND = crate::color::Color::hex(0xffffff),
        EXTENSION_BUTTON_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0xff9d00),
        FOCUS_BORDER = crate::color::Color::hex(0x1e1e3f),
        FOREGROUND = crate::color::Color::hex(0xa599e9),
        INPUT_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        INPUT_BORDER = crate::color::Color::hex(0x1e1e3f),
        INPUT_FOREGROUND = crate::color::Color::hex(0xfad000),
        INPUT_PLACEHOLDER_FOREGROUND = crate::color::Color::hex(0xa599e9),
        INPUT_OPTION_ACTIVE_BORDER = crate::color::Color::hex(0x1e1e3f),
        INPUT_VALIDATION_ERROR_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        INPUT_VALIDATION_ERROR_BORDER = crate::color::Color::hex(0xfad000),
        INPUT_VALIDATION_INFO_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        INPUT_VALIDATION_INFO_BORDER = crate::color::Color::hex(0x2d2b55),
        INPUT_VALIDATION_WARNING_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        INPUT_VALIDATION_WARNING_BORDER = crate::color::Color::hex(0xfad000),
        INPUT_OPTION_ACTIVE_BACKGROUND = crate::color::Color::hex(0x5d37f0),
        LIST_DROP_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        LIST_ACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        LIST_ACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_FOCUS_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        LIST_FOCUS_FOREGROUND = crate::color::Color::hex(0xffffff),
        LIST_HIGHLIGHT_FOREGROUND = crate::color::Color::hex(0xfad000),
        LIST_HOVER_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        LIST_HOVER_FOREGROUND = crate::color::Color::hex(0xcec5ff),
        LIST_INACTIVE_SELECTION_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        LIST_INACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        MERGE_CURRENT_HEADER_BACKGROUND = crate::color::Color::hex_alpha(0x3ad90050),
        MERGE_CURRENT_CONTENT_BACKGROUND = crate::color::Color::hex_alpha(0x3ad90050),
        MERGE_INCOMING_HEADER_BACKGROUND = crate::color::Color::hex_alpha(0xa599e950),
        MERGE_INCOMING_CONTENT_BACKGROUND = crate::color::Color::hex_alpha(0xa599e950),
        NOTIFICATION_CENTER_BORDER = crate::color::Color::hex(0x1e1e3f),
        NOTIFICATION_CENTER_HEADER_FOREGROUND = crate::color::Color::hex(0xffffff),
        NOTIFICATION_CENTER_HEADER_BACKGROUND = crate::color::Color::hex(0x6943ff),
        NOTIFICATION_TOAST_BORDER = crate::color::Color::hex(0x1e1e3f),
        NOTIFICATIONS_FOREGROUND = crate::color::Color::hex(0xcec5ff),
        NOTIFICATIONS_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        NOTIFICATIONS_BORDER = crate::color::Color::hex(0x2d2b55),
        NOTIFICATION_LINK_FOREGROUND = crate::color::Color::hex(0xffffff),
        PANEL_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        PANEL_BORDER = crate::color::Color::hex(0xfad000),
        PANEL_TITLE_ACTIVE_BORDER = crate::color::Color::hex(0xfad000),
        PANEL_TITLE_ACTIVE_FOREGROUND = crate::color::Color::hex(0xfad000),
        PANEL_TITLE_INACTIVE_FOREGROUND = crate::color::Color::hex(0xa599e9),
        PEEK_VIEW_BORDER = crate::color::Color::hex(0xfad000),
        PEEK_VIEW_EDITOR_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        PEEK_VIEW_EDITOR_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x19354900),
        PEEK_VIEW_EDITOR_GUTTER_BACKGROUND = crate::color::Color::hex(0x191935),
        PEEK_VIEW_RESULT_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        PEEK_VIEW_RESULT_FILE_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        PEEK_VIEW_RESULT_LINE_FOREGROUND = crate::color::Color::hex(0xffffff),
        PEEK_VIEW_RESULT_MATCH_HIGHLIGHT_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        PEEK_VIEW_RESULT_SELECTION_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        PEEK_VIEW_RESULT_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        PEEK_VIEW_TITLE_BACKGROUND = crate::color::Color::hex(0x1f1f41),
        PEEK_VIEW_TITLE_DESCRIPTION_FOREGROUND = crate::color::Color::hex(0xaaaaaa),
        PEEK_VIEW_TITLE_LABEL_FOREGROUND = crate::color::Color::hex(0xfad000),
        PICKER_GROUP_BORDER = crate::color::Color::hex(0x1e1e3f),
        PICKER_GROUP_FOREGROUND = crate::color::Color::hex(0xa599e9),
        PROGRESS_BAR_BACKGROUND = crate::color::Color::hex(0xfad000),
        SCROLLBAR_SHADOW = crate::color::Color::hex_alpha(0xa599e981),
        SCROLLBAR_SLIDER_BACKGROUND = crate::color::Color::hex_alpha(0xa599e981),
        SCROLLBAR_SLIDER_HOVER_BACKGROUND = crate::color::Color::hex(0x4d21fc),
        SCROLLBAR_SLIDER_ACTIVE_BACKGROUND = crate::color::Color::hex(0xfad000),
        STATUS_BAR_BORDER = crate::color::Color::hex(0x1e1e3f),
        STATUS_BAR_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        STATUS_BAR_FOREGROUND = crate::color::Color::hex(0xa599e9),
        STATUS_BAR_DEBUGGING_BACKGROUND = crate::color::Color::hex(0xfad000),
        STATUS_BAR_DEBUGGING_FOREGROUND = crate::color::Color::hex(0x1e1e3f),
        STATUS_BAR_NO_FOLDER_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        STATUS_BAR_NO_FOLDER_FOREGROUND = crate::color::Color::hex(0xa599e9),
        STATUS_BAR_ITEM_ACTIVE_BACKGROUND = crate::color::Color::hex(0x4d21fc),
        STATUS_BAR_ITEM_HOVER_BACKGROUND = crate::color::Color::hex(0x4d21fc),
        STATUS_BAR_ITEM_PROMINENT_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        STATUS_BAR_ITEM_PROMINENT_HOVER_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        TERMINAL_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        TERMINAL_FOREGROUND = crate::color::Color::hex(0xffffff),
        TERMINAL_ANSI_BLACK = crate::color::Color::hex(0x000000),
        TERMINAL_ANSI_RED = crate::color::Color::hex_alpha(0xec3a37f5),
        TERMINAL_ANSI_GREEN = crate::color::Color::hex(0x3ad900),
        TERMINAL_ANSI_YELLOW = crate::color::Color::hex(0xfad000),
        TERMINAL_ANSI_BLUE = crate::color::Color::hex(0x7857fe),
        TERMINAL_ANSI_MAGENTA = crate::color::Color::hex(0xff2c70),
        TERMINAL_ANSI_CYAN = crate::color::Color::hex(0x80fcff),
        TERMINAL_ANSI_WHITE = crate::color::Color::hex(0xffffff),
        TERMINAL_ANSI_BRIGHT_BLACK = crate::color::Color::hex(0x5c5c61),
        TERMINAL_ANSI_BRIGHT_RED = crate::color::Color::hex_alpha(0xec3a37f5),
        TERMINAL_ANSI_BRIGHT_GREEN = crate::color::Color::hex(0x3ad900),
        TERMINAL_ANSI_BRIGHT_YELLOW = crate::color::Color::hex(0xfad000),
        TERMINAL_ANSI_BRIGHT_BLUE = crate::color::Color::hex(0x6943ff),
        TERMINAL_ANSI_BRIGHT_MAGENTA = crate::color::Color::hex(0xfb94ff),
        TERMINAL_ANSI_BRIGHT_CYAN = crate::color::Color::hex(0x80fcff),
        TERMINAL_ANSI_BRIGHT_WHITE = crate::color::Color::hex(0xffffff),
        TERMINAL_CURSOR_BACKGROUND = crate::color::Color::hex(0xfad000),
        TERMINAL_CURSOR_FOREGROUND = crate::color::Color::hex(0xfad000),
        GIT_DECORATION_MODIFIED_RESOURCE_FOREGROUND = crate::color::Color::hex(0xfad000),
        GIT_DECORATION_DELETED_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0xec3a37f5),
        GIT_DECORATION_UNTRACKED_RESOURCE_FOREGROUND = crate::color::Color::hex(0x3ad900),
        GIT_DECORATION_IGNORED_RESOURCE_FOREGROUND = crate::color::Color::hex_alpha(0xa599e981),
        GIT_DECORATION_CONFLICTING_RESOURCE_FOREGROUND = crate::color::Color::hex(0xff7200),
        TEXT_BLOCK_QUOTE_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        TEXT_BLOCK_QUOTE_BORDER = crate::color::Color::hex(0x6943ff),
        TEXT_CODE_BLOCK_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        TEXT_LINK_ACTIVE_FOREGROUND = crate::color::Color::hex(0xb362ff),
        TEXT_LINK_FOREGROUND = crate::color::Color::hex(0xb362ff),
        TEXT_PREFORMAT_FOREGROUND = crate::color::Color::hex(0xfad000),
        TEXT_SEPARATOR_FOREGROUND = crate::color::Color::hex(0x1e1e3f),
        TITLE_BAR_ACTIVE_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        TITLE_BAR_ACTIVE_FOREGROUND = crate::color::Color::hex(0xffffff),
        TITLE_BAR_INACTIVE_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        TITLE_BAR_INACTIVE_FOREGROUND = crate::color::Color::hex(0xa599e9),
        WALK_THROUGH_EMBEDDED_EDITOR_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        WELCOME_PAGE_BUTTON_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        WELCOME_PAGE_BUTTON_HOVER_BACKGROUND = crate::color::Color::hex(0x262650),
        WIDGET_SHADOW = crate::color::Color::hex_alpha(0x00000026),
        BREADCRUMB_FOREGROUND = crate::color::Color::hex(0xa599e9),
        BREADCRUMB_FOCUS_FOREGROUND = crate::color::Color::hex(0xfad000),
        BREADCRUMB_ACTIVE_SELECTION_FOREGROUND = crate::color::Color::hex(0xffffff),
        BREADCRUMB_PICKER_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        SETTINGS_HEADER_FOREGROUND = crate::color::Color::hex(0xffffff),
        SETTINGS_DROPDOWN_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        SETTINGS_CHECKBOX_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        SETTINGS_TEXT_INPUT_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        SETTINGS_NUMBER_INPUT_BACKGROUND = crate::color::Color::hex(0x1e1e3f),
        SETTINGS_DROPDOWN_FOREGROUND = crate::color::Color::hex(0xe5e4fb),
        SETTINGS_CHECKBOX_FOREGROUND = crate::color::Color::hex(0xe5e4fb),
        SETTINGS_TEXT_INPUT_FOREGROUND = crate::color::Color::hex(0xe5e4fb),
        SETTINGS_NUMBER_INPUT_FOREGROUND = crate::color::Color::hex(0xe5e4fb),
        SETTINGS_DROPDOWN_BORDER = crate::color::Color::hex(0x1e1e3f),
        SETTINGS_CHECKBOX_BORDER = crate::color::Color::hex(0x1e1e3f),
        SETTINGS_TEXT_INPUT_BORDER = crate::color::Color::hex(0x1e1e3f),
        SETTINGS_NUMBER_INPUT_BORDER = crate::color::Color::hex(0x1e1e3f),
        SETTINGS_DROPDOWN_LIST_BORDER = crate::color::Color::hex(0x2d2b55),
        SETTINGS_MODIFIED_ITEM_INDICATOR = crate::color::Color::hex(0xfad000),
        MENU_SEPARATOR_BACKGROUND = crate::color::Color::hex(0xa599e9),
        EDITOR_SNIPPET_TABSTOP_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x6943ff62),
        EDITOR_SNIPPET_TABSTOP_HIGHLIGHT_BORDER = crate::color::Color::hex_alpha(0x6943ff62),
        EDITOR_SNIPPET_FINAL_TABSTOP_HIGHLIGHT_BACKGROUND = crate::color::Color::hex_alpha(0x6943ff62),
        EDITOR_SNIPPET_FINAL_TABSTOP_HIGHLIGHT_BORDER = crate::color::Color::hex_alpha(0x6943ff62),
        LIST_FILTER_WIDGET_BACKGROUND = crate::color::Color::hex(0x2d2b55),
        LIST_FILTER_WIDGET_OUTLINE = crate::color::Color::hex(0x2d2b55),
        LIST_FILTER_WIDGET_NO_MATCHES_OUTLINE = crate::color::Color::hex_alpha(0xec3a37f5),
        SASH_HOVER_BORDER = crate::color::Color::hex(0xfad000),
        TOKEN_COMMENTS_THE_MAIN_COMMENTS_COLOR = crate::color::Color::hex(0xb362ff),
        TOKEN_ENTITY_THE_MAIN_ENTITY_COLOR = crate::color::Color::hex(0xfad000),
        TOKEN_CONSTANT_THE_MAIN_CONSTANTS_COLOR = crate::color::Color::hex(0xff628c),
        TOKEN_KEYWORD_THE_MAIN_COLOR_FOR_KEYWORD = crate::color::Color::hex(0xff9d00),
        TOKEN_META_THE_MAIN_COLOR_FOR_META = crate::color::Color::hex(0x9effff),
        TOKEN_INVALID_THE_MAIN_COLOR_FOR_INVALID = crate::color::Color::hex_alpha(0xec3a37f5),
        TOKEN_META_BRACE_THE_MAIN_COLOR_FOR_META_BRACE = crate::color::Color::hex(0xe1efff),
        TOKEN_PUNCTUATION_THE_MAIN_COLOR_FOR_PUNCTUATION = crate::color::Color::hex(0xe1efff),
        TOKEN_PUNCTUATION_COLOR_FOR_PUNCTUATION_PARAMETERS = crate::color::Color::hex(0xffee80),
        TOKEN_PUNCTUATION_COLOR_FOR_PUNCTUATION_TEMPLATE_EXPRESSION = crate::color::Color::hex(0xffee80),
        TOKEN_STORAGE_THE_MAIN_COLOR_FOR_STORAGE = crate::color::Color::hex(0xfad000),
        TOKEN_STORAGE_THE_COLOR_FOR_STORAGE_TYPE_ARROW_FUNCTION = crate::color::Color::hex(0xfad000),
        TOKEN_STRING = crate::color::Color::hex(0xa5ff90),
        TOKEN_STRING_TEMPLATE_COLOR = crate::color::Color::hex(0x3ad900),
        TOKEN_SUPPORT = crate::color::Color::hex(0x80ffbb),
        TOKEN_SUPPORT_FUNCTION_COLORS = crate::color::Color::hex(0xff9d00),
        TOKEN_SUPPORT_VARIABLE_PROPERTY_DOM_COLORS = crate::color::Color::hex(0x9effff),
        TOKEN_VARIABLE = crate::color::Color::hex(0xe1efff),
        TOKEN_INI_COLOR_FOR_ENTITY = crate::color::Color::hex(0xe1efff),
        TOKEN_INI_COLOR_FOR_KEYWORD = crate::color::Color::hex(0xfad000),
        TOKEN_INI_COLOR_FOR_PUNCTUATION_DEFINITION = crate::color::Color::hex(0xffee80),
        TOKEN_INI_COLOR_FOR_PUNCTUATION_SEPARATOR = crate::color::Color::hex(0xff9d00),
        TOKEN_CSS_COLOR_FOR_ENTITY = crate::color::Color::hex(0x3ad900),
        TOKEN_CSS_COLOR_FOR_CLASS_SELECTOR = crate::color::Color::hex(0x9effff),
        TOKEN_CSS_COLOR_FOR_ID_SELECTOR = crate::color::Color::hex(0xffb454),
        TOKEN_CSS_COLOR_FOR_ELEMENT_SELECTOR = crate::color::Color::hex(0x9effff),
        TOKEN_CSS_COLOR_FOR_SUPPORT = crate::color::Color::hex(0xa5ff90),
        TOKEN_CSS_COLOR_FOR_CONSTANT = crate::color::Color::hex(0xffee80),
        TOKEN_CSS_COLOR_FOR_STRING = crate::color::Color::hex(0xffee80),
        TOKEN_CSS_COLOR_FOR_VARIABLE = crate::color::Color::hex(0x9effff),
        TOKEN_HTML_COLOR_FOR_ENTITY_NAME = crate::color::Color::hex(0x9effff),
        TOKEN_HTML_COLOR_FOR_ID_VALUE = crate::color::Color::hex(0xa5ff90),
        TOKEN_HTML_COLOR_FOR_ENTITY_OTHER = crate::color::Color::hex(0xfad000),
        TOKEN_HTML_COLOR_FOR_SCRIPT_TAG = crate::color::Color::hex(0xfad000),
        TOKEN_HTML_QUOTES_DIFFERENT_COLOR_TO_HANDLE_EXPANDED_SELECTION = crate::color::Color::hex(0x92fc79),
        TOKEN_HTML_PUG_EQUALS_SIGN = crate::color::Color::hex(0xff9d00),
        TOKEN_JSON_COLOR_FOR_SUPPORT = crate::color::Color::hex(0xfad000),
        TOKEN_JSON_COLOR_FOR_STRING = crate::color::Color::hex(0x92fc79),
        TOKEN_JAVASCRIPT_COLOR_FOR_STORAGE_TYPE_FUNCTION = crate::color::Color::hex(0xfb94ff),
        TOKEN_JAVASCRIPT_COLOR_FOR_VARIABLE_LANGUAGE = crate::color::Color::hex(0xfb94ff),
        TOKEN_JAVASCRIPT_COLOR_FOR_INHERITED_COMPONENT = crate::color::Color::hex(0xffee80),
        TOKEN_JAVASCRIPT_COLOR_FOR_REACT_EXTENDS_KEYWORD = crate::color::Color::hex(0xff9d00),
        TOKEN_JAVASCRIPT_DOCS_KEYWORDS = crate::color::Color::hex(0xff9d00),
        TOKEN_JAVASCRIPT_DOC_VAR_TYPES = crate::color::Color::hex(0x9effff),
        TOKEN_JAVASCRIPT_VAR_TYPES = crate::color::Color::hex(0x9effff),
        TOKEN_JAVASCRIPT_REACT_JSX_HTML = crate::color::Color::hex(0x9effff),
        TOKEN_JAVASCRIPT_REACT_JSX_HTML_CHILDREN_TEXT = crate::color::Color::hex(0xffffff),
        TOKEN_JAVASCRIPT_STORAGE_TYPES = crate::color::Color::hex(0xff9d00),
        TOKEN_JAVASCRIPT_DOCS_USELESS_STUFF = crate::color::Color::hex(0x494685),
        TOKEN_TYPESCRIPT_REACT_ASSIGNMENT_OPERATOR = crate::color::Color::hex(0xff9d00),
        TOKEN_JAVASCRIPT_KEYWORD_OPERATOR_ASSIGNMENT = crate::color::Color::hex(0xff9d00),
        TOKEN_JAVASCRIPT_TYPESCRIPT_REACT_CHILDREN = crate::color::Color::hex(0xffffff),
        TOKEN_JAVASCRIPT_OBJECT_KEYS = crate::color::Color::hex(0x80ffbb),
        TOKEN_TYPESCRIPT_REACT_CLASSNAMES_AND_MODULES = crate::color::Color::hex(0x9effff),
        TOKEN_JAVASCRIPT_SOMETHING = crate::color::Color::hex(0xffee80),
        TOKEN_JAVASCRIPT_COLOR_FOR_TEXT_INSIDE_JSX = crate::color::Color::hex(0xffffff),
        TOKEN_JAVASCRIPT_PARAMETERS = crate::color::Color::hex(0x9effff),
        TOKEN_PYTHON_COLOR_FOR_SELF_ARGUMENT = crate::color::Color::hex(0x9effff),
        TOKEN_PYTHON_FUNCTIONS = crate::color::Color::hex(0xfad000),
        TOKEN_TYPESCRIPT_COLOR_FOR_ENTITY_NAME_TYPE = crate::color::Color::hex(0x80ffbb),
        TOKEN_TYPESCRIPT_COLOR_FOR_KEYWORD = crate::color::Color::hex(0xfad000),
        TOKEN_TYPESCRIPT_COLOR_FOR_PUNCTUATION_PARAMETERS = crate::color::Color::hex(0xe1efff),
        TOKEN_TYPESCRIPT_COLOR_FOR_PUNCTUATION_ARROW_PARAMETERS = crate::color::Color::hex(0xffee80),
        TOKEN_TYPESCRIPT_COLOR_FOR_STORAGE = crate::color::Color::hex(0x9effff),
        TOKEN_MARKDOWN_COLOR_FOR_HEADING_NAME_SECTION = crate::color::Color::hex(0xfad000),
        TOKEN_MARKDOWN_DIFF_CODE_INSERTED_BLOCK = crate::color::Color::hex(0x8efa00),
        TOKEN_MARKDOWN_DIFF_DELETED_CODE_BLOCK = crate::color::Color::hex(0xf16e6b),
        TOKEN_MARKDOWN_DIFF_META_TEXT = crate::color::Color::hex(0xffffff),
        TOKEN_MARKDOWN_COLOR_FOR_PARAGRAPH = crate::color::Color::hex(0xffffff),
        TOKEN_MARKDOWN_COMMENT_PUNCTUATION = crate::color::Color::hex(0xb362ff),
        TOKEN_MARKDOWN_COLOR_FOR_TEXT_INSIDE_INLINE_CODE_BLOCK_CODE = crate::color::Color::hex(0xa599e9),
        TOKEN_MARKDOWN_COLOR_FOR_QUOTE_PUNCTUATION = crate::color::Color::hex(0xfad000),
        TOKEN_MARKDOWN_COLOR_FOR_QUOTE_PARAGRAPH = crate::color::Color::hex(0xa599e9),
        TOKEN_MARKDOWN_COLOR_FOR_SEPARATOR = crate::color::Color::hex(0xfad000),
        TOKEN_MARKDOWN_COLOR_FOR_LISTS = crate::color::Color::hex(0xfad000),
        TOKEN_MARKDOWN_LINK_IMAGE_TITLE_STRING = crate::color::Color::hex(0xa5ff90),
        TOKEN_MARKDOWN_COLOR_FOR_LINK_TITLE = crate::color::Color::hex(0xfad000),
        TOKEN_MARKDOWN_COLOR_FOR_LINK_IMAGE_TITLE = crate::color::Color::hex(0xa599e9),
        TOKEN_MARKDOWN_COLOR_FOR_INLINE_CODE = crate::color::Color::hex(0x9effff),
        TOKEN_MARKDOWN_COLOR_FOR_PUNCTUATION_HEADING_CODE_AND_FENCED_CODE_BLOCKS_BOLD = crate::color::Color::hex(0x494685),
        TOKEN_MARKDOWN_LINK_BRACKETS = crate::color::Color::hex(0xfad000),
        TOKEN_MARKDOWN_IMG_LINK_BRACKETS = crate::color::Color::hex(0xff9d00),
        TOKEN_MARKDOWN_LINK_ALT_URI = crate::color::Color::hex(0xa599e9),
        TOKEN_PUG_COLOR_FOR_ENTITY_NAME = crate::color::Color::hex(0x9effff),
        TOKEN_PUG_TYPES = crate::color::Color::hex(0xff9d00),
        TOKEN_PUG_VAR_PARAMS = crate::color::Color::hex(0x9effff),
        TOKEN_PUG_IMPORTS = crate::color::Color::hex(0x92fc79),
        TOKEN_PUG_COLOR_FOR_STRING_INTERPOLATED = crate::color::Color::hex(0xffee80),
        TOKEN_C_COLOR_FOR_ANNOTATIONS = crate::color::Color::hex(0x9effff),
        TOKEN_C_COLOR_FOR_PROPERTIES = crate::color::Color::hex(0x9effff),
        TOKEN_C_COLOR_FOR_STORAGE_MODIFIERS = crate::color::Color::hex(0x80ffbb),
        TOKEN_PHP_COLOR_FOR_ENTITY = crate::color::Color::hex(0x9effff),
        TOKEN_PHP_DOCS_KEYWORDS = crate::color::Color::hex(0xff9d00),
        TOKEN_PHP_FUNCTIONS = crate::color::Color::hex(0xfad000),
        TOKEN_PHP_VARIABLES = crate::color::Color::hex(0x9effff),
        TOKEN_PHP_COLOR_FOR_STORAGE_MODIFIERS = crate::color::Color::hex(0xff9d00),
        TOKEN_YML_KEYWORDS = crate::color::Color::hex(0xfad000),
        TOKEN_YML_PUNCTUATION = crate::color::Color::hex(0xe1efff),
        TOKEN_PHP_KEYWORDS_FOR_DEFINITION = crate::color::Color::hex(0xfb94ff),
        TOKEN_PHP_BLADE_KEYWORDS_FOR_DEFINITION = crate::color::Color::hex(0xff9d00),
        TOKEN_PHP_BLADE_PUNCTUATION = crate::color::Color::hex(0xe1efff),
        TOKEN_PHP_BLADE_CONSTRUCT = crate::color::Color::hex(0xffee80),
        TOKEN_GO_KEYWORDS_FOR_DEFINITION = crate::color::Color::hex(0xff9d00),
        TOKEN_GO_FUNCTIONS = crate::color::Color::hex(0xfb94ff),
        TOKEN_GO_VARIABLES = crate::color::Color::hex(0x9effff),
        TOKEN_GO_PUNCTUATION = crate::color::Color::hex(0xfad000),
        TOKEN_RUBY_INTERPOLATION_QUOTED_DOUBLE_BLOCK_INLINE = crate::color::Color::hex(0xffee80),
        TOKEN_RUBY_CONSTANT = crate::color::Color::hex(0x80ffbb),
        TOKEN_RUBY_CLASS = crate::color::Color::hex(0xfb94ff),
        TOKEN_RUBY_VARIABLES = crate::color::Color::hex(0x9effff),
        TOKEN_RUBY_SEPARATORS = crate::color::Color::hex(0xff9d00),
        TOKEN_RUBY_SPECIAL_METHODS = crate::color::Color::hex(0xffee80),
        TOKEN_SHELL_FUNCTION_KEYWORD = crate::color::Color::hex(0xfb94ff),
        TOKEN_SHELL_VAR_OTHER = crate::color::Color::hex(0xff9d00),
        TOKEN_GRAPHQL_VARIABLE = crate::color::Color::hex(0xfaefa5),
        TOKEN_GRAPHQL_KEYWORDS = crate::color::Color::hex(0xfb94ff),
        TOKEN_SQL_SOURCE = crate::color::Color::hex(0xe1efff),
        TOKEN_SQL_KEYWORDS = crate::color::Color::hex(0xfaefa5),
        TOKEN_SQL_FUNCTIONS_USED = crate::color::Color::hex(0xfad000),
        TOKEN_SQL_REG_EXP_STRING = crate::color::Color::hex(0xe1efff),
        TOKEN_SQL_OTHER_KEYWORDS = crate::color::Color::hex(0xff9d00),
        TOKEN_TOML_SYNTAX = crate::color::Color::hex(0xe1efff),
        TOKEN_TOML_OTHER_KEYWORDS = crate::color::Color::hex(0xff9d00),
        TOKEN_TOML_KEYWORDS = crate::color::Color::hex(0xfad000),
        TOKEN_DOCKER_KEYWORDS = crate::color::Color::hex(0xfad000),
        TOKEN_RUST_KEYWORDS = crate::color::Color::hex(0xff9d00),
        TOKEN_RUST_KEYWORD_FN = crate::color::Color::hex(0xfb94ff),
        TOKEN_ENV_KEYWORD = crate::color::Color::hex(0xff9d00),
        TOKEN_ENV_VARIABLE = crate::color::Color::hex(0xfad000),
        TOKEN_ENV_SOURCE = crate::color::Color::hex(0xe1efff),
        TOKEN_ENV_PUNCTUATION = crate::color::Color::hex(0xff9d00),
        TOKEN_JS_DOUBLE_DESTRUCTURE_OF_OBJECT = crate::color::Color::hex(0x9effff),
        TOKEN_JS_REGEX = crate::color::Color::hex(0xfb94ff),
        TOKEN_CSV_KEYWORD_2 = crate::color::Color::hex(0xff9d00),
        TOKEN_NIM_KEYWORD = crate::color::Color::hex(0xff9d00),
        TOKEN_NIM_BOOLEAN = crate::color::Color::hex(0xff628c),
        TOKEN_NIM = crate::color::Color::hex(0xfad000),
        TOKEN_DELETED = crate::color::Color::hex(0xf16e6b),
        TOKEN_INSERTED = crate::color::Color::hex(0x8efa00),
    }
    accents {
        Red = TERMINAL_ANSI_RED => ("red", "Red"),
        Green = TERMINAL_ANSI_GREEN => ("green", "Green"),
        Yellow = TERMINAL_ANSI_YELLOW => ("yellow", "Yellow"),
        Blue = TERMINAL_ANSI_BLUE => ("blue", "Blue"),
        Magenta = TERMINAL_ANSI_MAGENTA => ("magenta", "Magenta"),
        Cyan = TERMINAL_ANSI_CYAN => ("cyan", "Cyan"),
    }
    default TERMINAL_ANSI_YELLOW => "yellow";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::EDITOR_BACKGROUND,
            surface: Self::SIDE_BAR_BACKGROUND,
            raised: Self::DROPDOWN_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::SIDE_BAR_BACKGROUND,
            surface: Self::EDITOR_BACKGROUND,
            raised: Self::SIDE_BAR_BACKGROUND,
            overlay: Self::EDITOR_WIDGET_BACKGROUND,
            hover: Self::LIST_HOVER_BACKGROUND,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::EDITOR_FOREGROUND,
            muted: Self::DESCRIPTION_FOREGROUND,
            subtle: Self::EDITOR_LINE_NUMBER_FOREGROUND,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::TERMINAL_ANSI_MAGENTA),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::SIDE_BAR_BACKGROUND,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::TERMINAL_ANSI_MAGENTA,
            hover: crate::palette::primary_hover(Self::TERMINAL_ANSI_MAGENTA),
            pressed: crate::palette::action_pressed(Self::TERMINAL_ANSI_MAGENTA),
            muted: Self::SIDE_BAR_BACKGROUND,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::TERMINAL_ANSI_GREEN,
            warning: Self::EDITOR_WARNING_FOREGROUND,
            error: Self::EDITOR_ERROR_FOREGROUND,
            critical: Self::TERMINAL_ANSI_BRIGHT_RED,
            info: Self::TERMINAL_ANSI_BLUE,
            trace: Self::EDITOR_LINE_NUMBER_FOREGROUND,
        },
        border: Self::EDITOR_WIDGET_BORDER,
        border_muted: Self::SIDE_BAR_BACKGROUND,
        focus: primary,
    }
}
