#!/usr/bin/env python3
"""Tests for the staged CSS pre-commit check and its installer."""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HOOK = ROOT / ".githooks/pre-commit"
INSTALLER = ROOT / "tools/install-hooks.sh"
GENERATOR = ROOT / "tools/generate_css.rs"
DEFINITIONS = ROOT / "src/css/definitions.rs"
CSS = ROOT / "src/css/default.css"


def run(*args: str, cwd: Path, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, cwd=cwd, text=True, capture_output=True, check=check)


def make_repo() -> tuple[tempfile.TemporaryDirectory[str], Path]:
    temp = tempfile.TemporaryDirectory(prefix="ferriswatch-css-hook-test-")
    repo = Path(temp.name)
    run("git", "init", "-q", cwd=repo)
    for source in (GENERATOR, DEFINITIONS, CSS):
        target = repo / source.relative_to(ROOT)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
    run("git", "add", ".", cwd=repo)
    run("git", "-c", "commit.gpgsign=false", "-c", "user.name=Hook Test", "-c", "user.email=hook@example.test", "commit", "-qm", "initial", cwd=repo)
    return temp, repo


def install_hook(repo: Path) -> None:
    hooks = repo / ".githooks"
    hooks.mkdir()
    shutil.copyfile(HOOK, hooks / "pre-commit")
    (hooks / "pre-commit").chmod(0o755)
    run("git", "config", "core.hooksPath", ".githooks", cwd=repo)


def commit(repo: Path, message: str = "change") -> subprocess.CompletedProcess[str]:
    return run("git", "-c", "commit.gpgsign=false", "-c", "user.name=Hook Test", "-c", "user.email=hook@example.test", "commit", "-m", message, cwd=repo, check=False)


def test_clean_and_unstaged_mismatch() -> None:
    temp, repo = make_repo()
    try:
        install_hook(repo)
        marker = repo / "file with spaces.txt"
        marker.write_text("staged marker\n", encoding="utf-8")
        run("git", "add", str(marker), cwd=repo)
        clean = commit(repo)
        assert clean.returncode == 0, clean.stderr
        css = repo / CSS.relative_to(ROOT)
        original = css.read_bytes()
        css.write_bytes(b"stale working tree\n")
        marker.write_text("second staged marker\n", encoding="utf-8")
        run("git", "add", str(marker), cwd=repo)
        result = commit(repo)
        assert result.returncode == 0, result.stderr + result.stdout
        assert css.read_bytes() == b"stale working tree\n"
        assert original != css.read_bytes()
    finally:
        temp.cleanup()


def test_stale_and_missing_staged_css() -> None:
    temp, repo = make_repo()
    try:
        install_hook(repo)
        css = repo / CSS.relative_to(ROOT)
        css.write_bytes(b"stale staged CSS\n")
        run("git", "add", str(css), cwd=repo)
        result = commit(repo)
        assert result.returncode != 0
        assert "stale" in (result.stderr + result.stdout).lower()
        run("git", "restore", "--staged", str(css), cwd=repo)
        css.unlink()
        run("git", "add", "-u", cwd=repo)
        result = commit(repo)
        assert result.returncode != 0
    finally:
        temp.cleanup()


def test_partially_staged_generator_change() -> None:
    temp, repo = make_repo()
    try:
        install_hook(repo)
        definitions = repo / DEFINITIONS.relative_to(ROOT)
        css = repo / CSS.relative_to(ROOT)
        definitions.write_text(
            definitions.read_text(encoding="utf-8").replace(
                "Generated by ferriswatch-generate-css.",
                "Generated by ferriswatch-generate-css changed.",
            ),
            encoding="utf-8",
        )
        run(
            "rustc",
            "--edition=2024",
            str(repo / GENERATOR.relative_to(ROOT)),
            "-o",
            str(repo / "ferriswatch-generate-css"),
            cwd=repo,
        )
        run("./ferriswatch-generate-css", cwd=repo)
        run("git", "add", str(definitions), cwd=repo)
        definitions_before = definitions.read_bytes()
        css_before = css.read_bytes()
        marker = repo / "staged marker"
        marker.write_text("commit this\n", encoding="utf-8")
        run("git", "add", str(marker), cwd=repo)
        index_before = run("git", "diff", "--cached", cwd=repo).stdout
        result = commit(repo)
        assert result.returncode != 0
        assert "stale" in (result.stderr + result.stdout).lower()
        assert run("git", "diff", "--cached", cwd=repo).stdout == index_before
        assert definitions.read_bytes() == definitions_before
        assert css.read_bytes() == css_before
    finally:
        temp.cleanup()


def test_installer_preserves_existing_hook() -> None:
    temp, repo = make_repo()
    try:
        hooks = repo / ".git/hooks"
        existing = hooks / "pre-commit"
        existing.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        existing.chmod(0o755)
        before = existing.read_bytes()
        result = run("sh", str(INSTALLER), cwd=repo)
        assert result.returncode == 0
        assert existing.read_bytes() == before
        assert run("git", "config", "--get", "core.hooksPath", cwd=repo, check=False).returncode != 0
    finally:
        temp.cleanup()


def test_installer_preserves_unrelated_executable_hook() -> None:
    temp, repo = make_repo()
    try:
        existing = repo / ".git/hooks/pre-push"
        existing.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        existing.chmod(0o755)
        result = run("sh", str(INSTALLER), cwd=repo)
        assert result.returncode == 0
        assert "pre-push" in result.stdout
        assert run("git", "config", "--get", "core.hooksPath", cwd=repo, check=False).returncode != 0
    finally:
        temp.cleanup()


def test_installer_preserves_custom_hooks_path() -> None:
    temp, repo = make_repo()
    try:
        run("git", "config", "core.hooksPath", ".custom-hooks", cwd=repo)
        result = run("sh", str(INSTALLER), cwd=repo)
        assert result.returncode == 0
        assert ".custom-hooks" in result.stdout
        assert run("git", "config", "--get", "core.hooksPath", cwd=repo).stdout.strip() == ".custom-hooks"
    finally:
        temp.cleanup()


def test_installer_configures_when_no_hook_exists() -> None:
    temp, repo = make_repo()
    try:
        result = run("sh", str(INSTALLER), cwd=repo)
        assert result.returncode == 0
        assert run("git", "config", "--get", "core.hooksPath", cwd=repo).stdout.strip() == ".githooks"
    finally:
        temp.cleanup()


if __name__ == "__main__":
    test_clean_and_unstaged_mismatch()
    test_stale_and_missing_staged_css()
    test_partially_staged_generator_change()
    test_installer_preserves_existing_hook()
    test_installer_preserves_unrelated_executable_hook()
    test_installer_preserves_custom_hooks_path()
    test_installer_configures_when_no_hook_exists()
    print("CSS hook tests passed")
