//! GitHub Dark. See `REGISTRATION` for pinned upstream sources.
//!
//! GitHub default theme with Primer 7.10.0 and explicit fg/accent overrides. Canvas inset/subtle/overlay retain their meanings. Actions use the selected curated scale hue; status hues remain independent.

define_palette! {
    Dark, "GitHub Dark",
    identity("github/dark", "github", "GitHub", "dark", "Dark", Dark, None);
    support(Dark);
    sources: super::SOURCE_DARK;
    colors {
        SCALE_GRAY_0 = crate::color::Color::hex(0xf0f6fc),
        SCALE_GRAY_1 = crate::color::Color::hex(0xc9d1d9),
        SCALE_GRAY_2 = crate::color::Color::hex(0xb1bac4),
        SCALE_GRAY_3 = crate::color::Color::hex(0x8b949e),
        SCALE_GRAY_4 = crate::color::Color::hex(0x6e7681),
        SCALE_GRAY_5 = crate::color::Color::hex(0x484f58),
        SCALE_GRAY_6 = crate::color::Color::hex(0x30363d),
        SCALE_GRAY_7 = crate::color::Color::hex(0x21262d),
        SCALE_GRAY_8 = crate::color::Color::hex(0x161b22),
        SCALE_GRAY_9 = crate::color::Color::hex(0x0d1117),
        SCALE_BLUE_0 = crate::color::Color::hex(0xcae8ff),
        SCALE_BLUE_1 = crate::color::Color::hex(0xa5d6ff),
        SCALE_BLUE_2 = crate::color::Color::hex(0x79c0ff),
        SCALE_BLUE_3 = crate::color::Color::hex(0x58a6ff),
        SCALE_BLUE_4 = crate::color::Color::hex(0x388bfd),
        SCALE_BLUE_5 = crate::color::Color::hex(0x1f6feb),
        SCALE_BLUE_6 = crate::color::Color::hex(0x1158c7),
        SCALE_BLUE_7 = crate::color::Color::hex(0x0d419d),
        SCALE_BLUE_8 = crate::color::Color::hex(0x0c2d6b),
        SCALE_BLUE_9 = crate::color::Color::hex(0x051d4d),
        SCALE_GREEN_0 = crate::color::Color::hex(0xaff5b4),
        SCALE_GREEN_1 = crate::color::Color::hex(0x7ee787),
        SCALE_GREEN_2 = crate::color::Color::hex(0x56d364),
        SCALE_GREEN_3 = crate::color::Color::hex(0x3fb950),
        SCALE_GREEN_4 = crate::color::Color::hex(0x2ea043),
        SCALE_GREEN_5 = crate::color::Color::hex(0x238636),
        SCALE_GREEN_6 = crate::color::Color::hex(0x196c2e),
        SCALE_GREEN_7 = crate::color::Color::hex(0x0f5323),
        SCALE_GREEN_8 = crate::color::Color::hex(0x033a16),
        SCALE_GREEN_9 = crate::color::Color::hex(0x04260f),
        SCALE_YELLOW_0 = crate::color::Color::hex(0xf8e3a1),
        SCALE_YELLOW_1 = crate::color::Color::hex(0xf2cc60),
        SCALE_YELLOW_2 = crate::color::Color::hex(0xe3b341),
        SCALE_YELLOW_3 = crate::color::Color::hex(0xd29922),
        SCALE_YELLOW_4 = crate::color::Color::hex(0xbb8009),
        SCALE_YELLOW_5 = crate::color::Color::hex(0x9e6a03),
        SCALE_YELLOW_6 = crate::color::Color::hex(0x845306),
        SCALE_YELLOW_7 = crate::color::Color::hex(0x693e00),
        SCALE_YELLOW_8 = crate::color::Color::hex(0x4b2900),
        SCALE_YELLOW_9 = crate::color::Color::hex(0x341a00),
        SCALE_ORANGE_0 = crate::color::Color::hex(0xffdfb6),
        SCALE_ORANGE_1 = crate::color::Color::hex(0xffc680),
        SCALE_ORANGE_2 = crate::color::Color::hex(0xffa657),
        SCALE_ORANGE_3 = crate::color::Color::hex(0xf0883e),
        SCALE_ORANGE_4 = crate::color::Color::hex(0xdb6d28),
        SCALE_ORANGE_5 = crate::color::Color::hex(0xbd561d),
        SCALE_ORANGE_6 = crate::color::Color::hex(0x9b4215),
        SCALE_ORANGE_7 = crate::color::Color::hex(0x762d0a),
        SCALE_ORANGE_8 = crate::color::Color::hex(0x5a1e02),
        SCALE_ORANGE_9 = crate::color::Color::hex(0x3d1300),
        SCALE_RED_0 = crate::color::Color::hex(0xffdcd7),
        SCALE_RED_1 = crate::color::Color::hex(0xffc1ba),
        SCALE_RED_2 = crate::color::Color::hex(0xffa198),
        SCALE_RED_3 = crate::color::Color::hex(0xff7b72),
        SCALE_RED_4 = crate::color::Color::hex(0xf85149),
        SCALE_RED_5 = crate::color::Color::hex(0xda3633),
        SCALE_RED_6 = crate::color::Color::hex(0xb62324),
        SCALE_RED_7 = crate::color::Color::hex(0x8e1519),
        SCALE_RED_8 = crate::color::Color::hex(0x67060c),
        SCALE_RED_9 = crate::color::Color::hex(0x490202),
        SCALE_PURPLE_0 = crate::color::Color::hex(0xeddeff),
        SCALE_PURPLE_1 = crate::color::Color::hex(0xe2c5ff),
        SCALE_PURPLE_2 = crate::color::Color::hex(0xd2a8ff),
        SCALE_PURPLE_3 = crate::color::Color::hex(0xbc8cff),
        SCALE_PURPLE_4 = crate::color::Color::hex(0xa371f7),
        SCALE_PURPLE_5 = crate::color::Color::hex(0x8957e5),
        SCALE_PURPLE_6 = crate::color::Color::hex(0x6e40c9),
        SCALE_PURPLE_7 = crate::color::Color::hex(0x553098),
        SCALE_PURPLE_8 = crate::color::Color::hex(0x3c1e70),
        SCALE_PURPLE_9 = crate::color::Color::hex(0x271052),
        SCALE_PINK_0 = crate::color::Color::hex(0xffdaec),
        SCALE_PINK_1 = crate::color::Color::hex(0xffbedd),
        SCALE_PINK_2 = crate::color::Color::hex(0xff9bce),
        SCALE_PINK_3 = crate::color::Color::hex(0xf778ba),
        SCALE_PINK_4 = crate::color::Color::hex(0xdb61a2),
        SCALE_PINK_5 = crate::color::Color::hex(0xbf4b8a),
        SCALE_PINK_6 = crate::color::Color::hex(0x9e3670),
        SCALE_PINK_7 = crate::color::Color::hex(0x7d2457),
        SCALE_PINK_8 = crate::color::Color::hex(0x5e103e),
        SCALE_PINK_9 = crate::color::Color::hex(0x42062a),
        SCALE_CORAL_0 = crate::color::Color::hex(0xffddd2),
        SCALE_CORAL_1 = crate::color::Color::hex(0xffc2b2),
        SCALE_CORAL_2 = crate::color::Color::hex(0xffa28b),
        SCALE_CORAL_3 = crate::color::Color::hex(0xf78166),
        SCALE_CORAL_4 = crate::color::Color::hex(0xea6045),
        SCALE_CORAL_5 = crate::color::Color::hex(0xcf462d),
        SCALE_CORAL_6 = crate::color::Color::hex(0xac3220),
        SCALE_CORAL_7 = crate::color::Color::hex(0x872012),
        SCALE_CORAL_8 = crate::color::Color::hex(0x640d04),
        SCALE_CORAL_9 = crate::color::Color::hex(0x460701),
        SCALE_BLACK = crate::color::Color::hex(0x010409),
        SCALE_WHITE = crate::color::Color::hex(0xffffff),
        FG_DEFAULT = crate::color::Color::hex(0xe6edf3),
        FG_MUTED = crate::color::Color::hex(0x7d8590),
        FG_SUBTLE = crate::color::Color::hex(0x6e7681),
        FG_ON_EMPHASIS = crate::color::Color::hex(0xffffff),
        CANVAS_DEFAULT = crate::color::Color::hex(0x0d1117),
        CANVAS_OVERLAY = crate::color::Color::hex(0x161b22),
        CANVAS_INSET = crate::color::Color::hex(0x010409),
        CANVAS_SUBTLE = crate::color::Color::hex(0x161b22),
        BORDER_DEFAULT = crate::color::Color::hex(0x30363d),
        BORDER_MUTED = crate::color::Color::hex(0x21262d),
        NEUTRAL_EMPHASIS_PLUS = crate::color::Color::hex(0x6e7681),
        NEUTRAL_EMPHASIS = crate::color::Color::hex(0x6e7681),
        ACCENT_FG = crate::color::Color::hex(0x2f81f7),
        ACCENT_EMPHASIS = crate::color::Color::hex(0x1f6feb),
        SUCCESS_FG = crate::color::Color::hex(0x3fb950),
        SUCCESS_EMPHASIS = crate::color::Color::hex(0x238636),
        ATTENTION_FG = crate::color::Color::hex(0xd29922),
        ATTENTION_EMPHASIS = crate::color::Color::hex(0x9e6a03),
        SEVERE_FG = crate::color::Color::hex(0xdb6d28),
        SEVERE_EMPHASIS = crate::color::Color::hex(0xbd561d),
        DANGER_FG = crate::color::Color::hex(0xf85149),
        DANGER_EMPHASIS = crate::color::Color::hex(0xda3633),
        OPEN_FG = crate::color::Color::hex(0x3fb950),
        OPEN_EMPHASIS = crate::color::Color::hex(0x238636),
        CLOSED_FG = crate::color::Color::hex(0xf85149),
        CLOSED_EMPHASIS = crate::color::Color::hex(0xda3633),
        DONE_FG = crate::color::Color::hex(0xa371f7),
        DONE_EMPHASIS = crate::color::Color::hex(0x8957e5),
        SPONSORS_FG = crate::color::Color::hex(0xdb61a2),
        SPONSORS_EMPHASIS = crate::color::Color::hex(0xbf4b8a),
        PRIMER_DISABLED = crate::color::Color::hex(0x484f58),
        PRIMER_ACTIVE = crate::color::Color::hex(0xf78166),
    }
    accents {
        Blue = SCALE_BLUE_3 => ("blue", "Blue"),
        Green = SCALE_GREEN_3 => ("green", "Green"),
        Yellow = SCALE_YELLOW_3 => ("yellow", "Yellow"),
        Orange = SCALE_ORANGE_3 => ("orange", "Orange"),
        Red = SCALE_RED_3 => ("red", "Red"),
        Purple = SCALE_PURPLE_3 => ("purple", "Purple"),
        Pink = SCALE_PINK_3 => ("pink", "Pink"),
    }
    default SCALE_BLUE_3 => "blue";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::CANVAS_DEFAULT,
            surface: Self::CANVAS_SUBTLE,
            raised: Self::CANVAS_OVERLAY,
            overlay: Self::CANVAS_OVERLAY,
            hover: Self::BORDER_DEFAULT,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::CANVAS_INSET,
            surface: Self::CANVAS_DEFAULT,
            raised: Self::CANVAS_SUBTLE,
            overlay: Self::CANVAS_OVERLAY,
            hover: Self::BORDER_DEFAULT,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FG_DEFAULT,
            muted: Self::FG_MUTED,
            subtle: Self::FG_SUBTLE,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::ACCENT_EMPHASIS),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::CANVAS_SUBTLE,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::ACCENT_EMPHASIS,
            hover: crate::palette::primary_hover(Self::ACCENT_EMPHASIS),
            pressed: crate::palette::action_pressed(Self::ACCENT_EMPHASIS),
            muted: Self::CANVAS_SUBTLE,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::SUCCESS_FG,
            warning: Self::ATTENTION_FG,
            error: Self::DANGER_FG,
            critical: Self::DANGER_EMPHASIS,
            info: Self::ACCENT_FG,
            trace: Self::FG_SUBTLE,
        },
        border: Self::BORDER_DEFAULT,
        border_muted: Self::BORDER_MUTED,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::SCALE_RED_3,
            orange: Self::SCALE_ORANGE_3,
            yellow: Self::SCALE_YELLOW_3,
            green: Self::SCALE_GREEN_3,
            cyan: Self::SCALE_BLUE_3,
            blue: Self::SCALE_BLUE_3,
            purple: Self::SCALE_PURPLE_3,
            pink: Self::SCALE_PINK_3,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::SCALE_ORANGE_2,
            boolean: Self::SCALE_BLUE_2,
            builtin: Self::SCALE_ORANGE_2,
            builtin_function: Self::SCALE_PURPLE_2,
            builtin_type: Self::SCALE_ORANGE_2,
            comment: Self::FG_MUTED,
            constant: Self::SCALE_BLUE_2,
            control_keyword: Self::SCALE_RED_3,
            deleted: Self::DANGER_FG,
            deprecated: Self::DANGER_FG,
            documentation: Self::FG_MUTED,
            escape: Self::SCALE_RED_3,
            foreground: Self::FG_DEFAULT,
            function: Self::SCALE_PURPLE_2,
            heading: Self::SCALE_PURPLE_2,
            inserted: Self::SUCCESS_FG,
            invalid: Self::DANGER_FG,
            keyword: Self::SCALE_RED_3,
            link: Self::SCALE_PURPLE_2,
            markup_bold: Self::FG_DEFAULT,
            markup_italic: Self::FG_DEFAULT,
            modifier: Self::SCALE_RED_3,
            namespace: Self::SCALE_ORANGE_2,
            number: Self::SCALE_BLUE_2,
            operator: Self::SCALE_RED_3,
            parameter: Self::FG_DEFAULT,
            property: Self::FG_DEFAULT,
            punctuation: Self::FG_DEFAULT,
            string: Self::SCALE_BLUE_1,
            tag: Self::SCALE_RED_3,
            type_keyword: Self::SCALE_RED_3,
            type_name: Self::SCALE_ORANGE_2,
            variable: Self::FG_DEFAULT,
        },
    }
}
