//! GitHub Light. See `REGISTRATION` for pinned upstream sources.
//!
//! GitHub default theme with Primer 7.10.0 and explicit fg/accent overrides. Canvas inset/subtle/overlay retain their meanings. Actions use the selected curated scale hue; status hues remain independent.

define_palette! {
    Light, "GitHub Light",
    identity("github/light", "github", "GitHub", "light", "Light", Light, None);
    support(Light);
    sources: super::SOURCE_LIGHT;
    colors {
        SCALE_GRAY_0 = crate::color::Color::hex(0xf6f8fa),
        SCALE_GRAY_1 = crate::color::Color::hex(0xeaeef2),
        SCALE_GRAY_2 = crate::color::Color::hex(0xd0d7de),
        SCALE_GRAY_3 = crate::color::Color::hex(0xafb8c1),
        SCALE_GRAY_4 = crate::color::Color::hex(0x8c959f),
        SCALE_GRAY_5 = crate::color::Color::hex(0x6e7781),
        SCALE_GRAY_6 = crate::color::Color::hex(0x57606a),
        SCALE_GRAY_7 = crate::color::Color::hex(0x424a53),
        SCALE_GRAY_8 = crate::color::Color::hex(0x32383f),
        SCALE_GRAY_9 = crate::color::Color::hex(0x24292f),
        SCALE_BLUE_0 = crate::color::Color::hex(0xddf4ff),
        SCALE_BLUE_1 = crate::color::Color::hex(0xb6e3ff),
        SCALE_BLUE_2 = crate::color::Color::hex(0x80ccff),
        SCALE_BLUE_3 = crate::color::Color::hex(0x54aeff),
        SCALE_BLUE_4 = crate::color::Color::hex(0x218bff),
        SCALE_BLUE_5 = crate::color::Color::hex(0x0969da),
        SCALE_BLUE_6 = crate::color::Color::hex(0x0550ae),
        SCALE_BLUE_7 = crate::color::Color::hex(0x033d8b),
        SCALE_BLUE_8 = crate::color::Color::hex(0x0a3069),
        SCALE_BLUE_9 = crate::color::Color::hex(0x002155),
        SCALE_GREEN_0 = crate::color::Color::hex(0xdafbe1),
        SCALE_GREEN_1 = crate::color::Color::hex(0xaceebb),
        SCALE_GREEN_2 = crate::color::Color::hex(0x6fdd8b),
        SCALE_GREEN_3 = crate::color::Color::hex(0x4ac26b),
        SCALE_GREEN_4 = crate::color::Color::hex(0x2da44e),
        SCALE_GREEN_5 = crate::color::Color::hex(0x1a7f37),
        SCALE_GREEN_6 = crate::color::Color::hex(0x116329),
        SCALE_GREEN_7 = crate::color::Color::hex(0x044f1e),
        SCALE_GREEN_8 = crate::color::Color::hex(0x003d16),
        SCALE_GREEN_9 = crate::color::Color::hex(0x002d11),
        SCALE_YELLOW_0 = crate::color::Color::hex(0xfff8c5),
        SCALE_YELLOW_1 = crate::color::Color::hex(0xfae17d),
        SCALE_YELLOW_2 = crate::color::Color::hex(0xeac54f),
        SCALE_YELLOW_3 = crate::color::Color::hex(0xd4a72c),
        SCALE_YELLOW_4 = crate::color::Color::hex(0xbf8700),
        SCALE_YELLOW_5 = crate::color::Color::hex(0x9a6700),
        SCALE_YELLOW_6 = crate::color::Color::hex(0x7d4e00),
        SCALE_YELLOW_7 = crate::color::Color::hex(0x633c01),
        SCALE_YELLOW_8 = crate::color::Color::hex(0x4d2d00),
        SCALE_YELLOW_9 = crate::color::Color::hex(0x3b2300),
        SCALE_ORANGE_0 = crate::color::Color::hex(0xfff1e5),
        SCALE_ORANGE_1 = crate::color::Color::hex(0xffd8b5),
        SCALE_ORANGE_2 = crate::color::Color::hex(0xffb77c),
        SCALE_ORANGE_3 = crate::color::Color::hex(0xfb8f44),
        SCALE_ORANGE_4 = crate::color::Color::hex(0xe16f24),
        SCALE_ORANGE_5 = crate::color::Color::hex(0xbc4c00),
        SCALE_ORANGE_6 = crate::color::Color::hex(0x953800),
        SCALE_ORANGE_7 = crate::color::Color::hex(0x762c00),
        SCALE_ORANGE_8 = crate::color::Color::hex(0x5c2200),
        SCALE_ORANGE_9 = crate::color::Color::hex(0x471700),
        SCALE_RED_0 = crate::color::Color::hex(0xffebe9),
        SCALE_RED_1 = crate::color::Color::hex(0xffcecb),
        SCALE_RED_2 = crate::color::Color::hex(0xffaba8),
        SCALE_RED_3 = crate::color::Color::hex(0xff8182),
        SCALE_RED_4 = crate::color::Color::hex(0xfa4549),
        SCALE_RED_5 = crate::color::Color::hex(0xcf222e),
        SCALE_RED_6 = crate::color::Color::hex(0xa40e26),
        SCALE_RED_7 = crate::color::Color::hex(0x82071e),
        SCALE_RED_8 = crate::color::Color::hex(0x660018),
        SCALE_RED_9 = crate::color::Color::hex(0x4c0014),
        SCALE_PURPLE_0 = crate::color::Color::hex(0xfbefff),
        SCALE_PURPLE_1 = crate::color::Color::hex(0xecd8ff),
        SCALE_PURPLE_2 = crate::color::Color::hex(0xd8b9ff),
        SCALE_PURPLE_3 = crate::color::Color::hex(0xc297ff),
        SCALE_PURPLE_4 = crate::color::Color::hex(0xa475f9),
        SCALE_PURPLE_5 = crate::color::Color::hex(0x8250df),
        SCALE_PURPLE_6 = crate::color::Color::hex(0x6639ba),
        SCALE_PURPLE_7 = crate::color::Color::hex(0x512a97),
        SCALE_PURPLE_8 = crate::color::Color::hex(0x3e1f79),
        SCALE_PURPLE_9 = crate::color::Color::hex(0x2e1461),
        SCALE_PINK_0 = crate::color::Color::hex(0xffeff7),
        SCALE_PINK_1 = crate::color::Color::hex(0xffd3eb),
        SCALE_PINK_2 = crate::color::Color::hex(0xffadda),
        SCALE_PINK_3 = crate::color::Color::hex(0xff80c8),
        SCALE_PINK_4 = crate::color::Color::hex(0xe85aad),
        SCALE_PINK_5 = crate::color::Color::hex(0xbf3989),
        SCALE_PINK_6 = crate::color::Color::hex(0x99286e),
        SCALE_PINK_7 = crate::color::Color::hex(0x772057),
        SCALE_PINK_8 = crate::color::Color::hex(0x611347),
        SCALE_PINK_9 = crate::color::Color::hex(0x4d0336),
        SCALE_CORAL_0 = crate::color::Color::hex(0xfff0eb),
        SCALE_CORAL_1 = crate::color::Color::hex(0xffd6cc),
        SCALE_CORAL_2 = crate::color::Color::hex(0xffb4a1),
        SCALE_CORAL_3 = crate::color::Color::hex(0xfd8c73),
        SCALE_CORAL_4 = crate::color::Color::hex(0xec6547),
        SCALE_CORAL_5 = crate::color::Color::hex(0xc4432b),
        SCALE_CORAL_6 = crate::color::Color::hex(0x9e2f1c),
        SCALE_CORAL_7 = crate::color::Color::hex(0x801f0f),
        SCALE_CORAL_8 = crate::color::Color::hex(0x691105),
        SCALE_CORAL_9 = crate::color::Color::hex(0x510901),
        SCALE_BLACK = crate::color::Color::hex(0x1b1f24),
        SCALE_WHITE = crate::color::Color::hex(0xffffff),
        FG_DEFAULT = crate::color::Color::hex(0x1f2328),
        FG_MUTED = crate::color::Color::hex(0x656d76),
        FG_SUBTLE = crate::color::Color::hex(0x6e7781),
        FG_ON_EMPHASIS = crate::color::Color::hex(0xffffff),
        CANVAS_DEFAULT = crate::color::Color::hex(0xffffff),
        CANVAS_OVERLAY = crate::color::Color::hex(0xffffff),
        CANVAS_INSET = crate::color::Color::hex(0xf6f8fa),
        CANVAS_SUBTLE = crate::color::Color::hex(0xf6f8fa),
        BORDER_DEFAULT = crate::color::Color::hex(0xd0d7de),
        NEUTRAL_EMPHASIS_PLUS = crate::color::Color::hex(0x24292f),
        NEUTRAL_EMPHASIS = crate::color::Color::hex(0x6e7781),
        ACCENT_FG = crate::color::Color::hex(0x0969da),
        ACCENT_EMPHASIS = crate::color::Color::hex(0x0969da),
        ACCENT_SUBTLE = crate::color::Color::hex(0xddf4ff),
        SUCCESS_FG = crate::color::Color::hex(0x1a7f37),
        SUCCESS_EMPHASIS = crate::color::Color::hex(0x1f883d),
        SUCCESS_SUBTLE = crate::color::Color::hex(0xdafbe1),
        ATTENTION_FG = crate::color::Color::hex(0x9a6700),
        ATTENTION_EMPHASIS = crate::color::Color::hex(0xbf8700),
        ATTENTION_SUBTLE = crate::color::Color::hex(0xfff8c5),
        SEVERE_FG = crate::color::Color::hex(0xbc4c00),
        SEVERE_EMPHASIS = crate::color::Color::hex(0xbc4c00),
        SEVERE_SUBTLE = crate::color::Color::hex(0xfff1e5),
        DANGER_FG = crate::color::Color::hex(0xcf222e),
        DANGER_EMPHASIS = crate::color::Color::hex(0xcf222e),
        DANGER_SUBTLE = crate::color::Color::hex(0xffebe9),
        OPEN_FG = crate::color::Color::hex(0x1a7f37),
        OPEN_EMPHASIS = crate::color::Color::hex(0x2da44e),
        OPEN_SUBTLE = crate::color::Color::hex(0xdafbe1),
        CLOSED_FG = crate::color::Color::hex(0xcf222e),
        CLOSED_EMPHASIS = crate::color::Color::hex(0xcf222e),
        CLOSED_SUBTLE = crate::color::Color::hex(0xffebe9),
        DONE_FG = crate::color::Color::hex(0x8250df),
        DONE_EMPHASIS = crate::color::Color::hex(0x8250df),
        DONE_SUBTLE = crate::color::Color::hex(0xfbefff),
        SPONSORS_FG = crate::color::Color::hex(0xbf3989),
        SPONSORS_EMPHASIS = crate::color::Color::hex(0xbf3989),
        SPONSORS_SUBTLE = crate::color::Color::hex(0xffeff7),
        PRIMER_DISABLED = crate::color::Color::hex(0x8c959f),
        PRIMER_ACTIVE = crate::color::Color::hex(0xfd8c73),
    }
    accents {
        Blue = SCALE_BLUE_5 => ("blue", "Blue"),
        Green = SCALE_GREEN_5 => ("green", "Green"),
        Yellow = SCALE_YELLOW_5 => ("yellow", "Yellow"),
        Orange = SCALE_ORANGE_5 => ("orange", "Orange"),
        Red = SCALE_RED_5 => ("red", "Red"),
        Purple = SCALE_PURPLE_5 => ("purple", "Purple"),
        Pink = SCALE_PINK_5 => ("pink", "Pink"),
    }
    default SCALE_BLUE_5 => "blue";
    roles(primary) {
        surface: crate::theme_variant::SurfaceColors {
            background: Self::CANVAS_DEFAULT,
            surface: Self::CANVAS_SUBTLE,
            raised: Self::CANVAS_OVERLAY,
            overlay: Self::CANVAS_OVERLAY,
            hover: Self::BORDER_DEFAULT,
        },
        surface_alt: crate::theme_variant::SurfaceColors {
            background: Self::CANVAS_INSET,
            surface: Self::CANVAS_DEFAULT,
            raised: Self::CANVAS_SUBTLE,
            overlay: Self::CANVAS_OVERLAY,
            hover: Self::BORDER_DEFAULT,
        },
        text: crate::theme_variant::TextColors {
            normal: Self::FG_DEFAULT,
            muted: Self::FG_MUTED,
            subtle: Self::FG_SUBTLE,
            on_primary: crate::palette::action_text(primary),
            on_secondary: crate::palette::action_text(Self::ACCENT_EMPHASIS),
        },
        primary: crate::theme_variant::ActionColors {
            normal: primary,
            hover: crate::palette::primary_hover(primary),
            pressed: crate::palette::action_pressed(primary),
            muted: Self::CANVAS_SUBTLE,
        },
        secondary: crate::theme_variant::ActionColors {
            normal: Self::ACCENT_EMPHASIS,
            hover: crate::palette::primary_hover(Self::ACCENT_EMPHASIS),
            pressed: crate::palette::action_pressed(Self::ACCENT_EMPHASIS),
            muted: Self::CANVAS_SUBTLE,
        },
        status: crate::theme_variant::StatusColors {
            success: Self::SUCCESS_FG,
            warning: Self::ATTENTION_FG,
            error: Self::DANGER_FG,
            critical: Self::DANGER_EMPHASIS,
            info: Self::ACCENT_FG,
            trace: Self::FG_SUBTLE,
        },
        border: Self::BORDER_DEFAULT,
        border_muted: Self::CANVAS_SUBTLE,
        focus: primary,
        chromatic: crate::theme_variant::ChromaticColors {
            red: Self::SCALE_RED_5,
            orange: Self::SCALE_ORANGE_5,
            yellow: Self::SCALE_YELLOW_5,
            green: Self::SCALE_GREEN_5,
            cyan: Self::SCALE_BLUE_5,
            blue: Self::SCALE_BLUE_5,
            purple: Self::SCALE_PURPLE_5,
            pink: Self::SCALE_PINK_5,
        },
        syntax: crate::theme_variant::SyntaxColors {
            attribute: Self::SCALE_ORANGE_6,
            boolean: Self::SCALE_BLUE_6,
            builtin: Self::SCALE_ORANGE_6,
            builtin_function: Self::SCALE_PURPLE_5,
            builtin_type: Self::SCALE_ORANGE_6,
            comment: Self::FG_MUTED,
            constant: Self::SCALE_BLUE_6,
            control_keyword: Self::SCALE_RED_5,
            deleted: Self::DANGER_FG,
            deprecated: Self::DANGER_FG,
            documentation: Self::FG_MUTED,
            escape: Self::SCALE_RED_5,
            foreground: Self::FG_DEFAULT,
            function: Self::SCALE_PURPLE_5,
            heading: Self::SCALE_PURPLE_5,
            inserted: Self::SUCCESS_FG,
            invalid: Self::DANGER_FG,
            keyword: Self::SCALE_RED_5,
            link: Self::SCALE_PURPLE_5,
            markup_bold: Self::FG_DEFAULT,
            markup_italic: Self::FG_DEFAULT,
            modifier: Self::SCALE_RED_5,
            namespace: Self::SCALE_ORANGE_6,
            number: Self::SCALE_BLUE_6,
            operator: Self::SCALE_RED_5,
            parameter: Self::FG_DEFAULT,
            property: Self::FG_DEFAULT,
            punctuation: Self::FG_DEFAULT,
            string: Self::SCALE_BLUE_8,
            tag: Self::SCALE_RED_5,
            type_keyword: Self::SCALE_RED_5,
            type_name: Self::SCALE_ORANGE_6,
            variable: Self::FG_DEFAULT,
        },
    }
}
